### ISSUE TITLE
Netdata not showing

### ISSUE THREAD

**Issue by dforce** [dtag-dev-sec/tpotce#100]
Using T-Pot 16.10

After upgrading to the latest version (07/05/2017) of netdata I don't see any results when clicking on the button, the page is opening but stays blank.
Netdata is running and persistent is set "on".

How can I solve this problem ?

Thanks

**Comment by t3chn0m4g3** [comment]
@dforce Thanks for the catch, reverted back to netdata v.1.6.0, just run ...
```
sudo su -
docker pull dtagdevsec/netdata:latest1610
systemctl stop netdata
systemctl start netdata
```
... and everything should work again.

**Comment by dforce** [comment]
@t3chn0m4g3 
Everything is working fine now.

Thanks
