### ISSUE TITLE
Docker Image Updates?

### ISSUE THREAD

**Issue by Sn00zr** [dtag-dev-sec/tpotce#102]
Greetings,

Apologies if this is not the correct place (as it is just a general question, not an issue), but I was wondering if there is any changelog, or a frequency at which the Docker Images are updated? For example, I made some visual changes to Kibana, and I noticed that they were wiped out late last night. After checking it seems that a bunch of new Docker images were pushed. I understand this is intended, but was hoping to get more information about what changed?

Thank you!

**Comment by t3chn0m4g3** [comment]
Visualizations are independent of updates and are stored on the host as long you stay on the same version (16.03, 16.10). If you are on the dev (17.06) this is a different story, though 😁

**Comment by Sn00zr** [comment]
I believe I am on 16.10. So by visual changes, I meant editing some HTML actually, not like a Kibana dashboard. 

Is there also any changelog?

**Comment by t3chn0m4g3** [comment]
Those changes are volatile and will be reset upon every container start. You can of course prepare modifications and mount them into the container (has been discussed in the issues, just search for **volume** or head over to the docker documentation)

**Comment by t3chn0m4g3** [comment]
Closing for now, please reopen if still not answered.
