### ISSUE TITLE
some problem in output log in suricata

### ISSUE THREAD

**Issue by jjjan** [dtag-dev-sec/tpotce#103]
Hello,
1-when i add hpfeed config every request to hpfeed brokers is catch by suricata. so how can i ignore this ip in suricata and all other honeypot?
2- where should i add new rule to suricata. can you make it auto? for example every 24 h rule update from sum bunch of open source and commercial source?
3- do we really need SSD hard disk for elk or just 15k SAS disk is enough?

**Comment by t3chn0m4g3** [comment]
1. This requires a [capture filter](http://suricata.readthedocs.io/en/latest/performance/ignoring-traffic.html). The default command for suricata when the container is started needs to be replaced which will be available in T-Pot 17.06 through a central T-Pot config file.
2. You need to map you own ruleset into the container using `-v <src>:<dst>` option. Issue #79 describes that also.
3. This depends on your IO, I'd always opt for SSDs nowadays.

**Comment by t3chn0m4g3** [comment]
Considering this answered, if not please reopen.
