### ISSUE TITLE
Parallels Desktop for mac install tpot.iso hava a error

### ISSUE THREAD

**Issue by nx4dm1n** [dtag-dev-sec/tpotce#104]
- What T-Pot version are you currtently using?

i use 16.10， parallels Desktop for mac ,

download the iso file from this url:
http://community-honeypot.de/tpot.iso

set the web username and password etc..

when the system setup, have a error like this:

```
[FAILED] Failed to start /etc/rc.local Compatibility.
See 'systemctl status rc-local.service' for details.
```

can anyone help me to resolve this question。

**Comment by t3chn0m4g3** [comment]
Unfortunately nobody on the team uses Parallels. Can you login and run `systemctl status rc-local.service` and provide further information?
Please ensure the interface is bridged and can directly access the internet.

**Comment by t3chn0m4g3** [comment]
Considering this answered, if not please reopen.
