### ISSUE TITLE
add ntop docker

### ISSUE THREAD

**Issue by dpicollege** [dtag-dev-sec/tpotce#105]
Hello,
AS you know ntop is great project. this is the name of docker lucaderi/ntopng-docker
and also add nDPI mangalaman93/ndpi.
thanks for attention

**Comment by t3chn0m4g3** [comment]
Please be more specific, while NTOP is great I do not think it would fit into the current scope of T-Pot. However, T-Pot 17.06 will introduce a docker-compose config and therefore be more pluggable regarding external containers.

**Comment by t3chn0m4g3** [comment]
Considering this answered, if not please reopen.
