### ISSUE TITLE
Requirement: Network via DHCP

### ISSUE THREAD

**Issue by MarcinNaw** [dtag-dev-sec/tpotce#106]
What is the motivation behind the statement, that "Network via DHCP" is a requirement?

Or: What happens, if we configure t-pot with a static IP-address in /etc/network/interfaces?

**Comment by t3chn0m4g3** [comment]
Ease of use. Of course you may set a static IP :smiley:

**Comment by MarcinNaw** [comment]
Perfect, Thank you!
