### ISSUE TITLE
Honeytrap UDP Traffic

### ISSUE THREAD

**Issue by MarcinNaw** [dtag-dev-sec/tpotce#107]
I want to configure honeytrap, so that it also binds dynamically sockets for UDP ports and reports them. Tried to do it the tpot way, I edited **/data/systemd/honeytrap.service**:

```
  + ExecStartPre=/sbin/iptables -w -A INPUT -p udp -m state --state NEW -m multiport ! --dports 69,5060 -j NFQUEUE
  + ExecStopPost=/sbin/iptables -w -D INPUT -p udp -m state --state NEW -m multiport ! --dports 69,5060 -j NFQUEUE
```

After a reboot neither `iptables -L` does show a change nor the dashboard shows any attacks if I try to trigger them with `echo -n "hello" | nc -4u -q1 a.b.c.d 8000`.

However, adding the new rules manually (just as commands in the shell) works. Honeytrap and the Dashboard report incoming requests.

What did I miss?

**Comment by MarcinNaw** [comment]
I did miss
```
cp /data/systemd/honeytrap.service /etc/systemd/system/honeytrap.service
```

**Comment by t3chn0m4g3** [comment]
With 17.06 things will get easier with only one docker-compose file and one service file.

**Comment by MarcinNaw** [comment]
If anyone also attempts to capture the UDP traffic, there is a small problem how UDP requests are counted.

For every UDP Packet, honeytrap answers with several UDP packets. The counter in Kibana will show the UDP packets received + sent by honeytrap. In my case, that resulted in about 10 udp replies for one incoming packet, which biased the analysis by factor 10. Currently, i do not know any fix but to filter entries  where srcIP == honeypotIP.

**Comment by t3chn0m4g3** [comment]
@MarcinNaw Thanks for the update. Also have a look [here](https://github.com/dtag-dev-sec/tpotce/blob/17.06/installer/etc/tpot/systemd/tpot.service). For 17.06 a new iptables config is in place that fixes some strange behaviour WRT honeytrap. Maybe UDP is affected as well.

**Comment by MarcinNaw** [comment]
Just took a look at `sudo vim /opt/tpot/bin/rules.sh`, which shows the default iptables entry for honeytrap:
```
 /usr/sbin/iptables-legacy -w -A INPUT -p tcp --syn -m state --state NEW -j NFQUEUE
```
What is the reasoning behind accepting only packets from _new_ TCP connections and not also established ones, i.e.:
```
 /usr/sbin/iptables-legacy -w -A INPUT -p tcp --syn -m state --state NEW,ESTABLISHED -j NFQUEUE
```
Also, $myRULESPORTS seems to contain all ports (TCP and UDP) from the compose-file, however only a rule for TCP is explicitly set.
```
    for myPORT in $myRULESPORTS; do
      /usr/sbin/iptables-legacy -w -A INPUT -p tcp --dport $myPORT -j ACCEPT
```

(Please don't get me wrong, overall, I like how the project has evolved into having single points of configuration! :)

**Comment by t3chn0m4g3** [comment]
Since honeytrap does not keep sessions we did not see the need to keep track of ESTABLISHED connections.
Still only want TCP traffic, UDP causes just too many events that's also why we did not modify the script to account for UDP as well.

**Comment by MarcinNaw** [comment]
Thank you for the additional information. UDP traffic is definitely challenging! If anyone else feels interested in my experiences with TPOT and UDP, just drop me a message.
