### ISSUE TITLE
TCP ports 3010 and 3104 Outbound 

### ISSUE THREAD

**Issue by shezzski** [dtag-dev-sec/tpotce#109]
Hi,

I am seeing TCP ports 3010 and 3104 blocked on my firewall interface connecting to T-Pot for traffic outbound from T-Pot.  Can you advise what these ports are used for?

TIA

**Comment by t3chn0m4g3** [comment]
Based upon your information I could only guess.

**Comment by shezzski** [comment]
Thanks for the information, so if this is not T-Pot attempting to make a connection would it be one of the docker honeypots?  I could not find it in the documentation, but are the various docker honeypots able to reach the internet from the 172.17.0.0/16 network?
