### ISSUE TITLE
Request for docker image hash(s) to be published

### ISSUE THREAD

**Issue by shezzski** [dtag-dev-sec/tpotce#110]
Hi, I was wondering if there is a repository where the SHA256 hash/digests of the docker images could be published?

I ask because when looking through portainer I discovered two docker images without tags and with SHA256 hashes that do not match anything I have on a T-Pot instance I built 12 hours later.

**Comment by t3chn0m4g3** [comment]
Some of the images are updated nightly, so this behaviour is normal.

**Comment by t3chn0m4g3** [comment]
Considering this answered, if not please reopen.
