### ISSUE TITLE
Dashboard backup

### ISSUE THREAD

**Issue by jonnynux** [dtag-dev-sec/tpotce#113]
Hi,
is possibile to automatically backup dashboards/searches/visualizzation and then restore? I've seen that I can export from kibana (settings/objects), but I couldn't find them from the disk, I searched everywhere.

**Comment by t3chn0m4g3** [comment]
T-Pot 17.06 will come with a corresponding set of [scripts](https://github.com/dtag-dev-sec/tpotce/tree/17.06/installer/bin).

**Comment by jonnynux** [comment]
WOW, great 👍
