### ISSUE TITLE
Some question by a begineer

### ISSUE THREAD

**Issue by royikle** [dtag-dev-sec/tpotce#115]
Hi ,
I'm a beginner in honey pot. The T-pot is really a convenient tool.
I have some question that have to figure out before studying T-pot.
I install version 16.10 in VM.

1. I know t-pot is based on docker.
    Can T-pot receive honey pot sensor information which on other device?
    Example: Device A install T-pot , B install glastopf , can A receive B's information?
2. If I want to install the sensor that T-port is not support like Snort , 
    Can T-pot receive the sensor information?
3. If I want to send log to arcsight , is there had recommend solutions to do it?
4. I know it be better to contribute the information to the community.
    But if I get sensitive information , I will consider to close the ews poster.
    So change ews = true to false in /data/ews/conf/ews.cfg is all thing I have to do?
    Or there are something else I have to do?

Sorry for low level question.
Best Regards

**Comment by t3chn0m4g3** [comment]
1. No, T-Pot is designed as stand-alone. However with some minor changes which already have been discussed and answered in the issues (please use the search function) you may achieve exactly that.
2. T-Pot will is shipping with Suricata which is a rule-based NSM of its own and serves the same purpose as Snort.
3. T-Pot is based upon Ubuntu, so everything working within Ubuntu should work here.
4. This is just too sad 😢. You may opt-out exactly the way you mentioned.

**Comment by royikle** [comment]
Hi t3chn0m4g3
I will use search function to find answer.
Thanks for your answer.
