### ISSUE TITLE
Restart Issue

### ISSUE THREAD

**Issue by seantree** [dtag-dev-sec/tpotce#117]
Hi Guys,

Thank you for doing a great job, I am just facing one issue my T-pot is not capturing any events globally but if I do attack on my behalf it's capturing the events. I have installed the T-pot into my VMWARE as per your notes I saw that somewhere you guys mentioned that within the 24 hours docker will be restarted, so all the data will be lost so I have some doubts I just want some clarity:

1. I want that honeypot should keep running till any crash, because I want to capture the malware I don't want to loss any event or threat.

2. Is there any settings in config to stop the restart within 24 hours?

3. How to retrieve a file from the docker?

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? Ubuntu 16.10 Latest one
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? 2 days
- Did you install any upgrades or packages? no
- Did you modify any scripts? no
- Have you turned persistence on/off? no 
- How much RAM available (login via ssh and run `htop`)? 4 GB
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)? 200 GB
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by MarcinNaw** [comment]
1) Only temporary log files from each docker are deleted, however all these log files are imported into the elastic search engine. So no attack information is lost on restart. Just use Kibana and you will see that request older then 24 hours are possible. You can disable the cleaning in clean.sh, but thats not what you want.

2) Keep that restart, it saves you a lot of trouble. Again, you dont want to disable this, but the restart is a simple cronjob, the table should be in /etc.

3) You dont need to retrieve the files, al is stored in shared directories in /data.

All this information are in the README. Just read it.

**Comment by t3chn0m4g3** [comment]
I assume this is resolved. Please feel free to re-open if that is not the case.
