### ISSUE TITLE
Initial Boot problem after ISO installation

### ISSUE THREAD

**Issue by eivanhoe** [dtag-dev-sec/tpotce#118]
I'm having issues booting the t-pot after a fresh install. Here are some of the errors I encountered:

Here is the first error that pops. I did systemctl status through alt+f2 to check the logs.
```
Failed to start /etc/rc.local Compatibility.
rc-local.service: Unit entered failed state.
rc-local.service: Failed with result 'exit-code'
```

The boot process then gets stucked at:
`[OK] Started update utmp about system runlevel changes`

My laptop's specs is an AMD Processor with 6GB of RAM.

**Comment by t3chn0m4g3** [comment]
@eivanhoe Based on your information I can only guess. It might be related to #119, however we are only testing on Intel NUC hardware, VirtualBox, VMWare and ESXi.

**Comment by t3chn0m4g3** [comment]
I am assuming this issue has been resolved. If not please feel free to re-open.
