### ISSUE TITLE
www.nsanamegenerator.com is no longer available

### ISSUE THREAD

**Issue by ctindel** [dtag-dev-sec/tpotce#119]
The install script depends on www.nsanamegenerator.com for generating a hostname:

https://github.com/dtag-dev-sec/t-pot-autoinstall/blob/master/install.sh#L24

But that site doesn't work anymore.  Also the backup plan in the script is to read from /usr/share/dict/names which also doesn't exist on ubuntu.  I can't even find a package that installs it.  Closest thing I can find is miscfiles that installs /usr/share/dict/propernames.gz so for now I'm doing a workaround by unzipping that file and creating a symlink, but really this part of the install script is basically broken at the moment I think.

**Comment by t3chn0m4g3** [comment]
@ctindel Thanks for reporting. Backported fix from 17.06-dev, can you test and report back please.

**Comment by t3chn0m4g3** [comment]
New ISO can be found here:
https://github.com/dtag-dev-sec/tpotce/releases

**Comment by t3chn0m4g3** [comment]
This should be resolved. Please feel free to re-open should you still face the issue.

**Comment by ctindel** [comment]
@t3chn0m4g3 where does /usr/share/dict/a.txt come from?

**Comment by t3chn0m4g3** [comment]
Why?

**Comment by ctindel** [comment]
@t3chn0m4g3 I was looking at the PR, if someone installs just by downloading the install script and not by using the ISO, it will use the a.txt and b.txt that you ship in the installer directory I guess?

**Comment by t3chn0m4g3** [comment]
If you just want to use the install script please use [t-pot-autoinstall](https://github.com/dtag-dev-sec/t-pot-autoinstall), fixes have been applied here as well.
