### ISSUE TITLE
what's the password for the built-in honeypot?

### ISSUE THREAD

**Issue by qxsomeone** [dtag-dev-sec/tpotce#121]
Dear guys, I have installed the tpot  successfully ,I think it's really a fantastic tool. Now I have the following questions:

1).what's the weak password for the built-in honeypots? As we know ,the Tpot supports multiple honeypots, the cowrie is listening on port 22, honeytrap is listening on port 3389, then what's the password for ssh and windows RDP?

2).can we selectively start or stop a honeypot ?for example  ,stop the honeytrap or dionaea ;if so ,how to start or stop a specific honeypot?

Thanks.

**Comment by t3chn0m4g3** [comment]
@qxsomeone Thanks for joining the T-Pot community :bowtie: 

1. There is none, please review the [config](https://github.com/dtag-dev-sec/cowrie/blob/master/dist/cowrie.cfg) for more information

2. Yes, `systemctl [start|stop] <honeypot>`, i.e. `systemctl stop cowrie`

**Comment by qxsomeone** [comment]
@t3chn0m4g3 Thanks for your reply.

Where can I find the cowrie.cfg? There are only four folds under /data/cowrie:
downloads, keys, log, misc.
I didn't find any *.cfg files or path.

**Comment by t3chn0m4g3** [comment]
@qxsomeone All the configs reside within the docker image.

**Comment by qxsomeone** [comment]
@t3chn0m4g3 So how can I change the configs ?thanks

**Comment by t3chn0m4g3** [comment]
@qxsomeone The only way for you to change configs is by mapping your own config file into the image upon start of the container. The outlines have been discussed in issue #79. You might want to read up on the [docker volume documentation](https://docs.docker.com/engine/tutorials/dockervolumes/).
BTW - setting up a password for Cowrie will result in a easier detection of the honeypot.

**Comment by qxsomeone** [comment]
@t3chn0m4g3 thank you so much

**Comment by qxsomeone** [comment]
@t3chn0m4g3 I searched the cowrie.cfg by filename ,and found there are four cowrie.cfg under different path,:
one under /var/lib/docker/aufs/mnt/xxxxxxxxx/home/cowrie/cowrie/ , 
one under /var/lib/docker/aufs/diff/yyyyyyyyy/root/dist/ ,
and two under /var/lib/docker/aufs/diff/aaabbbccc/home/cowrie/cowrie ,

if I need to change the config file to let it auth with userdb ,which config file I should change?Thanks

**Comment by t3chn0m4g3** [comment]
@qxsomeone I posted all the necessary information and links in my previous post. You have to read up on docker to fully understand what is happening. Please understand that an [introduction to docker](http://training.play-with-docker.com/) is beyond the scope of T-Pot. Thank you.
