### ISSUE TITLE
Finding the malwares/downloads from deleted /data logs

### ISSUE THREAD

**Issue by eivanhoe** [dtag-dev-sec/tpotce#122]
### Baisc support information

- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? DigitalOcean server
- How long has your installation been running? 20 days
- Did you install any upgrades or packages? just xfce but didnt work
- Did you modify any scripts? no
- Have you turned persistence on/off? on
- How much RAM available (login via ssh and run `htop`)? about 1GB
- How much stress are the CPUs under (login via ssh and run `htop`)? spikes to around 65%
- How much swap space is being used (login via ssh and run `htop`)? 0K
- How much free disk space is available (login via ssh and run `sudo df -h`)? about 40GB
- What is the current container status (login via ssh and run `sudo start.sh`)? cant find start.sh

Hey awesome job with these honeypots. I just have a few inquiries regarding the logs.

So I happen to lately find about the persistence. So all my log files have been deleted at a certain interval. But I read this answer from @MarcinNaw:

> Only temporary log files from each docker are deleted, however all these log files are imported into the elastic search engine. So no attack information is lost on restart. Just use Kibana and you will see that request older then 24 hours are possible. You can disable the cleaning in clean.sh, but thats not what you want.

I want to access the downloads (cowrie) and binaries (dionaea) folder of both dionaea and cowrie. My question is if the URL/filename of the malwares are still viewable in ELK Stack? Basically I'm looking for the /data/log/dionaea.log files that have been deleted. 

I tried viewing the logstatsh in elastic search but I wasn't able to find any. I was wondering if I need to change the settings a bit or is it not accessible anymore?

**Comment by t3chn0m4g3** [comment]
Thank you for your positive feedback and joining the T-Pot community :bowtie: 
All log files are stored in `/data` and are immediately forwarded by **Logstash** into Elastic Search. However, downloaded binaries, bistreams. etc. are solely stored in the subfolders of each honeypot `/data/<honeypot>`.
If you only recently turned on *persistence* then you will only be able to access the events within **Kibana**, additional files in the honeypot subfolders have been deleted already.
From the looks of your Digital Ocean configuration you should consider at least 4GB of RAM and 2 cores. The 40GB hard drive might last you only a few days (depending on your exposure) if persistence is turned on.

**Comment by eivanhoe** [comment]
Does Kibana store the details of the downloaded binaries, bistreams. etc? If yes, what parameter or specific field should I configure/find on Kibana?

Let us say for example I am looking for the logs of all downloaded binaries of (dionaea).
