### ISSUE TITLE
Testing cowrie with ssh command

### ISSUE THREAD

**Issue by eivanhoe** [dtag-dev-sec/tpotce#123]
Baisc support information

    What T-Pot version are you currtently using? 16.10
    Are you running on a Intel NUC or a VM? DigitalOcean server
    How long has your installation been running? 20 days
    Did you install any upgrades or packages? just xfce but didnt work
    Did you modify any scripts? no
    Have you turned persistence on/off? on
    How much RAM available (login via ssh and run htop)? about 1GB
    How much stress are the CPUs under (login via ssh and run htop)? spikes to around 65%
    How much swap space is being used (login via ssh and run htop)? 0K
    How much free disk space is available (login via ssh and run sudo df -h)? about 40GB
    What is the current container status (login via ssh and run sudo start.sh)? cant find start.sh

Hi I was testing my tpot for documenting reconnaissance activity. Basically I want to try to test if cowrie is working. So I tried 
`
ssh -p 2222 <ip address>`

But I get this error message:
`
ssh_exchange_identification: Connection closed by remote host`

Is there a way to access the docker IP of cowrie to test an SSH brute force attack?

Ok I tired `ssh -p 22 <ip address>`, since port 22 forwards it to port 2222 (cowrie). It prompts me with a password. But I still cant get in using the credentials for userdb.txt

I also tried `ssh -p 22 root@<ip address>`, still no luck in gaining access.

**Comment by DivyanshGohil** [comment]
You have close this issue. if it is solved please explain me. I am facing the same issue. It like at one time i can connect the ssh with any username and password i provide to server. On other time  I am not able to connect it even if am login to ssh server with the authenticated username and password also. As shown in below figure even though kali is not the user in ssh server it is still connecting.
![Screenshot_2024-01-17_16_49_49](https://github.com/telekom-security/tpotce/assets/71933142/4c5bbc54-b49f-4dc2-9532-e70ae6ede3c5)
