### ISSUE TITLE
Syslog forwarding to SIEM

### ISSUE THREAD

**Issue by zurpa** [dtag-dev-sec/tpotce#129]
Hello,

first of all, thank you for all your doing on this project. I'm testing it for pure internal purpose. I tried to forward logs to an external syslog (SIEM). I understood how to modify the local configuration to add a syslog entry in the output section of the logstash.conf, but this seem to required a logstash syslog plugin, not available in the elk container.

What should I do to add this plugin in the container (logstash-plugin install logstash-output-syslog)?

**Comment by t3chn0m4g3** [comment]
Thanks and understood. Will add the plugin to the logstash image for the 17.10 release, then your config changes will work.

**Comment by t3chn0m4g3** [comment]
Implemented via https://github.com/dtag-dev-sec/elk/commit/ba81dcb44c1ed9c459ee7f2487ac1f4a2b61f013

17.x Alpha will be available soon :bowtie:
