### ISSUE TITLE
Enhancement request: X-Pack Reporting module.

### ISSUE THREAD

**Issue by battletux** [dtag-dev-sec/tpotce#131]
This is not so much an issue as an enhancement request.

It would be fantastic if the X-Pack reporting module (https://www.elastic.co/products/x-pack/reporting) could be installed as it would allow for PDF exports of the dashboards so it can be easily shared.

**Comment by t3chn0m4g3** [comment]
Yes, it would, but X-Pack is commercial and cannot be distributed with our current license. Sorry, but it will not be integrated.
