### ISSUE TITLE
iso install issue

### ISSUE THREAD

**Issue by tpotuser101** [dtag-dev-sec/tpotce#132]
Hello,

I tried installing the latest tpot iso (http://community-honeypot.de/tpot.iso) 
and for some reason none of the honeypot docker containers seem to get installed.
This is a VirtualBox VM install, but I had the same issue over VMware.

This seems to be a recent issue as my prior install (3-4 months ago) succeeded without
issues.   I am attaching the installation log file...
[install.log.txt](https://github.com/dtag-dev-sec/tpotce/files/1264484/install.log.txt)

Any advise would be appreciated...

**Comment by t3chn0m4g3** [comment]
Please use the updated [16.10.1](https://github.com/dtag-dev-sec/tpotce/releases/tag/16.10.1). Thank you for reporting, will update the article.
