### ISSUE TITLE
May i know the database backend? Is there any technical manual to understand T-POT. how i can import the database. how do we backup the database?

### ISSUE THREAD

**Issue by chris88888888** [dtag-dev-sec/tpotce#135]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by schmalle** [comment]
Dear Chris,

I actually dont know, what you mean by database backend ? The local one from a t-pot (then please have a look at our github repositories, here you will find all scripts etc.) or the backend, where we collect the alarms, show them on the sicherheitstacho ui ? We plan to open source parts of our collection backend somewhen in q4, before we dont offer here any documentation.

Best wishes

Markus

**Comment by chris88888888** [comment]
Dear Schmahalle,

I thank you for the quick answering our inquires, that's means the data is stored in the log for each honeypot ?
and in case i need to get the IP addresses with some fields , how can I collect ?
I'm looking for Data base tables?
one more, if i need to have  a data backup, how can we backup the data ?

**Comment by t3chn0m4g3** [comment]
@chris88888888 Everything is well described [here](https://github.com/dtag-dev-sec/tpotce/blob/17.06/README.md). Please understand that we do not have the resources for deep diving into the technical details as the code is open source. However we do not use a database but an [ELK stack](https://www.elastic.co/) instead.

Thank you for understanding 😃
