### ISSUE TITLE
Clear all log data

### ISSUE THREAD

**Issue by artv2007** [dtag-dev-sec/tpotce#136]
### Baisc support information
- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? On HW
- How long has your installation been running? 10 days
- Did you install any upgrades or packages? No
- Did you modify any scripts? No
- Have you turned persistence on/off? No
- How much RAM available (login via ssh and run `htop`)? 8gb
- How much stress are the CPUs under (login via ssh and run `htop`)? 4
- How much swap space is being used (login via ssh and run `htop`)? 0k
- How much free disk space is available (login via ssh and run `sudo df -h`)? 80gb
- What is the current container status (login via ssh and run `sudo start.sh`)? 

I was tested your T-Pot system some days and now want to clear all historical logs data. I need that my system will be like the new installation.
How can I do this?

**Comment by t3chn0m4g3** [comment]
@artv2007 The easiest way is a reinstall. There is no *factory reset* option available.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved, closing for now.

**Comment by lele89ca** [comment]
With tpot docker Stack:

- I have solved after purged Suricata log and ELK index:

root@$hostname:/home/$user/tpotce/data/suricata/log# ll
total 23397968
drwxrwx--- 2 tpot tpot        4096 Aug 17 17:43 ./
drwxrwx--- 3 tpot tpot        4096 Jul 26 14:51 ../
-rwxrwx--- 1 tpot tpot 23959403311 Aug 17 17:44 eve.json*
-rwxrwx--- 1 tpot tpot        5413 Aug 17 17:24 suricata.log*
-rwxrwx--- 1 tpot tpot        1420 Aug 17 17:22 suricata.log.1.gz*
-rwxrwx--- 1 tpot tpot        1109 Aug 15 01:44 suricata.log.27.gz*
-rwxrwx--- 1 tpot tpot         819 Aug 14 01:44 suricata.log.28.gz*
-rwxrwx--- 1 tpot tpot        1113 Aug 13 01:44 suricata.log.29.gz*
-rwxrwx--- 1 tpot tpot        1120 Aug 12 01:44 suricata.log.30.gz*
-rwxrwx--- 1 tpot tpot        3168 Aug 16 02:24 suricata.log.3.gz*
root@$hostname:/home/$user/tpotce/data/suricata/log# rm eve.json (24gb)

ELK INDEX
root@$hostname:/home/$user/tpotce/data/elk/data/indices# rm ./* -rf (45gb)

Reboot and try with systemctl daemon-reload
