### ISSUE TITLE
replace geoip

### ISSUE THREAD

**Issue by galaxy3000** [dtag-dev-sec/tpotce#141]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

hello, I make a geoip by myself, I want to use it to replace the geoip in T-pot, What should I do? 

Thank you :smiley:

-

**Comment by t3chn0m4g3** [comment]
T-Pot and its dashboards are optimized around geoip. If you want to use your own implementation for geoip you should probably build your own logstash image from scratch.
Please understand that this is out of the T-Pot scope and for a starting point please check out the logstash and docker documentation.
Thank you.
