### ISSUE TITLE
Malware download 

### ISSUE THREAD

**Issue by gabbiano83** [dtag-dev-sec/tpotce#143]
Hi Guys,

is it possible to download all captured malwares executable? How I can download binaries found?
I would like to run on a sandbox all malwares captured by Tpot.

I didn't find this on Tpot Guide

**Comment by t3chn0m4g3** [comment]
Please see issue #122.

Thanks.

**Comment by gabbiano83** [comment]
Thanks for you very much for your quick reply, but currently I didn't have any binaries on /data/dionaea folder. 
Console show about 15 events per minute on dionaea docker, but no files found on binary folder.
Can persistence on mode solve this ?

**Comment by t3chn0m4g3** [comment]
Malware samples are downloaded into `/data/dionaea/binaries`. If you are on 17.10 these will be archived and rotated on a daily basis with a 30 day persistence. However there is no guarantee with regard to malware samples.
