### ISSUE TITLE
Internet connection problem after ISO installation

### ISSUE THREAD

**Issue by alexsalvetti** [dtag-dev-sec/tpotce#144]
Hi there,

I'm having issues with tpot 17.10 after the installation of the iso. 
Installed on a PC with the minimum HW requirements, directly on HW no VM.

While installing the iso I've used a WiFi connection and everything was ok.
After reboot I'm getting this error:
![img_5791](https://user-images.githubusercontent.com/7389032/32526623-aa1392fa-c42a-11e7-964b-b87951795af0.JPG)
![img_5810](https://user-images.githubusercontent.com/7389032/32526628-acf6b948-c42a-11e7-8888-a49b53348b6b.JPG)

After clicking "yes" it shows me the installation type:
![img_5813](https://user-images.githubusercontent.com/7389032/32526682-f99b3706-c42a-11e7-9a9d-382e1f9dc31a.JPG)

I've even tried with a working ethernet connection but didn't solve the problem. Hope someone could help.
Thanks.

**Comment by t3chn0m4g3** [comment]
@alexsalvetti Thanks for your submission.
While the underlying Ubuntu Network Installer will be using the WiFi setting for the basic Ubuntu installation, it will not reuse those settings for subsequent boots. A wired reinstallation should resolve the issue as long your NIC is supported by the kernel. We are only testing on the Intel NUC series which works fine up until Gen6 for Ubuntu 16.04.x LTS. Gen7 will be supported starting with Ubuntu 18.04.

**Comment by alexsalvetti** [comment]
Thanks @t3chn0m4g3 for the prompt reply.
The main reason I've used a WiFi connection during the install is because of this error that occurs all the time I try to proceed with an Ethernet connection:
![img_5826](https://user-images.githubusercontent.com/7389032/32564821-a237ffb8-c4b5-11e7-96a7-b0c2a159b644.JPG)

My network, both WiFi and Ethernet cable, is working properly. I think that maybe it's a configuation issue. 
I also tried different archives, and tried manual input but same results. 
Plugging in the wifi card, refresh interfaces and boom it's working.

**Comment by t3chn0m4g3** [comment]
This seems to be hardware / chipset related. Unfortunately we can only test on Intel NUC.
You can try an expert install however and set everything manually or wait until the new auto installer is finished.

**Comment by t3chn0m4g3** [comment]
You may install Ubuntu 16.04.3 LTS and afterwards you can use the [autoinstaller](https://github.com/dtag-dev-sec/t-pot-autoinstall) for T-Pot 16.10.

**Comment by alexsalvetti** [comment]
Thanks @t3chn0m4g3 it works really well with the autoinstaller ;)

**Comment by t3chn0m4g3** [comment]
Thanks for your feedback. Will be updated to 17.10 soon.
