### ISSUE TITLE
Availability of the ISO file 17.10

### ISSUE THREAD

**Issue by opotmans** [dtag-dev-sec/tpotce#145]
Hello,

I would like to test the new version of this fantastic product for a deception approach. However, I didn't find the prebuilt iso for the new version.
Today, do I have as unique possibility to generate "iso", if not could please give the link?
If I click on "tpot" in your introduction sentence "This repository contains the necessary files to create the[ T-Pot ](https://github.com/dtag-dev-sec/tpotce/releases) ISO image, i come back to the page."

Thanks in advance for your answer

Best Regards,

Olivier

**Comment by t3chn0m4g3** [comment]
@opotmans Go [here](https://github.com/dtag-dev-sec/tpotce/releases/tag/17.10) and scroll all the way down to the bottom, there will you find the **Download** section.

**Comment by t3chn0m4g3** [comment]
I assume this is resolved :bowtie:

**Comment by opotmans** [comment]
Sorry for the delay, Yes you can close the ticket.

I recommend to put a link in the first sentence to the end of the post to avoid that stupid person like me only focuses on the first sentence and doesn't go to the end of the document :-) 

Interesting evolution with the last version: new installation + honeypot RPD and VNC is really an added value... FYI : I pushed a demo of your tool [Tpot-17.0](https://youtu.be/YwnNfDgOShQ) to show your software working against against SPARTA (Kali Linux)

if comment feel free and again thanks for your support !  👍

**Comment by t3chn0m4g3** [comment]
Thank you for the feedback. I simply removed the long text :bowtie:
