### ISSUE TITLE
Any experiences with minnowboard

### ISSUE THREAD

**Issue by paetzoldthomas** [dtag-dev-sec/tpotce#146]
Hi,

I wonder if anybody installed already on "MinnowBoard Turbot Dual Ethernet Quad-Core" board?
If so, I would be happy to read some experiences, since I consider to buy one for tpot purpose.

Thanks,

**Comment by t3chn0m4g3** [comment]
Does not meet the minimum specs (only 2GB RAM). Intel NUCs up to Gen6 work fine.

**Comment by paetzoldthomas** [comment]
Oh, thanks. That I overlooked. Sorry.

**Comment by paetzoldthomas** [comment]
Gen. 7 would not be good?

**Comment by t3chn0m4g3** [comment]
Not yet supported by Ubuntu 16.04.x, support for the new chipsets will be final in Ubuntu 18.04.x

**Comment by paetzoldthomas** [comment]
Thanks a lot for fast response.
