### ISSUE TITLE
Files Upload for Honeypots

### ISSUE THREAD

**Issue by zTemplar85** [dtag-dev-sec/tpotce#147]
Hi, 

Recently setup T-pot using VirtualBox. Mine is not a performance / setup issue.
Would like to know if the honeypot are config to allow attackers to upload files?

**Comment by t3chn0m4g3** [comment]
Every honeypot does allow some kind of download / upload of files, either via RFI (Glastopf), Upload (Dionaea, FTP, but limited due to Container usage) or Cowrie (if shell is opened, wget and such).

**Comment by zTemplar85** [comment]
Ok, thanks for the great work.
Hoping to see what would get uploaded in the wild.
