### ISSUE TITLE
键盘键序都是乱的

### ISSUE THREAD

**Issue by naozibuhao** [dtag-dev-sec/tpotce#154]
你好,我用的T-pot16  安装完成以后键盘键序都是乱掉的  比如 我按f 出来的是y  我按g出来的是i  全部都乱掉了  是我哪里设置的不对吗?>

**Comment by t3chn0m4g3** [comment]
English please :)

**Comment by zTemplar85** [comment]
Hi @t3chn0m4g3 @naozibuhao has issue with his keyboard input after installing T-pot16. E.g input `f`would become `y`

Perhaps dpkg-reconfigure keyboard-configuration can fixed this?

**Comment by t3chn0m4g3** [comment]
Thanks, a reconfigure should solve it. However if it is a fresh install please reinstall with 17.10. Keyboard should be detected during install which has been tested with DE, CH, AT, FR and US keyboard layouts.

**Comment by zTemplar85** [comment]
@naozibuhao 如果是新安装,建议你用最新版本 17.10。 新版本有自动键盘键序自动检测.

**Comment by naozibuhao** [comment]
收到,已经安装最新版T-pot 该问题已经解决
万分感谢

**Comment by zTemplar85** [comment]
Hi @t3chn0m4g3 , @naozibuhao has installed the latest version. Issue fixed.

**Comment by t3chn0m4g3** [comment]
@zTemplar85 Thank you!
