### ISSUE TITLE
I can't install tpot an virtuabox

### ISSUE THREAD

**Issue by lixp528** [dtag-dev-sec/tpotce#155]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues
I downloaded the ISO mirror from github,and then use it to create a VM an virtualbox,(the ROM and disk is enough,and the  network is bridge, the promiscuous mode is  for all)
but  then it turned that the DHCP is failed 
then  i  configure network manually,
but  finally it turned  out that it says i specified a  bad archive mirror
it advised that the possible reason is mirror broken; wrong ubuntu virson; no network connection etc
but the whole thing  i have checked is right
Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by mrcokito** [comment]
Hi, I have the same problem. I spend the last three days trying to install it, and I have exactly the same answers that lixp528. I don't know what is the problem, I follow like 3000 internet tutorials but I can't install it. Please, help! :(

**Comment by t3chn0m4g3** [comment]
Does the issue still persist or has it been resolved?

**Comment by mrcokito** [comment]
Still persist..

**Comment by t3chn0m4g3** [comment]
Cannot, reproduce, did a fresh install today and works just fine with the latest version of VirtualBox.

![image](https://user-images.githubusercontent.com/4318452/34680579-ca36efce-f499-11e7-9d60-d6497aff5134.png)

Maybe it is a [settings](https://youtu.be/XpZBXlwrOZg) problem?

**Comment by t3chn0m4g3** [comment]
Assuming solved.
