### ISSUE TITLE
How can I customize each honeypots on T-Pot?

### ISSUE THREAD

**Issue by teppay** [dtag-dev-sec/tpotce#156]
Hi

I want to customize each honeypots on T-Pot.
e.g. To add users to Cowrie

**Comment by t3chn0m4g3** [comment]
If you want to customize the configuration you have to copy the relevant config files to the host, adjust the config to your needs and assign the new config as [Docker Volume](https://docs.docker.com/engine/admin/volumes/volumes/). Volumes have been discussed in #79 and assigning them for the compose file you may have a look into the [FAQ](https://github.com/dtag-dev-sec/tpotce/wiki/FAQ-17.10).

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, closing for now.

**Comment by DivyanshGohil** [comment]
Hello @teppay 
My aim is also do this same task. changing authrandom parameters . But though following your all step, tpot ssh is not configure as i want. Is there any other step i must perform after Step-7.
