### ISSUE TITLE
How to add users to the T-Pot web interface?

### ISSUE THREAD

**Issue by battletux** [dtag-dev-sec/tpotce#157]
How can I add additional users to the T-pot web interface?

- What T-Pot version are you currently using?
17.10
- Are you running on a Intel NUC or a VM?
Kimsufi  KS3 VPS, built using Ubuntu 16.04 LTS and the T-pot auto install script.

Thanks.

**Comment by vorband** [comment]
`htpasswd /etc/nginx/nginxpasswd myOtherUser`

**Comment by t3chn0m4g3** [comment]
Assuming this is closed.

**Comment by hvdkooij** [comment]
This seems to have been changed with T-Pot 18.11 :
htpasswd: cannot modify file /etc/nginx/nginxpasswd; use '-c' to create it

**Comment by t3chn0m4g3** [comment]
Yes. NGINX is dockered now, you find it here `/data/nginx/conf/nginxpasswd`. Please stop T-Pot before making changes with `systemctl stop tpot` and restart it with `systemctl start tpot`

**Comment by t3chn0m4g3** [comment]
Updated the Wiki.
