### ISSUE TITLE
LetsEncrypt SSL cert

### ISSUE THREAD

**Issue by battletux** [dtag-dev-sec/tpotce#158]
How can I go about applying an SSL cert from LetsEncrypt? The reason I need this is because in Firefox I can not access the site due to the self signed certificate.

Thanks.

### Baisc support information

- What T-Pot version are you currtently using?
17.10
- Are you running on a Intel NUC or a VM?
Kimsufi KS3 VPS on Ubuntu 16.04 with t-pot auto installer script.

**Comment by t3chn0m4g3** [comment]
In Firefox you have to add an [exception](https://support.solarwinds.com/Success_Center/Virtualization_Manager_(VMAN)/Accept_a_self-signed_certificate).

However, paths for SSL certs can be found in the [nginx config](https://github.com/dtag-dev-sec/tpotce/blob/master/host/etc/nginx/tpotweb.conf) and follow the [Let's encrpyt guide](https://letsencrypt.org/getting-started/).

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, closing for now.
