### ISSUE TITLE
T-Pot 16.10 Session timeout

### ISSUE THREAD

**Issue by barrydekong** [dtag-dev-sec/tpotce#159]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues
I'm using T-Pot 16.10 for more than 6 months and recently the elastic search  couldn't load the data due to session timeout.  It resume normal after removed elk 3 months data. Is it limited data storage up to 6 months? Any other way to fix it more than 6 months? 

Thank you

<a name="faq"></a>
### 

###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
Based on the given information I could only guess. Can you please run the commands for the Basic support information?

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, closing for now.
