### ISSUE TITLE
Site close and Failed to start raise network

### ISSUE THREAD

**Issue by the94lucas** [dtag-dev-sec/tpotce#160]
So basically, I have an error while starting up T-Pot 17.10 Failed to start raise network interfaces. When I get to the login screen I copy the IP address to connect to the web portal, and then input the following 

**commands:**

_sudo su –
systemctl start t-pot
dps.sh_

**Screenshots:**

![screenshot from 2017-12-24 19-54-03](https://user-images.githubusercontent.com/32166396/34503652-88df8608-f011-11e7-8e70-19042651da66.png)
![screenshot from 2018-01-02 20-22-46](https://user-images.githubusercontent.com/32166396/34503653-88fd38c4-f011-11e7-9f7e-736ad5e359db.png)
![screenshot from 2018-01-02 20-23-37](https://user-images.githubusercontent.com/32166396/34503654-891bfd5e-f011-11e7-8b72-64d29bc65a94.png)
![screenshot from 2018-01-02 20-27-40](https://user-images.githubusercontent.com/32166396/34503655-8934d7e8-f011-11e7-928b-9a1977c06cc1.png)

- http://www.deharo.xyz/t-pot/Screenshot%20from%202017-12-24%2019-54-03.png
- http://www.deharo.xyz/t-pot/Screenshot%20from%202018-01-02%2020-22-46.png
- http://www.deharo.xyz/t-pot/Screenshot%20from%202018-01-02%2020-23-37.png
- http://www.deharo.xyz/t-pot/Screenshot%20from%202018-01-02%2020-27-40.png
- http://www.deharo.xyz/t-pot/

While I attempt to connect the website, it says it is closed as well, I guess it has to do with the previous error.

**System Architecture:**

Ubuntu Server 16.04 TLS > VMware workstation 14 Pro > T-POT 17.10

**Related points:**

•	Failed to start raise network interfaces
•	Site closed

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
Based on the screenshots your error is inconclusive since it seems you have tried with different network configurations and hence different IP addresses.
Did you assign more than one NIC?
What is the hardware type / driver of the assigned NIC? (should be e1000)
Does your setup allow for DHCP requests to be answered?
Is T-Pot allowed to directly access the internet?

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, closing for now.
