### ISSUE TITLE
[RFE] Support for cowrie dshield_output module

### ISSUE THREAD

**Issue by rskallies** [dtag-dev-sec/tpotce#165]
Cowrie can submit reports to DShield see [https://www.dshield.org/howto.html](url) and
[https://github.com/micheloosterhof/cowrie/blob/master/cowrie/output/dshield.py](url)

For this the python requests module must be installed in the dtagdevsec/cowrie:1710 image. 
Then it would be possible to use a custom cowrie.cfg with the relevant configuration for output_dshield module in tpot.yml. 

e.g. /opt/tpot/docker/cowrie/dist/cowrie-custom.cfg:/home/cowrie/cowrie/cowrie.cfg:ro

Ideally some way of putting an override for a custom cowrie.cfg would work out of the box.

**Comment by t3chn0m4g3** [comment]
Sounds good to me. Will look into it.

**Comment by t3chn0m4g3** [comment]
Just built and pushed the Cowrie image with `py-requests` package pre-installed.

Please run ...
```
systemctl stop tpot
docker pull dtagdevsec/cowie:1710
systemctl start tpot
```

Let me know if it works.

**Comment by rskallies** [comment]
Works great, thank you!

cowrie           | 2018-01-15T14:56:20+0000 [-] Twisted Version 17.9.0
cowrie           | 2018-01-15T14:56:20+0000 [-] Loaded output engine: jsonlog
cowrie           | 2018-01-15T14:56:20+0000 [-] Loaded output engine: dshield
cowrie           | 2018-01-15T14:56:20+0000 [-] Loaded output engine: textlog

**Comment by xECK29x** [comment]
Confirmed here as well! Thanks guys, great enhancement!
