### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by MarcinNaw** [dtag-dev-sec/tpotce#166]
Just some quick questions regarding IPv6 support:

- Is there any documentation or tests if and how good each honeypot (docker container) works with IPv6?
- How good does tpot work with IPv6 in general?
- Any gotchas and caveats for a IPv4+IPv6 setup?

**Comment by t3chn0m4g3** [comment]
@MarcinNaw 

> Is there any documentation or tests if and how good each honeypot (docker container) works with IPv6?
> How good does tpot work with IPv6 in general?
> Any gotchas and caveats for a IPv4+IPv6 setup?

We have not conducted any tests regarding IPv6 on T-Pot or the used honeypots. In a real world scenario it is highly unlikely that any machine will be enumerated utilizing the currently known scanning techniques.

If you are interested in IPv6 honeypots you may want to check out [6Guard](https://www.honeynet.org/node/944) or [honeydv6](https://github.com/ChristosKon/honeyd-ipv6).

As for IPv6 compatability you might want to check out the source repos of the honeypots used in T-Pot.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by certrik** [comment]
@t3chn0m4g3 Please reference this in the main readme.md .
