### ISSUE TITLE
ICMP Honeypot

### ISSUE THREAD

**Issue by MarcinNaw** [dtag-dev-sec/tpotce#167]
Just a feature request: 

Is there any ICMP honeypot, that could be deployed so that we could log ping-scans?

**Comment by t3chn0m4g3** [comment]
@MarcinNaw Do you have any suggestions? However, Suricata already detects suspicious ICMP events.

**Comment by MarcinNaw** [comment]
Unfortunately, I am not aware of a good ping-honeypot. If Suricata already detects such events, I guess its just a matter of visualisation of the logs. Let's see if we can create a nice ICMP attack view.
