### ISSUE TITLE
Upgrade tpot 16.10 to 17.10

### ISSUE THREAD

**Issue by sphereict** [dtag-dev-sec/tpotce#168]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? - Desktop i7 8gig ram
- How long has your installation been running? 4 months
- Did you install any upgrades or packages? no
- Did you modify any scripts? no
- Have you turned persistence on/off? default
- How much RAM available (login via ssh and run `htop`)? 8gb
- How much stress are the CPUs under (login via ssh and run `htop`)? 60%
- How much swap space is being used (login via ssh and run `htop`)? 0.07
- How much free disk space is available (login via ssh and run `sudo df -h`)? yes lots
- What is the current container status (login via ssh and run `sudo start.sh`)? All running

Hi 
is there a script to upgrade from 16.10 to 17.10 I have noticed that kibana cannot load as it has a time out 30000ms so I have 0 visualization:

Looking forward to your urgent assistance

**Comment by t3chn0m4g3** [comment]
There’s so upgrade path from 16.10 to 17.10. However 17.10 install only takes 30 minutes.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
