### ISSUE TITLE
Access to Kibana Dashboard without SSH-tunnel possible?

### ISSUE THREAD

**Issue by jahlives** [dtag-dev-sec/tpotce#17]
Is it possible to access the kibana dashboard without prior setup a ssh-tunnel? I tried with some NAT rules but no success so far. Background: I want to retrieve sensor data with my own scripts. Is it maybe possible to access the sensor data without the dashboard? Is there an export option I missed? Would be really great to access the data from my own scripts :-)
Thanks for any hint

tobi

**Comment by t3chn0m4g3** [comment]
@jahlives the current setup does not allow to access the kibana dashboard directly. per default the kibana dashboard does not include authentication. setting it up with tls and htdigest would complicate things and also use up another port on the machine. without using shield (https://www.elastic.co/products/shield) the safest way to access kibana is via ssh tunnel.
if you want to access the hp events you can do so by pulling "/data/ews/json/*" (which is still a work-in-progress) or suricata logs in "/data/suricata/log/eve.json".
