### ISSUE TITLE
Include two new options in compose and adapt install.sh

### ISSUE THREAD

**Issue by Tzaoh** [dtag-dev-sec/tpotce#170]
Would it be worth to have a new shared-docker volume to the `dist/logstash.conf` file with the `logstash` instance? Now, we need to rebuild the `logstash` docker image if we want to make modifications like:
  · adding drop filters
  · sending the logs to a central server.

After that we can include some extra `.yml` files under `etc/compose`. I am thinking about having two extra configurations some people already asked for, like:
* Having a `central_node.yml` which receive some logs. We would need to change some settings from `127.0.0.1:9200:64298` to `0.0.0.0:9200:64298` and disable unwanted HoneyPots. 
* Having a `probe_node.yml` (maybe without the web portal).

I have already those configurations and some other changes done in the `t-pot-autoinstall` `install.sh` script. I can prepare a pull request if you wish to include these two new options.

**Comment by t3chn0m4g3** [comment]
@Tzaoh You do not have to build a new image to do that. Please follow this issue #156 on how to modify T-Pot to meet your needs.

**Comment by Tzaoh** [comment]
Yep, I meant to have that shared volume from the beginning. Now the default installation is copying the file.
What about having the other options by default?

**Comment by t3chn0m4g3** [comment]
@Tzaoh With the alteration of the `tpot.yml` the volume is present at all times.
Exposing ES with tcp/9200 to the internet is a security risk. ES does not come with any type of an authentication and thus leaving your ES completely exposed to the internet allowing everyone to access, modify and delete your indexes.
For now, T-Pot is single seated and there are currently no plans with regard to a distributed installation.

**Comment by Tzaoh** [comment]
@t3chn0m4g3 
As you like, but that is true only if we do not use shield / x-packs plugins.
If there are no plans to add them, that is another story.

Thank you.

**Comment by t3chn0m4g3** [comment]
@Tzaoh Actually, we would very much like to do so, but since X-Pack / Shield is not available as open source we cannot include it within T-Pot.
