### ISSUE TITLE
Dionaea not receiving any attacks on SMB port 445

### ISSUE THREAD

**Issue by MxResearch** [dtag-dev-sec/tpotce#171]
Dear T-Pot developer team,

I have a setup T-Pot using VMWare and port forwarded following ports on router having DSL line.

1. Cowrie Ports: 22 and 23.
2. Dionaea Ports: 21 and 445.

I am receiving some traffic on Port 21 however I am not observing any traffic on SMB 445. When I telnet public IP 445 from other networks , I get an error message "could not connect connection failed". 

Need your assistance in identifying what could be causing the aforementioned issue. Is it that my internet service provider is blocking any automated attacks to SMB port 445 or is there any other setting which I am missing to apply ?

Note: I am observing the same issue on honeydrive distro and honeeepi distro.

**Comment by t3chn0m4g3** [comment]
Can you please verify by logging into T-Pot:

```
sudo su -
apt-get install nmap
nmap --script /usr/share/nmap/scripts/smb-vuln-ms10-061.nse -p445 127.0.0.1
```

Output should look like this:
```
Starting Nmap 7.01 ( https://nmap.org ) at 2018-02-02 17:03 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000055s latency).
PORT    STATE SERVICE
445/tcp open  microsoft-ds
Host script results:
|_smb-vuln-ms10-061: false
Nmap done: 1 IP address (1 host up) scanned in 0.49 seconds
```

Then open Kibana and check if you can see a similar output:
![image](https://user-images.githubusercontent.com/4318452/35745508-c9f95228-0843-11e8-99a6-8bf227a813fa.png)

**Comment by t3chn0m4g3** [comment]
@MxResearch This confirms a working installation. However tcp/445 is not attacked that frequently in the first place.

**Comment by MxResearch** [comment]
Thanks for your assistance @t3chn0m4g3 . 

Regards,
