### ISSUE TITLE
Suricata pcap files

### ISSUE THREAD

**Issue by alifayyazhussain** [dtag-dev-sec/tpotce#172]
# Contr
[Suricata.docx](https://github.com/dtag-dev-sec/tpotce/files/1743379/Suricata.docx)

"Well I installed T-POT a month ago, it had captured only 39 samples in Dionaea and second the Suricata log folders does not have any pcap files for analysis "

ibution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
@alifayyazhussain What is the question, please?

**Comment by alifayyazhussain** [comment]
Im unable to extract malware sample out from Bistreams.tgz.1.gz folder of dionaea sensor

**Comment by t3chn0m4g3** [comment]
Please use `gunzip <filename>` and then `tar xvfz <filename>`

**Comment by alifayyazhussain** [comment]
Thanks Respected ! You solved my issue


Best Regards,
Ali Fayyaz

 

    On Friday, March 2, 2018, 9:47:33 PM GMT+5, Marco Ochse <notifications@github.com> wrote:  
 
 
Please use gunzip <filename> and then tar xvfz <filename>

**Comment by alifayyazhussain** [comment]
Thanks Marco Ochse

**Comment by ArslanArshad022** [comment]
@alifayyazhussain can you please guide me how you are analyzing bistreams for malware analysis?
