### ISSUE TITLE
Modified ELK Docker Files (UI) - Where are they in 17.10?

### ISSUE THREAD

**Issue by Sn00zr** [dtag-dev-sec/tpotce#173]
### Baisc support information

- What T-Pot version are you currently using?
**17.10**
- Are you running on a Intel NUC or a VM?
**VM**
- How long has your installation been running?
**2 weeks**
- Did you install any upgrades or packages?
**No**
- Did you modify any scripts?
**No (not yet)**
- Have you turned persistence on/off?
**Not sure**
- How much RAM available (login via ssh and run `htop`)?
**8gb**
- How much stress are the CPUs under (login via ssh and run `htop`)?
**10%**
- How much swap space is being used (login via ssh and run `htop`)?
**266mb of 8gb**
- How much free disk space is available (login via ssh and run `sudo df -h`)?
**9% used**
- What is the current container status (login via ssh and run `sudo start.sh`)?
**All online**

Hi there, I was developing the t-sec in 16.10 version, however recently upgraded to 17.10. I changed some UI items like icons, and colors in 16.10, but I am unable to locate the same "elk" container in 17.10 to port my changes over. I checked in the "kibana" docker, but it does not appear to contain the same file structure as the old "elk" one. Any ideas?

**Comment by t3chn0m4g3** [comment]
Yes, migrated to micro services, now located [here](https://github.com/dtag-dev-sec/tpotce/tree/master/docker/elk).

**Comment by Sn00zr** [comment]
Thank you for the info! With these changes, in which container can I find the same files? How could I modify title bar and colors?

**Comment by Sn00zr** [comment]
Found what I was looking for. Files are in /usr/share/kibana/src/ui. Thank you!
