### ISSUE TITLE
Change to NGINX files do not propagate (even after reboot)?

### ISSUE THREAD

**Issue by Sn00zr** [dtag-dev-sec/tpotce#174]
Sorry for spamming issues... another quick question, I am trying to modify the files at /opt/tpot/host/usr/share/nginx/html but after updating the files, the changes are not taking affect. I have tried rebooting the NGINX service, as well as a hard reboot, but still no change. Any ideas?

- What T-Pot version are you currently using?
**17.10**
- Are you running on a Intel NUC or a VM?
**VM**

**Comment by t3chn0m4g3** [comment]
Yes, those are the source files. You want to change the ones in `/usr/share/nginx/html`. However NGINX will be dockered in 18.04 anyways :bowtie:
