### ISSUE TITLE
how to collect data from TPOT using winscp

### ISSUE THREAD

**Issue by alifayyazhussain** [dtag-dev-sec/tpotce#176]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [x] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
Please be more specific. Thank you.

**Comment by alifayyazhussain** [comment]
Since my TPOT is placed in my server room, a restricted place to access. For the first time i detached the T-POT hard disk and connected it to another computer, using Chmod and chown i changed the permissions and copied the data . Now i dont want to perform this again, so i want to transfer malware samples collected by dionaea my DB using WinSCP , but it is not letting me to access the data/dionaea data folder

**Comment by t3chn0m4g3** [comment]
The easiest way is to add the `tsec` user to the `tpot` group:
```
usermod -a -G tpot tsec
```
Please let me know if this works for you.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by MxResearch** [comment]
Hi @t3chn0m4g3 ,

I want to get hold of all honeypot logs present inside data/ folder. For that purpose, I added tsec user to the tpot group as mentioned by you in the above post. 
But still, WinSCP throws error to access the data folder:

```
Error listing directory '/data'.
Server returned empty listing for directory '/data'.
```

Is there any other way through which I can access the data directory using WinSCP without changing it's file permission ?

Regards,

**Comment by tlbcc** [comment]
将root用户的ssh访问权限打开也可以，直接用root用户访问，但总感觉这样不安全
