### ISSUE TITLE
TPot 17.10 Pre-Built ISO - Does not boot when set to EFI

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#177]
Hi Team,

TPot 17.10 Pre-Built ISO does not load if the VMWare is set to use EFI instead of BIOS :)

Boots fine when set to BIOS.

Just a heads up, that's all :)

Cheers,
Ray

**Comment by t3chn0m4g3** [comment]
Thank you. T-Pot is based on the Ubuntu Net Installer and ships with the same features / limitations.
