### ISSUE TITLE
How to deposit the database?

### ISSUE THREAD

**Issue by K0mas** [dtag-dev-sec/tpotce#178]
Hello!
  Will t-pot honeypot data how to deposit mysql database?
Such as: cowrie honeypot data stored in the mysql database?

**Comment by t3chn0m4g3** [comment]
Please be more specific, I am not sure what you mean exactly? All data will be written to ES and stored in `/data`

**Comment by K0mas** [comment]
@t3chn0m4g3 
thank you for your reply!
I mean the data in the /data directory can be stored in the mysql database?
Take cowrie honeypot data as an example

**Comment by t3chn0m4g3** [comment]
Everything is stored locally in the ES index using logstash.
