### ISSUE TITLE
Q: Cannot configure ssh tunnel due to 'connection refused' message

### ISSUE THREAD

**Issue by RogerWeihrauch** [dtag-dev-sec/tpotce#18]
Howdy colleagues

I Just installed TpotCE successfully w/ support from your inst-video. Now I am stuck at minute 6:56 of your video at that point where to configure the ssh tunnel to get access via browser on localhost:8080. Here I get the message of 'connection refused'. Where does this message belong to? Does it refer to the access to my pub-IP via ssh? Or does it say that the access to localhost is denied?
Where exactly does the tunnel want to connect to and where is this request rejected then?

Your response will be highly appreciated.

Kind regards,

Roger

**Comment by t3chn0m4g3** [comment]
Have you enabled SSH already? (~/.ssh_enable.sh)
If SSH is enabled, you can connect via tcp/64295:
ssh -p 64295 -l tsec <IP> or connect with tunnel:
ssh -p 64295 -l tsec -L8080:127.0.0.1:64296 <IP> and then use the browser to open kibana (http://127.0.0.1:8080)

For more information please visit: http://dtag-dev-sec.github.io/mediator/feature/2015/03/17/concept.html

**Comment by RogerWeihrauch** [comment]
Howdy Marco

Yes, sshd is up and running with system start. See what i get a message
from raspi client in case i am going to configure the tunnel:

pi@raspberrypi:~ $ ssh -p 64295 -l tsec -N -L8080:127.0.0.1:64296
46.127.202.235ssh: connect to host 46.127.202.235 port 64295: Connection
refused
pi@raspberrypi:~ $ ssh -p 64295 -l tsec
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L [bind_address:]port:host:hostport] [-l login_name] [-m
mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W
host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
pi@raspberrypi:~ $

What can you imagine may be reasons for that?

Thanks for your response; I am still stuck here.


Regards from Switzerland,
Roger



2016-01-17 23:27 GMT+01:00 Marco Ochse <notifications@github.com>:

**Comment by t3chn0m4g3** [comment]
I can only think of 2 possibilities:
1. SSH server is not enabled
2. tcp port translation for tcp/64295 on your internet router / firewall does not work

Are the honeypot services reachable (i.e. glastopf via http://[your_ip])?
Have you tried connecting within your local network?
Is T-Pot reachable via ICMP?

Cheers,
Marco.

**Comment by RogerWeihrauch** [comment]
Howdy Marco

Ok, I managed to get ports forwarded and to be asked for Auth code from Google Authenticator and the pswd for the user (tsec) this ssh-tunnel is used under.
Nevertheless, now I get the message from 'bind': 'address already in use'; 'channel setup fwd listener: cannot listen to port:8080'; 'Could not request local forwarding'
Which address is meant here?
How to get access to port 8080? (Since it is already forwarded in my airport extreme to the local IP this tpotce is running on)
Is it the (private) IP address my tpotce is running at?
Or is the pub IP meant at this point?
Thanks you very much for your response.

Regards from Switzerland,
Roger

**Comment by t3chn0m4g3** [comment]
With "ssh -p 64295 -l tsec -L8080:127.0.0.1:64296 [TPOT-IP]" you can only open one tunneled connection from your client machine to T-Pot. As soon as the connection is established a local tcp/8080 port is used to forward all request from http://127.0.0.1:8080 via SSH to the T-Pot machine on tcp/64296.
If your client machine already uses tcp/8080 for a different daemon (check with sudo netstat -anp) you are out of luck :o( because T-Pot requires the tunnel to established as mentioned above.

Cheers,
Marco.
