### ISSUE TITLE
T-Pot 16.10 RAM issues and session timeout

### ISSUE THREAD

**Issue by asafgam** [dtag-dev-sec/tpotce#180]
## Issues

I'm using T-Pot 16.10 for something like 5 months and recently the dashboard and the elastic search couldn't load the data due to session timeout.
In the netdata I see it using 60% of the RAM.

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using? **16.10**
- Are you running on a Intel NUC or a VM? **VM**
- How long has your installation been running? **5 months**
- How much RAM available (login via ssh and run `htop`)? 
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
![image](https://user-images.githubusercontent.com/32816407/37093506-38d31e34-2218-11e8-9130-319eb6dbabf3.png)

- How much free disk space is available (login via ssh and run `sudo df -h`)?
![image](https://user-images.githubusercontent.com/32816407/37093544-5d2b2fba-2218-11e8-9c3d-412bac676e77.png)

- What is the current container status (login via ssh and run `sudo status.sh`)?
![image 1](https://user-images.githubusercontent.com/32816407/37093559-6c238878-2218-11e8-8d86-bd86ec0231b9.png)

**Comment by t3chn0m4g3** [comment]
@asafgam From the looks of it you are running a `Everything` installation on a 16.10 T-Pot. There is no easy solution to limit RAM consumption of ELK and emobility. With 17.10 we adressed those issues by introducing docker-compose with a configuration set where you can easily limit RAM consumption for ELK `https://github.com/dtag-dev-sec/tpotce/blob/master/etc/compose/all.yml`.
Please consider installing the latest [17.10 release.](https://github.com/dtag-dev-sec/tpotce/releases)

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
