### ISSUE TITLE
Conpot - Not listening on typical ICS Ports?

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#181]
Hi Team,

I notice that the Conpot deployment in T-Pot is not the same as a default Conpot Deployment which has all the typical ICS Ports listening, such as Modbus, S7Comm, Bacnet, SNMP, etc.

Any ideas on how we can enable this and if not, when this will be available? Simply having only the current "Smart Meter" Kamstrup template is not really ideal nor beneficial in capturing ICS based attacks.

Is there anyway we can get the typical Conpot Default template embedded? Appreciate the assist!

Cheers,
Ray

### Basic support information

- What T-Pot version are you currtently using? 17.10
- Are you running on a Intel NUC or a VM? VMWare
- How long has your installation been running? 2 Days
- Did you install any upgrades or packages? No
- Did you modify any scripts? No
- Have you turned persistence on/off? No - Changed to 90 Days however
- How much RAM available (login via ssh and run `htop`)? 7.7/11.7 Used, approx 4GB available
- How much stress are the CPUs under (login via ssh and run `htop`)? Minimal, Load 1.2, 1.37, 1.43
- How much swap space is being used (login via ssh and run `htop`)? 12.3MB
- How much free disk space is available (login via ssh and run `sudo df -h`)? 87% Free on /
- What is the current container status (login via ssh and run `sudo start.sh`)? dps.sh shows all running and healthy

**Comment by RogerWeihrauch** [comment]
@Ray: Hello
I just had a short look on a how-to to install conpot natively on (an older) Ubuntu version, here:
http://mushorg.github.io/conpot/installation/ubuntu.html
There it is written that (all?) necessary services may be enabled/configured manually in the 'standard' config file.
Unfortunatly, due to be less on time, I did not check on my TPotCE installation:
1st) the existence of this file for the conpot docker part/container
2nd) how the conpot-portation is realised in TPotCE to get 1st) answered
3rd) how near the portation in TPotCE is to the native conpot
But I will do as soon as possible for me.
Maybe the link above could be of little help to you.

Regards,
Roger

**Comment by UncleRaymondo** [comment]
Hi Roger :)

Thanks for the reply!

Yes, I'm used to the standard installation of Conpot using its default template, this is how I know that there are key ICS/SCADA ports missing from the T-Pot implementation of Conpot.

I'm not familiar with how T-Pot's implementation of Conpot within docker is configured or whether it can be modified to allow attacks against the other ports and interaction with what was being presented as a Siements SIMATIC S7-200 device, a common device used within ICS/SCADA environments.

Appreciate your assistance :)

Cheers,
Ray

**Comment by t3chn0m4g3** [comment]
Conpot runs its services templates oriented. By default the honeypot is running a set of services mimicking a Siemens S7-200 which we have been using previously. However in the current T-Pot Industrial installation we are running Kamstrup and with 18.04 / 18.10 we will change the beahviour again.

**Comment by UncleRaymondo** [comment]
I've forked 17.10 and seem to have managed to successfully run 4 x Conpot containers, each running a separate template with their respective ports (with overlapping ports removed so as to not cause any conflict)

dps.sh reports they're all started, so I'm just going to do some more testing now before I create a pull request for you to have a look...

**Comment by UncleRaymondo** [comment]
FYI...

![17_10_fork_conpot_x_4](https://user-images.githubusercontent.com/5147133/37205188-f1a17066-23e7-11e8-9061-55f43094ec25.png)

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo  Please bare in mind that only adjusting the `tpot.yml` will make your installation susceptible to race conditions at start. You still have to adjust the `/etc/systemd/system/tpot.service` iptables rules so NFQUEUE will not forward traffic to honeytrap instead of your conpot instances.
Also, your conpot_default does not correctly resemble the necessary protocol stack for the S7-200. Also, you have to modify the conpot templates or the services will be easily fingerprintable.

**Comment by UncleRaymondo** [comment]
Yep, I've already adjusted the tpot.yml, tpot.service, IPTables rules and have copied the required folders from a standard conpot instance, with their respective files, along with all the respective DockerFile's and docker-compose.yml's so that each is unique and in its own container. The only common thing between them is that it's using the conpot:1710 image...

Not sure what you mean about conpot_default incorrectly resembling the protocol stack of an S7-200... the only thing missing from the S7-200 is HTTP?

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo Perfect, now you have the conpot features we will be releasing with 18.04 for the industrial installation :bowtie: However, HTTP is an essential part of the said protocol stack.

**Comment by UncleRaymondo** [comment]
Yeah I disabled HTTP as it would conflict with Dionaea which is probably more tempting given that that is a much larger attack surface and may convince an attacker to try a few other things... 

As far as what the Controls Team at work who deal with ICS's all day tell me, they're more interested in attacks on Modbus, Bacnet, SNMP, S7Comm, and those sort of protocols that would be found in a typical BMS installation rather than HTTP ;)

**Comment by t3chn0m4g3** [comment]
Could not agree more 😄

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved with #187 

We are currently working on T-Pot 18.04 which will have a Industrial installation running ConPot with all possible templates in parallel. The approach however differs from the PR for a better match of the T-Pot services and planned update script and automatic iptables rules.
