### ISSUE TITLE
Getting rid of hardcoded stuff: hardcoded certificate in nginx/Kibana

### ISSUE THREAD

**Issue by uolevi** [dtag-dev-sec/tpotce#184]
If I understand correctly, T-Pot uses hardcoded certificate (Internet Widgits Pty Ltd, Some-State, AU,...) in nginx that is serving Kibana management interface. Would it be good idea to randomize that one or let the user to configure it during the T-Pot image creation or T-Pot (auto)installation? Changing the certificate afterwards is possible, but then I would like to have a notice about this to installation procedures.

**Comment by t3chn0m4g3** [comment]
@uolevi This is not hard-coded. You may freely exchange the certificate which resides in `/etc/nginx/ssl/nginx.*`

**Comment by uolevi** [comment]
True. Exchanging is possible, as I said in mylast sentence. Perhaps we understand hard coding differently, see "hard coding" from Wikipedia. Same comment goes to other questions (ports + IP ranges).

Would it then be possible to modify text "As mentioned before, the system was designed to be low maintenance. Basically, there is nothing you have to do but let it run." so that it proposes first to modify the default configs (in this the certificate) to prevent fingerprinting?

**Comment by t3chn0m4g3** [comment]
We are using openssl default values for the certificate, which are common on so many systems that trying to fingerprinting them is equivalent to find the needle in the haystack.

If you are still concerned you may modify ports or exchange the certificate.

**Comment by whalehub** [comment]
@t3chn0m4g3 I replaced the default certificates with my own certificates and restarted the VM, but after the restart, the server is still presenting the default certificates. My own certificates were still there after the restart. I also noticed that the path /etc/nginx/ssl doesn't exist on my fresh installation, instead I found the default certificates in /data/nginx/cert.

Do you have any idea what I could be doing wrong? Are there perhaps multiple places where those default certificates have to be replaced?

**Comment by whalehub** [comment]
@t3chn0m4g3 Any update on this?

**Comment by t3chn0m4g3** [comment]
NGINX certificate resides in `/data/nginx/cert`. Just exchange it and you are good to go. However Cockpit is not related to this. Please check out the Cockpit documentation on how to do this.
