### ISSUE TITLE
Getting rid of hardcoded stuff: hardcoded management IP address ranges

### ISSUE THREAD

**Issue by uolevi** [dtag-dev-sec/tpotce#185]
If I understand correctly, T-Pot allows SSH password authentication to management SSH port from RFC1918 networks. Would it be good idea to let user to configure these IP address ranges or even specific IPs during the T-Pot image creation or T-Pot (auto)installation? Configuration of OpenSSH server is possible to do afterwards, as well as using local firewall, but then I would like to have a notice about this to installation procedures.

BTW, are the same ranges for web management interface?

**Comment by t3chn0m4g3** [comment]
@uolevi Nothing ist hard-coded. You may freely adjust configs to your likings after T-Pot has been installed.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
