### ISSUE TITLE
Script makeiso.sh does not work due to ISO Mount as R/O

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#186]
Hi Team,

When running the makeiso.sh script within build 17.10, the following error is generated:

mount: /tmp/tpotce/tmp: WARNING: device write-protected, mounted read-only

Attempting to use mount -o,rw loop does not work, reports bad usage. Research shows that ISO's are non-mountable as RW.

Can you please confirm this is the case and how we can resolve this? Running this script on Kali Linux as root.

Appreciate the assist!

Cheers,
Ray

**Comment by UncleRaymondo** [comment]
Never Mind... It seems like Kali Linux does not have mkisofs claiming it has been replaced. Replacing the command mkisofs in makeiso.sh with genisoimage, leaving all other switches the same, seems to work and build successfully. 

About to test this new ISO now, will report back shortly...

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo Only Ubuntu is supported.

**Comment by UncleRaymondo** [comment]
That seems to be the case as the makeiso script didn't seem to copy my customised configuration across... all good, will try on a ubuntu native system later :)
