### ISSUE TITLE
update to ES breaks tpot functionality 

### ISSUE THREAD

**Issue by seccentral** [dtag-dev-sec/tpotce#188]
Basically updating es to 6.2.2 gives errors similar to these:

`Rejecting mapping update to [logstash-2018.03.13] as the final mapping would have more than 1 type: [Honeytrap, P0f] 
`
tpot is 17.10. Obviously this breaks functionality completely. since no data can be inserted in es and the dashboards are totally broken.

**Comment by t3chn0m4g3** [comment]
Why is that an issue of T-Pot?

**Comment by seccentral** [comment]
hmm i'm just saying it doesnt work with latest ES. and if you want to update tpot to use latest ES you should keep this in mind.

**Comment by seccentral** [comment]
As it stands right now, unless i become an es guru overnight i don't think i have a choice but to revert to 5.x So yes, it is a very important thing to consider in 18.10 if you want to use the 6.x version. Also, do you have an eta on 18.10 ?

**Comment by t3chn0m4g3** [comment]
Yes, last week of October / first week of November (18.10).
18.04 (last week of April / fist week of May) will focus on latest Ubuntu LTS (18.04) which looks currently very promising.

**Comment by t3chn0m4g3** [comment]
T-Pot 18.x will use ELK 6.x
