### ISSUE TITLE
Installation fails with "Unable to install selected kernel" message

### ISSUE THREAD

**Issue by aikinci** [dtag-dev-sec/tpotce#19]
While trying to install from the prebuild image http://community-honeypot.de/tpot.iso I get this error message. I have tried it twice but no luck.
![virtualbox_tpot_11_03_2016_16_11_10](https://cloud.githubusercontent.com/assets/995116/13704408/73a5100e-e7a4-11e5-9b6c-3ef6128239ee.png)
![virtualbox_tpot_11_03_2016_16_14_49](https://cloud.githubusercontent.com/assets/995116/13704410/741f7dda-e7a4-11e5-9308-e9a161d985dc.png)

**Comment by t3chn0m4g3** [comment]
Can you provide some more information about your environment? VMWare, VirtualBox? Do you have at least 4GB of RAM and 64GB of free diskspace?

**Comment by aikinci** [comment]
I have used your suggested settings and I am using VirtualBox but I had a clue so I used another location rather than turkey and it worked. I guess the local mirror is missing files.  Thanks!
