### ISSUE TITLE
Support for ET Pro rules in Suricata Docker Image?

### ISSUE THREAD

**Issue by xECK29x** [dtag-dev-sec/tpotce#193]
Didn't see this asked but is there a way I can modify the Suricata docker image to enable the download/use of the ET Pro ruleset? Can this be added to future TPot setups by asking for an Oinkcode during install?

Thanks!

**Comment by t3chn0m4g3** [comment]
I have no means to test or monitor this since I do not have permanent access to ET Pro. Suggestions? With regard to T-Pot, what is your take on added value if we supported this?

**Comment by xECK29x** [comment]
It's more-so just another place for me to get value out of a subscription I already have access to. Would say if this rule-set were to be enabled for use support would be put back on the user (me). I wouldn't expect you guys to test anything additional then you already do with ET-Open.  I would just like to have the option. Based on my experience with the rule-set I believe there would be nice additional context/telemetry gained.

**Comment by t3chn0m4g3** [comment]
Included ET Pro support for 18.04, please check if that works for you ... (I do not know if the rules names are the same)
```
git clone https://github.com/dtag-dev-sec/tpotce -b 18.04
cd docker/suricata
vi docker-compose.yml (add your oinkcode)
docker-compose up --build
```

**Comment by xECK29x** [comment]
You guys are awesome, will this out and report any problems!

**Comment by xECK29x** [comment]
You guys are awesome, will this out and report any problems!
