### ISSUE TITLE
Can't connect the elasticsearch

### ISSUE THREAD

**Issue by weiyuchen** [dtag-dev-sec/tpotce#195]
![_20180328215249](https://user-images.githubusercontent.com/9763862/38033392-87b08fb2-32d2-11e8-9a1e-a51574d6f3da.png)
hello, I'm confused now, as you can see in the picture, I can't connect the elasticsearch, and I tried to modify the elasticsearch.yml, but I found the http.host is 0.0.0.0, it's not a local url, so I don't change it

**Comment by t3chn0m4g3** [comment]
The way I see it you are trying to connect to Elasticpot. Please review the README for detailed port descriptions.

**Comment by weiyuchen** [comment]
too much thanks, I tried this morning and I found it was the configuration's problem, I didn't have normal user in my server before, and I have only 4G memory, but I chose the fully installation, it might be a problem too, anyway, thanks for your reply
