### ISSUE TITLE
T-Pot Deployment

### ISSUE THREAD

**Issue by jtorrejon** [dtag-dev-sec/tpotce#196]
Hi team,

I was wondering into deploy T-Pot into my company, but I have a doubt about it.

I've seen that there are 4 types of installation, but before doing anything, I want to ask if there is any chance to deploy the ELK stack in one machine, and all the honeypots in another machine.

My purpose is to reinitialize the machine with the sensors everyday, and to maintain all data collected into the ELK machine.

Many thanks and kind regards,

**Comment by t3chn0m4g3** [comment]
Out of the box we do not support a distributed installation. This has been discussed in different issues, please use the search function :bowtie:
