### ISSUE TITLE
Fresh Installation

### ISSUE THREAD

**Issue by seantree** [dtag-dev-sec/tpotce#199]
Hi I am running Amazon EC2 and ubuntu 16 Version and running T-pot 16.10 just want to know, how to do fresh installation of latest of T-pot without losing the data.
.
Thanks & Regards
Seantree

**Comment by t3chn0m4g3** [comment]
T-Pot 16.10 is no longer supported.
```
git clone https://github.com/dtag-dev-sec/t-pot-autoinstall -b 16.10
```
The install script however will not run for a second time unless you modify it and compensate for duplicates or erasing your old data.
