### ISSUE TITLE
Initial tsec credentials not working

### ISSUE THREAD

**Issue by vallagenah** [dtag-dev-sec/tpotce#20]
Hi,
I successfully installed the T-Pot 16.03 system with Ubuntu 14.04.4 LTS. I had windows OS installed with Symantec disk encryption in the same PC. But the problem is when I boot the TPot, the login screen appears and it denies the login:tsec password:tsec credentials. What can I do?

**Comment by t3chn0m4g3** [comment]
@vallagenah Do you mean the T-Pot login screen or Pre-Boot-Authentication screen of Symantec disk encryption? Can you please provide a screenshot and drag it into your post? Also press CTRL+F2 and provide also a screenshot and to check if the containers are running.

During installation all partitions which are found by the Ubuntu installer are unmounted, a new disk layout created and the new partitions formatted. It would be really interesting to learn more about the fact that username **tsec** and password **tsec** are not working.

Please also check the [tutorials](https://youtu.be/0ib7MG28ag0?list=PLBRkfSbyxi-ArIfQv-3XOaKun1UpZnr0X).

**Comment by firepro20** [comment]
Hi Marco I was running the TPOT for 4 hrs and suddenly the elastic search became fatal and this is what resulted in local host address. What can I do?
![df](https://cloud.githubusercontent.com/assets/17837413/13762770/726bd73c-ea41-11e5-8384-13cb09819ac6.png)

**Comment by t3chn0m4g3** [comment]
Please login to T-Pot and run `sudo status.sh` and provide a screenshot of the output. Also need a screenshot of `htop` and the `/data/elk/log/elasticsearch.log`. What are the specs for your VM? At least 4GB RAM and 64GB diskspace?

**Comment by t3chn0m4g3** [comment]
@firepro20 Closing this issue as not related to original question, please post a new issue. Thanks.

**Comment by firepro20** [comment]
![image](https://cloud.githubusercontent.com/assets/17837413/13763041/8f04dc7a-ea43-11e5-9bff-cd787b6d7d61.png)

![image](https://cloud.githubusercontent.com/assets/17837413/13763057/b05849de-ea43-11e5-8699-8db53eb95709.png)


for the log file there is nothing in the directory

**Comment by t3chn0m4g3** [comment]
@firepro20 Please open a new issue, BTW screenshots are the same as in original post.

**Comment by t3chn0m4g3** [comment]
@vallagenah Issue resolved for you?

**Comment by vallagenah** [comment]
Somehow the issue remains when installed on the hardware. On the hardware, it keeps trying mounting from CD-Rom even if I am using bootable USB. Sometimes the DHCP auto configuration does not work. But it works on VM using virtual box.

**Comment by t3chn0m4g3** [comment]
What type of hardware are you using? What is your hardware / components (motherboard,NIC, hard drive, ssd, RAM, CD-ROM, etc.) configuration? Did you use the downloaded ISO or did you use the ISO creator? Have you tried burning the ISO to a CD? What is your DHCP situation, do you run your own DHCP server, internet router? Can you install Ubuntu 14.04.4 without any problems on that machine?
So far we had no issues using Intel NUCs (which is the only hardware platform we do officially support).
