### ISSUE TITLE
White-list / Ignore Certain IPs

### ISSUE THREAD

**Issue by Sn00zr** [dtag-dev-sec/tpotce#200]
### Baisc support information

- What T-Pot version are you currtently using?
17.10
- Are you running on a Intel NUC or a VM?
VM
- How long has your installation been running?
Couple months
- Did you install any upgrades or packages?
No
- Did you modify any scripts?
No

Quick question here... I have scheduled vulnerability scans occurring from internal IPs (/32). Is there any way I can white-list or ignore these IPs from the HoneyPot? I have not looked too deep into it, but I assume IPTables would suffice in this scenario? Any input is appreciated.

**Comment by t3chn0m4g3** [comment]
Yes, iptables should do the trick.

**Comment by Sn00zr** [comment]
Just using `iptables -A INPUT -s IP-ADDRESS -j DROP` should do the job right?

**Comment by t3chn0m4g3** [comment]
Sorry, but please understand that your issue is not specifically related to T-Pot and there are lots of resources on the net with regard to iptables. Just bare in mind to make the changes in `/etc/systemd/system/tpot.service`. Thank you.
