### ISSUE TITLE
Spoofing

### ISSUE THREAD

**Issue by packet808** [dtag-dev-sec/tpotce#202]
Hi Tpot Team,

I just ask  if we can modify the system for website spoofing, instead of tpotweb.html as the default page it will be change as spoofing webpage. e.g. samplespoof.html

Do you think it there will be a conflict to the T-POT functionality?

Your utmost reply is appreciated.  

Thank you.

Note: Let me know if there some clarification?

**Comment by t3chn0m4g3** [comment]
@packet808 That's what Glastopf and Dionaea are for, the admin webpage and ports should not be exposed to the internet.

If you want to establish a spoofed website you can do so by modifying the `/opt/tpot/etc/tpot.yml` sections for glastopf / dionaea and include your own webpages as a volume.
