### ISSUE TITLE
Change Kibana Password in T-Pot 17.10

### ISSUE THREAD

**Issue by postoffice0815** [dtag-dev-sec/tpotce#206]
First of all a big compliment to you guys and your awesome work on the T-Pot.

I have one T-Pot installed on VM-Ware Workstation and did some config on the web-honeypots to look more like a company system. Now I would like to clone this VM 5 times and and deploy them to several departments, but with different passwords for the several dashboard users.
To be clear, I dont need 5 different users on one T-Pot-dashboard, I just want to provide them with different passwords.

Greetings :-)

**Comment by t3chn0m4g3** [comment]
Thank you.

Please have a look at #157

**Comment by postoffice0815** [comment]
Thank you! That was fast,... and helpful.

Works!

**Comment by t3chn0m4g3** [comment]
Your assumption is correct and at this point we do not plan to integrate X-Pack. Even with Kibana 6.3 you will need a paid license for user management to work.
