### ISSUE TITLE
T-Pot

### ISSUE THREAD

**Issue by praveen739** [dtag-dev-sec/tpotce#208]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?
I was able to set up and starting running the tpot. Now i am looking for documentation to explore tpot and its different components. I am new to tpot and would like to see some kind of documentation or videos that hights lights how , what , when , where and other simple things that you come across. What i was looking for is some kind of manual that could be downloaded or watched. I have searched and have not been able to locate it. I can't even located my IP address so i can log in , ipconfig is the command. So where can i find it ??

**Comment by t3chn0m4g3** [comment]
All the documentation / videos available is either written or linked in the [README.MD](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).

If T-Pot had direct access to the internet during setup you should see a login screen like featured in the video:
[![T-Pot 17.10](https://img.youtube.com/vi/G-_OabDowFU/0.jpg)](https://youtu.be/G-_OabDowFU?t=56s)

Otherwise, something went wrong, see issue #210 for infos I need.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, otherwise feel free to reopen.
