### ISSUE TITLE
why open the web console display as a blank page after the installation

### ISSUE THREAD

**Issue by u-raison** [dtag-dev-sec/tpotce#210]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [x] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [x] Check the [FAQ](#faq)
- [x] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?   T-Pot 17.10
- Are you running on a Intel NUC or a VM?  VM
- How long has your installation been running? 1 day
- Did you install any upgrades or packages? T-Pot 17.10 is last version , I should not need to install the upgrade bag, right?
- Did you modify any scripts? No
- Have you turned persistence on/off? No, I don't know how to turn it on or off.
- How much RAM available (login via ssh and run `htop`)?  213M/3.84G ，large free mem
- How much stress are the CPUs under (login via ssh and run `htop`)? 
- How much swap space is being used (login via ssh and run `htop`)? 0k/7.63G
- How much free disk space is available (login via ssh and run `sudo df -h`)? Avail 53G  used 5.3G
- What is the current container status (login via ssh and run `sudo start.sh`)? where is the start.sh ? I use `find / -name start.sh` command can't find it. but I execute `sudo ./dps.sh` show  all Status of  honeypot(columns fields)  is `down`

I installed T-pot on Ubuntu Server. The Ubuntu Server can go to internet, but no mapping to Internet.

after installation. I login the web console with password.  I can only see  pink Tab.  Then I try clicking  all the tabs also display blank page. Only WebTTY can be used normally.

and I trying excute dps.sh. All status is "down",  why ? Is it because the honeypot does not have any attack data? Or am I installing wrong?

![honeypot error](https://user-images.githubusercontent.com/39359901/40159300-418dd71c-59db-11e8-8870-11ed5c52cdd6.png)

![status](https://user-images.githubusercontent.com/39359901/40337618-255cbf42-5da3-11e8-8867-b6e15b094118.png)

**Comment by u-raison** [comment]
@t3chn0m4g3

**Comment by t3chn0m4g3** [comment]
Please fill out the basic support information (the stuff you deleted, when you opened the ticket :bowtie: ) and also the output of:
```
sudo su -
dps.sh
htop
glances
ctop
docker images
docker ps -a
journalctl -xe
systemctl status tpot
```

**Comment by u-raison** [comment]
@t3chn0m4g3 

Thank you for your reminding. I have completed the basic information. The following is the output of the execution command .I did not make any configuration  changes after installation.

![ctop](https://user-images.githubusercontent.com/39359901/40337788-1c592d4e-5da4-11e8-9ad6-6a42054b8468.png)
![docker imgages](https://user-images.githubusercontent.com/39359901/40337789-1cb2818c-5da4-11e8-8e93-379c4d748ff0.png)
![docker ps](https://user-images.githubusercontent.com/39359901/40337790-1ce527d6-5da4-11e8-9b42-4d6b3d085f45.png)
![glances](https://user-images.githubusercontent.com/39359901/40337792-1d2c322a-5da4-11e8-9904-3f83b42d2aeb.png)
![htop](https://user-images.githubusercontent.com/39359901/40337794-1d8fef2c-5da4-11e8-9b0e-40275646a58f.png)
![j](https://user-images.githubusercontent.com/39359901/40337795-1dc3a59c-5da4-11e8-900e-83d201882ce6.png)
![status](https://user-images.githubusercontent.com/39359901/40337796-1df581f2-5da4-11e8-81b7-fc50ff23e35c.png)
![systemctl](https://user-images.githubusercontent.com/39359901/40337797-1e296efe-5da4-11e8-8e4d-461a86cce1db.png)

**Comment by t3chn0m4g3** [comment]
From the looks of it `docker-compose` was not installed during installation. Were all internet checks passed successfully before the installation of T-Pot was started?

Have you tried a reinstallation?

**Comment by u-raison** [comment]
@t3chn0m4g3 

I am in China that access to foreign networks may be very slow, The installation time is very long, So I not stay in front of the computer,when I go back to computer. It has been installed, T-pot shows the terminal interface waiting for me to enter the `tsec` password. So I think it's finished successfully .if not, Can I continue to complete the installation for `docker-compose`?

**Comment by t3chn0m4g3** [comment]
yes,
```
sudo su -
systemctl stop tpot
pip install --upgrade pip
pip install docker-compose ctop
```

**Comment by u-raison** [comment]
@t3chn0m4g3  Thank you very much. The problem has been solved!
