### ISSUE TITLE
Do you recommend deploying sensor (install all honeypots) in production VLAN or Separate VLAN?

### ISSUE THREAD

**Issue by masifpak** [dtag-dev-sec/tpotce#213]
Hi,

My question does not directly relate to the repo but it still concern as a technical point of view.

**Comment by t3chn0m4g3** [comment]
The idea of a honeypot is to actually place it in an productive environment so it can act as a decoy and attract attackers. You have decide for yourself if and where to place it so it gives you as much return value as possible.
