### ISSUE TITLE
using external elasticsearch/kibana instances

### ISSUE THREAD

**Issue by killbartonking** [dtag-dev-sec/tpotce#214]
hi there. i looked through older issues and couldn't find anything- i was able to get the logstash container outputting to my personal elasticsearch instances, however, found that that i was missing data and search fields, both of which were present in the kibana instance included with tpot. it looked as though i was only getting PAM logs.

is there anything that needs to be done aside from setting the hosts variable in logstash.conf to a different instance?

thanks.

**Comment by t3chn0m4g3** [comment]
You need to copy the `logstash.conf` from the container to the host, add your `elasticsearch` host and / or adjust to your needs. Then modify `/opt/tpot/etc/tpot.yml` and add the modified `logstash.conf` as volume. If you need to use a FQDN, just add it to the `tpot.yml` as extra host.

[Example logstash.conf](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-hosts):
```
output {
  elasticsearch {
    hosts => ["myelasticsearch:9200"]
  }
```

Example `tpot.yml`, add this to the logstash service:
```
    extra_hosts:
      - myelasticsearch:1.2.3.4
```

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by wilsonchandra** [comment]
Hi There,
I am interested to using external elasticsearch/kibana instances.

Additionally, I would like to copy the entire dashboards to the external kibana.
What should be done?

On a clean install ELK stack, I have tried using kibana > management > saved objects > export
Then on importing, I got error messages like:
Saved Objects: Importing ConPot Response - Top 10 (ConPot-Response-Top-10) failed: Could not locate that index-pattern-field (id: response.keyword)

Thanks

Thanks

**Comment by wilsonchandra** [comment]
Hi There,
I am interested to using external elasticsearch/kibana instances.

Additionally, I would like to copy the entire dashboards to the external kibana.
What should be done?

On a clean install ELK stack, I have tried using kibana > management > saved objects > export
Then on importing, I got error messages like:
Saved Objects: Importing ConPot Response - Top 10 (ConPot-Response-Top-10) failed: Could not locate that index-pattern-field (id: response.keyword)

Thanks

**Comment by wilsonchandra** [comment]
I have found a way to import the kibana visualizations:
1. Clone tpotce to /opt/tpot
2. sudo apt install jq
3. cd /opt/tpot/bin
4. edit the import_kibana-objects.sh, change myES to point to your ES url
5. bash import_kibana-objects.sh ../etc/objects/kibana-objects.tgz 

Upon successful transfer, this should be the output:
### Statistics
###### Imported 384 index patterns. 
###### Imported 14 dashboards. 
###### Imported 161 visualizations. 
###### Imported 17 searches.

**Comment by wilsonchandra** [comment]
I have found a way to import the kibana visualizations:
1. Clone tpotce to /opt/tpot
2. sudo apt install jq
3. cd /opt/tpot/bin
4. edit the import_kibana-objects.sh, change myES to point to your ES url
5. bash import_kibana-objects.sh ../etc/objects/kibana-objects.tgz 

Upon successful transfer, this should be the output:

```
### Statistics
###### Imported 384 index patterns. 
###### Imported 14 dashboards. 
###### Imported 161 visualizations. 
###### Imported 17 searches. 
```

**Comment by LandonStewart** [comment]
> You need to copy the `logstash.conf` from the container to the host...

Can you elaborate on what exactly this means?  Do I copy `/opt/tpot/docker/elk/logstash/dist/logstash.conf` to somewhere before modifying it?

**Comment by wilsonchandra** [comment]
One way is to copy the logstash.conf from logstash docker to the host machine.
Then, to edit the tpot.yml for the logstash docker to import the logstash.conf from the host machine.
