### ISSUE TITLE
Extract "Honeypot Source IP - Top 10"

### ISSUE THREAD

**Issue by Zacktarus** [dtag-dev-sec/tpotce#215]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [x] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [x] Check the [FAQ](#faq)
- [x] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 17.10
- Are you running on a Intel NUC or a VM? dell server
- How long has your installation been running? since 07/05
- Did you install any upgrades or packages? no
- Did you modify any scripts? yes, for ssh access and "Community Data Submission"
- Have you turned persistence on/off? yes, on
- How much RAM available (login via ssh and run `htop`)? 21Gb
- How much stress are the CPUs under (login via ssh and run `htop`)? ...
- How much swap space is being used (login via ssh and run `htop`)? ...
- How much free disk space is available (login via ssh and run `sudo df -h`)? ...
- What is the current container status (login via ssh and run `sudo start.sh`)? ...

Hello there...

The T-pot is in production since 07/05 and it's works perfectly. Great job! it's exactly what I need for my purpose... 

I know where the datas/logs are stored but i'd like to extract "the Honeypot Source IP - Top 10"...
I could "save as" the .csv file, but i have to automate the process.
Can you tell me how I can obtain these Top 10 IP adresses?

Thanks a lot!
Zack.

**Comment by t3chn0m4g3** [comment]
Thank you :bowtie: 

You cannot access this directly, you need to build your own ES queries. Examples on how to communicate with ES can be found in `/opt/tpot/bin`. [JQ](https://stedolan.github.io/jq/) is your best friend from this point on 😃

**Comment by Zacktarus** [comment]
Hello,
I don't know well ELK stack... :S ... but I'll try JQ to manipulate JSON data logs.
Thanks!

**Comment by t3chn0m4g3** [comment]
You are welcome 😄
