### ISSUE TITLE
Duration of Attacks

### ISSUE THREAD

**Issue by mrcokito** [dtag-dev-sec/tpotce#217]
Hi,

I have been trying for a long time to show in Kibana the duration of attacks on a honeypot, but I do not get it in any way.

Could you briefly explain how to do it, please?

Thank you.

KR
Carlos.

**Comment by t3chn0m4g3** [comment]
AFAIK there is no default function / plugin available to do this in Kibana.

**Comment by mrcokito** [comment]
Okay thanks you. There is no problem, I will can survive :)
Your project is very well, it help me a lot in my final degree project.

KR
Carlos.
