### ISSUE TITLE
downloading is very slow in my country

### ISSUE THREAD

**Issue by ksufer** [dtag-dev-sec/tpotce#218]
### so, what should i do to accelerate the downloading?
for example, can i download the ubuntu's full iso before making tpot.iso?

**Comment by schmalle** [comment]
Hmm hard to say as we dont know, what is the bottleneck , as eg I suppose dockerhub etc are connected with high bandwidth. What is slow exactly ,the iso, the docker images dl ?
Best wishes
Markus

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved due to inactivity.
