### ISSUE TITLE
Question about "ews.cfg"

### ISSUE THREAD

**Issue by Zacktarus** [dtag-dev-sec/tpotce#219]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [x] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [x] Check the [FAQ](#faq)
- [x] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 17.10
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages? just "update.sh"
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?
- - - - - - - - - -
Hi all,
Always in the way to extract data's and make reports of the IP adresses who are attack T-pot...

- It's possible to modify the file "ews.cfg" to send repport to a specific email adresses?

I've check the FAQ 17.10 "Reconfigure ews.cfg" but I'm not shure to understand it correctly...
Can you describe me this file more in details?

Thanks so much for your patience... :)

**Comment by t3chn0m4g3** [comment]
Alerts will be sent using the EWS protocol. The eMail address from `ews.cfg` has nothing to do with the remote reciever. You can setup your own EWS based backend however, check out [PEBA](https://github.com/dtag-dev-sec/PEBA)

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved. Please feel free to reopen should that not be the case.
