### ISSUE TITLE
 Elasticsearch plugin is red Error

### ISSUE THREAD

**Issue by seantree** [dtag-dev-sec/tpotce#220]
Hi, 

Kibana is not loading properly
![elastic error issue](https://user-images.githubusercontent.com/29730058/41290872-bf6acde4-6e6b-11e8-853a-8833cc56ec6a.png)

Everything is running but why I am getting an error?
![all working](https://user-images.githubusercontent.com/29730058/41290867-bafe5a50-6e6b-11e8-83be-e6821a678e0a.png)

**Comment by t3chn0m4g3** [comment]
https://github.com/dtag-dev-sec/tpotce/issues/212

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved. Please feel free to reopen should that not be the case.
