### ISSUE TITLE
Downloading iso WIN10 home dead link

### ISSUE THREAD

**Issue by nusasw** [dtag-dev-sec/tpotce#225]
Hey ,
Not sure but if the iso isnt Ready yet? what can i do at my Computer?

 :)

Thank you :smiley:

-

**Comment by t3chn0m4g3** [comment]
[releases](https://github.com/dtag-dev-sec/tpotce/releases/tag/17.10)

**Comment by t3chn0m4g3** [comment]
assuming this is resolved, please feel free to open a new issue should that not be the case.
