### ISSUE TITLE
Login fail , first login 17.10

### ISSUE THREAD

**Issue by nusasw** [dtag-dev-sec/tpotce#227]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues
Hey again,
i m not sure what happens here, after pc boot the first Login screen : 
tieped Login: (showed) [pass] like descriebed and
tieped Password: (isn t showed anyway) [pass] like descriebed.

wich results in : incorrect attemped
:(
help?

Thank you :smiley: 

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

**Comment by t3chn0m4g3** [comment]
On the console, username is `tsec` and `password` is what you set it up to be during the installation. For the web console (`https://<your_ip>:64297`) username and password is what you chose during the installation.

**Comment by nusasw** [comment]
yeah,
fine now i watched the you tube tpot 17.10 too. When tieping 
tsec
********

dps.sh
.
.
.

dps.sh 2 (here s the thing)

the displayed loops !? and not a window.

#[Service]
Restart=always
RestartSec=5
TimeoutSec=infinity 
----set

I installed from the iso i burned like i said on a Win10
(thought Things wrong?!)
don t understand,

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
