### ISSUE TITLE
Issue: Log controller

### ISSUE THREAD

**Issue by ikermuniz** [dtag-dev-sec/tpotce#228]
Hello,

We are using Tpot 17.10 on a Intel machine.

We know that each honeypot (Honeypot_x) creates each log at /data/Honeypot_x. But we don't know exactly which container/system is in charge of parsing the logs/controlling?

**Comment by t3chn0m4g3** [comment]
@ikermuniz Thank you for joining the T-Pot community.
1. Logs are controlled via a SystemD start script `/etc/systemd/system/tpot.service` which in turn uses `/opt/tpot/bin/clean.sh` and `/opt/tpot/etc/logrotate/logrotate.conf` to control the logs.
2. The logs are fed to the ELK stack by the `logstash` container and fed to the community using the `ewsposter` container.

**Comment by t3chn0m4g3** [comment]
According to the 👍 I am assuming this is resolved :bowtie:
