### ISSUE TITLE
Post My tpot data to json for visualization

### ISSUE THREAD

**Issue by EsenkayShady** [dtag-dev-sec/tpotce#229]
I would like to post my own data in json format and make it appear like this https://community.sicherheitstacho.eu/alert/retrieveAlertsJson?, for attack visualization within our network infrastructure, could you please help?

**Comment by vorband** [comment]
If you *only* want the json feed and integrate it into your own visualization (our map is not open source), you could run our open source backend application [PEBA](https://github.com/dtag-dev-sec/PEBA) and redirect your T-Pot data to your own domain. 

Note that we do not have something like a tutorial and we do not provide extensive support for this, but the basic steps are: 
- Install Backend Server: 
  - Have a spare Ubuntu 16.04 server, install elasticsearch, memcached and PEBA. 
  - Setup and run PEBA using ansible - read the docs available, you need to tweak the `/ansible/hosts` and possibly the `/ansible/roles/` according to the desired setup. Note that this is tailored to our environment, so you *will* need some tweaking.
  - Add a user for your honeypots using `/misc/add-user.py` (to be used in ews.cfg, see below)

- On your T-Pots, redirect the ewsposter output to your domain running PEBA: 
  - Create your own [ews.cfg,](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/ews/dist/ews.cfg) on each T-Pot, change rhost_first/rhost_second to your domain running PEBA, adjust username / token to your setup
  - Copy ews.cfg to /data/ews/conf/ews.cfg
  - Edit /opt/tpot/etc/tpot.yml, add the following line at the end of the ewsposter section
     `- /data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg`
  - Restart tpot service `service tpot restart` 
  - Your T-Pot should be submitting to your PEBA server and you can query the json feed using `<your-domain>/alert/retrieveAlertsJson`.


Hope this helps and gives you an idea of what needs to be done. However this is not as simple as a config change.

**Comment by t3chn0m4g3** [comment]
Alternatively search the issues there are lots of examples on how to adjust `logstash.conf` to forward JSON logs to a central ELK instance.

**Comment by EsenkayShady** [comment]
Ok, thanks, lemme research on this

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved. Closing for now.

**Comment by EsenkayShady** [comment]
I'm glad you helped :)

**Comment by t3chn0m4g3** [comment]
Welcome :)

**Comment by EsenkayShady** [comment]
Hi Marco, once again I come with my annoying questions. I re-embarked back
to the project and it seems things changed. For example I hant find
/data/ews/conf/ews.cfg, PEBA doesn't work e.t.c. Are you in a position to
help me?? We can agree on compensation.

**Comment by t3chn0m4g3** [comment]
Please check the Wiki on how to reconfigure [ews.cfg](https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-ews.cfg).
Open PEBA related questions / issues in the [PEBA repo](https://github.com/dtag-dev-sec/PEBA) please.
Thank you.

**Comment by EsenkayShady** [comment]
Thanks, on it

**Comment by EsenkayShady** [comment]
Hey, here I come again. Apologies for bagging you a lot though.
My question is, after changing where the logs are sent, example, my server.
How do I test whether the logs are coming in, is there a command I can run
to see the traffic, example should be something like tcpdump and to which
port. Kindly if you don't mind.

Also if you can share your direct contacts, skype or email. Thanks
