### ISSUE TITLE
T-Pot 17.10 configuration

### ISSUE THREAD

**Issue by cheo2322** [dtag-dev-sec/tpotce#230]
- What T-Pot version are you currtently using? 17.10
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? 1 week
- Did you install any upgrades or packages? Just ./update.sh -y from /opt/tpot
- Did you modify any scripts? No
- Have you turned persistence on/off? no
- How much RAM available (login via ssh and run `htop`)? 5.95G
- How much stress are the CPUs under (login via ssh and run `htop`)? 13%
- How much swap space is being used (login via ssh and run `htop`)? 0K/7.63G
- How much free disk space is available (login via ssh and run `sudo df -h`)? 95%
- What is the current container status (login via ssh and run `sudo start.sh`)? sudo: start.sh: command not found

Hi Sir, first I think this is a great project from all points of view.

Then, I have a lot of questions about it, but depending on the first answer, I will make or not more questions.

1) The dockerized honeypots (conpot, emobility, ...) work in the same way as over an individual installation? I mean, the configuration, ports and all that issues.

2) (This question arises from your questions) Why I received that answer in the last script 'sudo start.sh'?

I am really sorry if these issues are so basic. I am just starting on this.

**Comment by t3chn0m4g3** [comment]
1) In 17.10 only Dionaea has some constraints. All other honeypots work exactly as their standalone counterparts. In 18.10 even Dionaea will work 100% like a stand-alone Installation.

2) Yes this is an artifact of an older version. Now `dps.sh`.

**Comment by cheo2322** [comment]
Thank you for your answers! It is a very interesting and useful contribution. Closing this issue...
