### ISSUE TITLE
How can I get email alert from Tpot

### ISSUE THREAD

**Issue by qidama** [dtag-dev-sec/tpotce#231]
How  can I get email alert from T-pot? 

<a name="info"></a>
### Baisc support information

- What T-Pot 17.10
-  running on VM?

**Comment by t3chn0m4g3** [comment]
T-Pot does not support eMail alerts out-of-the-box. You will need to adjust `logstash.conf` (search the issues lots of examples there) and setup a service like [alerta.io](http://alerta.io/). Somewhere in the issues / older releases you may find even examples for that.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved. Closing for now.

**Comment by furiiibond** [comment]
> How can I get email alert from T-pot?
> 
> ### Baisc support information
> * What T-Pot 17.10
> * running on VM?

Hello, did you manage to implement the email alerts in T-pot that would also greatly interest me ?

**Comment by TDanny** [comment]
I created a manual how to create and configure Mail Alerts for Tpot:

https://github.com/TDanny/Honeypot-Realtime-Mail-Alert-project

Enjoy , I hope you will find it useful.
