### ISSUE TITLE
Is there a way to retrieve ews-format XML file sent to the community?

### ISSUE THREAD

**Issue by WebSSH** [dtag-dev-sec/tpotce#233]
- What T-Pot version are you currtently using?
17.10

- Are you running on a Intel NUC or a VM?
VM

- How long has your installation been running?
7 days

- Did you install any upgrades or packages?
No

- Did you modify any scripts?
No

Hello!

Is there a way to retrieve ews-format XML file sent to the community?
Or are we required to parse each logs file in /data/* ?

Thanks for this awesome project!

**Comment by t3chn0m4g3** [comment]
@WebSSH Thank you :bowtie:
If you want to feed a central ELK, Splunk or just a large JSON it is best to use a modified `logstash.conf` and mount it into the `logstash` container. However this will not contain any malwares / attachments which are residing in `/data/*`.
You can of course run your own backend, check out the [PEBA](https://github.com/dtag-dev-sec/PEBA) repo.

**Comment by WebSSH** [comment]
@t3chn0m4g3 Thanks for your quick reply!

Finally the best way for me was to query the elasticsearch instance. 
All informations are stored there, so, I'm happy 😎

Nice day!
