### ISSUE TITLE
Redirect Traffic to a Cloud Setup

### ISSUE THREAD

**Issue by blackhatethicalhacking** [dtag-dev-sec/tpotce#234]
### Baisc support information

- What T-Pot version are you currtently using? 17.10
- Are you running on a Intel NUC or a VM? = Google Cloud - Installation on Ubuntu of the image you provide.
- How long has your installation been running? 1 month
- Did you install any upgrades or packages? no
- Did you modify any scripts? no
- Have you turned persistence on/off? no
- How much RAM available (login via ssh and run `htop`)? Cloud Server using 2 Xeon Skylake CPUs and 8.5GB Memory with SSD Drives
- How much stress are the CPUs under (login via ssh and run `htop`)? 47%
- How much swap space is being used (login via ssh and run `htop`)? we have over 40GB Free afte rinstallation
- How much free disk space is available (login via ssh and run `sudo df -h`)? we have over 40GB Free afte rinstallation

Hello, our question and assistance is needed for this.

Everything is working perfect, we installed on google cloud server through google console, by installing / upload the image from ubuntu, and installing tpot from that.

We tested that: if the google cloud server IP that has TPOT installation on it is working perfect, and we do tests, nmap, bruteforce, ping etc.. both in tpot/suricata everywhere it logs everything.

Lets say we want to add that server having TPOT in front of an IP Machine (Client).

How would we transfer the traffic to our honeypot on the cloud from the client or clients (they could have 10), so that TPOT can track also those machines if you ran nmap on their ip instead of the cloud.

I know, Windows/Mac/Linux could have 3 different techniques to do it, lets say its a home user and the router from ISP doesnt support forward of traffic, only ports.

You should do the transfer the traffic on client side? means if they have 1000 machines you got to do that?

Kindly let us know where to look for the solution or things we can do / so that our TPOT server on the cloud, after adding the IP / redirecting traffic to it (acting as MITM?) starts logging the attacks on those IP

**Comment by t3chn0m4g3** [comment]
You would need to make sure i.e. via iptables that the clients forward all traffic to your central T-Pot installation.

However Please be so kind to understand that T-Pot is not intended to be used as a central hub for multiple clients.

Please understand this is not an issue with T-Pot itself, I am closing this ticket.

Thank you.
