### ISSUE TITLE
how can I set my own honeypot auto_start when rebooting?

### ISSUE THREAD

**Issue by weiyuchen** [dtag-dev-sec/tpotce#235]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

I'm very interested in this project, so I put my own honeypot(built with docker) in the system and it can run well, but I notice that the system will reboot every morning, and I have to restart my own honeypot everyday.

I have tried to modify the rc.local and it didn't work well, so I'm here for  some help, too much thanks!

**Comment by weiyuchen** [comment]
I'm very interested in this project, so I put my own honeypot(built with docker) in the system and it can run well, but I notice that the system will reboot every morning, and I have to restart my own honeypot everyday.

I have tried to modify the rc.local and it didn't work well, so I'm here for some help, too much thanks!

**Comment by t3chn0m4g3** [comment]
Your honeypot must be started as part of the `docker-compose` configuration. You have to modify `/opt/tpot/etc/tpot.yml`.

**Comment by weiyuchen** [comment]
ok, I will solve it , thanks!

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved. If not please let me know.

**Comment by t3chn0m4g3** [comment]
@FarhanaYusaini Only x86_64 systems are supported.

**Comment by FarhanaYusaini** [comment]
can i install t-pot on rasbian ?

**Comment by t3chn0m4g3** [comment]
no

**Comment by FarhanaYusaini** [comment]
on raspberry pi direct also cant ?

**Comment by t3chn0m4g3** [comment]
no
