### ISSUE TITLE
Permission denied/output module setup failure on Docker image

### ISSUE THREAD

**Issue by alphaDev23** [dtag-dev-sec/tpotce#238]
From the Docker image dtagdevsec/suricata:1804 (and 1710), I receive the following errors below:

<Warning> - [ERRCODE: SC_ERR_INVALID_ARGUMENT(13)] - output module setup failed
<Error> - [ERRCODE: SC_ERR_FOPEN(44)] - Error opening file: "/var/log/suricata//eve.json": Permission denied

Full log below.
The following is the compose file.  
version: '2'
services:
  suricata:
    image: dtagdevsec/suricata:1804
    container_name: suricata
    restart: always
    network_mode: "host"
    cap_add:
    - NET_ADMIN
    - SYS_NICE
    - NET_RAW

I see nothing in the compose file that would trigger the above errors.  Why are the above errors triggered on Docker hub image, especially the permissions issue?

FULL log:
Attaching to suricata
suricata    | 31/8/2018 -- 18:17:25 - <Notice> - This is Suricata version 4.0.4 RELEASE
suricata    | 31/8/2018 -- 18:17:25 - <Info> - CPUs/cores online: 4
suricata    | 31/8/2018 -- 18:17:25 - <Info> - Found an MTU of 1500 for 'p2p1'
suricata    | 31/8/2018 -- 18:17:25 - <Info> - Found an MTU of 1500 for 'p2p1'
suricata    | 31/8/2018 -- 18:17:32 - <Info> - 53 rule files processed. 23191 rules successfully loaded, 0 rules failed
suricata    | 31/8/2018 -- 18:17:32 - <Info> - Threshold config parsed: 0 rule(s) found
suricata    | 31/8/2018 -- 18:17:32 - <Info> - 23208 signatures processed. 1199 are IP-only rules, 8460 are inspecting packet payload, 16345 inspect application layer, 106 are decoder event only
suricata    | 31/8/2018 -- 18:17:35 - <Info> - dropped the caps for main thread
suricata    | 31/8/2018 -- 18:17:35 - <Warning> - [ERRCODE: SC_ERR_INVALID_ARGUMENT(13)] - output module setup failed
suricata    | 31/8/2018 -- 18:17:35 - <Error> - [ERRCODE: SC_ERR_FOPEN(44)] - Error opening file: "/var/log/suricata//eve.json": Permission denied
suricata    | 31/8/2018 -- 18:17:35 - <Info> - Going to use 4 thread(s)
suricata    | 31/8/2018 -- 18:17:35 - <Notice> - all 4 packet processing threads, 2 management threads initialized, engine started.
suricata    | 31/8/2018 -- 18:17:35 - <Info> - All AFP capture threads are running.

**Comment by t3chn0m4g3** [comment]
This docker image only works in context of T-Pot, either 17.10 or 18.04 which is dev branch.
