### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by camaro23** [dtag-dev-sec/tpotce#239]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues
When installing TPot in Oracle VirtualBox, it finishes the install and performs the system reboot. However, it then reverts to the status that it was before the install was performed, and informs me that I need to run the install again. I have met all system requirements, has anyone else had this issue?

Thank you.

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
Did you have a look at the [Virtual Box installation video](https://www.youtube.com/watch?v=XpZBXlwrOZg&feature=youtu.be&t=175)?
Otherwise it sounds if the installation media needs to be ejected.

**Comment by camaro23** [comment]
I followed the Virtual Box installation and encountered the same issue. Do you have any more suggestions?

Thank you for the help.

**Comment by camaro23** [comment]
I did not. I am not sure what you mean by that, or how to perform that. Do you know of any instructional videos or articles?

**Comment by camaro23** [comment]
I have been using the ISO file you provide.

**Comment by t3chn0m4g3** [comment]
Yes, after installation you need to disable the .iso file from the config or it will always boot from the iso instead of the newly installed machine.

**Comment by camaro23** [comment]
That worked, thank you so much! However I have not received any hits that display in Kibana. Do I need to port forward port 64297 to the IP address that TPOT is running?

Thanks for the help!

**Comment by t3chn0m4g3** [comment]
Great. Please see the [Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md) for your other question.

Since the original issue is answered I am closing this issue.
