### ISSUE TITLE
Introduce SNARE & Tanner as optional image

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#24]
Eventually replace Glastopf with SNARE.

**Comment by synackpsh** [comment]
I find dionaea http and https handlers better to use thay SNARE.
I liked a lot the py script to replicate the content of a website.
But for instance I've tried some complex/heavy load web site, and dionaea serves them better both on HTTP an HTTPS than SNARE.

cheers

**Comment by t3chn0m4g3** [comment]
@0x7fff9 Thanks for sharing, I like the dork concept of Snare / Tanner very much which is the main reason why I want to exchange it.

**Comment by t3chn0m4g3** [comment]
Will be included in the next version of T-Pot.
