### ISSUE TITLE
Disable honeypots

### ISSUE THREAD

**Issue by camaro23** [dtag-dev-sec/tpotce#243]
Hey t3chn0m4g3,

What is the best way to disable some of the honeypots incorporated into Tpot? I am looking to set up Tpot in the environment, but I do not want to run all instances on Tpot.

Thanks for all your help!

**Comment by camaro23** [comment]
Do I just comment out the services I do not want running in the tpot.yml file?

**Comment by cryptax** [comment]
I'm not sure  it's the right way to do it, but personally I did a `docker stop` on the honeypots I did not want.

**Comment by kesaco-droid** [comment]
Hey ! Same question here. How did you finally solve it ? Did you find any solution like modify the tpot.yml with : restart:nver ?

**Comment by honeypuh** [comment]
Go into tpot.yml and just comment("#") the lines for the honeypots you want to shut down. 
then run the command "systemctl stop tpot" wait and turn it back on again with replacing stop to start.

**Comment by pdolinic** [comment]
Hi, even on both Standalone and Sensor+Hive I turned off as such in `tpot.yml`

```
## Mailoney service
#  mailoney:
#    container_name: mailoney
#    restart: always
#    environment:
#     - HPFEEDS_SERVER=
#     - HPFEEDS_IDENT=user
#     - HPFEEDS_SECRET=pass
#     - HPFEEDS_PORT=20000
#     - HPFEEDS_CHANNELPREFIX=prefix
#    networks:
#     - mailoney_local
#    ports:
#     - "25:25"
#    image: "dtagdevsec/mailoney:2204"
#    read_only: true
#    volumes:
#     - /data/mailoney/log:/opt/mailoney/logs
#
## Medpot service
#  medpot:
#    container_name: medpot
#    restart: always
#    networks:
#     - medpot_local
#    ports:
#     - "2575:2575"
#    image: "dtagdevsec/medpot:2204"
#    read_only: true
#    volumes:
#     - /data/medpot/log/:/var/log/medpot
#
```
after a full reboot you can still see them on `dps.sh` and on `docker ps` . 

Now one would do:
Even after stopping the container via `docker stop $ID` and `docker rmi -f $ID-Image` 
plus after  running `dps.sh` or `docker ps` you can still see containers even though they had their images removed.
