### ISSUE TITLE
Reinstallation instead of booting

### ISSUE THREAD

**Issue by Ropena** [dtag-dev-sec/tpotce#245]
### Baisc support information

- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? It has not run yet
- Did you install any upgrades or packages? NO
- Did you modify any scripts? NO
- Have you turned persistence on/off? NO
- How much RAM available (login via ssh and run `htop`)? 8 GB
- How much stress are the CPUs under (login via ssh and run `htop`)? None
- How much swap space is being used (login via ssh and run `htop`)? It has not booted yer
- How much free disk space is available (login via ssh and run `sudo df -h`)? 70 GB
- What is the current container status (login via ssh and run `sudo start.sh`)? Don't know

After the installation, the menu comes up and I choose to boot up, but instead it starts to install again. I have tried installing on both VirtualBox and VM with the same results. I am running my virtual box and VM on a Macbook Pro, 10 GB RAM 500 GB disk with the new Mojave OS:

**Comment by Ropena** [comment]
Have the 17.x and 16.10 versions of t-pot been tested on virtual box and/or VM Ware running on Mojave?

**Comment by t3chn0m4g3** [comment]
Have you tried to eject the install image?

**Comment by Ropena** [comment]
No, but I was suspecting as much. I will do that in the present install.

**Comment by Ropena** [comment]
Ahhh, it worked!

**Comment by t3chn0m4g3** [comment]
Great.

**Comment by Ropena** [comment]
But, I think something should be put into the installation program to warn of this. I have installed quite a few things in my VirtualBox and have never had to "eject" my media (.iso files).

**Comment by Ropena** [comment]
I have trouble logging into the "administrativegoruper login: I am trying to login with the tsec user and password I created when installing, but it says my login in incorrect. The web/browser interface works fine. Am I missing something?
