### ISSUE TITLE
Kibana does not start, issues and error code (0)

### ISSUE THREAD

**Issue by Ropena** [dtag-dev-sec/tpotce#247]
When I click on the Kibana tag on the main menu bar, I get this:

Script error. (:0)
Version: 5.6.9
Build: 15629
Error: Script error. (:0)
onerror@https://192.168.15.31:64297/kibana/bundles/commons.bundle.js?v=15629:90:22037

**Comment by t3chn0m4g3** [comment]
Did a fresh install. Works perfectly fine here.
