### ISSUE TITLE
to 18.04 fix update.sh ^_^

### ISSUE THREAD

**Issue by 0x01feng** [dtag-dev-sec/tpotce#248]
in the 18.04 

update.sh line 170
code:
`npm install "https://github.com/taskrabbit/elasticsearch-dump#9fcc8cc" -g`
fixd to:
`npm install "https://github.com/taskrabbit/elasticsearch-dump" -g`

iso/installer/install.sh 551
code:
`npm install https://github.com/taskrabbit/elasticsearch-dump#9fcc8cc  ..........`
fixd to:
`npm install https://github.com/taskrabbit/elasticsearch-dump  ...........`

^o^

**Comment by t3chn0m4g3** [comment]
Thank you for your contribution and noticing.

In the past we had some issues with es-dump which is why I pinned it to `9fcc8cc`. Will be pinning it to the latest available version upon release if testing shows no problems.

**Comment by t3chn0m4g3** [comment]
Solved with 3cca47b0f1db0934f1f2a9fb2139bfa14ebe221d
