### ISSUE TITLE
Surciata Implementation in T-Pot

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/tpotce#25]
The tool Suricata used in T-Pot does it just labelling traffic using signatures and letting it pass or else stopping traffic in some way?

For my research I need all traffic to pass. If it is stopping some traffic, is there a way to let it all pass?

Thankyou

**Comment by t3chn0m4g3** [comment]
Suricata on T-Pot runs purely in IDS mode, thus not blocking any traffic.

**Comment by schmalle** [comment]
Hi, It sees all traffic and passes it through, best wishes Markus

**Comment by firepro20** [comment]
Thankyou very much.
