### ISSUE TITLE
Suricata Rules Customization

### ISSUE THREAD

**Issue by camaro23** [dtag-dev-sec/tpotce#252]
Hello, 

I am attempting to remove some Suricata alerts that are causing nuisance alerts. For example: "ET POLICY Reserved Internal IP Traffic" is an alert I am trying to remove. When I go into the docker instance running directory, and go into "/etc/suricata/rules" I find all the different suricata .rules. The above mentioned rule resides in "emerging-policy.rules". I edit that file and remove the rule. However, I am still alerted. I have removed Tpot's daily reboot command from crontab to ensure that a new docker container that holds suricata is not configured. I am not sure what other steps I can take. Is there a script that downloads the latest rules from https://rules.emergingthreats.net/open/suricata-4.0/emerging.rules.tar.gz and that overwrites any changes to the rules files I have made?

Thank you for the help!

**Comment by t3chn0m4g3** [comment]
Rules will be updated on container [start](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/Dockerfile). Also all modifications inside the container will not be persistent.
If you want persistence you need to map your own ruleset into the container upon start (as a volume) by modifying `/opt/tpot/etc/tpot.yml` for the suricata service. In addition you need to include a [command](https://docs.docker.com/compose/compose-file/#command) in the same file to overwrite the container default:
```
command: suricata -v -F /etc/suricata/capture-filter.bpf -i $(/sbin/ip address | grep '^2: ' | awk '{ print $2 }' | tr -d [:punct:])
```
Make sure to align it with the other statements of the serivce or you will receive an error.

**Comment by camaro23** [comment]
I have customized Kibana dashboards to ignore specific alerts. Seems to be an easier solution. Thank you for the help!
