### ISSUE TITLE
Stop  docker  service

### ISSUE THREAD

**Issue by taylorwin** [dtag-dev-sec/tpotce#253]
when i use "sudo service docker stop"
but just moment it is autostart .

how can i stop  docker do not autostart?

i use   sudo systemctl stop docker.service
 sudo systemctl disable docker.service
but failed.

i find docker service autostart every 5minute

**Comment by t3chn0m4g3** [comment]
The `docker.service` is required by `tpot.service`, you would need to disable them both.

**Comment by taylorwin** [comment]
Thank you ~

**Comment by t3chn0m4g3** [comment]
Welcome.
