### ISSUE TITLE
18.04 Can't export kibana objects

### ISSUE THREAD

**Issue by 0x01feng** [dtag-dev-sec/tpotce#255]
I'm used TPot 18.04 , i need export kibana objects
used `bin/export_kibana-objects.sh`  this script file
Return:
```
### Elasticsearch is available, now continuing.

jq: error (at <stdin>:0): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
### Now exporting 0 index patterns. 

### Now exporting 0 dashboards. 

### Now exporting 0 visualizations. 

### Now exporting 0 searches. 

### Now building archive kibana-objects_201811060925.tgz

### Statistics
###### Exported 0 index patterns. 
###### Exported 0 dashboards. 
###### Exported 0 visualizations. 
###### Exported 0 searches. 
```

i'm try to use 
```
curl http://127.0.0.1:64296/api/saved_objects/index-pattern
and 
curl http://127.0.0.1:64296/api/saved_objects/index-pattern/
```
Return  Status Code: 404

I checked the official document of kibana and seemed to need to add a parameter.
But I don't know exactly what to do.

Thanks~

**Comment by t3chn0m4g3** [comment]
Thanks for reporting, it seems the API calls have changed. However I do not think keeping the script is necessary since you can now export all objects (even the index pattern) using the Kibana UI (**Management > Saved Objects > Export**).

![image](https://user-images.githubusercontent.com/4318452/48127736-bed52400-e284-11e8-9eb8-d3b6ce5e8f19.png)

**Comment by 0x01feng** [comment]
hey guy, Thanks for your quick response. 

I know used  the Kibana UI,But I have 100+ server to do synchronization, bash shell is the most convenient.
Now, I am trying to modify this script.

**Comment by t3chn0m4g3** [comment]
@0x01feng This is fixed now. Please be aware that 18.04 is just a dev branch and will be removed by the end of november with the release of 18.11.
