### ISSUE TITLE
Failed to load output engine: csirtg due to ImportError: No module named csirtgsdk.indicator

### ISSUE THREAD

**Issue by micoots** [dtag-dev-sec/tpotce#257]
### Baisc support information

- What T-Pot version are you currtently using? 17.10
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? 48 hours
- Did you install any upgrades or packages? no
- Did you modify any scripts? no
- Have you turned persistence on/off? no
- How much RAM available (login via ssh and run `htop`)? 3.80G available, 2.53G used
- How much stress are the CPUs under (login via ssh and run `htop`)? little, load avergae 0.34,0.32,0.29
- How much swap space is being used (login via ssh and run `htop`)? 10MB out of 8GB
- How much free disk space is available (login via ssh and run `sudo df -h`)? 48GB available
- What is the current container status (login via ssh and run `sudo start.sh`)?
Using WebTTY, start.sh command not found.
Using Portainer, all containers are up.

I went into cowrie and added my DShield details, VirusTotal and csirtg details.

Restarting the cowrie container, DShield and VirusTotal started fine by "Stderr logs" shows:

Failed to load output engine: csirtg due to ImportError: No module named csirtgsdk.indicator

Any ideas?

**Comment by t3chn0m4g3** [comment]
It seems this is directly related to Cowrie. Can you please open this issue with the [Cowrie developers](https://github.com/cowrie/cowrie).

Thank you.

**Comment by micoots** [comment]
Hi. Please read Cowrie's response:

https://github.com/cowrie/cowrie/issues/970

which:

_Yes, you need extra imports. Look in requirements-output.txt for a list of prereqs.
In your case you'll need csirtgsdk. That should probably be added to the T-Pot system._

So it looks like it's missing a prerequisite in the cowrie image.

Thanks.

**Comment by t3chn0m4g3** [comment]
I looked into supporting this, but the resulting docker-image would grow too large for something we do not use.
