### ISSUE TITLE
18.11 Iso

### ISSUE THREAD

**Issue by camaro23** [dtag-dev-sec/tpotce#263]
Has an 18.11 iso been released? I am still seeing Tpot 17.10 iso as the latest release. Will this also install Ubuntu 18.0 as the OS?

Thanks

**Comment by t3chn0m4g3** [comment]
Not released yet. Today we prepped the master branch for extensive testing. Official release is near. Stay tuned.

**Comment by t3chn0m4g3** [comment]
The update script will take care of releases within the T-Pot 18.11.x branch.

**Comment by t3chn0m4g3** [comment]
Good catch, thanks. Set old release to deprecated.

**Comment by camaro23** [comment]
Will release 17.10 no longer be applicable to install?

**Comment by t3chn0m4g3** [comment]
17.10 is no longer available.
