### ISSUE TITLE
Snare Clone

### ISSUE THREAD

**Issue by camaro23** [dtag-dev-sec/tpotce#264]
Is it possible to clone a website that SNARE will project? Instead of cloning a random webpage, can I clone a webpage of my choosing and have SNARE project that page even after reboot?

Thanks

**Comment by t3chn0m4g3** [comment]
Yes, however I built Snare / Tanner to cycle through 10 different webpages. If you want to inject your own webpages you need Snare to clone the corresponding site and then ...
1. ... mount the corresponding subfolder as volume
2 ... use your own `cmd` call in the `tpot.yml` to skip the randomization. Just have a look at the Snare Dockerfile.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
