### ISSUE TITLE
How to make a static page for big screen usage?

### ISSUE THREAD

**Issue by hvdkooij** [dtag-dev-sec/tpotce#268]
Mainly curious how I can create a screen that I can use to get a live feed on a big TV screen showing some of the things we can get.
Preferably it should be rather fool proof.  (and never underestimate the fools  ;-)

Can someone describe this shortly and put it in the WIKI?

### Basic support information

- What T-Pot version are you currently using? 18.11
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? Couple of hours
- Did you install any upgrades or packages? No (not yet at least ;-)
- Did you modify any scripts? No
- Have you turned persistence on/off? No change after standard install yet
- How much RAM is available (login via ssh and run `htop`)? 12 GB installed, 4.5 GB in use
- How much stress are the CPUs under (login via ssh and run `htop`)? 4 CPU cores, Mostly under 20% use
- How much swap space is being used (login via ssh and run `htop`)? No swap space used yet
- How much free disk space is available (login via ssh and run `sudo df -h`)? 453 GB available
- What is the current container status (login via ssh and run `sudo dps.sh`)? All active

**Comment by t3chn0m4g3** [comment]
Run the Kibana dashboard on the "Big Screen" and set to to `auto-refresh` on a per minute basis with 24h view?

**Comment by hvdkooij** [comment]
Something like that. But the default (Kibana) page has a lot of information I don't want on that screen.
The whole menu on the left and the top menu are things I could do without.
At the moment I keep hitting the "Kibana did not load properly. Check the server output for more information." issue.
I am running through https://github.com/dtag-dev-sec/tpotce/issues/142 to see if anything in there helps me to resolve the issue.

**Comment by hvdkooij** [comment]
Got this error in the logs ....
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

My guess is that 60 seconds is indeed too short. But what is the best place to change it?

**Comment by hvdkooij** [comment]
I will close this one and make a specific issue for the Kibana issue.
