### ISSUE TITLE
Automated cloud deployment using Terraform

### ISSUE THREAD

**Issue by prateepb** [dtag-dev-sec/tpotce#269]
I've created some [Terraform](https://www.terraform.io/) configuration that allows me to automatically provision a T-Pot instance to EC2. This could easily be extended to support any of the providers that Terraform includes.

My repo is here: https://github.com/prateepb/tpot-terraform

If anyone is interested, I could merge this in to this repo instead of keeping it separate?

**Comment by t3chn0m4g3** [comment]
Thank you very much. I will link to your repo as part of the README.

**Comment by t3chn0m4g3** [comment]
@prateepb We move to Debian, in `/cloud/open-telekom-cloud` you can now find a solution for Ansible & OTC. If you are interested you can add `cloud/terraform` and base on 19.03.
