### ISSUE TITLE
Revisit decision on using netplan

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#274]
Revisit decision on using netplan, however if we use netplan this means still no support for 802.1x WPA Enterprise:
https://bugs.launchpad.net/netplan/+bug/1739578
https://bugs.launchpad.net/netplan/+bug/1735288

However some problems with static ip usage might be resolved.

**Comment by t3chn0m4g3** [comment]
Just issued a pre-release based on netplan https://github.com/dtag-dev-sec/tpotce/releases/tag/18.11.1.

Please let us know if problems regarding reachability are fixed.

Please keep in mind that the T-Pot Standard Installation will need 6-8GB of RAM to work properly.

**Comment by mahmoodn** [comment]
Great job. I tested 18.11.1 with VMware network interface and static IP. The static IP was assigned in the installation steps and after a reboot, both 64297 and 64294 were online.

**Comment by t3chn0m4g3** [comment]
@mahmoodn Thanks for the feedback and for testing!

**Comment by t3chn0m4g3** [comment]
Ubuntu branch will be closed when we are moving to Debian by the end of March.
