### ISSUE TITLE
Permissions error setting time zone in Admin UI

### ISSUE THREAD

**Issue by amishrabbit** [dtag-dev-sec/tpotce#275]
While using the web-based Admin console on :64294, when I attempt to change the time zone from its default to the local timezone, the UI displays a Permission Denied error message

### Basic support information

- What T-Pot version are you currently using? 18.11 (2018-12-08 install from .iso)
- Are you running on a Intel NUC or a VM? VM (ESX)
- How long has your installation been running? 15 hours
- Did you install any upgrades or packages? no
- Did you modify any scripts? no
- Have you turned persistence on/off? no
- How much RAM is available (login via ssh and run `htop`)? 4.36G/11.7G used
- How much stress are the CPUs under (login via ssh and run `htop`)? Load average 0.67 0.47 0.43
- How much swap space is being used (login via ssh and run `htop`)? 0K
- How much free disk space is available (login via ssh and run `sudo df -h`)? 223G
- What is the current container status (login via ssh and run `sudo dps.sh`)? sudo: ./dps.sh: command not found

![set time denied](https://user-images.githubusercontent.com/2653726/49694136-219a3380-fb41-11e8-9b12-8247726266e0.png)

**Comment by t3chn0m4g3** [comment]
Please be aware that changing time from UTC will have affects on your logs. Kibana will always translate to your local TZ.
If you must just check the box on the Cockpit login page.

**Comment by amishrabbit** [comment]
Thank you! I didn't realize that changing the time zone was a privileged modification. 

Translating the logs to my local TZ was always the desired effect.
