### ISSUE TITLE
Is it possible to use multiple network cards to deploy T-POTs to different network areas (such as different VLANs) at the same time?

### ISSUE THREAD

**Issue by lk444** [dtag-dev-sec/tpotce#276]
Can i use multiple network cards to deploy T-POTs into different network areas (such as different VLANs) at the same time?
Or a T-POT can only be deployed in a single network area？

**Comment by t3chn0m4g3** [comment]
By design only one NIC is supported.

**Comment by itsbentheboy** [comment]
Hey @t3chn0m4g3 ! 

Do you have any recommendations for those that would like to use this tool on multiple networks?

I have a couple networks internally that i would like to run Tpot in. Would this suggest to run a separate instance of the tpot appliance in each separate network?

**Comment by ChessSpider** [comment]
For services which do not have ``network_mode: host`` in its docker-compose.yml file, you can specify the listening IP. Example, though untested;

```
$ nano /opt/tpot/etc/tpot.yml
  cowrie:
    container_name: cowrie
    restart: always
    tmpfs:
     - /tmp/cowrie:uid=2000,gid=2000
     - /tmp/cowrie/data:uid=2000,gid=2000
    networks:
     - cowrie_local
    ports:
     - "192.168.4.2:22:22"
     - "10.10.12.2:23:23"
    image: "dtagdevsec/cowrie:1811"
    read_only: true
    volumes:
     - /data/cowrie/downloads:/home/cowrie/cowrie/dl
     - /data/cowrie/keys:/home/cowrie/cowrie/etc
     - /data/cowrie/log:/home/cowrie/cowrie/log
     - /data/cowrie/log/tty:/home/cowrie/cowrie/log/tty
```

etc.. You will need to add multiple network interfaces to your system and configure their IP-addresses, of course. Also be aware changes may be overridden when you do an `update.sh`; if you do that, it will default back to listening on all interfaces for all services.
