### ISSUE TITLE
Besides exporting and importing the Kibana dashboard/visualizations is there another way?

### ISSUE THREAD

**Issue by LandonStewart** [dtag-dev-sec/tpotce#277]
### Issues

Logstash is configured to go to a different ELK cluster.  This is working.

On the external ELK cluster for some reason, without anyone modifying anything, the Kibana dashboard and visualizations are broken saying there's no index pattern.  I tried creating a new one but it already existed so I removed that one and created a new one but it still says there isn't one.

I checked the TPOT Kibana dashboards to see if those still worked and they are doing the exact same thing.  The *only* modification to TPOT is the logstash hosts directive to send to a different ES cluster.

Short version:
Is there a way to rebuild the Dashboard and Visuzations etc without exporting from TPOT's Kibana and then importing it?  I'm looking for a way to do it similar to how the installer might do it but do it on my own Kibana install.

### Basic support information

- What T-Pot version are you currently using? 18.11
- Are you running on a Intel NUC or a VM? hardware
- How long has your installation been running? weeks
- Did you install any upgrades or packages? I did run /opt/tpot/update.sh -y but after this issue occurred
- Did you modify any scripts? Just the hosts that logstash sends to
- Have you turned persistence on/off? No
- How much RAM is available (login via ssh and run `htop`)? A lot
- How much stress are the CPUs under (login via ssh and run `htop`)? Load is around 2
- How much swap space is being used (login via ssh and run `htop`)? none
- How much free disk space is available (login via ssh and run `sudo df -h`)? A lot
- What is the current container status (login via ssh and run `sudo dps.sh`)? All are good

**Comment by t3chn0m4g3** [comment]
Check the `/opt/tpot/bin` folder. There you can find some export / import scripts. Just modify them for your environment.

**Comment by LandonStewart** [comment]
I should have mentioned that I've already been using those but since the source is bad (the TPOT ELK) exporting and importing results in the same issue (broken visualizations on the external ELK).

**Comment by t3chn0m4g3** [comment]
Sorry, but this is out of scope with regard to T-Pot. Closing this.
