### ISSUE TITLE
A question about the honeypot sharing community

### ISSUE THREAD

**Issue by OrdinaryUser123** [dtag-dev-sec/tpotce#278]
Dear dtag-dev-sec,

FIrst of all, thanks for making this possible! This project is such a blessing for those who want to use a honeypot, but don't necessarily have the knowledge to build such an amazing platform. Thanks 😄 !

My question regards to usability of the information that is sent by those who submit their honeypot information to https://sicherheitstacho.eu. The attack map (*pew pew*) is cool and all, but i wondered if it is possible (as a member of this community) to gain access to the honeypot information sent by other community members (Like a large honeypot feed). I'm particularly in the IP-addresses of these attackers.   
Of course I can understand if this information would only be available to the creators of this honeypot-platform. By all means, thanks for creating this!

Kind regards.

**Comment by schmalle** [comment]
Dear all, We plan to make the community data in 2019 available, details to follow in q1, we had (besides the great T-Pot from Marco), also quite some challenges with our backend, and now can look more relaxed in the future, Best wishes , happy christmas time ! Markus

**Comment by hvdkooij** [comment]
Additional is there something needed additionally to tag the location of a Honeypot?
(I have 2 contributing honeypots. One has 4 public IP addresses the other one at least 8. but I am not sure if the IP adresses are correctly shown in the feedback as they are behind a NAT firewall.)

**Comment by hvdkooij** [comment]
I noticed 1 very stubborn attacker:
![image](https://user-images.githubusercontent.com/15157000/50589742-17413000-0e88-11e9-97c2-00daa648064f.png)
It's on the Canada/US boundry and it's at it for weeks.

**Comment by hvdkooij** [comment]
And what does PIR stand for?

**Comment by t3chn0m4g3** [comment]
@hvdkooij Thank you for the contribution :bowtie:
PIR? In which context?
No additional tagging is necessary.

**Comment by hvdkooij** [comment]
If I look at https://sicherheitstacho.eu/start/main I see a lot of events related to source and/or destination PIR.

**Comment by vorband** [comment]
PIR is short for „private IP range“, so rfc1918 private IP addresses

**Comment by Derek000** [comment]
Hi all,

Is there away to exclude my internal scanning and SIEM machine testing traffic from the T-Pot data collection and reporting?
Although it appears as PIR traffic, it changes a number of the graphs and Tag visualisations.

Thanks
Derek

**Comment by HeroGamers** [comment]
Sorry for the complete necropost, but this was marked as completed, however I don't see much documentation about how to get raw information which is shared from the community? Only how to access the [website](https://www.sicherheitstacho.eu/#/en/tacho).

Or is it possible to subscribe to it as a hpfeed?

Is there a method to somehow subscribe to the events that other send, or otherwise get access to an API or database dump daily of events that happened? Would be great, since others share the data :)

**Comment by haroldLuiz** [comment]
Same question, i cant find a known attackers resource from the community to block on my firewall, where can it be found?
