### ISSUE TITLE
duplicate field 

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#281]
Hello,
I am getting the IP_rep field now in all the honey pot logs and not just in Suricata logs.

Did not have this issue until the latest update. 

any suggestions?

**Comment by iukea1** [comment]
![image](https://user-images.githubusercontent.com/35882815/51419184-082bd480-1b4e-11e9-96d2-8c9cfbea2682.png)

**Comment by iukea1** [comment]
![image](https://user-images.githubusercontent.com/35882815/51432714-bf355800-1c01-11e9-881f-f47d4d5316c9.png)
example of known attacker slipping into the HoneyTrap logs

**Comment by t3chn0m4g3** [comment]
Hello, thank you for using T-Pot and welcome to the community.

This behaviour is intentional. All events handled by logstash (not limited to suricata) will be enriched with reputation information if the source is known.

**Comment by iukea1** [comment]
And that reputation data

"Known attacker" etc

Is stored where?


Is it stored on the logstash server or Suricata ?

**Comment by t3chn0m4g3** [comment]
Stored [here](https://github.com/dtag-dev-sec/listbot).
Updated [here](https://github.com/dtag-dev-sec/tpotce/blob/475452688450df1bd5c2c4980e8068e91fb84ba8/docker/elk/logstash/Dockerfile#L53).
Referenced [here](https://github.com/dtag-dev-sec/tpotce/blob/475452688450df1bd5c2c4980e8068e91fb84ba8/docker/elk/logstash/dist/logstash.conf#L364-369).

**Comment by ehmueller** [comment]
Hello, who is the maintainer of the ip_rep file? Is this something you created and maintain ?
