### ISSUE TITLE
Unhealthy head, logstash and kibana block restart of T-Pot

### ISSUE THREAD

**Issue by cryptax** [dtag-dev-sec/tpotce#283]
Hello,

**T-pot complains about "unhealthy containers"**. I tried _stopping_ and even _removing_ the containers head, logstash, kibana and 3863e4db73e7 but that did not solve the problem. I can't bring T-Pot back up :(

```
docker-compose -f tpot.yml up -d
p0f is up-to-date
nginx is up-to-date
cowrie is up-to-date
suricata is up-to-date
dionaea is up-to-date
conpot_kamstrup_382 is up-to-date
Creating elasticsearch ... 
conpot_ipmi is up-to-date
conpot_iec104 is up-to-date
conpot_guardian_ast is up-to-date
cyberchef is up-to-date
Creating elasticsearch
ewsposter is up-to-date
Creating elasticsearch ... done

ERROR: for head  Container "3863e4db73e7" is unhealthy.
ERROR: for logstash  Container "3863e4db73e7" is unhealthy.
ERROR: for kibana  Container "3863e4db73e7" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

Info:

- I am using T-Pot 18.11 on a Google Instance running 18.04 LTS Ubuntu
- The install had been running fine for a couple of days
- I tweaked the yml to remove the honeypots I did not want to launch. So for instance, I don't have rdpy, tanner etc.
- I have lots of free disk space available, the system is not particularly loaded, and free RAM

NB. Below I don't want adhoney, ciscoasa, heralding, honeytrap, mailoney, medpot, rdpy, snare, tanner so it's normal they are not launched :-)

```
========| System |========
    Date:  Mon Jan 21 10:40:56 UTC 2019
  Uptime:  10:40:56 up 18:13,  1 user,  load average: 0.82, 1.33, 2.90
No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.
CPU temp:                      

NAME                  STATUS                       PORTS
adbhoney            Exited (0) 7 hours ago     
ciscoasa            Exited (0) 7 hours ago     
cowrie              Up 19 minutes              0.0.0.0:22-23->22-23/tcp
cyberchef           Up 19 minutes (healthy)    127.0.0.1:64299->8000/tcp
dionaea             Up 19 minutes              
elasticpot          Exited (0) 7 hours ago     
ewsposter           Up 6 seconds               
heralding           Exited (0) 7 hours ago     
honeytrap           Exited (1) 7 hours ago     
mailoney            Exited (0) 7 hours ago     
medpot              Exited (2) 7 hours ago     
nginx               Up 19 minutes              
rdpy                Exited (0) 7 hours ago     
snare               Exited (137) 7 hours ago   
suricata            Up 19 minutes              
tanner              Exited (137) 7 hours ago   
tanner_api          Exited (137) 7 hours ago   
tanner_phpox        Exited (137) 7 hours ago   
tanner_redis        Exited (137) 7 hours ago   
tanner_web          Exited (137) 7 hours ago   
conpot_guardian_ast   DOWN                  
conpot_iec104         DOWN                  
conpot_ipmi           DOWN                  
conpot_kamstrup_382   DOWN                  
elasticsearch         DOWN                  
head                  DOWN                  
kibana                DOWN                  
logstash              DOWN                  
p0f                   DOWN                  
spiderfoot            DOWN          
```

**Comment by t3chn0m4g3** [comment]
@cryptax Thanks for using T-Pot and welcome to the community.

Based on your info I assume the T-Pot service tries to come up as well. Also just running `docker-compose` is not enough, since it does not create the necessary firewall rules.

You can try ...
1. Run `systemctl stop tpot`
2. Restore the original config.
3. Edit `vi /opt/tpot/etc/tpot.yml` and remove all the services you do not wish to come up.
4. Clean up `docker rm $(docker ps -aq)`
5. Do a `sudo su -` and run `/opt/tpot/update.sh -y`

... or simply reinstall, stop T-Pot (`systemctl stop tpot`) and adjust `vi /opt/tpot/etc/tpot.yml` to your needs and reboot.

**Comment by t3chn0m4g3** [comment]
@cryptax Thanks for the update & probably yes, but what can I say, I am a Neat Freak 😄
