### ISSUE TITLE
Outbound connection

### ISSUE THREAD

**Issue by camaro23** [dtag-dev-sec/tpotce#293]
Hey Guys,

I noticed an outbound connection made to a German website https://cord.de/ (37.120.189.254), and was wondering if this is a new feature implemented within honeypot that reaches out to this server? 

The website advertises that they parse logfiles from Squid, NetCache, Inktomi Traffic, etc. and VirusTotal has deemed the website clean. However, Suricata generated an alert stating that it is a Command and Control server. Does anyone know if T-POT uses this as a 3rd party service of some kind?

Thanks

**Comment by t3chn0m4g3** [comment]
For the honeypots to work and in order to collect malware samples, outbound connections are necessary. From the looks of your description I'd say that seems to be the case since `cord.de` is neither affiliated with us or part of T-Pot's configuration.
