### ISSUE TITLE
gathering data in  distributed network 

### ISSUE THREAD

**Issue by pady12** [dtag-dev-sec/tpotce#297]
Hi
We installed standard mode of t-pot and it work correctly then installed a sensor  mode to send data to a central t-pot (standard t-pot), but we don't know  how configure sensor to send data to standard honey pot
There is a way to  gathering data from sensors in network and send data to central t-pot?
Tanks a lot

-

**Comment by t3chn0m4g3** [comment]
A distributed Installation is not supported (yet) and will be part of a future release.
There were some previous discussions on how to adjust `logstash.conf` and use a `docker volume` statement in `tpot.yml` to support such a central solution and we kindly ask you to review the previous issues.
Thank you for understanding.
