### ISSUE TITLE
安装T-Pot18没有设置用户密码的选项，直接安装了。怎么登录

### ISSUE THREAD

**Issue by aiifan** [dtag-dev-sec/tpotce#299]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the FAQs in our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM is available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo dps.sh`)?

**Comment by JamesBradyBear** [comment]
你好，
首先，这里没有那么多人懂中文。 当您安装“Tpot”时，它会要求您创建一个用户。 您可以使用该用户登录。
so next time please write in English 👍

**Comment by t3chn0m4g3** [comment]
Please follow the instructions. Thank you.
