### ISSUE TITLE
IP Address Assignment

### ISSUE THREAD

**Issue by eluvatl** [dtag-dev-sec/tpotce#30]
Hello,

I understand that the honeypots are designed such that little to no configuration is necessary. DHCP is not enabled on my network; all VMs are assigned static IPs. Is it possible to assign individual IP addresses to the honeypots? Some of them need to be in the internal network and others in the DMZ.

**Comment by dev-t-sec** [comment]
Dear Eluvatl, Sure, simply change the config frm the underlying ubuntu system.
Best wishes
Markus

On 09 Apr 2016, at 18:54, eluvatl <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I understand that the honeypots are designed such that little to no configuration is necessary. DHCP is not enabled on my network; all VMs are assigned static IPs. Is it possible to assign individual IP addresses to the honeypots? Some of them need to be in the internal network and others in the DMZ.

**Comment by eluvatl** [comment]
Do you mean I should, for instance, modify the glastopf.cfg file? And do the same for the other honeypots?

**Comment by dev-t-sec** [comment]
Ah, no, just for the ubuntu itself, see eg
https://www.howtoforge.com/linux-basics-set-a-static-ip-on-ubuntu

Best wishes
Markus


On 09 Apr 2016, at 19:32, eluvatl <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean I should, for instance, modify the glastopf.cfg file? And do the same for the other honeypots?

**Comment by eluvatl** [comment]
I see. So all of the honeypots will be using the same IP address?

**Comment by dev-t-sec** [comment]
yep

On 09 Apr 2016, at 19:45, eluvatl <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. So all of the honeypots will be using the same IP address?
