### ISSUE TITLE
MQTT publish topics

### ISSUE THREAD

**Issue by JamesBradyBear** [dtag-dev-sec/tpotce#301]
Hi,
Has anyone experience with publishing topics for mqtt? [Like this](https://github.com/bruhautomation/ESP-MQTT-JSON-Digital-LEDs/blob/master/Example%20Home%20Assistant%20Configuration.yaml) My honepot has been indexed but it does not publishes any topics. I wonder if anyone was able to do it in Tpot since I don't know attributes I can write in this file [https://github.com/dtag-dev-sec/tpotce/blob/144bdb8315d53f852faec842be44001f438789c3/docker/dionaea/dist/etc/services/mqtt.yaml](https://github.com/dtag-dev-sec/tpotce/blob/144bdb8315d53f852faec842be44001f438789c3/docker/dionaea/dist/etc/services/mqtt.yaml)
![image](https://user-images.githubusercontent.com/1931778/53038333-c6f45080-347c-11e9-9f8f-ac3e734c76a4.png)

Thanks.

**Comment by t3chn0m4g3** [comment]
This is part of the Dionaea service config. Since it is not directly related to T-Pot, please open an issue [upstream](https://github.com/DinoTools/dionaea). Thank you.
