### ISSUE TITLE
Technical working of Tpot - packet forwarding strategy to different honeypots? - Question

### ISSUE THREAD

**Issue by JamesBradyBear** [dtag-dev-sec/tpotce#305]
Hi,
I have  a question as you can see in the following figure that same ports are bind with different Honeypot, so does it means that Tpot forwards packets to all the honeypots and then after which ever Honeypot replies according to payload is forwarded back to the attacker? or if it works in an other way? 

1) Does it works by forwarding all the packets to all the running honepots?
2) Does it do intelligent payload detection? and forward packets to related honeypots? if so how?

![image](https://user-images.githubusercontent.com/1931778/53236052-a94d0400-3693-11e9-9d4b-2e86b2fc7e0a.png)

Thanks.

**Comment by t3chn0m4g3** [comment]
This is with regard to different editions you can choose from during installation. This will ensure no port conflicts.

**Comment by JamesBradyBear** [comment]
Thank you very much for your reply and clearing the confusion.
