### ISSUE TITLE
Need only Honeypot logs and need to send a logs to Other Analytic engine?

### ISSUE THREAD

**Issue by Blason** [dtag-dev-sec/tpotce#308]
Hi Team,

I need to achieve below scenario hence need help on the same. I wanted to deploy only Honeypot and wanted data to be dumped in my other Graylog server and not to the local ELK engine. 

Can we do that? Please confirm?

**Comment by t3chn0m4g3** [comment]
#297

**Comment by Blason** [comment]
No problem, I am not seeking to put it in a distributed mode. Let it be in a standard mode and I can direct the output to other engine, right?

Where do I change that?
