### ISSUE TITLE
How do start only certain containers at a boot time?

### ISSUE THREAD

**Issue by Blason** [dtag-dev-sec/tpotce#309]
Hi there,

Wondering would it be possible to start certain containers only at a boot time? I need RDPy/SSH/SMTP and few others. Also I do not want ELK container to start instead thinking to install logstash separately and forward the logs to my Graylog since that would need few logstash-output-plugins to be installed like logstash-output-gelf

And if I make certain changes in logstash.conf file under /opt how do I restart the logstash docker container to make those changes live?

**Comment by t3chn0m4g3** [comment]
Run `systemctl stop tpot`, modify `/opt/tpot/etc/tpot.yml` to your needs and `reboot`.
