### ISSUE TITLE
How to realize the log transmission and log formatting display. Where are the specific files? I want distributed transmission logs, is it easy to implement?

### ISSUE THREAD

**Issue by 26389** [dtag-dev-sec/tpotce#310]
I want to distribute these honeypots in a distributed way. I want to find out how the t-pot18.11 honeypot logs are transferred to elk. I would be grateful if you can specify a specific configuration file.
The current approach I have taken is:
1. Use the command "service stop tpot" after standard installation. End all containers.
2. Modify the /opt/tpot/etc/tpot.yml file to keep only the honeypot configuration information you want to start.
I have already implemented the distributed deployment honeypot initially, but I can't figure out the log transmission. How can I render the log perfectly like tap18.11?

**Comment by t3chn0m4g3** [comment]
[Our Wiki](https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-logstash.conf) should give you a helping hand. Since we do not support distributed installations (yet) please understand that I will close this issue now.
