### ISSUE TITLE
Any user can be root (privilege escalation)

### ISSUE THREAD

**Issue by ChessSpider** [dtag-dev-sec/tpotce#311]
Great work on this guys, just found it yesterday and Im super enthusiastic about it!

Hopefully not a new finding? But priv esc is possible for any user with a shell:

```
[tsec@crudepasta:~]$ docker run -it -v "/:/host/" ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
6cf436f81810: Pull complete
987088a85b96: Pull complete
b4624b3efe06: Pull complete
d42beb8ded59: Pull complete
Digest: sha256:7a47ccc3bbe8a451b500d2b53104868b46d60ee8f5b35a24b41a86077c650210
Status: Downloaded newer image for ubuntu:latest
root@62bc14527ff4:/# cat /host/etc/shadow
root:!:17960:0:99999:7:::
daemon:*:17960:0:99999:7:::
bin:*:17960:0:99999:7:::
sys:*:17960:0:99999:7:::
sync:*:17960:0:99999:7:::
(etc)
```

Due to:
```
./host/etc/systemd/tpot.service:# Modify access rights on docker.sock for netdata
./host/etc/systemd/tpot.service:ExecStartPre=-/bin/chmod 666 /var/run/docker.sock
```

I just downloaded this yesterday, so I'm not sure yet, but can this be made a bit more secure? E.g. only adding required users to a specific docker group, etc ?

**Comment by t3chn0m4g3** [comment]
@ChessSpider Thanks for noticing, fixed it on the Debian branch a month ago (https://github.com/dtag-dev-sec/tpotce/blob/debian/host/etc/systemd/tpot.service) which will be released this month and to be honest I thought I had merged it to master as well.
Thanks for paying close attention, that's what open source is all about.

**Comment by t3chn0m4g3** [comment]
@ChessSpider Please run `/opt/tpot/update.sh`, afterwards the fix should be active on your end.
New installation will not be affected since pulled from `master`.
