### ISSUE TITLE
Collect Samples from HP

### ISSUE THREAD

**Issue by l0ft1369** [dtag-dev-sec/tpotce#312]
Hi There,

I am seeing a ton of attacks that should be yielding some pretty interesting shell codes, binaries and other fun little dropped items. Is there a way to cache those samples? If so is there a way to grab those?

-l0ft

**Comment by JamesBradyBear** [comment]
Hi,
first of all before posting the question please consider reading the introduction of the framework and also search in the previously posted issues. 
If you will go to the main page you can see the following content under the framework technical figure. 

`"While data within docker containers is volatile we do now ensure a default 30 day persistence of all relevant honeypot and tool data in the well known /data folder and sub-folders. The persistence configuration may be adjusted in /opt/tpot/etc/logrotate/logrotate.conf."`

I hope this answers your question.

Thanks.

**Comment by l0ft1369** [comment]
Hi,

Your response actually doesn't help me in the least.

I am aware that ascii logs are well kept and easily accessible. I was able to locate those. However I am seeing worms, and other things that should be leaving actual binaries. I am not finding those binaries. I have checked the dionaea binaries folder but it is empty. This shouldn't be the case. I believe that dionaea is capable of hanging on to binaries that are submitted. I would like to have those analyzed in house. 

That's what I am asking. 

I will revisit the docs of course, but I didn't know if there was anyone who could help me take a shortcut?

-l0ft

**Comment by t3chn0m4g3** [comment]
@l0ft1369 Based on your information there is only guesswork involved in what people can actually help you to achieve. Please be more specific and elaborate on what you are expecting Dionaea or the other honeypots to achieve. If you cannot find what you are looking for in the `data` folder or in the `logrotate` generated archives it is highly likely that the honeypot might not be capable to achieve what you are seeking. In such a case you may review the honeypots configuration in the `docker` folder and adjust it to your needs according to the examples in the Wiki.
If that does not help please provide the corresponding honeypot developer with as much logs as you can get and should the developer include the feature / fix upstream we can also include it into T-Pot.

I am closing this issue now, please open a specific issue with the required details.

Thank you for understanding.
