### ISSUE TITLE
UI visualization Bug

### ISSUE THREAD

**Issue by JamesBradyBear** [dtag-dev-sec/tpotce#314]
Hi,
I have tested it on Chrome and Mozilla both updated version to date but I have noticed when there are two lines row then it does not adjust the graph with the line. I am posting a picture in below.

![image](https://user-images.githubusercontent.com/1931778/54083631-57a8a880-4326-11e9-8bf3-adc5f2448f19.png)

Danke.

**Comment by t3chn0m4g3** [comment]
Thanks. Unfortunately there is nothing I can do about it. We are using Kibana off the shelf.
However you can check out the Debian based 19.03 Beta, this also includes the latest ELK Stack.

Gern geschehen 😊

**Comment by t3chn0m4g3** [comment]
Closing this as upstream issue.
