### ISSUE TITLE
Blank screen when starting installation

### ISSUE THREAD

**Issue by xcampax** [dtag-dev-sec/tpotce#315]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the FAQs in our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using? T-Pot 18.11 on Ubuntu 18.04.2 LTS
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? not at all
- Did you install any upgrades or packages? no
- Did you modify any scripts? no
- Have you turned persistence on/off? n/a
- How much RAM is available (login via ssh and run `htop`)? 11.7GB
- How much stress are the CPUs under (login via ssh and run `htop`)? 0-1%
- How much swap space is being used (login via ssh and run `htop`)? 0k
- How much free disk space is available (login via ssh and run `sudo df -h`)? 180GB
- What is the current container status (login via ssh and run `sudo dps.sh`)? n/a

Hello, 

This is my first time working with T-Pot. I have a brand-new VMware running Ubuntu and meeting all system requirements. After mounting the tpot.iso and rebooting the VMware Remote Console, regardless of whether I select the regular T-Pot install or the command-line expert mode, I see a few modules getting loaded but eventually end up with a white-ish screen and nothing else happening. Can anybody please give me a hint what is going on here?

Thanks :)

Nora

![2019_03_12_12_44_01_VMware_Remote_Console](https://user-images.githubusercontent.com/9562968/54197696-e8b58600-44c4-11e9-80dc-678893fbe8cd.png)

![2019_03_12_12_45_02_VMware_Remote_Console](https://user-images.githubusercontent.com/9562968/54197694-e8b58600-44c4-11e9-9826-da7bb8f6ca0f.png)

**Comment by xcampax** [comment]
Update: Even though I assumed that the installer would just wipe out the previously installed OS, I tried again with an empty VM - with the same result.

**Comment by t3chn0m4g3** [comment]
Unfortunately I cannot reproduce. Can you download the latest Debian Beta from releases and retry?

**Comment by xcampax** [comment]
I did but ended up with the same result.

**Comment by t3chn0m4g3** [comment]
To narrow it down, we are using the [Debian Network Installer](http://ftp.debian.org/debian/dists/stable/main/installer-amd64/current/images/netboot/mini.iso). Does this work?

What are the specs of your VMWare Installation? Version, settings of your VM.

[VM Settings can be found here](https://www.youtube.com/channel/UCN8meUGEBa2xkJhcfkb9reQ).

**Comment by xcampax** [comment]
Same result with the mini.iso.

VMware compatibility: ESXi6.5 and higher (VM-Version 13)
4 CPUs, 12GB RAM, 200GB HD
VMware® Remote Console 10.0.3 build-9300449

I did not configure the VM but if you need more details, please let me know and I will ask the admin.

**Comment by t3chn0m4g3** [comment]
That is odd, using ESXi 6.5 also and it works perfectly fine. Not using VMRC though. Maybe someone else can test this?

**Comment by t3chn0m4g3** [comment]
That is odd, using ESXi 6.5 also and it works perfectly fine. Not using VMRC though. Maybe someone else can test this?

**Comment by vorband** [comment]
no problem for me installing tpot 18.11 on esxi 6.7 using vmrc (on mac). 
There are many things which can fail here. I suggest in case you cannot get it working you use an ubuntu base system and install without iso.

**Comment by t3chn0m4g3** [comment]
@vorband Thank you

**Comment by xcampax** [comment]
@vorband Thank you, eventually this worked for me.
