### ISSUE TITLE
MISP

### ISSUE THREAD

**Issue by ChessSpider** [dtag-dev-sec/tpotce#316]
Has anyone thought about automatically feeding information from tpotce into MISP? https://www.misp-project.org/

**Comment by t3chn0m4g3** [comment]
We will be supporting [SISSDEN](https://sissden.eu/).

**Comment by ChessSpider** [comment]
Thanks, but, this does not seem open for everyone? Thus not really a replacement for MISP, or will it be opened up in the future?

**Comment by t3chn0m4g3** [comment]
Will be open.

**Comment by anust** [comment]
@ChessSpider  any progress on it? I need it too

**Comment by Brunohpb** [comment]
Any news ?
