### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by xcampax** [dtag-dev-sec/tpotce#317]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the FAQs in our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using? 18.11
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? n/a
- Did you install any upgrades or packages? n/a
- Did you modify any scripts? n/a
- Have you turned persistence on/off? n/a
- How much RAM is available (login via ssh and run `htop`)? 12GB
- How much stress are the CPUs under (login via ssh and run `htop`)? 0%
- How much swap space is being used (login via ssh and run `htop`)? 0
- How much free disk space is available (login via ssh and run `sudo df -h`)? 200GB
- What is the current container status (login via ssh and run `sudo dps.sh`)? n/a

Hi,

I am trying to install T-Pot on Ubuntu 18.04 LTS but am getting lots of errors. I started with the 19.03beta and attributed the errors to the, well, beta status, but the latest stable 18.11 does not work for me either. So far the errors have all been connection-related: 

`19 error git clone --template=/home/potty/.npm/_git-remotes/_templates --mirror https://github.com/taskrabbit/elasticsearch-dump.git /home/potty/.npm/_git-remotes/git-https-github-com-taskrabbit-elasticsearch-dump-git-92b24efd: fatal: unable to access 'https://github.com/taskrabbit/elasticsearch-dump.git/': Failed to connect to github.com port 443: Connection timed out`

`20 silly fetchPackageMetaData fatal: unable to access 'https://github.com/taskrabbit/elasticsearch-dump.git/': Failed to connect to github.com port 443: Connection timed out`

etc.

I am performing a manual install (./install.sh --type=user) because the ISO did not work for me. I configured the http_proxy and https_proxy environment variables:

```
abc@def:~/tpotce-18.11/iso/installer$ env |grep http
https_proxy=http://xxx:8080
http_proxy=http://xxx:8080
```

When attempting to clone one of the failing repositories manually, it works just fine:

```
abc@def:~/tpotce-18.11/iso/installer$ git clone https://github.com/taskrabbit/elasticsearch-dump.git/
Cloning into 'elasticsearch-dump'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 2986 (delta 29), reused 34 (delta 15), pack-reused 2933
Receiving objects: 100% (2986/2986), 1.06 MiB | 558.00 KiB/s, done.
Resolving deltas: 100% (1783/1783), done.
```

What am I missing?

TIA :)
Nora

**Comment by t3chn0m4g3** [comment]
@xcampax The installer will invoke a new root shell, probably not inheriting your proxy ENVs. You can try `sudo su -` set the proxy ENVs and run the installer again.

**Comment by xcampax** [comment]
Ok, that worked ... kind of ... 

I have access to the AdminUI but not to the WebUI (:64297). As the tpot process reported issues with Docker, I found #274 and tried to install 18.11.1 (update.sh -y) but am still getting errors from the Docker part:

```
### Now pulling latest docker images
###### This might take a while, please be patient!
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[...]
```

I made sure to run it as root with the environment correctly configured - the previous actions in the update sequence succeeded.

**Comment by t3chn0m4g3** [comment]
That is expected, Docker needs a different set of ENVs for supporting a proxy.

**Comment by xcampax** [comment]
Thanks for the hint. Docker is another first for me ... I am able to log into the WebUI now.

This documented solution helped me: [https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy](url)
