### ISSUE TITLE
import_kibana-objects.sh 

### ISSUE THREAD

**Issue by djerrystyle** [dtag-dev-sec/tpotce#318]
execute `myESSTATUS=$(curl -s -XGET ''$myES'_cluster/health' | jq '.' | grep -c green)
` 
is not right: "parse error: Invalid numeric literal at line 1, column 5"

correct:
`myESSTATUS=$(curl -s -XGET ''$myKIBANA'_cluster/health' | jq '.' | grep -c green)`

**Comment by t3chn0m4g3** [comment]
Fixed in #298.
