### ISSUE TITLE
DPS All Down / Docker Permission Denied after Update / Honeypot Alive?

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#319]
M,

After running update.sh to perform updates and reboot, running dps.sh on T-Pot 18.11 shows everything as down presenting a Permission Denied error on the Docker Socket.

Trying to start the Docker Service prompts for authentication which does not help either. (See Screenshot)

![TpotDockerIssue](https://user-images.githubusercontent.com/5147133/54485760-f3ac5400-48d2-11e9-8900-087dad08d9f8.png)

Interesting thing is, the honeypot seems to up and running even though all is showing down. I can log on to the Web Portal fine and view our dashboard. Tailing syslog is also a flood of incoming log data.

Any ideas?

Cheers,
Ray

**Comment by UncleRaymondo** [comment]
Seems like there was an update to docker.io as well when I look at dpkg.log... not sure if this is the cause... 

![TpotDockerUpgrade](https://user-images.githubusercontent.com/5147133/54485900-d24c6780-48d4-11e9-8204-10b71ceae054.png)

**Comment by t3chn0m4g3** [comment]
Hi Ray,
yes with #311 you need to either run as root or add your user to the docker group.
I will add a notification to the script should it be started without the necessary privileges.
Best,
M.

**Comment by UncleRaymondo** [comment]
Yep - Confirmed dps.sh working as root, and also working as standard once user is added to the docker group

Command for others: `usermod -a -G docker <yourusername>`
**(You must log out then log back in for the change to take effect)**


_Off topic... noticing kibana and logstash reporting unhealthy... easy fix?_

**Comment by UncleRaymondo** [comment]
Never mind... seems to have resolved itself... cluster health = green :) 
Closing Issue :)
