### ISSUE TITLE
Bad Archive Mirror 

### ISSUE THREAD

**Issue by eluvatl** [dtag-dev-sec/tpotce#32]
Hello,

I am installing t-pot in a VM and am at the point of "Configure Package Manager." However, I get the error message: Bad Archive Mirror. The ubuntu mirror hostname is archive.ubuntu.com and the mirror directory is /ubuntu. Has this changed? Or is there an alternative mirror that I can use?

**Comment by schmalle** [comment]
Dear Eluvatl, Please have a look e.g. at
http://askubuntu.com/questions/385627/why-did-i-a-get-a-bad-archive-mirror
the problem you are describing seems to be not related to the honeypots,
but to ubuntu itself. Best wishes Markus

**Comment by schmalle** [comment]
No, it is the basic config.
