### ISSUE TITLE
How to get data about a specific honeypot from dev tools 

### ISSUE THREAD

**Issue by changtong1996** [dtag-dev-sec/tpotce#321]
I used 17.10 versions 4 months ago, I can find attack data on the dev tools about a specific honeypot, like Cowrie and Suricata. But now I can not find attack data about a specific honeypot on the dev tools. After using `GET _mapping` command, I get data just like this.
```
{
"logstash-2019.03.18" :
"logstash-2019.03.14"：
".monitoring-kibana-6-2019.03.16" :
".kibana_2" :
".monitoring-es-6-2019.03.19" :
"logstash-2019.03.13" :
".monitoring-es-6-2019.03.16" :
"logstash-2019.03.16" :
"logstash-2019.03.12" :
}
```
After using `GET */Honeytrap/_search` command, I get 
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 14,
    "successful" : 14,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```
Did I use the wrong command? If not, how to get data about a specific honeypot from dev tools .
Looking forward to your reply.
Thanks.

**Comment by t3chn0m4g3** [comment]
I am not sure what you are referring to with 

> dev tools

However there were loads of changes regarding the ELK stack. I suggest you follow up on the ELK stack documentation.

**Comment by changtong1996** [comment]
The sidebar of the kibana page. There are some <div> like discover\dashboard\timelion\dev tools and so on. And there is a console that I can type the requests in the dev tools.
Thanks for your reply.

**Comment by t3chn0m4g3** [comment]
Works perfectly fine here, just an example.
```
GET /_search
{
    "query" : {
        "term" : { "type.keyword": "Cowrie" }
    }
}
```
However this really is within the scope of the ELK stack and how to query ES. Please follow up on the recent [documentation of the ELK stack](https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html).

Thank you for understanding.
