### ISSUE TITLE
How do i Make sure it is public

### ISSUE THREAD

**Issue by ngupdemla** [dtag-dev-sec/tpotce#323]
I Installed this on hardware 8 hours before, it is connected to my home router no proxy at all nothing is filtered. even after 8 hours i did not see any activity from the outer world, how can i male sure it is public reachable.

**Comment by t3chn0m4g3** [comment]
This depends on your router. Please review your router manual on how to expose hosts / ports towards the internet. Then follow up on the [README](https://github.com/dtag-dev-sec/tpotce#placement)
