### ISSUE TITLE
Cant connect to Webinterface T-Pot 19.03

### ISSUE THREAD

**Issue by breinkober** [dtag-dev-sec/tpotce#325]
<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using?
19.03 beta
- Are you running on a Intel NUC or a VM?
Oracle Virtual Box 6
- How long has your installation been running?
15min
- Did you modify any scripts?
No
- Have you turned persistence on/off?
No
- How much RAM is available (login via ssh and run `htop`)?
8GB
- How much stress are the CPUs under (login via ssh and run `htop`)?
10%
- How much swap space is being used (login via ssh and run `htop`)?
0K/7,63G

I have successfully installed T-Pot 19.03 in Virtual Box. 
I have set the Bridget adapter and activated promiscuous mode. 
Now I try to access the admin interface via my browser from the host system (Win 7). However, I can't get a connection to the IP address that shows me T-Pot.

What am I doing wrong?

**Comment by t3chn0m4g3** [comment]
I have configured NGINX to require TLS 1.3 now, maybe your browser does not support this?
Can you reach the T-Pot VM via ICMP?
What if you try to reach other hosts from within your T-Pot installation, i.e. via ICMP?

**Comment by breinkober** [comment]
I need to test next monday. Have a nice weekend :)

**Comment by breinkober** [comment]
I think it has something to do with the network in my company.
Although I can reach Google etc. in the browser (host system), I can't ping Google via cmd.  That's kind of weird.
And when I try to ping the IP of the VM, it first goes to the outside and then it can no longer come from the outside to the VM.

I don't think you can help me. But maybe you have a tip what I can tell my coworkers from the network team.

(Ich bin nur Praktikant :) )

**Comment by breinkober** [comment]
Ok, finally! :smile: 
I found my issue.

All I needed to do is to set a static IP for the T-Pot VM.

Solution:

> nano /etc/network/interfaces

> auto enp0s3
iface enp0s3 inet static
        address 192.168.1.100
        netmask 255.255.255.0
        gateway 192.168.1.1
        dns-nameservers 8.8.8.8

To get your name of your physical ethernet interface (for me emp0s3) just simply: 

> ls -l /sys/class/net/ | grep -v virtual

Don't forget to comment out the "primary network interace" .

**Comment by 00ihsan** [comment]
THANK YOU!! You saved me lots of headaches!
