### ISSUE TITLE
Inconsistency between visualize and dashboard

### ISSUE THREAD

**Issue by JamesBradyBear** [dtag-dev-sec/tpotce#326]
Hi, 
I am running Tpot 18.11.1 and I have just find out visualization inconsistency between dashboard and visualize. 
For the specific time period top attacking countries are totally different for same date range and same honeypot. 

Dashboard Image: 
![image](https://user-images.githubusercontent.com/1931778/54867430-76745980-4d80-11e9-84e8-4629294411a2.png)
It shows Ukraine as the top attacking country.

If I go to Visualize and enter the following query it shows United States as the top attacking country for the said honeypot and same date rage.  .

https://*****:64297/kibana/app/kibana#/visualize/edit/bd5e53d0-fa30-11e8-838f-fff066e21110?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-02-09T00:00:00.000Z',mode:absolute,to:'2019-03-16T23:59:59.999Z'))&_a=(filters:!(),linked:!t,query:(language:lucene,query:''),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:geoip.country_name.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:200),schema:segment,type:terms)),params:(addLegend:!t,addTooltip:!t,isDonut:!t,labels:(last_level:!t,show:!f,truncate:100,values:!t),legendPosition:right,shareYAxis:!t,type:pie),title:'Adbhoney%20-%20Attacks%20by%20Country',type:pie))

![image](https://user-images.githubusercontent.com/1931778/54867462-b9363180-4d80-11e9-9d30-682d12a6655c.png)

Please let me know how to fix it?

Thanks.

**Comment by t3chn0m4g3** [comment]
Your query has a different absolute date range than the screenshot:

> (from:'2019-02-09T00:00:00.000Z',mode:absolute,to:'2019-03-16T23:59:59.999Z'))
