### ISSUE TITLE
Logs 2hrs backwards

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/tpotce#33]
![image](https://cloud.githubusercontent.com/assets/17837413/14501340/14231aec-01a6-11e6-9229-591a99a85f99.png)

For some reason, the logs are registering the hour of an event two hours in the past. So if now its 18:33 and there is an event on Honeytrap, in the timestamp its registering as 16:33. Is there a way I can arrange this?

**Comment by t3chn0m4g3** [comment]
It is UTC as timezone.

**Comment by firepro20** [comment]
So I need to find a command to set the timezone?

**Comment by t3chn0m4g3** [comment]
Please check out the Ubuntu support pages:
https://help.ubuntu.com/community/UbuntuTime
