### ISSUE TITLE
T-Pot 19.03 - iptables-legacy: No such file or directory

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#330]
M,

Using the update script worked great to go from 18.11 to 19.03 - well done!

Noticing it not starting now however, tailing /var/log/syslog, it's repeatedly trying to start and failing with the error messages as follows (screenshots below):

![image](https://user-images.githubusercontent.com/5147133/55333756-a390dc80-54e3-11e9-8af0-43bdc9aa6b91.png)

![image](https://user-images.githubusercontent.com/5147133/55333606-5f054100-54e3-11e9-928e-2701dc6dd1ce.png)

Thoughts?

R

**Comment by t3chn0m4g3** [comment]
Interesting, that should not work at all.

**Comment by UncleRaymondo** [comment]
Could this be related?

https://github.com/docker/libnetwork/issues/2331

**Comment by t3chn0m4g3** [comment]
Well, the base system is no longer Ubuntu, so all sorts of things might happen. A reinstall for 19.03 is required.

**Comment by UncleRaymondo** [comment]
Ah I see ... ok I can rebuild... no problem...

Would be nice to save the old data and migrate across though... possible?

**Comment by t3chn0m4g3** [comment]
You can try `/opt/tpot/bin/dump_es.sh` and on the new system `restore_es.sh`. It untested with regard cross versioning.

**Comment by UncleRaymondo** [comment]
I'll give it a go... what's the worst that can happen ;)

**Comment by UncleRaymondo** [comment]
Well we can forget that idea...

![image](https://user-images.githubusercontent.com/5147133/55334684-704f4d00-54e5-11e9-9375-827099a165fd.png)

lol... never mind... new build here we go :D

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo Thanks for reporting. Checking now for `Debian` as release ID and this should not occur again.
Apologies for the inconveniences!

**Comment by UncleRaymondo** [comment]
No problemo my friend - glad I can be of assistance :)

**Comment by t3chn0m4g3** [comment]
Highly appreciated and valued 😄
