### ISSUE TITLE
T-Pot 19.03 - netselect-apt needs ICMP

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#332]
M,

Not sure what's going on here but I've tried this twice and it's not working.

Installed Debian 9.8 via it's smaller netinst image (not sure if the base system requires the full install image), selecting only standard system utilities to keep it headless, netinst seems to complete successfully. Installed Git (which is not part of the standard utilities), cloned tpotce and ran the installer per the Post Install User instructions.

Install completes, although I notice numerous issues as I'm reading the progress... 

- npm not found
- pip not found
- exim-base not found
- docker.io not found? (something like that as I'm reading it on the fly)

Can't recall where the log file for the installation process is (if there is one)...

On reboot, it looks like everything is installed normally but everything is down. Tried to start T-Pot, fails with docker.service not found?

dps.sh also has an OSError / stack trace

![image](https://user-images.githubusercontent.com/5147133/55339877-40a54280-54ef-11e9-94ca-8206046c8c9c.png)

What am I missing here? I'm under the impression that all dependencies are installed by default?

Let me know what I can do to test this further and resolve :)

Cheers,
R

**Comment by t3chn0m4g3** [comment]
`service` is deprecated, please try `systemctl start tpot` or `systemctl stop tpot`

**Comment by t3chn0m4g3** [comment]
Can you attach `/install.log` and `install.err`, please.

**Comment by UncleRaymondo** [comment]
Same... Docker seems to be installed though???

![image](https://user-images.githubusercontent.com/5147133/55340261-0be5bb00-54f0-11e9-9408-a7943e32a14b.png)

**Comment by t3chn0m4g3** [comment]
That is the old docker from 9.8.

**Comment by t3chn0m4g3** [comment]
It looks if the move to unstable did not work ...
What are the contents of `/etc/apt/source.list`?
If you run `netselect-apt -n -a amd64 unstable` and then `cat sources.list`?

**Comment by UncleRaymondo** [comment]
Hmmm... weird... 

I'll screenshot the errors as the system is isolated and no way to extract the files from it ;) 

`install.err`

![image](https://user-images.githubusercontent.com/5147133/55340412-5bc48200-54f0-11e9-85ca-00fe9f7ee9ce.png)
![image](https://user-images.githubusercontent.com/5147133/55340428-64b55380-54f0-11e9-8fb5-1feedd634cf8.png)
![image](https://user-images.githubusercontent.com/5147133/55340444-6d0d8e80-54f0-11e9-9001-c173ed1df663.png)
![image](https://user-images.githubusercontent.com/5147133/55340461-772f8d00-54f0-11e9-9dda-f7eba941e002.png)


`install.log`

![image](https://user-images.githubusercontent.com/5147133/55340493-8d3d4d80-54f0-11e9-959a-26c104b30d1e.png)
![image](https://user-images.githubusercontent.com/5147133/55340513-94fcf200-54f0-11e9-85a3-c3162c168181.png)
![image](https://user-images.githubusercontent.com/5147133/55340530-9dedc380-54f0-11e9-9f4a-0e1a490305d0.png)
![image](https://user-images.githubusercontent.com/5147133/55340549-a514d180-54f0-11e9-8a60-e31e1f750fe1.png)
![image](https://user-images.githubusercontent.com/5147133/55340559-ad6d0c80-54f0-11e9-94da-14dd2024a443.png)
![image](https://user-images.githubusercontent.com/5147133/55340576-b65dde00-54f0-11e9-876a-7f6acb6ce2c5.png)
![image](https://user-images.githubusercontent.com/5147133/55340613-c5449080-54f0-11e9-9bb6-d7ca8dad668e.png)

**Comment by UncleRaymondo** [comment]
Yeah definitely no unstable repositories here...

![image](https://user-images.githubusercontent.com/5147133/55340775-16ed1b00-54f1-11e9-8144-8bb2cfe33703.png)

The netselect command seems to repeat those Duplicate Address messages in the screenshots above...

**Comment by t3chn0m4g3** [comment]
Thanks, found it. But this will need  some more time for tweaking. ``netselect-apt` does not work correctly for some reason in your setup. Need to properly intercept the error and write a generic `sources.list` if it occurs.

**Comment by UncleRaymondo** [comment]
I've just noticed this error...

![image](https://user-images.githubusercontent.com/5147133/55341026-9bd83480-54f1-11e9-89d3-a52ea7f52d30.png)

ICMP is blocked outbound... are you telling me that netselect is that incompetent that it needs ICMP or UDP Traceroute?

**Comment by t3chn0m4g3** [comment]
Unfortunately it looks that way 🙁 I am as surprised by that as you are.

**Comment by UncleRaymondo** [comment]
Let me open up ICMP outbound, blow the box away again, reinstall 9.8 via netinst and try clone and build again... give me 30 mins :)

**Comment by UncleRaymondo** [comment]
Looks like it definitely needs ICMP Outbound... it's flooding through on unstable installs now...

![image](https://user-images.githubusercontent.com/5147133/55342318-43566680-54f4-11e9-918a-a070c23f717d.png)

**Comment by t3chn0m4g3** [comment]
Thanks, not sure though it if is not better to leave it this way and document it. Especially with Australia and Asia as region the default mirror was reported to us as too slow.

What do you think?

**Comment by UncleRaymondo** [comment]
I would document that ICMP Outbound is required due to the incompetence of netselect, but also have a fall back to protect the amateurs. Do a test ping, if it fails, write a manual sources.list, skipping the netselect process entirely. If it works, proceed as normal with netselect.

Everything in Australia is slow :P but my ISP has a localised Debian mirror so I don't really notice much slowness. All the mirrors above except the last two are Australian hosted/based. If you're going do a manual script, the aarnet.edu.au mirror is a safe bet with ftp.au.debian.org as a fall back.

**Comment by UncleRaymondo** [comment]
It ultimately seems like that netselect ICMP issue was the problem... install's still going, docker's pulling images now, seems to be running smoothly so far...

**Comment by t3chn0m4g3** [comment]
Will have a fallback option.
How does the netselect-apt chosen mirror work for you? Is the automatic choice bearable with regard to speed, a.k.a. does netselect do a good job?

**Comment by UncleRaymondo** [comment]
I think it does a pretty reasonable job... I'm on 100Mbps down, 40 Mbps here, fibre to the home. It is also 3:20am so network is pretty quiet.

In saying that, installation is done...

![image](https://user-images.githubusercontent.com/5147133/55343147-3c305800-54f6-11e9-8046-c4b106bd88fd.png)

30 mins to rebuild Debian 9.8 from the netinst image, and to install T-Pot 19.03... I think that's pretty reasonable ;)

**Comment by t3chn0m4g3** [comment]
Perfect! Thanks for the prompt feedback!

**Comment by UncleRaymondo** [comment]
Looks like all is healthy

![image](https://user-images.githubusercontent.com/5147133/55343386-b365ec00-54f6-11e9-8cb4-8de80b36cca4.png)

**Comment by t3chn0m4g3** [comment]
That's how I like my `dps.sh` 😄

**Comment by UncleRaymondo** [comment]
Now to go get some sleep - and play with it more tomorrow!
Enjoy the rest of your day :)

**Comment by t3chn0m4g3** [comment]
Thanks and have a good night!

**Comment by UncleRaymondo** [comment]
M,

Just thinking - maybe make a note as well that it's only required during the installation process. Yet to confirm but I can't see any other reason why this needs to remain open after install...

Cheers,
R

**Comment by t3chn0m4g3** [comment]
Can you check out the `fast` branch, please. Should fix and improve speed even more.

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo Now in master.
