### ISSUE TITLE
ntp daemon killing network interfaces

### ISSUE THREAD

**Issue by spudstr** [dtag-dev-sec/tpotce#333]
Found an issue with ntp killing network interfaces, the solution is to add the -L flag to /etc/default/ntp

The issue was found running Debian on AWS ec2 instances.

syslog would show normal activity and then.. nothing.  Looking back at the log right after the network disconnect was the following.

```
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: Deleting interface #3 eth0, 172.16.0.165#123, interface stats: received=553, sent=556, dropped=0, active_time=3589 secs
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: x.155.79.108 local addr 172.16.0.165 -> <null>
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: x88.126.235 local addr 172.16.0.165 -> <null>
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: x.43.30.59 local addr 172.16.0.165 -> <null>
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: x.30.35.88 local addr 172.16.0.165 -> <null>
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: x.36.182.57 local addr 172.16.0.165 -> <null>
Apr  3 01:21:26 ip-172-16-0-165 ntpd[861]: x.131.160.7 local addr 172.16.0.165 -> <null>
```
So far this has seemed to have resolved the issue.

**Comment by spudstr** [comment]
nevermind, this did not resolve the issue.  But something is causing a network disconnect somewhere.

**Comment by t3chn0m4g3** [comment]
NTP does not delete interfaces it simply closes previously opened sockets on an interface that is undergoing changes. These messages usually occur at boot time and usually an interface state change is involved.

The [`-L`](https://linux.die.net/man/8/ntpd) option you proposed simply prevents ntpd to bind to virtual IPs which will not resolve the `delete` messages.

I am closing this for now, based on the information given this seems to be normal behaviour with regard to ntpd.
