### ISSUE TITLE
nmap result on TPOT

### ISSUE THREAD

**Issue by ptitpoulpe** [dtag-dev-sec/tpotce#334]
I try to test TPOT (in a VM) with nmap (7.70), but I never get the same result (different ports opened),
there is some random openned port ? Is it possible to avoid randomness ?
Thanks in advance

**Comment by t3chn0m4g3** [comment]
The question seems to be a little out of T-Pot scope. `nmap` offers way to many scanning options to give you an exact answer.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, closing for now.
