### ISSUE TITLE
Kibana connection refused TPOT 1903

### ISSUE THREAD

**Issue by ghost** [dtag-dev-sec/tpotce#335]
Hi, I installed TPOT 1903 with a brand new installation but Kibana refused the connection and seem to listen to a different port. The documentation show 64297 but Kibana listen on port 64296 with the issue previously mentioned. The command dps.sh show that all docker image are UP and healthy. Thank you for this amazing project

**Comment by t3chn0m4g3** [comment]
@raffutz85 Thanks.
Please run ...
```
netstat -tulpen | grep 64297
```
... and post the output.

Also, you need a TLS1.3 enabled browser like the latest Chrome, Safari or Firefox since the WebUI now enforces TLS1.3.

**Comment by backherozzo** [comment]
Attached the command output and also dps.sh output
<img width="555" alt="Screenshot 2019-04-03 at 11 04 28" src="https://user-images.githubusercontent.com/10944557/55466888-68d09680-5600-11e9-8c32-6b2fe058b3ef.png">
<img width="387" alt="Screenshot 2019-04-03 at 11 05 06" src="https://user-images.githubusercontent.com/10944557/55466896-6d954a80-5600-11e9-874f-50f592b06ba7.png">

**Comment by t3chn0m4g3** [comment]
In the `dps.sh` you have to look for `nginx` which reverse proxies requests to `kibana`. `64297` and `nginx` seem to be running. I am assuming your browser does not support TLS 1.3.

**Comment by backherozzo** [comment]
I checked in all my browser if TLS 1.3 is compatible and this is the screen for Firefox that support TLS 1.3

<img width="548" alt="Screenshot 2019-04-03 at 11 50 29" src="https://user-images.githubusercontent.com/10944557/55469900-c4058780-5606-11e9-865d-696c11619686.png">

**Comment by t3chn0m4g3** [comment]
Do you have a weird reverse proxying or NAT going on?
Can you reach the machine via the other services (http, https, cockpit on 64294, etc.)?
What error does Firefox show you when you try to connect?
What is your exact setup? VM, Phys, etc.? Maybe NAT instead of bridge?

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved, closing for now.

**Comment by MadGeckoo** [comment]
Hi, I got the same exact problem. Today, I installed latest version of T-pot using installer on clean cloud Debian.  

I can access cockpit and also tcpdump shows incoming and outgoing packets when I connect to 64297, but I can't seem to get Kibana UI.

Outputs of netstat and dps.sh are the same as above.

My setup is cloud machine in openstack.  TLS 1.3 is supported by all my browsers
