### ISSUE TITLE
Problem interface for test the t-pot in the LAN

### ISSUE THREAD

**Issue by niening** [dtag-dev-sec/tpotce#337]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the FAQs in our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using? 18.11
- Are you running on a Intel NUC or a VM? VM(in the Proxmox)
- How long has your installation been running?  two week
- Did you install any upgrades or packages?  used update.sh one time
- Did you modify any scripts? no
- Have you turned persistence on/off?  persistence has the default setting so I think is off
- How much RAM is available (login via ssh and run `htop`)?  4G
- How much stress are the CPUs under (login via ssh and run `htop`)? 20%
- How much swap space is being used (login via ssh and run `htop`)?35%
- How much free disk space is available (login via ssh and run `sudo df -h`)?140G
- What is the current container status (login via ssh and run `sudo dps.sh`)? all the services are up and going well

 

Hello
I have one problem for the interface connected because I installed the t-pot in the Ubuntu LTS 18.02 and run in the Virtualization by proxmox in the company, the t-pot running well and all the service going well
 
I just want to test it inside the company at first(test in the LAN first and test in the WAN in the future), I could login from the browser and access the Web UI&Admin UI by port 64294 and 64297 but only by another Virtualization(i used Ubuntu 18.02 gnome) that was created in the same platform in the proxmox 

I can't connect (can't ping to the IP of t-pot) the t-pot by my computer(also for the other computer) in the LAN company. I can see all the IP of t-pot include en0s8, docker, and almost 12 bridge like 172.10.0.0, etc~  

Could you help me and tell me how to configure the interface to realize connect all the computer in the LAN company for test the t-pot.

Thank you very much and look forward to your reply
Best regard

**Comment by niening** [comment]
PS: I posted the same question in the GitHub last Saturday but i can't find it, maybe i posted by the wrong way

**Comment by breinkober** [comment]
Hello,

have you set a bridge network in your vm settings? and do you have a static ip? 
#325

**Comment by niening** [comment]
@breinkober Hi, thank you for your reply
I set the static IP and set the bridge network in the proxmox, and the rule of iptable are all accepted, i can see the number of the ping times in the iptable also, but i can't receive the package form t-pot  when i ping it, i saw the record of the information iptable and there is one transport from 172.X.X.0 to another 172.X.X.0

**Comment by t3chn0m4g3** [comment]
Another remark, please use [T-Pot 19.03](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03) which is based on Debian. 18.11 is no longer supported.

**Comment by niening** [comment]
I try to install the t-pot in the Debian9.8 and i dont know it's normal?
<img width="482" alt="t-pot2" src="https://user-images.githubusercontent.com/16206667/55637389-3623cb00-57c5-11e9-8daa-ef73a40fbb78.PNG">

**Comment by t3chn0m4g3** [comment]
No, please attach `/install.log` and `install.err`.

**Comment by t3chn0m4g3** [comment]
Just fixed it. Please run `git pull` and try again.

**Comment by niening** [comment]
Thank you very much for your apply and i try to install again
