### ISSUE TITLE
live visualisation 

### ISSUE THREAD

**Issue by nsk** [dtag-dev-sec/tpotce#342]
hello 
would it be possible to add a module "Logstalgia" to have a visualisaiton live of the activity of Tpot here is a links

https://www.youtube.com/watch?v=J39QjecJ-uQ&list=LLV6pwzXNgUxE-Uk3ThQlRUQ&index=2&t=2s 

Many Thanks 

ALex

**Comment by t3chn0m4g3** [comment]
Thanks, while it looks really nice it does not seem to support JSON based logs which most of our honeypots use. At least I could not find it on their [repo](https://github.com/acaudwell/Logstalgia). So, sadly no, we cannot implement it.

Even with 3rd party plugins available [plugins](https://www.elastic.co/guide/en/kibana/current/known-plugins.html) for the ELK stack it is always a gamble on how long these will be supported (given the high velocity of ELK development) and how good they are being maintained.
