### ISSUE TITLE
Logs Arriving in delay

### ISSUE THREAD

**Issue by matan1398** [dtag-dev-sec/tpotce#343]
Hi,
I try and perform attacks on the honeypot, but the logs of those attacks arrive to kibana in about 2 hours delay.
Is there any way of making it arrive immediately? or maybe few mins delay at worst case?

Thank you

**Comment by t3chn0m4g3** [comment]
An exact 2h delay usually points to the fact that the machine is not running on UTC. The BIOS clock is usually preferred over the of the OS.

**Comment by t3chn0m4g3** [comment]
Check if system is running UTC, then `systemctl stop tpot` and the sync time to BIOS with `hwclock --systohc`.

**Comment by matan1398** [comment]
thanks for the quick reply.
i tried what you said, rebooted, tried attacking again, and it's been few minutes and still it doesn't show in kibana.

**Comment by matan1398** [comment]
RTC is off, the clocks are in sync

**Comment by t3chn0m4g3** [comment]
What does `hwclock` show?
What timezone does Kibana show (Kibana > Settings):
![image](https://user-images.githubusercontent.com/4318452/55868028-f291de00-5b83-11e9-9ede-991e5da8de65.png)
What timezone does your desktop show?

**Comment by matan1398** [comment]
The hwclock and date show the same time.
kibana is set on browser and the timezone on my desktop is on jerusalem (UTC +2:00).
And it's working! thank you so much!

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback and welcome.
