### ISSUE TITLE
apt-fast and curl

### ISSUE THREAD

**Issue by FredericUhlmann** [dtag-dev-sec/tpotce#344]
Hi to you all,

I am currently trying to develop a custom solution to test a few things based on tpot.

So when the change from Ubuntu to Debian happened, I obviously had to adapt my custom solution to the new version. While doing so, I saw a little issue with the install script of the new version.

The problem should occur when using the install script on a debian with minimal installations. As to install cursl the script uses apt-fast, and to install apt-fast it uses curl.

So if neither apt-fast nor curl are avaiable on the new debian installation the script won't work properly.

Hopefully I'm letting you know about something you had not already discovered yourself.

Just to clearify, this is not an issue, it is a bug report (well I do think this is a bug).

Hope it helps. Nice product by the way. i am loving it!

**Comment by t3chn0m4g3** [comment]
?

**Comment by FredericUhlmann** [comment]
Sorry just updated the comment. I mistakenly hit enter before writing the propper text

**Comment by t3chn0m4g3** [comment]
This was fixed in https://github.com/dtag-dev-sec/tpotce/commit/9f7f5068c0684ca2d31e8af1238096de3f91a8d8

**Comment by t3chn0m4g3** [comment]
Thanks for reporting and the great feedback. I am closing this now, should the problem persist please let me know.
