### ISSUE TITLE
ip of bridge for the image in the container conflict ip of computer private in the LAN

### ISSUE THREAD

**Issue by niening** [dtag-dev-sec/tpotce#345]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the FAQs in our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="info"></a>
### Basic support information

- What T-Pot version are you currently using? 19.03
- Are you running on a Intel NUC or a VM? VM in the Proxmox
- How long has your installation been running? 1 week
- Did you install any upgrades or packages? update.sh 1 time
- Did you modify any scripts? no
- Have you turned persistence on/off? 
- How much RAM is available (login via ssh and run `htop`)? 
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)? 140G
- What is the current container status (login via ssh and run `sudo dps.sh`)? all up

Hello
I have a question bothering me for some days, I install t-pot in the virtual machine run in the Proxmox
I want to test it in the LAN as an internal environment, but every IP of all containers (every bridge of the image) are conflicting the IP of the internal computer, i try to create and configure the file "daemon.json" in /etc/docker, then almost all the image can't work
I think this is a simple question but i don't want to waste time in a purposeless search in the internet,  i appreciate if someone can help me, tell me where the file or how to configure the ip of every image in every container, or just some method to configure the bridge docker0 to configuration ip of bridge every image automatic what I need, so when i reboot the machine il will run well
Thanks

**Comment by t3chn0m4g3** [comment]
A good start is always the [official docker documentation](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/) or the [success center](https://success.docker.com/article/how-do-i-configure-the-default-bridge-docker0-network-for-docker-engine-to-a-different-subnet).

In either case this is not an issue with T-Pot but with your specific setup and docker.

**Comment by niening** [comment]
thank you for your reply @t3chn0m4g3
I will look carefully in the documents about docker
