### ISSUE TITLE
tpot not installing elasticsearch-dump

### ISSUE THREAD

**Issue by FredericUhlmann** [dtag-dev-sec/tpotce#346]
Hi,

I am not entirely sure if it's just me, but when installing tpot from the installation script on a debian, it does not seem to be able to execute the npm install elasticsearch-dump command (npm install https://github.com/taskrabbit/elasticsearch-dump -g) because it seems to be missing privileges.

The weirdest thing is that I'm only able to install it manually on the host whilst being root *AND* executing the command with sudo (which in my head does not make any sense at all, why should I require sudo if I'm already root?)

Any ideas? Is that normal? any way to solve that issue?

Thanks in advance!

**Comment by t3chn0m4g3** [comment]
Thanks for the info, however, none of our installs (iso, cloud, etc.) do show this behavior. The iso image is based on a 9.x mini iso and will be migrated to Sid upon the second stage of the install. Cloud images we are using are either 9.7 or 9.8. Everything works as expected.

Maybe the install logs (`/install.log, /install.err`) can shed some light on this.

**Comment by FredericUhlmann** [comment]
I'll leave you a screenshot of the install.err file, precisely of the section that I mentioned.

![image](https://user-images.githubusercontent.com/11219082/55957607-0b26f480-5c67-11e9-8418-eb290a60b84f.png)

Hopefully you might get any idea by seeing this. I just don't know why this error occurs, and specially only to me (considering it works for you with all of your installs). It's a regular debian 9.8 image.

Let me know if you detect anything unusual in the screenshot or have any idea on what to try. (As I said previously, by doing it manually from the command prompt the only way for it to get installed is running sudo whist being root, which again, doesn't make to much sense to me)

Thanks for the help!

**Comment by t3chn0m4g3** [comment]
Looks perfectly fine in any of our installs, cannot reproduce (`/install.log`):
```
 ___           _        _ _ _                     _
|_ _|_ __  ___| |_ __ _| | (_)_ __   __ _   _ __ | | ____ _ ___
 | || '_ \/ __| __/ _` | | | | '_ \ / _` | | '_ \| |/ / _` / __|
 | || | | \__ \ || (_| | | | | | | | (_| | | |_) |   < (_| \__ \
|___|_| |_|___/\__\__,_|_|_|_|_| |_|\__, | | .__/|_|\_\__, |___/
                                    |___/  |_|        |___/
/usr/local/bin/multielasticdump -> /usr/local/lib/node_modules/elasticdump/bin/multielasticdump
/usr/local/bin/elasticdump -> /usr/local/lib/node_modules/elasticdump/bin/elasticdump
+ elasticdump@4.7.0
```

**Comment by FredericUhlmann** [comment]
Could you maybe provide me a URL/link to the exact debian image you are using? I'd like to try, maybe it's related to the image I am using...

**Comment by t3chn0m4g3** [comment]
https://github.com/dtag-dev-sec/tpotce/blob/19c30f9709e7e348c044667c5069750699cbf759/makeiso.sh#L11

**Comment by FredericUhlmann** [comment]
Thank you so much for your help/time!

I'll try to set it up again with that image and see what happens.

I'll let you know as soon as I have tried it!

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
