### ISSUE TITLE
E: Package 'netselect-apt' has no installation candidate

### ISSUE THREAD

**Issue by Bi3g0** [dtag-dev-sec/tpotce#349]
`root@mycast:~/tpotce/iso/installer# ./install.sh --type=auto --conf=tpot.conf

Fetched 5,092 kB in 4s (1,119 kB/s)            
Reading package lists... Done

Working... this may take a while.
E: Package 'netselect-apt' has no installation candidate
Package manager quit with exit code.
Aborting. Debian xenial is not supported.

`
![image](https://user-images.githubusercontent.com/18691823/56020517-ebaccc00-5d39-11e9-9c26-bb76cad7e09f.png)

My env is as follow:
![image](https://user-images.githubusercontent.com/18691823/56020533-f5363400-5d39-11e9-8229-afcbd8d8546a.png)

**Comment by t3chn0m4g3** [comment]
This is expected, since you need a Debian installation. With 19.03 we switched to Debian.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by destech** [comment]
which version of debian ?

**Comment by adrianx26** [comment]
Any solution for this problem ?

**Comment by t3chn0m4g3** [comment]
This is by design. There is no upgrading from Ubuntu to Debian. Reinstallation is required.
