### ISSUE TITLE
How do I login into Cockpit?

### ISSUE THREAD

**Issue by mrdavi5** [dtag-dev-sec/tpotce#350]
# Issues

## ⚠️ Basic support information (commands are expected to run as `root`) ⚠️

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
- What T-Pot version are you currently using?
Latest 19.03 ( commit  5860fcd )
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Cloud VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
I have had to reinstall a few times as the username and passwords would not work on the web portals or SSH. 
- How long has your installation been running? 
31mins
- Did you install upgrades, packages or use the update script?
Only used the ./install script
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
69Gb
- What is the current container status (`dps.sh`)?
```
========| System |========
    Date:  Sat 13 Apr 2019 12:15:58 PM UTC
  Uptime:  12:15:58 up 33 min,  1 user,  load average: 0.36, 0.40, 0.37

NAME                  STATUS                       PORTS
adbhoney              Up 33 minutes             0.0.0.0:5555->5555/tcp
ciscoasa              Up 33 minutes             
conpot_guardian_ast   Up 33 minutes             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 33 minutes             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 33 minutes             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 33 minutes             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 33 minutes             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 33 minutes (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 33 minutes             
elasticpot            Up 33 minutes             0.0.0.0:9200->9200/tcp
elasticsearch         Up 33 minutes (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 33 minutes             
head                  Up 32 minutes (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 33 minutes             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up 33 minutes             
kibana                Up 32 minutes (healthy)   127.0.0.1:64296->5601/tcp
mailoney              Up 33 minutes             0.0.0.0:25->25/tcp
medpot                Up 33 minutes             0.0.0.0:2575->2575/tcp
nginx                 Up 33 minutes             
p0f                   Up 33 minutes             
rdpy                  Up 33 minutes             0.0.0.0:3389->3389/tcp
snare                 Up 33 minutes             0.0.0.0:80->80/tcp
spiderfoot            Up 33 minutes (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 33 minutes             
tanner                Up 33 minutes             
tanner_api            Up 33 minutes             
tanner_phpox          Up 33 minutes             
tanner_redis          Up 33 minutes             6379/tcp
tanner_web            Up 33 minutes             
logstash              DOWN       
```
- What is the status of the T-Pot service (`systemctl status tpot`)?
```
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-04-13 11:42:44 UTC; 33min ago
  Process: 965 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 987 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 1032 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 1035 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 1038 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 1056 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 1070 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 1085 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 1104 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx 
  Process: 1110 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gr
  Process: 1116 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc o
  Process: 1122 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 1193 (docker-compose)
    Tasks: 31 (limit: 4696)
   Memory: 49.3M
   CGroup: /system.slice/tpot.service
           └─1193 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Apr 13 12:16:27 Mr-T-01 docker-compose[1193]: ewsposter              |     => [GLUTTON] [ERROR] Missing LogFile /data/glutton/log/glutton.log.
Apr 13 12:16:27 Mr-T-01 docker-compose[1193]: ewsposter              |  => Send Limit is set to : 500. Adapting to limit!
Apr 13 12:16:27 Mr-T-01 docker-compose[1193]: ewsposter              |     -> 0 EWS alert records send ...
Apr 13 12:16:27 Mr-T-01 docker-compose[1193]: ewsposter              |  => Sleeping for 60 seconds ....
```

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

The Issue i am experiencing is after a fresh install and multiple attempts. I can now log into the Kibana portal hosted on port 64297 however I still cannot access the 64294 portal. I receive the log in page but when trying to log in i get: Wrong User name or password.

**Comment by t3chn0m4g3** [comment]
Login credentials are either `tsec` and the password you chose or the Linux user you have been installing under.

**Comment by mrdavi5** [comment]
Hi, 
Ive tried the variations and still not working, during the install wizard it told me I couldn't use tsec as a name so I created "webtsec". I ran this install under root. I have tried logging in with the webtsec creds I created and the root account both do not work. I have also tried tsec as the user name and the password I set during the install.

**Comment by t3chn0m4g3** [comment]
Cockpit and SSH are accessed by the user when you set up your machine. If you only had a root user to begin with then any login on Cockpit and SSH will fail for security reasons. You have to [create another user locally on your machine then and this user to the `sudo` group in `/etc/group`](https://www.digitalocean.com/community/tutorials/how-to-create-a-sudo-user-on-ubuntu-quickstart).
Also, you probably hit the authentication limit of fail2ban. Review the status of the jails with `fail2ban-client status` and by adding the `<jail name>` you can check if a ban is currently active. With `fail2ban-client unban --all` you unban all blocked IPs again.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by tututu-patch** [comment]
I also encountered the same problem and could not log in.

**Comment by tututu-patch** [comment]
Even if I create a new user, I can't log in.

**Comment by tututu-patch** [comment]
I also encountered the same problem and could not log in.
