### ISSUE TITLE
Feature Request: Kibana 7.0.0 

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#351]
Hello, not an issue more of a request.

could you guys upgrade to kibana 7.0.0? 

That dark theme everwhere is toooooooooo cool to pass up :D 

love what you guys are doing!!!!

**Comment by t3chn0m4g3** [comment]
@iukea1 Thank you :bowtie: 

Eventually we will be upgrading to ELK 7, however, what particular advantages do you see in Kibana 7.0.0? Personally I find the new UI very disappointing and also taking up too much vertical canvas, leaving less for the dashboard...

![image](https://user-images.githubusercontent.com/4318452/56193774-b9e57f00-6031-11e9-99e9-e1e5367a5d57.png)

**Comment by iukea1** [comment]
I am guessing it is not as simple as just updating 


# Get and install packages
    cd /root/dist/ && \
    mkdir -p /usr/share/kibana/ && \
    aria2c -s 16 -x 16 https://artifacts.elastic.co/downloads/kibana/kibana-6.6.2-linux-x86_64.tar.gz && \
    tar xvfz kibana-6.6.2-linux-x86_64.tar.gz --strip-components=1 -C /usr/share/kibana/ && \

to

# Get and install packages
    cd /root/dist/ && \
    mkdir -p /usr/share/kibana/ && \
    aria2c -s 16 -x 16 https://artifacts.elastic.co/downloads/kibana/kibana-7.0.0-linux-x86_64.tar.gz && \
    tar xvfz kibana-7.0.0-linux-x86_64.tar.gz --strip-components=1 -C /usr/share/kibana/ && \




never is that easy :(

**Comment by t3chn0m4g3** [comment]
Well yes, it is even easier. You can activate the Kibana 7 theme on the Kibana settings page. Just search for `K7`.

**Comment by t3chn0m4g3** [comment]
Closing this now, since we will be upgrading to ELK7 anyway at some point.

**Comment by Delta1977** [comment]
@t3chn0m4g3 Hi, Since June 25, 2019 Kibana 7.2.0. is in wild. Any Plans for upgrading Kibana and Elasticsearch ?

**Comment by t3chn0m4g3** [comment]
No, not before the next major release.
