### ISSUE TITLE
Suricata CVE question

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#352]
Hello I am only getting one vul in my suricata tab

Any suggestions on how to bump this number up? I know that Suricata goes off the cve.yml file in listbot that lives inside of Logstash. was just curious if you have any words of wisdom? 

![image](https://user-images.githubusercontent.com/35882815/56219898-23af5a00-602d-11e9-8e0a-8745ad5b1c1d.png)

**Comment by t3chn0m4g3** [comment]
Based on the information given I cannot even guess.
