### ISSUE TITLE
Enforced TLS 1.3 on the T-Pot WebUI - need TLS 1.2

### ISSUE THREAD

**Issue by ssl** [dtag-dev-sec/tpotce#354]
Hi,

We recently upgraded to T-Pot 19.03, which enforces TLS 1.3. Currently we are extracting data from the search API on a server that does not support TLS 1.3. Because of this we can no longer extract the data from the API.

Is there any way to also enable TLS 1.2? Thanks in advanced!

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux buster/sid
Release:	unstable
Codename:	sid
$ uname -a
Linux variedreality 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
```

**Comment by t3chn0m4g3** [comment]
Not out of the box.

Follow [this Wiki article](https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-ews.cfg) on how to work with volumes. Then retrieve `tpotweb.conf` and adjust TLS settings accordingly.

**Comment by ssl** [comment]
Hi @t3chn0m4g3,

Thanks for your help! This fixed the issue.

Topic can be closed.

**Comment by t3chn0m4g3** [comment]
@ssl You are welcome and thank you for the feedback!
