### ISSUE TITLE
Using Paid Snort Rules on Suricata IDS in T-Pot

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#357]
M,

Modifying /opt/tpot/etc/tpot.yml with a Snort Paid Rules Oinkcode seems to kill suricata (i.e doesn't start when I restart the tpot service). 

Ref: https://github.com/dtag-dev-sec/tpotce/issues/193

Is this supported on 19.03 at all?

R

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo We are supporting Emerging Threats at this time, which was reported working. However I personally have no key to test this.

Upon Suricata start the [update script](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/dist/update.sh) will be executed, basically it is just this line:
https://github.com/dtag-dev-sec/tpotce/blob/9ec1992929c3b615dfea7d5bbf711d4f4021f342/docker/suricata/dist/update.sh#L22
I suggest to enter Suricata `docker exec -it suricata ash` and ask you to debug the script by removing `-q` for `wget`. Please post the output so I can assist.

**Comment by UncleRaymondo** [comment]
Just tried that URL manually with out OINKCODE and it's a 404 - it's a Snort Oinkcode not an ET Pro Oinkcode... :( 

Looks like there's quite a number of differences between them: https://suricata.readthedocs.io/en/suricata-4.1.3/rules/differences-from-snort.html - Probably not worth the headache to look at and convert...

Snort Pro has a Personal Subscription for $29/year which is the one I have... ET Pro I think is much more pricy - I'll have a chat with them and see what they have on offer...

Suricata is the better IDS from what I've heard, although the newer Snort that's coming soon is supposed to close the gap...

**Comment by t3chn0m4g3** [comment]
Since we decided for Suricata because of the builtin multicore support and JSON logging I lost track of Snort entirely. ATM I do not think it will make much sense to switch to Snort.
I scanned through the link you provided and also think it is too much headache to make it work with Suricata, especially WRT future changes on both ends.
Closing this for now.
