### ISSUE TITLE
404 Not Found Kibana

### ISSUE THREAD

**Issue by scaredsecurity** [dtag-dev-sec/tpotce#363]
# Issues
Kibana is giving a 404 Not Found error after install. I've tried about 4 times now and on different operating systems and cloud arches. I just used the prebuilt iso to build everything up, but after installation I still get 404. I feel like I must be missing a step or something.

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
I tried Standard, Nextgen and Industrial reinstallations
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Digital Ocean cloud. I built a VDI from your ISO and uploaded to a droplet. I tried AWS first though.
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Not that I can see
- How long has your installation been running?
30 min
- Did you install upgrades, packages or use the update script?
I installed locate after the errors to try and debug, I tried the update script to fix it too.
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/49917952/57253491-b5dec880-7003-11e9-9459-99e62f36ae6f.png)
![image](https://user-images.githubusercontent.com/49917952/57253522-c8f19880-7003-11e9-83c0-f3c4b52ed4d9.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/49917952/57253583-ea528480-7003-11e9-96b2-b6c13e07af2e.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/49917952/57253597-f8080a00-7003-11e9-8681-db576e96bfe5.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/49917952/57253639-0d7d3400-7004-11e9-831e-4bcbde90c28b.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/49917952/57253667-1cfc7d00-7004-11e9-95e4-54f3cbcd520a.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
N/A

**Comment by scaredsecurity** [comment]
Also, I am SSH tunneled correctly for accessing Kibana since I forgot to mention that in the OP.

**Comment by t3chn0m4g3** [comment]
1. Can you access honeypot services, i.e. Cowrie on tcp/22 or Snare on tcp/80?
2. Access to Kibana is only supported through `https://<your_host>:64297`

**Comment by scaredsecurity** [comment]
Yes, I know that. When I load the kibana web page I'm presented with this error:
 {"statusCode":404,"error":"Not Found"} 

It is running, but not connected to the correct elasticsearch index I believe. See: https://discuss.elastic.co/t/reporting-error-404-and-kibana-unable-to-connect/79049

For more information. I've tried several different installs and architectures using both prebuilt isos and vms I built from the iso and I also tried just running the base install script at both ./install.sh and ./iso/installer/install.sh or whatever it is. None of them work. The honeypots install correctly but the interface to access the data does not.

**Comment by t3chn0m4g3** [comment]
Are you using different ports than from my example?
What about connecting directly as the documentation suggests?

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.

**Comment by leaustinwile** [comment]
No I am not. I've tried everything. Both according to the documentation and according to the internet's solutions. What I believe is happening is Kibana was configured incorrectly and is not pointing to the Elasticsearch instance. I don't know how to fix that as none of the kibana config files are where they normally are as everything is dockerized.

**Comment by h4sh5** [comment]
@leaustinwile  @scaredsecurity  You need to forward the port 64297 instead (`ssh .... -L 64297:127.0.0.1:64297`), and then access via https://127.0.0.1:64297 and ignore the HTTPS certificate error.

I got the same issue when using 64296 - assuming it's not supported anymore.
