### ISSUE TITLE
Can You FTP into the Data Folder?

### ISSUE THREAD

**Issue by izotope115** [dtag-dev-sec/tpotce#365]
Is it possible to FTP into the /data/dionaea/binaries directory? For some reason I cant log into the server via ssh anymore.

**Comment by t3chn0m4g3** [comment]
No, only ssh on tcp/64295. SSH is enabled by default (`systemctl enable ssh`) and started via `systemctl start ssh`.

**Comment by izotope115** [comment]
Ok thanks. And just to be sure Im doing things correctly. Do you log into tpotce by running the creds you originally set up on install? Or should they be the same creds I created when setting up my DigitalOcean VPS? 

Thanks for the help. I just dont understand why when I use my original creds I set up for my DO VPS - I dont see tpot installed anywhere. And the login user shows: ###@ubuntu:/#

Thanks for your patience and wonderful product. Im just a little new to setting up VPS's.

**Comment by t3chn0m4g3** [comment]
If you installed from ISO the SSH login user is `tsec` and your password. The webuser name / pw is chosen on your behalf.
If you manually installed on top of one of your VPSs you can login via SSH with the user you chose for remote access to your VPS (not part of the T-Pot installation). The webuser credentials are the ones you chose during install.
I noticed your prompt `ubuntu`, the 19.03 version of T-Pot only supports Debian. The update script did not have a proper check before we moved from Ubuntu to Debian. Hope that this was not the cause of your troubles :bowtie:

**Comment by izotope115** [comment]
Thanks for the info. Super helpful. 
Now to make things a bit more complicated :)..
My VPS is Debian 9. 
When logging into the "web" console (offered by DO when logged into my account) my prompt is: root@debian-s-2vcpu-4gb-sfo2-01. Here I can see data/dionaea/binaries for example. 

Oddly when logging into the same ip using ssh/ local terminal window (ubuntu prompt) - I dont see the binaries directory.

**Comment by t3chn0m4g3** [comment]
You need to login on tcp/64295 via SSH. On tcp/22 the honeypot Cowrie is active.

**Comment by izotope115** [comment]
Ahhh.. Ok again my bad. Newbie when it comes to some of these commands. 
I never had my command correct. It should be: ssh -p 64295 xxx@xx.xxx.xxx.xxx

Thank you AGAIN. Learning a lot with your help!

**Comment by t3chn0m4g3** [comment]
👍
