### ISSUE TITLE
Maintaining Bistreams Folder

### ISSUE THREAD

**Issue by izotope115** [dtag-dev-sec/tpotce#366]
Hello,
I collect a bunch of large files inside the data/dionaea/bistreams folder so therefore in order to maintain drive space I have set up a cron job that deletes the contents of the bistreams folder on an hourly basis: `@hourly find /data/dionaea/bistreams/* r -maxdepth 0 -exec rm -fr {}$`

If I dont set up an automated process to delete these large files then my VPS will max out of drive space.

My question is: whats the impact of removing these files hourly?

**Comment by t3chn0m4g3** [comment]
Removing does not impact T-Pot's function. However it leaves you without logs in the long run, since not all data is suited to be stored in the Elastic stack.

**Comment by izotope115** [comment]
Awesome thanks. Is there a better solution other than deleting?

**Comment by t3chn0m4g3** [comment]
More storage capacity or offloading (rsync, ssh, filebeats, ...) to a third party.
If you do not need it though deleting is fine I guess.

**Comment by izotope115** [comment]
Ok Ill check it out. Thanks for your great help!!
