### ISSUE TITLE
Exposing Logs

### ISSUE THREAD

**Issue by izotope115** [dtag-dev-sec/tpotce#368]
Hello,
Is it possible to expose for example dionaea.json or any other logs so that I can display log information on a separate website? 

For example: https://68.183.163.242:64297/data/dionaea/log/dionaea.json
Considering making a GET request using asynchronous Javascript.

Thank you for any insight!

**Comment by t3chn0m4g3** [comment]
No, not out of the box and it is not recommended. That's what the ELK stack is implemented.
