### ISSUE TITLE
Glastopf stopped persisting log entries

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/tpotce#37]
I have kept persistence.on file located in data folder for a week with no problem. Today, the glastopf.log deleted all other logs and started from 2016-04-23. Why did this happen?

**Comment by t3chn0m4g3** [comment]
``persistence.on``only ensures that the contents in ``/data`` folders will not be removed upon container restart. It does not prevent the honeypot itself from modifying the logs if it sees fit.

**Comment by firepro20** [comment]
So at random, the glastopf honeypot just decided to clear its log? Better
contact glastopf creator unless you might know a way how to stop this from
happening.
