### ISSUE TITLE
Connection timeout loading Kibana from Firefox (works in Chrome)

### ISSUE THREAD

**Issue by amishrabbit** [dtag-dev-sec/tpotce#370]
When attempting to browse to the Kibana instance from Firefox (Quantum, 66.0.4, Windows x64), the connection times out while attempting to negotiate the TLS handshake and I never see the login dialog. Kibana loads just fine in Chrome, but I don't use Chrome.

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Linux <machine name> 4.19.0-5-amd64 #1 SMP Debian 4.19.37-1 (2019-05-05) x86_64 GNU/Linux

- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nextgen
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VMware ESXi 6.5 VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
N/A
- How long has your installation been running?
Approximately three weeks, 16 hours since last reboot
- Did you install upgrades, packages or use the update script?
used upgrade.sh 16 hours ago
- Did you modify any scripts or configs? If yes, please attach the changes.
N/A (stock)
- Please provide a screenshot of `glances` and `htop`.
![glances](https://user-images.githubusercontent.com/2653726/57804028-fc74a700-7716-11e9-96fc-c9db06cc81de.png)
![htop](https://user-images.githubusercontent.com/2653726/57804039-026a8800-7717-11e9-919e-df6b5f83ef83.png)

- How much free disk space is available (`df -h`)?
Filesystem      Size  Used Avail Use% Mounted on
udev             12G     0   12G   0% /dev
tmpfs           2.4G  230M  2.2G  10% /run
/dev/sda2       307G   19G  273G   7% /
tmpfs            12G     0   12G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            12G     0   12G   0% /sys/fs/cgroup
tmpfs           2.4G     0  2.4G   0% /run/user/1000

- What is the current container status (`dps.sh`)?
/opt/tpot/bin]$ sudo ./dps.sh
./dps.sh: 20: ./dps.sh: function: not found
adbhoney              Up 16 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 16 hours
conpot_guardian_ast   Up 16 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 16 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 16 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 16 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 16 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 16 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 16 hours
elasticsearch         Up 16 hours (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 16 hours
glutton               Up 16 hours
head                  Up 16 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 16 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 16 hours             0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 16 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 16 hours (healthy)
mailoney              Up 16 hours             0.0.0.0:25->25/tcp
medpot                Up 16 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 16 hours
p0f                   Up 16 hours
rdpy                  Up 16 hours             0.0.0.0:3389->3389/tcp
snare                 Up 16 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 16 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 9 hours
tanner                Up 16 hours
tanner_api            Up 16 hours
tanner_phpox          Up 16 hours
tanner_redis          Up 16 hours             6379/tcp
tanner_web            Up 16 hours
./dps.sh: 22: ./dps.sh: Syntax error: "}" unexpected

- What is the status of the T-Pot service (`systemctl status tpot`)?
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-15 03:28:17 UTC; 16h ago
  Process: 879 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 899 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 988 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 991 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 994 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 1015 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 1035 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 1056 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 1082 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 1088 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 1094 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 1100 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 1176 (docker-compose)
    Tasks: 32 (limit: 4915)
   Memory: 234.7M
   CGroup: /system.slice/tpot.service
           └─1176 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

sudo netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          15198      646/sshd
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          14190      630/python3
tcp6       0      0 :::64294                :::*                    LISTEN      0          14461      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          15200      646/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          2041       525/dhclient
udp        0      0 192.168.0.20:123        0.0.0.0:*                           0          16152      645/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          16150      645/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          16146      645/ntpd
udp6       0      0 :::123                  :::*                                0          16143      645/ntpd

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
N/A

**Comment by t3chn0m4g3** [comment]
Works perfectly fine here, cannot reproduce.

![image](https://user-images.githubusercontent.com/4318452/57834313-52e7f100-77bc-11e9-8646-b9298b7bce5a.png)

**Comment by amishrabbit** [comment]
![honeynot](https://user-images.githubusercontent.com/2653726/58033626-09f8ab00-7ae2-11e9-8906-fc3039b98850.png)

Didn't know whether the issue was with a plugin, so I created a new profile for firefox with no add-ons, adblockers, etc., and I still can't get there from here. Tried to reduce the maximum supported TLS version to 1.2 and the server wouldn't negotiate at all, but this is what I see when I try to connect using TLS 1.3.

¯\_(ツ)_/¯

**Comment by t3chn0m4g3** [comment]
I'd guess this is Layer-3 related.

**Comment by t3chn0m4g3** [comment]
Closing this for now.
