### ISSUE TITLE
Not getting any hits in AWS

### ISSUE THREAD

**Issue by bradlux** [dtag-dev-sec/tpotce#374]
Hi -
I was able to get the T-Pot up and running in an EC2 instance running on Debian GNU-Linux 9 -Stretch and opened all TCP ports 0-64000 in the security groups inbound tab. Even after having it up and running for 1 hour and I'm not getting any hits. Suggestions on what to do or any help would be greatly appreciated!

Thanks!

**Comment by t3chn0m4g3** [comment]
Closing this. Please provide basic support info or we cannot help. Thanks for understanding.
