### ISSUE TITLE
Honeypot Beside Large-Surface Service in the DMZ?

### ISSUE THREAD

**Issue by fraber** [dtag-dev-sec/tpotce#375]
Hi!

Great work! And https://sicherheitstacho.eu/ has great colors! :-)

My use-case for T-Pot is apparently somehow different from what T-Pot is designed for: I'm really looking for an "APT horn". I would like it to sit isolated in a DMZ beside some service which I don't fully trust. Then I would like to get Email alerts if somebody tries "lateral movement".

=> Is there a simple way to add email alerts to all of the included services?

Or maybe I'm playing with the wrong toy?

I'm really looking for a small VM that would emulate a Windows 2012 server or similar apparently keeping the corporate crown jewels (RDP, MS-SQL server, a few shares) and would send me a quick mail if there is a nmap scan or somebody attempting to access one of the services.

Thanks a lot!
Frank

**Comment by t3chn0m4g3** [comment]
@fraber Thanks. By adjusting `/opt/tpot/etc/tpot.yml` you can enable / disable services to your liking. See the [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki) for an example.
