### ISSUE TITLE
python2.7/site-packages/twisted/python/log.py" error 

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#377]
Hello getting the following error 

Any idea what this is?

```
docker logs -f rdpy
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
```

**Comment by t3chn0m4g3** [comment]
Context please.

**Comment by iukea1** [comment]
@t3chn0m4g3 I started to notice I was not getting any hits on RDPY.

I went to the terminal and did a 

Docker logs -f rdpy and so those following errors in the event log.

**Comment by t3chn0m4g3** [comment]
Cannot reproduce, works fine here.

**Comment by iukea1** [comment]
@t3chn0m4g3 I am still on the Ubuntu but running the newer docker images.

Would that be the reason I am getting this error now?

I know you guys moved to Debian .

**Comment by t3chn0m4g3** [comment]
RDPY will throw errors, despite the errors it works fine. The problem is, unless I have isolated context it is pointless to open an upstream issue.

**Comment by iukea1** [comment]
@t3chn0m4g3 I understand and respect that. I was just curious if you ever came across this issue.

Looks like some of these guys also had this issue
https://github.com/cowrie/cowrie/issues/1085

**Comment by t3chn0m4g3** [comment]
Will look into it.

**Comment by iukea1** [comment]
@t3chn0m4g3 thank you :)

Again I might be a massive edge case.

I am moving over to Debian Linux today and I will tell you my results.

**Comment by t3chn0m4g3** [comment]
Looked into it and while I could optimize the image I could neither reproduce log errors nor find any references in the code to bcrypt.
Closing this.
