### ISSUE TITLE
Any plugin or third party app aware which can pull the IP addresses automatically?

### ISSUE THREAD

**Issue by Blason** [dtag-dev-sec/tpotce#379]
# Issues
Hi Team,

Is anyone aware of the method or script or app by which I could pull up the malicious or attackers IP addresses automatically and dump into file or on web server? 

Or any feed aggregator or repository where these data can be stored?

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by iukea1** [comment]
I am working on something like this now. It is has to be multiple python scrips that quarry the elk API.

Would love a hand with this if you are up for it

**Comment by Blason** [comment]
I m not a programmer but looking for logstash output plugin commands thus can dump those on web server or in CSV files. The only issue being logstash is dockerized and I am not sure how to dump those IP addresses in local drive instead inside logstash docker

**Comment by t3chn0m4g3** [comment]
I am not sure if this is what you want ... It will however give you the top IPs in descending order.

```
#!/bin/bash
function fuMYTOPIPS {
curl -s -XGET "http://127.0.0.1:64298/_search" -H 'Content-Type: application/json' -d'
{
  "aggs": {
    "ips": {
      "terms": { "field": "src_ip.keyword", "size": 5 }
      }
    }
  },
  "size" : 0
}'
}

fuMYTOPIPS | jq '.aggregations.ips.buckets[].key' | tr -d '"'
```

You can increase the size to a fitting value, however limitations of the [ES search, aggs and query APIs](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search.html) apply.

**Comment by iukea1** [comment]
> I am not sure if this is what you want ... It will however give you the top IPs in descending order.
> 
> ```
> #!/bin/bash
> function fuMYTOPIPS {
> curl -s -XGET "http://127.0.0.1:64298/_search" -H 'Content-Type: application/json' -d'
> {
>   "aggs": {
>     "ips": {
>       "terms": { "field": "src_ip.keyword", "size": 5 }
>       }
>     }
>   },
>   "size" : 0
> }'
> }
> 
> fuMYTOPIPS | jq '.aggregations.ips.buckets[].key' | tr -d '"'
> ```
> 
> You can increase the size to a fitting value, however limitations of the [ES search, aggs and query APIs](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search.html) apply.

Yup size limit is 10,000 per pull

**Comment by t3chn0m4g3** [comment]
You need to use to [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search-request-scroll.html) if you want more.

**Comment by Blason** [comment]
Yep this is what I wanted but I need to filter more since its capturing genuine traffic as well. I need to capture those IPs and need to create the list which will be dumped on web server and it will be consumed then by firewall to block it in real time.

Like its capturing DNS queries sent it to 8.8.8.8 or 8.8.4.4.

Any hints would be really appreciated.

**Comment by t3chn0m4g3** [comment]
You have all the links in this issue to solve this. Happy coding!

**Comment by iukea1** [comment]
Got my scrip done. Pulls all the data I wanted out... I am going to have to re-index all my indexes to give them more shards....so I can pull the data out a bit more faster. Currently at one shard and I need them at 5 shards per index.

**Comment by iukea1** [comment]
> Yep this is what I wanted but I need to filter more since its capturing genuine traffic as well. I need to capture those IPs and need to create the list which will be dumped on web server and it will be consumed then by firewall to block it in real time.
> 
> Like its capturing DNS queries sent it to 8.8.8.8 or 8.8.4.4.
> 
> Any hints would be really appreciated.

hit my brother focus on the _AfterKey when using the scroll api of elasticsearch.

**Comment by Blason** [comment]
> > Yep this is what I wanted but I need to filter more since its capturing genuine traffic as well. I need to capture those IPs and need to create the list which will be dumped on web server and it will be consumed then by firewall to block it in real time.
> > Like its capturing DNS queries sent it to 8.8.8.8 or 8.8.4.4.
> > Any hints would be really appreciated.
> 
> hit my brother focus on the _AfterKey when using the scroll api of elasticsearch.

hmm..example here is greatly appreciated!! I am not pro in ES hence will really appreciate if you can help me with the script?

**Comment by iukea1** [comment]
> > > Yep this is what I wanted but I need to filter more since its capturing genuine traffic as well. I need to capture those IPs and need to create the list which will be dumped on web server and it will be consumed then by firewall to block it in real time.
> > > Like its capturing DNS queries sent it to 8.8.8.8 or 8.8.4.4.
> > > Any hints would be really appreciated.
> > 
> > 
> > hit my brother focus on the _AfterKey when using the scroll api of elasticsearch.
> 
> hmm..example here is greatly appreciated!! I am not pro in ES hence will really appreciate if you can help me with the script?

no one is a pro at ES except @t3chn0m4g3  

I used this to get started.
https://gist.github.com/drorata/146ce50807d16fd4a6aa

I would send you mine but I had to rename a lot of fields and indexes because I am running a custom build of T-Pot because I am a try hard. (it has more types of honeypots and some custom ones I am trying to build for POS systems)

Also, I have Xpack on my Elk server and half my script is dealing with Authentication.

Also, this will save you about 4 days of pain (it did for me) use this URL lib library 
`
pip3 install --upgrade --user urllib3==1.24.3
pip3 install elasticsearch
`

**Comment by iukea1** [comment]
Also yo you can only scroll 10k objects a time in elk and DO NOT MODIFY THIS SETTING IN ELK OR YOU ARE GOING TO HAVE A BAD TIME WITH SWAPPING. 

![image](https://user-images.githubusercontent.com/35882815/59734725-24749000-9218-11e9-8cbf-d669af8fb28a.png)


you use the scroll api so you can scroll to the next page (where it has the next 10k) 

Also, you want to use the "terms" or you going to get a lot of duplicate results. 

Also, remember @t3chn0m4g3  did most of the fields with .keyword (this is a huge time saver and helps speed up searches in elk) 

please mind you I am not part of T-pot just a big fan of there work.

**Comment by Blason** [comment]
> > > > Yep this is what I wanted but I need to filter more since its capturing genuine traffic as well. I need to capture those IPs and need to create the list which will be dumped on web server and it will be consumed then by firewall to block it in real time.
> > > > Like its capturing DNS queries sent it to 8.8.8.8 or 8.8.4.4.
> > > > Any hints would be really appreciated.
> > > 
> > > 
> > > hit my brother focus on the _AfterKey when using the scroll api of elasticsearch.
> > 
> > 
> > hmm..example here is greatly appreciated!! I am not pro in ES hence will really appreciate if you can help me with the script?
> 
> no one is a pro at ES except @t3chn0m4g3
> 
> I used this to get started.
> https://gist.github.com/drorata/146ce50807d16fd4a6aa
> 
> I would send you mine but I had to rename a lot of fields and indexes because I am running a custom build of T-Pot because I am a try hard. (it has more types of honeypots and some custom ones I am trying to build for POS systems)
> 
> Also, I have Xpack on my Elk server and half my script is dealing with Authentication.
> 
> Also, this will save you about 4 days of pain (it did for me) use this URL lib library
> `pip3 install --upgrade --user urllib3==1.24.3`
> `pip3 install elasticsearch`

Hey buddy, 

Would you mind sharing you python script for scrolling? I need to fetch the maximum records using scroll parameter. Wondering if your script can help?
I am currently using opendistro for elasticsearch.

curl --insecure -u admin:admin -s -XGET "https://127.0.0.1:16577/malips-2019.12.07/_search" -H 'Content-Type: application/json' -d'
{
  "aggs": {
    "ips": {
      "terms": { "field": "src_ip.keyword", "size": 10000 }
      }
    },
  "size" : 0
  }'
}

MYTOPIPS | jq '.aggregations.ips.buckets[].key' | tr -d '"'

**Comment by Blason** [comment]
> I am working on something like this now. It is has to be multiple python scrips that quarry the elk API.
> 
> Would love a hand with this if you are up for it

Hey, iukea1 would you mind contacting offline on blason16@gmail.com for your certain other projects?

**Comment by t3chn0m4g3** [comment]
You can now find the sample working against ELK 7.x in `/opt/tpot/bin/mytopips.sh`. Feel free to PR on that 😄
