### ISSUE TITLE
ewsposter fatal error

### ISSUE THREAD

**Issue by eluvatl** [dtag-dev-sec/tpotce#38]
Hello. When I run sudo status.sh, a few of the containers show "ewsposter fatal: exited too quickly (process log may have details)." Should I be concerned? The pots affected are Dionaea, Glastopf and Honeytrap. 

A couple of reboots did not resolve problem.

**Comment by firepro20** [comment]
Did you try changing permissions or setting ownership?

**Comment by eluvatl** [comment]
Can you clarify?

**Comment by firepro20** [comment]
Did you use chmod recently and maybe authorised the wrong user? It happened
to me a while back and some containers started to fail. Best p ractise is
to take timely snapshots if you're using a VM

**Comment by eluvatl** [comment]
No. I have not made any modifications to permissions or users.

**Comment by t3chn0m4g3** [comment]
As @firepro20 pointed out this usually only happens if the config files in ``/data`` folder have beed modified by ``chown`` or ``chmod`` or have been edited.

You can run ``sudo dcres.sh``, if that does not fix it I recommend a reinstallation.

**Comment by eluvatl** [comment]
I will try that, but looking back at the instructions on github, I did make a modification that was recommended:

This will start the SSH daemon on port 64295. It is configured to prevent password login and use pubkey-authentication instead, so make sure you get your key on the system. **Just copy it to /home/tsec/.ssh/authorized_keys and set the appropriate permissions (chmod 600 authorized_keys) as well as the right ownership (chown tsec:tsec authorized_keys).**

**Comment by t3chn0m4g3** [comment]
That is fine, since it is outside the ``/data`` folder.

Good luck 😃
