### ISSUE TITLE
Nginx Logs

### ISSUE THREAD

**Issue by korzq** [dtag-dev-sec/tpotce#380]
I've accidentally entered something important in the username field of the nginx basic_auth popup. 

1, Are usernames of nginx sent to the community backend
2, I've removed the logs with the important info in /data/nginx/log/access.log and error.log, but the username still show up in kibana
3, I want to remove an ip from the block caused by nginx auth fail, i did `sudo iptables -D f2b-nginx-http-auth -s REDACTED -j REJECT`, it worked, but the ban came back after I restart the server.

# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
No, NGINX logs are only kept local.
You have to use fail2ban-client for removing the IP.

**Comment by korzq** [comment]
thanks, how do I remove the NGINX log that have my important info, it still appear in Kibana after I remove the logs where their is the important info in /data/nginx/

**Comment by t3chn0m4g3** [comment]
The easy way is to remove the whole index for the day within ES Head. Anything else just check the ES documentation on how to remove single documents.

**Comment by korzq** [comment]
Thanks! It worked.
