### ISSUE TITLE
Tag cloud not shown

### ISSUE THREAD

**Issue by mahmoodn** [dtag-dev-sec/tpotce#383]
Hi
It seems that tag cloud is not shown in the honeypot pages (19.03). For example, I remember a user/password cloud in Cowrie. But I don't see them now. How can I debug to see what happened?

**Comment by Delta1977** [comment]
Hi, did you this ? 
https://github.com/dtag-dev-sec/tpotce/blob/master/CHANGELOG.md#20190502

**Comment by mahmoodn** [comment]
May I ask how to import the objects from /opt/tpot/etc/objects/kibana-objects.json.zip

**Comment by t3chn0m4g3** [comment]
1. [Unzip](https://www.wikihow.com/Unzip-a-File)
2. [Import](https://support.logz.io/hc/en-us/articles/210207225-How-can-I-export-import-Dashboards-Searches-and-Visualizations-from-my-own-Kibana-)

**Comment by mahmoodn** [comment]
As I unzip the file, I see some folders containing several json files. 

```
[root@civilianhosiery:/opt/tpot/etc/objects]# ls
dashboards  elkbase.tgz  kibana_export.json.zip  kibana-objects.tgz  patterns  searches  visualizations
```
On the other hand, the import window accepts one file per browse.
Should I continue with the visualizations folder?

**Comment by t3chn0m4g3** [comment]
You unzipped the wrong file.

**Comment by mahmoodn** [comment]
I extracted kibana-objects.tgz as it is the closest name to what is suggested in the second post. There is no other related zip file about objects.
Please let me know the right file name. Thanks.

**Comment by t3chn0m4g3** [comment]
If you do not see the `kibana_export.json.zip` you just posted with the `ls` output, then I cannot help you.

**Comment by mahmoodn** [comment]
Does that mean a broken installation?!
Is there any way to download that file from somewhere?

**Comment by t3chn0m4g3** [comment]
No, because you have the file...

![image](https://user-images.githubusercontent.com/4318452/58862861-eb81da80-86b1-11e9-8530-4c65d800a0d9.png)

**Comment by mahmoodn** [comment]
So, extracting that yields 
```
[root@civilianhosiery:/opt/tpot/etc/objects]# unzip kibana_export.json.zip
Archive:  kibana_export.json.zip
  inflating: kibana_export.json
   creating: __MACOSX/
  inflating: __MACOSX/._kibana_export.json
[root@civilianhosiery:/opt/tpot/etc/objects]# ls
elkbase.tgz  kibana_export.json  kibana_export.json.zip  kibana-objects.tgz  __MACOSX
[root@civilianhosiery:/opt/tpot/etc/objects]# ls __MACOSX/
[root@civilianhosiery:/opt/tpot/etc/objects]#
```

I then uploaded kibana_export.json and after some seconds, I got 
```
Import failed

Failed to import 5 of 296 objects.Import failed

NetworkError when attempting to fetch resource. NetworkError when attempting to fetch resource. NetworkError when attempting to fetch resource. NetworkError when attempting to fetch resource. NetworkError when attempting to fetch resource.
```
However, the network is fine and I can access tpot pages.

**Comment by t3chn0m4g3** [comment]
Sorry cannot reproduce, works perfectly fine here.
