### ISSUE TITLE
下载了iso无法安装，系统是Ubuntu18.04

### ISSUE THREAD

**Issue by wuyuangithub** [dtag-dev-sec/tpotce#385]
![QQ截图20190605142547](https://user-images.githubusercontent.com/51149833/58935942-2f074200-87a1-11e9-92b0-61c8045bda31.png)

E: 软件包 netselect-apt 没有可安装候选
Package manager quit with exit code.
Aborting. Debian bionic is not supported.

**Comment by t3chn0m4g3** [comment]
Ubuntu is no longer supported.
