### ISSUE TITLE
T-Pot Cannot start after installation

### ISSUE THREAD

**Issue by wuyuangithub** [dtag-dev-sec/tpotce#386]
【Debian9】
[root@complexresist:/home/netstat]# systemctl start tpot

Job for tpot.service failed because the control process exited with error code.
See "systemctl status tpot.service" and "journalctl -xe" for details.

[root@complexresist:/home/netstat]#journalctl -xe

![123233](https://user-images.githubusercontent.com/51149833/59154757-48173800-8aac-11e9-8556-98d60d38469a.JPG)

How to solve????help me！
what should I do!!!

**Comment by iukea1** [comment]
have you tried Sudo and start the service?

**Comment by wuyuangithub** [comment]
Has been resolved.
Because of the problem of npm

**Comment by hunter-00** [comment]
> 已经解决了。 因为npm的问题
你好，请问怎么解决的
我也遇到了相同的问题

**Comment by jjovin** [comment]
have the same issue
