### ISSUE TITLE
User creation when type=user install

### ISSUE THREAD

**Issue by jovimon** [dtag-dev-sec/tpotce#389]
I believe this line is incorrect:
https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/install.sh#L808

If you install on a Debian VM on VMware hardware using your user guide:
https://github.com/dtag-dev-sec/tpotce#post-install-user

The tsec user never gets created. 

I browsed the code and could only find references to tsec if iso install method used, but never with user install method:
https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/install.sh#L515
https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/install.sh#L801

**Comment by t3chn0m4g3** [comment]
This is intentional, the tsec user will only be created during an ISO install.

**Comment by jovimon** [comment]
In that case, shouldn't this line be a few lines up inside the type=iso if?

https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/install.sh#L808

**Comment by t3chn0m4g3** [comment]
Yes, good catch :smile:
