### ISSUE TITLE
Glastopf sqllite information access

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/tpotce#39]
Is there a way to read or access the information stored in sqlite:///db/glastopf.db?

 I need more information as can be seen in Kibana in glastopf dashboard and not just the IP and dummy page as found in glastopf.log.

Thankyou

**Comment by t3chn0m4g3** [comment]
@firepro20 [Sqlite](https://www.sqlite.org/cli.html)

Please let me kindly remind you to keep topics related to T-Pot, we cannot provide individual support for the honeypots shipping with T-Pot.

Thank you.
