### ISSUE TITLE
Kernel panic on Debian in GCP

### ISSUE THREAD

**Issue by ohuk2** [dtag-dev-sec/tpotce#390]
Hello, thought I'd try to install it on a server in GCP on Debian 9 (3.75GB/128GB) but sadly the system is broken after the install, guess it's the Debian upgrade that caused this? I did:

git clone https://github.com/dtag-dev-sec/tpotce

and "./install.sh --type=user". I chose the first (Full) option. Tried twice with same result.

Has anyone here got it running in GCP? I've got it up in AWS OK.

Thanks!
serialport: Connected to immaginare.us-central1-a.t-pot port 1 (session ID: b922
d011d8e0fcd448a2c4d137569296700e11a2, active connections: 1).
[    1.060545]  panic+0xe7/0x24a
[    1.061328]  mount_block_root+0x2c2/0x2e6
[    1.061977]  ? do_early_param+0x8e/0x8e
[    1.062516]  prepare_namespace+0x130/0x166
[    1.063610]  kernel_init_freeable+0x208/0x218
[    1.064736]  ? rest_init+0xaa/0xaa
[    1.065312]  kernel_init+0xa/0x10d
[    1.066133]  ret_from_fork+0x35/0x40
[    1.067961] Kernel Offset: 0x2e00000 from 0xffffffff81000000 (relocation rang
e: 0xffffffff80000000-0xffffffffbfffffff)
[    1.069904] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs
 on unknown-block(0,0) ]---

**Comment by t3chn0m4g3** [comment]
Cloud Instance will need to support Debian 9.x (Buster in the near future). The instance will then be migrated to Debian Sid (unstable). I can strongly recommend Open Telekom Cloud as it supports this right out of the box.
