### ISSUE TITLE
AWS Build

### ISSUE THREAD

**Issue by mda1125** [dtag-dev-sec/tpotce#391]
This would make a great Wiki entry but...

If I want to put this into AWS EC2... what basic building should I choose?

Then I assume I could run the github pull and such to install....

**Comment by KBDKID** [comment]
@mda1125  What do you mean by "basic building"? Are you asking about instance reqs or where to place your instances or something else?

**Comment by mda1125** [comment]
Instance reqs... I can find a Debian build in the Community Section and Ubuntu 18.x in the default AWS builds.  

Created the ISO on my own VirtualBox instance and it works at home.  Put it in the DMZ and wow! 

Figured I'd maybe put this on AWS as well but it looks like I'll need a Debian community build (Stretch) and at least a Medium instance if I want this to work.

**Comment by KBDKID** [comment]
@mda1125  Large or xl t2 instance is what i would recommend. A medium just does not have the ram you want and it will cause swapping. Stretch on aws also is going to cost licensing so please keep that in mind. If you can host it locally, i would strongly recommend that as cost can run rampant quickly.

**Comment by mda1125** [comment]
@KBDKID You're right.. it's working fine on my VM.  I'm getting interesting stats.  My installs failed a bunch of times and that was ultimately because I didn't start off with 8GB of RAM.  When I did that and just started with a 125GB drive.. it works beautifully.

I'm wondering if I can ramp this up with some config options to make it look even more enticing?

I've got the community stats enabled.. they are by default and I've not touched those settings.

**Comment by KBDKID** [comment]
@mda1125 Realistically to make it look more enticing or more real you are going to have to actually configure the virtual enviroments of the honeypots inside of tpotce. one that comes to mind is https://github.com/d1vious/splunk_cowrie. Its much older script to make cowrie look more realisting and i can bet if you try to run it over tpotce it will more than likely break. But instead dig into the configs and see how to change functionality to the honeypots themselves. Then i would strongly recommend checking out the wikis of the honeypots that interest you and figure how they are controlled and customize them.

However at the end of the day there are 2 things to remember. 1. Most hackers are scripts now a days. and finally 2. A honeypot isnt meant to really catch the hacker. Its more so to annoy them enough that they go away and stop poking at you

**Comment by t3chn0m4g3** [comment]
Cloud Instance will need to support Debian 9.x (Buster in the near future). The instance will then be migrated to Debian Sid (unstable). I can strongly recommend Open Telekom Cloud as it supports this right out of the box.
