### ISSUE TITLE
Continuous restart of containers

### ISSUE THREAD

**Issue by nnasdlc** [dtag-dev-sec/tpotce#393]
Continuous restart of containers.
I look at the container logs。
I don't think the data folder has permissions.
I use Debian 9.9.
selinux is disable

[root@latincold:~]# docker logs rdpy
/bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
/bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
/bin/sh: can't create /var/log/rdpy/rdpy.log: Permission denied
root@latincold:~]# docker logs conpot_ipmi
WARNING:scapy.runtime:No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/usr/bin/conpot", line 461, in <module>
    main()
  File "/usr/bin/conpot", line 185, in main
    setup_logging(args.logfile, args.verbose)
  File "/usr/bin/conpot", line 88, in setup_logging
    file_log = logging.FileHandler(log_file)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/conpot/conpot_ipmi.log'
WARNING:scapy.runtime:No route found for IPv6 destination :: (no default route?)

**Comment by iukea1** [comment]
do a chmod 760 on /data/ see if that works


`chmod 760 -R /data/`

**Comment by iukea1** [comment]
saying that because of 

> "PermissionError: [Errno 13] Permission denied"

**Comment by iukea1** [comment]
after you do that 

reboot your VM

**Comment by iukea1** [comment]
if this keeps on having issues you may want to rebuild your VM from the ISO (you will lose data)

**Comment by nnasdlc** [comment]
thinks，Thank you, but it's not settled.
rebuild VM NOW~
