### ISSUE TITLE
Intermittent Connectivity Issues/Secure SSL Connection Failed on https://honeypotip:64297

### ISSUE THREAD

**Issue by Digibyte707** [dtag-dev-sec/tpotce#395]
Hello wonderful TPOT Honeypot devs. I am currently running TPOT 19.03 on a fresh unmodified install in KVM (VM) on my Centos 7 server. I can access my honeypot via https://honeypotip:64294 but I cannot view the Web ELK Dashboard on https://honeypotip:64297. When attempting to access the web dashboard over socket :64297 I either receive a "problem loading page" or "secure connection failed - specifically SSL_ERROR_PROTOCOL_VERSION_ALERT" in Firefox. I have the host/guest os operating over NAT connection mode in virt-manager/kvm for initial testing. The network interface on the host os is currently connected to unfiltered internet. 
As a last note, I have attempted to access the ELK dashboard over port :64297 in Google Chrome version 75 on the Centos 7 host. I receive an initial certificate warning, click 'advanced', and proceed to the site... but the "site can't be reached" error is later displayed. Sometimes the elk dashboard appears, but I can only see the tabs at the very top and receive a HTTP 502 error. Please assist and provide useful insight :) thank you very much!

Basic support information
What T-Pot version are you currently using? **19.03**
Are you running on a Intel NUC or a VM? **VM**
How long has your installation been running? **24 hours (this version)**
Did you install any upgrades or packages? **No**
Did you modify any scripts? **No**
Have you turned persistence on/off? **No**
How much RAM is available (login via ssh and run htop)? **Using 600M/9.55GB**
How much stress are the CPUs under (login via ssh and run htop)? Load average **20.00 17.72 17.73** 
How much swap space is being used (login via ssh and run htop)? **0K/7.63G**
How much free disk space is available (login via ssh and run sudo df -h)? **225GB/244GB**
What is the current container status (login via ssh and run sudo dps.sh)? **" need to run as root... " what is the root pass anyways?**

**Comment by iukea1** [comment]
I would try taking it out of that NAT for a little bit to see if you can get to the Kibana Dashboards. 

If you can it is something going on with your host NATing that is getting a little strange.

**Comment by t3chn0m4g3** [comment]
Based on the sparse information I can only guess that something went wrong during the install. Using only "600M" if RAM points to almost no container is running.

Please provide the basic support info asked on opening an issue.
