### ISSUE TITLE
How to log in?

### ISSUE THREAD

**Issue by kont45** [dtag-dev-sec/tpotce#396]
Guys, how can I log in to the console on port IP: 64294? My credentials created during instalation are not correct. 

Second issue: why web panel on IP: 64297 is not available?

**Comment by t3chn0m4g3** [comment]
@kont45: Please see the [README](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md#first-run) and use the `tsec` user.

Please provide basic support info for help on your second issue.

**Comment by kont45** [comment]
Tsec user with my password is not correct. I think that my issue is realted with #389

**Comment by t3chn0m4g3** [comment]
Could only guess based on your sparse info provided :bowtie:

**Comment by t3chn0m4g3** [comment]
FWIW - If you are using the post install method, there will be no tsec user. You need to use the user you installed Debian with.

**Comment by kont45** [comment]
I used following steps from WIKI https://github.com/dtag-dev-sec/tpotce/wiki/Add-new-users-to-the-T-Pot-WebUI Still no positive result. Cant login.

**Comment by t3chn0m4g3** [comment]
Cockpit is not the T-Pot WebUI.

**Comment by t3chn0m4g3** [comment]
Closing this until basic support info provided.
