### ISSUE TITLE
Sensor Installation installs p0f and suricata

### ISSUE THREAD

**Issue by MarcinNaw** [dtag-dev-sec/tpotce#399]
It seems like the Docs are incomplete or the installation does choose too many packets.

However, in my case p0f and suricata have been installed during a "sensor" installation.

Can anyone reproduce?

**Comment by t3chn0m4g3** [comment]
This is by design.

**Comment by t3chn0m4g3** [comment]
If you do not need p0f and Suricata you can always remove them from docker-compose config in `/opt/tpot/etc/tpot.yml`.

**Comment by MarcinNaw** [comment]
Thank you, I just wondered if I messed something up during the installation.
