### ISSUE TITLE
TPOT is an HIDS or NIDS?

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/tpotce#40]
I was wondering what the TPOT system should be classified under if installed in a VM environment on a host with a bridged connection. Is it still a host intrusion detection system or a network intrusion detection system since it now can be accessed through the Internet? Or is it an enhanced HIDS with internet access?

I am confused can you please clarify?

**Comment by schmalle** [comment]
Hi,

Suricata defines itself as "Suricata is a high performance Network IDS, IPS
and Network Security Monitoring engine".
The rest of TPot are simulated targets, aka honeypots. So it is a
honeyplatform with included NIDS:

Best wishes

Markus

**Comment by firepro20** [comment]
Ok thanks Markus

**Comment by firepro20** [comment]
So for clarity, it would be correct to say that the whole system is a network intrusion detection system server, given that it is built on Ubuntu LTS server and using Suricata?

**Comment by dev-t-sec** [comment]
NO, it is an honeypot, only that the attacker traffic will be also analysed by an iDS.

On 07 May 2016, at 15:35, firepro20 <notifications@github.com<mailto:notifications@github.com>> wrote:


So for clarity, it would be correct to say that the whole system is a network intrusion detection system server, given that it is built on Ubuntu LTS server and using Suricata?

-

**Comment by firepro20** [comment]
Analysed by Suricata, a network IDS and the Ubuntu server, TPOT, is in a VM with a bridged connection having Internet access through the bridged connection from my host. So the whole setup becomes what exactly? Maybe a host intrusion detection system then since its on a host or network IDS since it is getting network access through bridging?
