### ISSUE TITLE
kibana mapping Mapping conflict

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#400]
![image](https://user-images.githubusercontent.com/35882815/60315938-4368d580-992e-11e9-8044-140f1a578a17.png)

Have you guys ever ran across this problem before?

**Comment by iukea1** [comment]
Fixed it.... God bless backups

**Comment by iukea1** [comment]
Never mind it is broken again .


Wtf happened !

**Comment by t3chn0m4g3** [comment]
You have way too many fields (for a T-Pot setup) and probably one of the indices got fed with a conflicting type. You either have to reindex, eliminate the faulty indices by deleting them or reinstall.
