### ISSUE TITLE
Web interface goes down and requires a restart regularly. 

### ISSUE THREAD

**Issue by fouroctets** [dtag-dev-sec/tpotce#401]
I have been running multiple instances of Tpot and I am having the same problem with them all. After installation I am able to access the web interfaces and log in fine. After about an hour idle on the dashboards I am not able to do anything in the web interface without restarting Tpot. It does this for all 3 installs. I can't even SSH back into the box when this happens. I have to restart the entire instance. 
- What version of the OS are you currently using
4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Cloud AWS
- Did you have any problems during the install? 
No issues
- Did you install upgrades, packages or use the update script?
Fresh install
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
![Screenshot at 2019-06-28 17-23-44](https://user-images.githubusercontent.com/6326941/60377212-9b084f00-99c9-11e9-970b-353175b748d9.png)
 
![Screenshot at 2019-06-28 17-22-52](https://user-images.githubusercontent.com/6326941/60377216-a3f92080-99c9-11e9-9f2c-db65251af583.png)

- How much free disk space is available
/dev/xvda1      158G  7.1G  144G   5% /

- What is the current container status (`dps.sh`)?
![Screenshot at 2019-06-28 17-43-51](https://user-images.githubusercontent.com/6326941/60377490-8b3e3a00-99cc-11e9-80c2-018b0fcf9c16.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![Screenshot at 2019-06-28 17-28-59](https://user-images.githubusercontent.com/6326941/60377285-3ef1fa80-99ca-11e9-8f02-db73c399a220.png)

**Comment by fouroctets** [comment]
Update: I have tried on two other providers and am getting the same results. 8GB memory and 150+ ssd and the web interface and box comes to a crawl after I browse the web interface and leave the web interface alone for 30 minutes which requires a host restart to get back in.

**Comment by t3chn0m4g3** [comment]
Everything looks perfectly fine according to your screenshots. Did you install manually or from ISO?
Did you take the screenshots on a console after your machines run inaccessible? Will be needing the status after your machine is not accessible from the outside. For this we also need logs:
```
docker logs nginx
docker logs kibana
docker logs elasticsearch
docker logs logstash
cat /var/log/messages
cat /var/log/user.log
cat /var/log/auth.log
cat /var/log/syslog
cat /var/log/fail2ban.log
cat /install.err
cat /install.log
```
What do you mean by "WebInterface", access to Cockpit or Kibana?

However, the most likely scenario, since this is the first report we are receiving on such a behavior, is that probably `fail2ban` locked you out.

Review the jail stats:
```
sudo su -
fail2ban-client status nginx-http-auth
fail2ban-client status pam-generic
fail2ban-client status sshd
```

If it shows banned IPs just `fail2ban-client unban <your_ip>`

**Comment by t3chn0m4g3** [comment]
Whipped up 2 machines (T-Pot Standard) to eliminate side effects of latest packages, running Kibana dashboards on 5 second reload intervals and tailing some logs via SSH.

Even after 1 hour, everything works perfectly fine as expected.

I have also 8 machines running on different platforms which all show no signs of a similar behavior.

Looking forward to logs.

**Comment by fouroctets** [comment]
Thank you for the reply. I have made a mistake. Digital ocean is working fine. I appear to have somehow triggered  fail2ban on myself after already being logged in on two of the hosts. As for the "web interface " I meant anything at :64297 or :64294 being  not accessible and I couldn't ssh to :64295 when the random slow down happens. I was wrong about the other hosters, this issues seems to be isolated to AWS and has nothing to do with TPOT. I apologize for wasting your time. The error is somewhere between the computer and the chair on my end.

**Comment by t3chn0m4g3** [comment]
@fouroctets Appreciate your feedback and glad to see it working for you now.
