### ISSUE TITLE
Tpot view only configuration - Question

### ISSUE THREAD

**Issue by JamesBradyBear** [dtag-dev-sec/tpotce#402]
Hi,
How can I just start logstash and Kibana dashboard only? I don't want to run the honeypots but just to view all the collected data. 

Is that possible? (So that I don't require so high spec PC, rather I can deploy it on any 4GB RAM PC as well)

Thanks.

**Comment by MarcinNaw** [comment]
Tpot only shows data that your honeypot sensor has collected. If you don't run any honeypots, Logstash + Kibana will not have any data to process.

**Comment by JamesBradyBear** [comment]
I have already collected data, I don't want to collect further data but just to view and analyze the data that I have already collected without running any honeypot but I need just Kibana and logstash.

**Comment by t3chn0m4g3** [comment]
Stop T-Pot and remove all unwanted services from tpot.yml and reboot. This has been discussed quite often in the issues just search the previous issues.
