### ISSUE TITLE
Question: Aborting. Debian buster is not supported

### ISSUE THREAD

**Issue by SuperMike96** [dtag-dev-sec/tpotce#407]
I have a silly question that the detail is shown in below. 

''Aborting. Debian buster is not supported.''

Why could it cause? As I known, Debian buster should be same as sid, isn't it?

My OS is Debian 9.8.
[root@functionalpest:~/tpotce/iso/installer]# uname -a
Linux functionalpest 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

[root@functionalpest:~/tpotce/iso/installer]# ./install.sh --type=user

### Installing apt-fast
--2019-07-03 15:56:11--  https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21346 (21K) [text/plain]
Saving to: ‘/usr/local/sbin/apt-fast’

/usr/local/sbin/apt-fast    100%[=========================================>]  20.85K  77.6KB/s    in 0.3s    

2019-07-03 15:56:13 (77.6 KB/s) - ‘/usr/local/sbin/apt-fast’ saved [21346/21346]

### Checking for installer dependencies: [ OK ]
Aborting. Debian buster is not supported.

**Comment by Delta1977** [comment]
Actually the installer check hardcoded  for the supported versions :
myLSB_STABLE_SUPPORTED="stretch"
myLSB_TESTING_SUPPORTED="sid"

**Comment by t3chn0m4g3** [comment]
@SuperMike96 whats your release according to lsb_release?
```
lsb_release -i
lsb_release -c
```
If it is actually buster then it seems you already upgraded.

**Comment by SuperMike96** [comment]
> @SuperMike96 whats your release according to lsb_release?
> 
> ```
> lsb_release -i
> lsb_release -c
> ```
> 
> If it is actually buster then it seems you already upgraded.

[root@functionalpest:~/tpotce/iso/installer]# lsb_release -i
Distributor ID: Debian
[root@functionalpest:~/tpotce/iso/installer]# lsb_release -c
Codename:       buster

It seems Debian has been upgrades, I have no idea how to solve it.

**Comment by SuperMike96** [comment]
Those are all commonds I had use since I created ECS (Elastic Compute Service) Debian9.8 on Aliyun Cloud.

git clone https://github.com/dtag-dev-sec/tpotce
cd tpotce
sudo ./makeiso.sh
cd
cd tpotce/iso/installer/
./install.sh --type=user

cd tpotce/iso/installer/
cp tpot.conf.dist tpot.conf
./install.sh --type=auto --conf=tpot.conf

**Comment by TheHADILP** [comment]
Maybe you can try it with a freshly deployed ECS and only these commands:

git clone https://github.com/dtag-dev-sec/tpotce
cd tpotce/iso/installer/
cp tpot.conf.dist tpot.conf
./install.sh --type=auto --conf=tpot.conf

**Comment by SuperMike96** [comment]
> Maybe you can try it with a freshly deployed ECS and only these commands:
> 
> git clone https://github.com/dtag-dev-sec/tpotce
> cd tpotce/iso/installer/
> cp tpot.conf.dist tpot.conf
> ./install.sh --type=auto --conf=tpot.conf

Cool, I reinstall the Debian again and use these commands. It shows successful installing T-Pot. 

However, when I reboot the ECS and connect by ssh, 22 port(original connected port) needs a password which is not ECS password. So I'm confused I haven't set any password and username on the T-Pot system yet.

**Comment by TheHADILP** [comment]
https://github.com/dtag-dev-sec/tpotce#ssh
Ports change after reboot

**Comment by SuperMike96** [comment]
Thanks, but still in the Debian system. Does it suppose to be T-Pot system? How can I get into T-Pot system and setting my username and password. I read thought the document which is not mention about it.

[root@sharpbakeware:~]# ls
tpotce

**Comment by SuperMike96** [comment]
Surprisedly, I just can connect https://<my.ip>:64294, but the serious problem is I never set up any username and password. It seems to be last question.

**Comment by TheHADILP** [comment]
For Kibana (64297): If you didn't change the default, have a look here: https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/tpot.conf.dist (config file used during post install)

For AdminUI (64294) you first need to set a password via the ssh console.

For SSH (64295) You are probably using Public/Private keys for logging in I guess?

**Comment by SuperMike96** [comment]
These are two problems, how can I get into T-Pot system? How can I set up my username and password to log in AdminUI?

Sorry, maybe I didn't explain my situation clearly. 

Because of your helps, I can finally log into my ECS by SSH(64295) and use the original ECS password. But it still shows Debian system, I'm unsure how to get into T-Pot system. 

The interesting thing is even I can't get into T-Pot system, I can open the AdminUI(64294) website, but I didn't set up any usernames and passwords.

**Comment by TheHADILP** [comment]
I am not sure what you mean by "T-Pot System". Can you explain?

If you mean the Web-UI / Kibana therefore you can set your user/password during installation with the config file https://github.com/dtag-dev-sec/tpotce/blob/master/iso/installer/tpot.conf.dist

After the installation you can do this: https://github.com/dtag-dev-sec/tpotce/wiki/Add-new-users-to-the-T-Pot-WebUI

For the Admin-UI you use the user and password of your debian OS.

**Comment by SuperMike96** [comment]
1. I thought "T-Pot System" should look like the figure, but now I understood that the interface probably would be different when T-Pot installs on my own system. 
![image](https://user-images.githubusercontent.com/22272878/60692092-96cabd00-9f06-11e9-819e-c23ba8c08dc5.png)

2. To be clear, you recommended me set my user/password in tpot.conf.dist. One curious question is why I couldn't log in Web-UI by the default user/pw which is shown in below.

# tpot configuration file
# myCONF_TPOT_FLAVOR=[STANDARD, SENSOR, INDUSTRIAL, COLLECTOR, NEXTGEN]
myCONF_TPOT_FLAVOR='STANDARD'
myCONF_WEB_USER='webuser' ---------- here
myCONF_WEB_PW='w3b$ecret' -----------here

3. Execute the those commands and everything will be settled. Isn't it?

sudo su -
systemctl stop tpot
htpasswd /data/nginx/conf/nginxpasswd <username>
> New password:
> Re-type new password:
> Adding password for user foobar
systemctl start tpot

**Comment by TheHADILP** [comment]
I mean you can try setting your password that way and report back.
But if you couldn't login before with the default user/password, maybe your installation did not succeed after all.

**Comment by SuperMike96** [comment]
> I mean you can try setting your password that way and report back.
> But if you couldn't login before with the default user/password, maybe your installation did not succeed after all.

I think you're right that the installation maybe is not successful. Since I modified the tpot.conf.dist and these commands, the WebUI still not allows me to access.

I have no idea which was wrong in my installation.

**Comment by SuperMike96** [comment]
I deploied a new Debian9.8 server. Typing those commands
 
git clone https://github.com/dtag-dev-sec/tpotce
cd tpotce/iso/installer/
cp tpot.conf.dist tpot.conf
./install.sh --type=auto --conf=tpot.conf

During the installation was processing, there was not setting up username/password, fine.

After the T-Pot had been installed, I rebooted the server. However, I can't log into WebUI even if I modified the dist files and created the new users. One thing, I can log into server and sometimes it had been attacked, because cowrie honeypot recorded it in log. CPU got up to 99% after the T-Pot installed.

**Comment by TheHADILP** [comment]
So, just to be sure: You have to modify the tpot.conf file with your username/password and after that you can run the install command. Changing the tpot.conf afterwards doesn't have any effect.
Also: tpot.conf is solely responsible for the Kibana/Web-UI Login.

For the Admin-UI the Login is your Debian System OS user and you probably have to set a password for that user via a ssh terminal login with passwd.

**Comment by DaniyalYounis** [comment]
> 
> 
> So, just to be sure: You have to modify the tpot.conf file with your username/password and after that you can run the install command. Changing the tpot.conf afterwards doesn't have any effect. Also: tpot.conf is solely responsible for the Kibana/Web-UI Login.
> 
> For the Admin-UI the Login is your Debian System OS user and you probably have to set a password for that user via a ssh terminal login with passwd.

Hi, am using Ubuntu and everything is OK installed everything tpot as well.
./install.sh --type=auto --conf=tpot.conf
after this command system again shows 
aborting. debian focal is not supported.

WOuld you please help this stage why again same error while installing tpot?

**Comment by sayaaad** [comment]
> anyone solve this problem help me ?
