### ISSUE TITLE
Kibana Server is not ready yet?

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#410]
M,

For some reason, our instance is now saying "Kibana Server is not ready yet"?

![image](https://user-images.githubusercontent.com/5147133/60884983-b4df4700-a291-11e9-813e-b04948616a9b.png)

I've had a look via dps.sh and it seems like the kibana service keeps restarting every 90 seconds (so I don't think it's starting properly at all...

![image](https://user-images.githubusercontent.com/5147133/60885013-c9234400-a291-11e9-8068-a5f8dbccecae.png)

I'm just done an update thinking that might fix the issue but to no avail. A reboot also is to no avail.

For the life of me I can't find the kibana.log file; nothing inside syslog or messages with any clues. 

Where can I look to see what's going on?

Cheers,
R

**Comment by t3chn0m4g3** [comment]
Try `docker logs kibana --follow` for logs.

**Comment by UncleRaymondo** [comment]
Wow - talk about a massive flood in logs... Kibana seems to be having multiple cardiac arrests!

![image](https://user-images.githubusercontent.com/5147133/60939863-ae49e180-a31c-11e9-99d7-2a092583f9d3.png)

![image](https://user-images.githubusercontent.com/5147133/60939873-ba35a380-a31c-11e9-9cbf-165ae0063115.png)

![image](https://user-images.githubusercontent.com/5147133/60939951-18fb1d00-a31d-11e9-8e1b-6f55f8ef7b7e.png)

![image](https://user-images.githubusercontent.com/5147133/60939973-33cd9180-a31d-11e9-94ea-d562bdb3c289.png)

![image](https://user-images.githubusercontent.com/5147133/60939986-40ea8080-a31d-11e9-9039-d2688b1c28e7.png)


Seems to be repeating itself with the same content...

Any idea what's going on? There's been no changes on this end...

Cheers,
R

**Comment by t3chn0m4g3** [comment]
From the logs the Kibana Index is either corrupt or deleted.
Open ES Head, identify the Kibana Index and delete it. Reboot and download ZIP file from the etc/objects folder in the repo. Extract its contents and load the objects into Kibana.

**Comment by rokkopina** [comment]
I experienced a similar problem after upgrading Kibana from version 7.1.1 to 7.2. Recreating Kibana Index and importing objects, as @t3chn0m4g3 suggested, should help solve the issue.

**Comment by UncleRaymondo** [comment]
Looks like it's chewed through the 200GB there was and that's why it's all shit itself...

![image](https://user-images.githubusercontent.com/5147133/61019545-ea914680-a3dd-11e9-883b-4a2069f193cb.png)

![image](https://user-images.githubusercontent.com/5147133/61019585-0d235f80-a3de-11e9-92c5-b3b3a0518844.png)


I wonder if it's going to be easier just to drop and rebuild...

**Comment by iukea1** [comment]
@rokkopina would it be possible for you to share your docker image that you built for 7.2?

Been having issues upgrading mine to it.

**Comment by rokkopina** [comment]
@iukea1 I'm using a central Elasticsearch and Kibana installation, directly inside a VM (/wo Docker), where I forward all events from my T-Pot sensor instances (with added Logstash service in sensor.yml) to, so I'm not sure if that would be much help :)

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo There is not much left I could recommend. Ok to close?
