### ISSUE TITLE
Can't get T-Pot running, all services DOWN after installation

### ISSUE THREAD

**Issue by jonas-osw** [dtag-dev-sec/tpotce#411]
## ⚠️ Basic support information (commands are expected to run as `root`)

- `lsb_release -a`
`No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster` 
- `uname -a`
`Linux debian-stretch 4.14.127+ #1 SMP PREEMPT Wed Jun 26 06:13:43 UTC 2019 armv7l GNU/Linux`
- T-Pot version 19.03
- Standard edition
- Running on ODROID-XU4Q Hardware (ARMv7 / armhf)
- [install.log](https://github.com/dtag-dev-sec/tpotce/files/3373020/install.log) 
[install.err](https://github.com/dtag-dev-sec/tpotce/files/3373026/install.err.log)
- htop: ![htop](https://user-images.githubusercontent.com/52705415/60889708-ef2cf200-a259-11e9-80df-cc25d460b1bb.png)
- 24G free space 
- dps.sh: ![dps.sh](https://user-images.githubusercontent.com/52705415/60889872-53e84c80-a25a-11e9-8094-7b1d916afc27.png)

- `systemctl status tpot`
`● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-07-09 12:29:21 UTC; 3s ago
  Process: 3128 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 3147 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 3192 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS
)
  Process: 3193 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 3194 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 3220 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 3246 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 3272 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited
, status=1/FAILURE)
  Process: 3301 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2
}' | tr -d [:punct:]) rx off tx off (code=exited, status=127)
  Process: 3307 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr
 -d [:punct:]) gso off gro off (code=exited, status=127)
  Process: 3313 ExecStopPost=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset (code=exited, status=0/SUCCESS)
`
- `[root@debian-stretch:~]# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          21667      392/sshd       
tcp6       0      0 :::64295                :::*                    LISTEN      0          21669      392/sshd       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          128253     23693/dhclient `
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

## Issue 
- I can't get T-Pot running. I already tried reinstalling a few times. The installation never fails, but all services are DOWN afterwards. 
- I also can't get them up with ``systemctl start tpot`, because it fails
- I also already tried updating T-Pot with update.sh
- `docker images` show all images correctly
- `docker ps -a` shows nothing but the column headings
- I'm trying to get T-Pot running for more than 2 days now, and I don't know what to do next
- thanks for helping

**Comment by t3chn0m4g3** [comment]
ARM Plattform is not supported, only x86_64.

**Comment by jonas-osw** [comment]
Thank you for your fast answer. Too bad ARM isn't supported. I think you should write add to your System Requirements that a x86_64 CPU is needed.

Do you know a good single board computer to run T-Pot?

**Comment by t3chn0m4g3** [comment]
Info for x64 is in the Readme Architecture Diagram.
Intel NUC series works great.

**Comment by sergiosanzferrero** [comment]
Same problem with x86_64.

- lsb_release -a
No LSB modules are available. Distributor ID: Debian Description: Debian GNU/Linux 10 (buster) Release: 10 Codename: buster

- uname -a

Linux evidentjoin 4.19.0-13-amd64 #1 SMPD Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by stevegiovanni** [comment]
I am having the same issue x86.  I am getting the message No NFQ related honeypot detected and the service continually crashes.
