### ISSUE TITLE
Daily man-db regeneration

### ISSUE THREAD

**Issue by yizhimanpadewoniu** [dtag-dev-sec/tpotce#416]
I install tpot use tpot.iso in the virtualbox，but it prompt "Daily man-db regeneration" for a long time，and whether some mistakes were happened?

![image](https://user-images.githubusercontent.com/22395846/61421094-15c4ea00-a938-11e9-9ec0-57caeb107ede.png)

**Comment by t3chn0m4g3** [comment]
Cannot reproduce. Did you setup using the minimum hardware requirements?

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
