### ISSUE TITLE
Missing specific types of Cowrie logs

### ISSUE THREAD

**Issue by tsarpaul** [dtag-dev-sec/tpotce#417]
Hi,
TPot seems to not include some types of events from Cowrie in Kibana.
Specifically what I'm looking for is the "cowrie.log.closed" eventid as it appears in cowrie.json: 
![image](https://user-images.githubusercontent.com/21146452/61453071-e62cd680-a965-11e9-8631-48a12b5cd0a0.png)

I do get other events though:
![image](https://user-images.githubusercontent.com/21146452/61453196-3015bc80-a966-11e9-9d2a-b64b8a1ec132.png)

Is there any configuration, or hint of where can I reconfigure this filter?

Thanks

**Comment by iukea1** [comment]
@tsarpaul strange I see Cowire connection closed logs.when I get home I can send you the field name that is under.

**Comment by tsarpaul** [comment]
Do notice that this is cowrie.log.closed
Not cowrie.session.closed

**Comment by iukea1** [comment]
Oh thanks for the correction. I will see if i have that in my logs

**Comment by tsarpaul** [comment]
Reboot and it worked <.<
I'll reopen if I am able to reproduce
