### ISSUE TITLE
Issues with ports

### ISSUE THREAD

**Issue by Epicism** [dtag-dev-sec/tpotce#418]
Hello,

I'm having trouble identifying what ports each honeypot uses. For example, in the new diagram, both Dionaea and Heralding use port 21, both Heralding and Snare use port 80, etc. Also, when I run the command `docker port ciscoasa` I get no output. When I run the command `docker port ciscoasa 8443/tcp` I get `Error: No public port '8443/tcp' published for ciscoasa`. 

Thank you.

**Comment by t3chn0m4g3** [comment]
The diagram only shows the total of possible ports. Some honeypots (by design) have to run on the network stack of the host and thus do not display their port usages.
Check `/opt/tpot/etc/tpot.yml` for port details.
