### ISSUE TITLE
Allow easy pluging of non-dtagdevsec honeypot containers

### ISSUE THREAD

**Issue by cym13** [dtag-dev-sec/tpotce#42]
As it stands T-Pot is a nicely integrated solution but adding bricks to it is cumbersome and requires either changing most installation scripts or abandonning this nice integration to deploy other tools aside from T-Pot.

It is mostly a matter of hardcoded names. While I think making it work with ews may be troublesome as it would on the information sharing side it would still be nice to have a plugin system to add containers of other origins.

This would also IMHO make it easier to deploy as more specific honeypots have more value in enterprises.

**Comment by t3chn0m4g3** [comment]
Thank you. As a community project pull requests are always welcome on the current [16.10 dev branch](https://github.com/dtag-dev-sec/tpotce/tree/16.10).

**Comment by t3chn0m4g3** [comment]
Did not receive any pull requests and dev branch is now closed for features.
