### ISSUE TITLE
T-POT installation failed on azure.

### ISSUE THREAD

**Issue by alancdias7** [dtag-dev-sec/tpotce#421]
I am trying to deploy T-POT 19 on Debian 9 hosted on Azure.

To do this I created a Debian 9 server and performed the steps described in the Post-Install User.

git clone https://github.com/dtag-dev-sec/tpotce
cd tpotce/iso/installer/
./install.sh --type=user

The installation is successful and during automatic restart the server fails the file system.

Could someone help me with this implementation and / or guide me on some other way to install?

![T-POT](https://user-images.githubusercontent.com/53276043/61823730-b896d000-ae32-11e9-8938-96de1ad77c6e.png)

**Comment by barrydekong** [comment]
I have same issue after update T-Pot! I reinstalled T-pot still couldn't boot up after installation.

**Comment by iukea1** [comment]
I mean Azure kinda sucks :D

**Comment by barrydekong** [comment]
Yes, I installed T-Pot on Azure! I have tried several time delete VM and installed but still couldn't reboot yesterday until I read the posted of issue!

**Comment by sasukeuni** [comment]
i think is something related to the lastest unstable version of debian, not something of t-pot

**Comment by t3chn0m4g3** [comment]
Maybe related to #406.
