### ISSUE TITLE
Installer skips over gateway IP on manual network config

### ISSUE THREAD

**Issue by alphaDev23** [dtag-dev-sec/tpotce#424]
When installed from the latest downloaded iso, and upon failure of the automatic config via DHCP, the manual setup correctly requests the IP and the subnet mask, but then just assumes the gateway IP is at *.1, which it is not.

**Comment by t3chn0m4g3** [comment]
The presence of DHCP is a requirement for setting up and running T-Pot. IP config is solely based on Debian, nothing we can do about it.
