### ISSUE TITLE
ISO install fails

### ISSUE THREAD

**Issue by alphaDev23** [dtag-dev-sec/tpotce#426]
I have attempted to install the pre-built iso on both Virtualbox and QEMU/KVM both to no avail.  The following does not happen: "The system will reboot and please maintain the active internet connection. The T-Pot installer will start and ask you for an installation type, password for the tsec user and credentials for a web user."

Is there any chance that either a raw or qcow2 image could be made available so that the install process is not needed?  These common image formats could easily be uploaded into Openstack, for example, without have to install from iso, which is failing anyway, then converting to the appropriate image type, and then uploaded to Openstack.

**Comment by t3chn0m4g3** [comment]
Just did a fresh install on VirtualBox, VMWare ESXi and KVM. All installations went fine. Please provide `/install.log` and `install.err`.

**Comment by MarcinNaw** [comment]
Can confirm, works also for me on VMWare and KVM. 

Remember that the VMs need Internet-connectivity during installation/ setup.
