### ISSUE TITLE
E: You don't have enough free space in /var/cache/apt/archives/ When Trying to Install open-vm-tools

### ISSUE THREAD

**Issue by samuelkneppel** [dtag-dev-sec/tpotce#428]
Hi all,

I have installed T-Pot 19.03 using the ISO you provide and it installed with no issues that I saw.

Everything I have tried so far is working fine.

I am now trying to install `open-vm-tools`. However, each time I try to install via `apt`, I receive the following error: `E: You don't have enough free space in /var/cache/apt/archives/`

After some Google research, I tried running `sudo apt clean`. That cleaned up the contents of `/var/cache/apt/archives`. Yet, I am still receiving the same error.

Am I missing something? If anyone could point me in the right direction it would be much appreciated.

**Comment by t3chn0m4g3** [comment]
This seems to be Debian related, which is our distro of choice. Please check how much space you have left on your drive. You can always install on top of your own Debian 9.x installation with the installer.
