### ISSUE TITLE
Can't find my log data?! nothing from kippo, dionea, glastopf

### ISSUE THREAD

**Issue by Herah** [dtag-dev-sec/tpotce#43]
Hi there,

Looking at the honeypot we set up now it seems as if there is data logging missing, can I get some help/insight on this? in the /data folder there is nothing besides the Suricata folder ( no kippo folder nothing, just one lone folder) and the dashboard looks like this:

![h1](https://cloud.githubusercontent.com/assets/1164853/16266835/1717c000-3887-11e6-9840-df4eceb38051.PNG)
![h2](https://cloud.githubusercontent.com/assets/1164853/16266837/1725adf0-3887-11e6-8270-2baadaf3d739.PNG)
![h3](https://cloud.githubusercontent.com/assets/1164853/16266836/171be6f8-3887-11e6-9930-383217bb2f61.PNG)

Any insight would be appreciated!

**Comment by t3chn0m4g3** [comment]
From the screenshot it looks like you are using an old version of T-Pot.

Please check [here](https://github.com/dtag-dev-sec/tpotce) for the latest image builder or [here](https://github.com/dtag-dev-sec/tpotce#prebuilt) for a prebuilt ISO of T-Pot 16.03.
