### ISSUE TITLE
Not an issue general question about Dionana Honeypot 

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#430]
Hello,
Quick question about Dionana.

I am only seeing DLL files in the /binaries/ directory and I don't see anything in the other directories /ftp/ and so on.

Is this normal? 

Should I only be seeing DLL files? I mean I am cool with this just making sure I did not goof something up. 

(Also I know that you run a CRON job  that moves the malware from the other directories into into /binaries/)

**Comment by t3chn0m4g3** [comment]
This depends, I see all sorts of binaries there  (DLLs, EXEs, PSs). I'd say this is quite normal then 😄

**Comment by iukea1** [comment]
Strange I am am only getting DLL files .... 

I turned off Glutton because that was pissing me off. Would that impact anything in regards to capturing malware ?

**Comment by t3chn0m4g3** [comment]
No.
