### ISSUE TITLE
Logstash has been reporting Fetching origin this error, and I can't receive any data!

### ISSUE THREAD

**Issue by huangyuan666** [dtag-dev-sec/tpotce#432]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
Logstash has been reporting Fetching origin this error, and I can't receive any data!
![image](https://user-images.githubusercontent.com/24352334/62677322-7e0b6680-b9e0-11e9-9964-ac561d6b7d88.png)

<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by huangyuan666** [comment]
![image](https://user-images.githubusercontent.com/24352334/62677432-df333a00-b9e0-11e9-99cb-6fce03af5dbf.png)

**Comment by huangyuan666** [comment]
![image](https://user-images.githubusercontent.com/24352334/62677482-10136f00-b9e1-11e9-811c-880a090b3df8.png)

**Comment by iukea1** [comment]
Mmmm try 

Chmod 760 -R /data/

And reboot Tpot.

Never seen this issue before so I am shooting in the dark

**Comment by t3chn0m4g3** [comment]
Please provide a `docker logs logstash`.

**Comment by t3chn0m4g3** [comment]
The only reason I can currently think of is that Github is either not reachable or blocked. For logstash's translation maps [update](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/elk/logstash/dist/update.sh) we have no measures in place to catch a non reachable Github.
