### ISSUE TITLE
Avast connecting to Dionana Honeypot 

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#435]
![image](https://user-images.githubusercontent.com/35882815/62827332-cd919400-bb92-11e9-9200-f6fe45241658.png)
What are you doing, Avast?

Was curious if anyone else has seen this

**Comment by t3chn0m4g3** [comment]
This is common.

**Comment by iukea1** [comment]
@t3chn0m4g3 do you think it will be possible to get the MD5 hash of the Dionana payload into the logs? I made a comment on there GitHub page because it does look like that data is printed in there json file.

But it is in there little sql database file that that make

**Comment by t3chn0m4g3** [comment]
If it is written to the JSON logs it should be in there already.

**Comment by iukea1** [comment]
It is not sadly :(
It looks like it is not supported by default

**Comment by iukea1** [comment]
Do you have any recommendations for capturing different of malware  95℅ of the payloads I am getting are just different variants of wanna cry.

There wannacry can be identify  there file size  being 5.03 MB in /binaries/

**Comment by t3chn0m4g3** [comment]
MD5: What release have you tested against? We are using 0.8.0 release version not latest master.

One way to catch more and different malware is to broaden your sensor network on a global scale. Different countries, AS, networks and such.

**Comment by iukea1** [comment]
Using
0.8
(I think that is the latest)
I have sensors in

Japan
United states
And Singapore

**Comment by t3chn0m4g3** [comment]
Cannot find any fields with MD5 hashes in the json logs.

Usually that should cover it. Maybe adjust configs to your needs / requirements might help. Otherwise Dionaea is pretty much fingerprintable with nmap, so you probably will not catch any APTs.

**Comment by iukea1** [comment]
I found a way to make it not as printable by nmap
https://www.attacusatlas.com/how-to-set-up-dionaea-honeypot-to-evade-nmap-detection/

**Comment by iukea1** [comment]
I found the hashes in the little sql file in the Dionana directory

**Comment by t3chn0m4g3** [comment]
nmap: thx
sql: is not tracked by logstash. ewsposter does however and can transmit contents even to a third party hpfeeds broker.
