### ISSUE TITLE
cannot find all.yml

### ISSUE THREAD

**Issue by diegomessiah** [dtag-dev-sec/tpotce#438]
# Issues
ubuntu 16.04
problem on autoinstall - install.sh
can't find file all.yml 
### Preparing EVERYTHING flavor installation.
cp: cannot stat '/opt/tpot/etc/compose/all.yml' : No such file or directory
root@name:/home/user/.ssh/t-pot-autoinstall#

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Ubuntu is not support anymore. Please reinstall using latest [image](https://github.com/dtag-dev-sec/tpotce/releases) which is based on Debian.

**Comment by diegomessiah** [comment]
which version?

**Comment by t3chn0m4g3** [comment]
The latest.

**Comment by iukea1** [comment]
@diegomessiah you are on an old version of Tpot.

**Comment by diegomessiah** [comment]
thanks a lot
