### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by peet47** [dtag-dev-sec/tpotce#439]
newest release is not working

REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
dtagdevsec/elasticsearch   1903                fbe66110d949        15 hours ago        249MB
dtagdevsec/kibana          1903                8d89ea1361a8        15 hours ago        481MB
dtagdevsec/logstash        1903                a3e195401f1f        15 hours ago        450MB
dtagdevsec/suricata        1903                229db053237d        2 months ago        106MB

/ $ ldd /usr/share/kibana/data/headless_shell-linux/headless_shell | grep not
Error loading shared library libnss3.so: No such file or directory (needed by /usr/share/kibana/data/headless_shell-linux/headless_shell)
Error loading shared library libnssutil3.so: No such file or directory (needed by /usr/share/kibana/data/headless_shell-linux/headless_shell)
Error loading shared library libnspr4.so: No such file or directory (needed by /usr/share/kibana/data/headless_shell-linux/headless_shell)
Error loading shared library libexpat.so.1: No such file or directory (needed by /usr/share/kibana/data/headless_shell-linux/headless_shell)
Error loading shared library libuuid.so.1: No such file or directory (needed by /usr/share/kibana/data/headless_shell-linux/headless_shell)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/share/kibana/data/headless_shell-linux/headless_shell)
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __sbrk: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __res_nclose: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __res_ninit: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __vsnprintf_chk: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __isnan: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __isinf: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __isnanf: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: strtoll_l: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: strtoull_l: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __fdelt_chk: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: backtrace: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __strncat_chk: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: __longjmp_chk: symbol not found
Error relocating /usr/share/kibana/data/headless_shell-linux/headless_shell: CERT_GetDefaultCertDB: symbol not found

**Comment by t3chn0m4g3** [comment]
Unfortunately I cannot reproduce. Fresh installations as the ones in production are working flawlessly.
