### ISSUE TITLE
Is there a legend of what is logged by each honeypot available?

### ISSUE THREAD

**Issue by quimmontal** [dtag-dev-sec/tpotce#44]
Hi there,
I found the project really interesting, but I wanted to try to take control of the logs of the honeypots by my own means. The problem is that I didn't find any place which would tell all of the different logs that each honeypot can report in order to make rules, being stuck with Kibana for the visualization of the logs. Is there any documentation of all the unique alerts that each honeypot can log?
Thanks in advance, and great job guys!

**Comment by t3chn0m4g3** [comment]
Please check [here](https://github.com/dtag-dev-sec/tpotce/issues/41). Within [16.10](https://github.com/dtag-dev-sec/tpotce/tree/16.10) you can put your own `logstash.conf` in `/data/elk/logstash/conf`. I would recommend to copy the one from the elk-container and adjust it to your needs. As long as the file is present the elk-container will use it and also ignore updates should the elk-image change.
While the feature is already implemented and it works just fine, but it is still a development build :stuck_out_tongue_winking_eye:

**Comment by quimmontal** [comment]
Thank you! I'll have a look on that!

**Comment by quimmontal** [comment]
@t3chn0m4g3 For what I understood, your response was referred to the redirection part of my question. Is there a solution to the unique alerts part of each honeypot? Is waiting for them to arrive the only way to have them and then creating the rules? or can they be retrieved from somewhere to create the rules and have the deployment ready since the start?
I think it would be as "half implemented" on my server if I can't really sort all the alerts that are going to arrive until I get them. Thanks for your time!

**Comment by t3chn0m4g3** [comment]
You can find all logging data in `/data/` and you might find the logstash documentation really helpful since it will allow you to do all sorts of things with the JSON logs.
