### ISSUE TITLE
Installer Error - Errors were encountered while processing:  fuse E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by cappetta** [dtag-dev-sec/tpotce#440]
# Issue:
The installer is not setting up a complete tpot instance.  

Use case: 
I've created a debian 6 instance in aws, cloned the repo, and ran the cloud-init script to fully set everything up.  I can't get the system up, I don't see docker installed, appears fuse is causing an apt install issue.  I can help troubleshoot but I think a regression test on the installer is needed as something is off.  

I've tested with the AMI in the cloud terraform mappings ec2_ami variable for us-east-1, I tested against a different debian ami, specifically ami-0cebe9c5c89f17474.  Logging an issue and shifting to build the ISO locally, upload an OVA, and create an AMI to test against.  Note - the ISO also appears to have an issue w/ fuse, appears amazon is not accepting the v5 kernel...

Verbose output of the installer process is on [this GIST](https://gist.github.com/cappetta/ba94993a71a19a8efc4ab5dbeb87075e#file-tpot-install-output-txt-L9863) pointing to the specific line where the fuse error occurs.  I'm testing an ova of the iso & I'm working on creating an AMI as a possible alternative.

## ⚠️ Basic support information  - Due Diligence...

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
**I shared amis above** 

- What T-Pot version are you currently using?
**github master**
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
**standard**
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
**aws**
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
**yes, system didn't reboot, packages didnt install fully, issue w/ fuse above, deleted assets but can recreate if necessary.**
- How long has your installation been running?
**less than 30 minutes, created and installed multiple assets w/ terraform & cloud init, I am a previous tpot user on ubuntu (~1 yr ago)**
- Did you install upgrades, packages or use the update script?
**leveraged the projects cloud-init script**
- Did you modify any scripts or configs? If yes, please attach the changes.
**no**
- Please provide a screenshot of `glances` and `htop`.
**htop had nothing interesting, no docker services were up, not familiar w/ glances cmd will need to review/share it if I bootup another instance to troubleshoot.**
- How much free disk space is available (`df -h`)? 
**200gb**
- What is the current container status (`dps.sh`)?
**not executed**
- What is the status of the T-Pot service (`systemctl status tpot`)?
**not executed**
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by cappetta** [comment]
Added a PR...

**Comment by t3chn0m4g3** [comment]
Thank you for reporting, however we intentionally only support installing from stretch / buster.

**Comment by cappetta** [comment]
Thanks for the quick response.  I believe this issue is within the unstable packages.  Once those are used, stretch is upgraded to SID and everything breaks.  This occurs in the iso as well as the installer.sh  The PR simply reverts back to stable to avoid the SID upgrade

**Comment by t3chn0m4g3** [comment]
@cappetta Yes, it seems `fuse` is the culprit (see #442).

**Comment by t3chn0m4g3** [comment]
Closing this in favor of #442.

Thanks for reporting.
