### ISSUE TITLE
Repository: Add Social Preview 

### ISSUE THREAD

**Issue by TheHADILP** [dtag-dev-sec/tpotce#444]
We could add a picture for the Social Preview in the GitHub project settings.
This will appear on Twitter/Facebook/etc. when the URL to the repo is posted.
Looks much better and this way we could use the new T-Pot logo.

See below for a first concept:
![tpot_social_preview](https://user-images.githubusercontent.com/16366556/63597715-64604680-c5be-11e9-8086-0b10f69ec0ea.png)

This is how it currently looks on Twitter (tested with https://cards-dev.twitter.com/validator):

![old](https://user-images.githubusercontent.com/16366556/63598131-3cbdae00-c5bf-11e9-8403-f6008b6616c5.PNG)

This is how it could look like (tested it in my repo fork):

![new](https://user-images.githubusercontent.com/16366556/63598140-43e4bc00-c5bf-11e9-9b64-15fe5a873584.PNG)

Let me know what you think 😁

**Comment by t3chn0m4g3** [comment]
I like it. The new T-Pot logo is still in the making including wallpapers for various resolutions.

**Comment by t3chn0m4g3** [comment]
[Done.](4620666d4ea63497548e2382b3f0fa3ad421730f)
