### ISSUE TITLE
Expand disk

### ISSUE THREAD

**Issue by alancdias7** [dtag-dev-sec/tpotce#446]
good afternoon,
Is it possible to expand the disk used in TPOT?
I performed the installation using the steps below on a 150 GB disk, but it created a 30 GB partition and left 120 GB unused.
At this time the 30 GB has been fully utilized and would like to expand this partition.

I even read the article "https://github.com/dtag-dev-sec/tpotce/issues/355" but it didn't help me.

![image](https://user-images.githubusercontent.com/53276043/63888768-ffd62a80-c9b5-11e9-92f8-2a4fb3e86dbf.png)
![image](https://user-images.githubusercontent.com/53276043/63888791-095f9280-c9b6-11e9-8553-efaf05fc2895.png)
![image](https://user-images.githubusercontent.com/53276043/63888804-11b7cd80-c9b6-11e9-9e91-bb19bff4be80.png)
![image](https://user-images.githubusercontent.com/53276043/63888887-357b1380-c9b6-11e9-92a5-40e51e34da8a.png)
![image](https://user-images.githubusercontent.com/53276043/63888931-504d8800-c9b6-11e9-9641-343dc6698cc6.png)

**Comment by t3chn0m4g3** [comment]
Based on your previous issue your installation is not based on the ISO. Only an ISO install will take care of that at the time of installation.

**Comment by alancdias7** [comment]
Thanks for the answer.
So there is nothing you can do to expand the partition?

**Comment by t3chn0m4g3** [comment]
I am sure there is, but please understand this is out of T-Pot's scope and not really and issue with T-Pot.

Thank you.
