### ISSUE TITLE
not an issue (question)adbhoney  change

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#447]
Hello,
just quick dev question on what you guys added / changed /modified to adbhoney.

Saw that a .cfg file was added. And was curious what that .cfg file do?
https://github.com/dtag-dev-sec/tpotce/commit/cae95ebe20eb9c0159f98562c360fc45e3be9028

Will it change any log fields?
or does it just change how adbhoneyappears to attackers?

**Comment by t3chn0m4g3** [comment]
1. A replacement for the command line options (introduced upstream).
2. Add config option for device type.

Log fields remain the same.

**Comment by iukea1** [comment]
@t3chn0m4g3 thank you!!!
