### ISSUE TITLE
Installation in proxmox fails: "no kernel modules were found"

### ISSUE THREAD

**Issue by s55ma** [dtag-dev-sec/tpotce#449]
T-pot version 19.03
Proxmox version: 6.0-4
Using tpot.iso

https://imgur.com/a/V7xm3QZ

**Comment by t3chn0m4g3** [comment]
@s55ma Thank you for noticing. There was an upstream change and I recreated the [T-Pot ISO](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.1) accordingly. The installation should work as expected now.

**Comment by xme** [comment]
Is there a chance that the same occurs with 19.03.3? I'm facing exactly the same issue.

**Comment by t3chn0m4g3** [comment]
Did a fresh install in Proxmox yesterday with 19.03.3 and it was working perfectly fine.

Am 10.05.2020 um 11:14 schrieb Xavier Mertens <notifications@github.com>:

﻿

Is there a chance that the same occurs with 19.03.3? I'm facing exactly the same issue.

**Comment by xme** [comment]
Hmmm... weird, will retry and check deeper...

**Comment by thaneye** [comment]
Same error here using vmware and 19.03.3

**Comment by t3chn0m4g3** [comment]
Thanks. Today I was able to reproduce. Please find the update images (1305 in filename) [here](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.3).

**Comment by thaneye** [comment]
It seems to be working now, thanks!

**Comment by AngelUs04** [comment]
Hi. I'm having problems with the last tpod's iso image when installing in Oracle VM. When selecting mirror, this error shows up : "no kernel modules found". Is there any solution?
Software version: Debian 11 Bullseye (64)
ISO version: T-Pot 22.04.0

**Comment by t3chn0m4g3** [comment]
@AngelUs04 Updated the current release with the latest images.

**Comment by AngelUs04** [comment]
It works perfectly fine now, thanks!
