### ISSUE TITLE
Honeypot Map broken since July 11

### ISSUE THREAD

**Issue by hmlio** [dtag-dev-sec/tpotce#45]
Hello T-Pot Team! :-)

I just installed the latest tpot.iso and noticed something odd with the Honeypot Map:
Instead of displaying a world map there is a message from MapQuest stating  they have discontinued their tile service since the 11th of July 2016.

Cheers,

Emre

<img width="466" alt="tilemap" src="https://cloud.githubusercontent.com/assets/11684719/16785735/f3565bae-488f-11e6-8e2a-16d7278bd682.png">

**Comment by t3chn0m4g3** [comment]
Thank you Emre, it seems to be related to the default map provider within kibana. For now please follow this [thread](https://github.com/elastic/kibana/issues/7717).
Best regards,
Marco.

**Comment by t3chn0m4g3** [comment]
Kibana devs are currently working on finding a new Map provider. As soon as there will be a fix I will update the T-Pot installation files. Existing installations can be easily fixed by following the instructions of @jamesspi in this [thread](https://github.com/elastic/kibana/issues/7717).

**Comment by t3chn0m4g3** [comment]
A fix has been [issued](https://www.elastic.co/blog/kibana-4-5-3-and-4-1-10).
Will try to have a working and tested fix by the end of the week.

**Comment by t3chn0m4g3** [comment]
I just pushed a fixed ELK container with the latest Kibana version and thus a fixed map issue.
