### ISSUE TITLE
Spiderfoot a lot of errors.

### ISSUE THREAD

**Issue by s55ma** [dtag-dev-sec/tpotce#450]
Default setup, version 19.03

My t-pot connection is not firewalled, egress = allow all, manually going to timeout links with a PC is working fine.

https://i.imgur.com/dgi9JeV.png

**Comment by t3chn0m4g3** [comment]
Some services require you to enter an API key so you can use them. The services in use are also external, so might not be available.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
