### ISSUE TITLE
Tpotweb don't show nothing

### ISSUE THREAD

**Issue by tXambe** [dtag-dev-sec/tpotce#452]
# Issues

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
   Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
- What T-Pot version are you currently using?
   19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
   Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
  VMWare
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
  N/A
- How long has your installation been running?
   1 week
- Did you install upgrades, packages or use the update script?
  N/A
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
  
![glance](https://user-images.githubusercontent.com/12039753/65138747-f3fce780-d9fa-11e9-9f92-ffc73bbd1e29.JPG)
![htop](https://user-images.githubusercontent.com/12039753/65138759-fb23f580-d9fa-11e9-9368-f9fd312c1fd2.JPG)

- How much free disk space is available (`df -h`)?
`[root@judicialsalesman:~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           782M   26M  756M   4% /run
/dev/sda2       149G   19G  123G  14% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           782M     0  782M   0% /run/user/1000
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/f8258ce02ca66f0518e3d02a831ab3b71592381e2ecac8325358314a28468454/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/6bee3ab494d121eb453a629f85b05dd981e6badf9400c2a61a7e16358097dd88/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/abaa40e930c8a93781c577903b25222c4c0d804a20852b940d9b482d198fb363/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/aff04c27af3f67921a9b3ee82c6746e89fdf82fdb6f95da9c04ada60fdba50b0/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/196b34f850a65a82859740e11d3ac42669abd9dde9ca59f2e7fafa4c6d9bdf36/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/f6995ba66245e03e6e2d08ff9a56d78b82108749622c46bf22c541c1c9675192/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/e6f3547ef86f7d7befe362f75ed94f28c31549292cf0e7ad8d759382e992d347/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/b7dd268d3d85b83a21db66ae95df65b8dccdcce56b399ab55aa5149efc8dba15/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/85a2de8d81f951041f622fd3906bfdfa3aed096d97fef34e350f19d2d92e6c41/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/9be51fed7a2718f448386f69958c766edbdd9ea987adc09557ad9a8493e1934c/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/4269a94aed0eaaf06eb043f99e65408d09fa5089e30c397c0adfd8f9142ad523/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/f3bbb6e4b1d40d0bcf7391ddb741368721373a4a23412a4ae21e12440804450e/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/e9bc789807b35d10b86739c9603522c0c8ae9bed1bf4d3d9c6712915efd6dfea/merged
shm              64M     0   64M   0% /var/lib/docker/containers/7071582c4d974fc51375863e6e52ec08a5266dd416bc49e602045d79de3b7294/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a5ff9205e93c5f30ff116c3f29f4fcd0cc3365dd0f9f5df8204f5cb36a54685b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/f4361363caf7ac5bce8cf301a68ec4c2894b261d74b7a6dcd4852bbd4f81108c/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d9eee3604ebe88ceb86990b19df0ddc054e3652d7bd01134d0f6d23e88ace2a2/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c5d450cda4bcf1caaa3c36e9c843faecea5879b2cfccfb376ea476593b18193b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bbbb2725f204301ba15be89c6576e5e936cccc825e73d86c36a3b6de76f6cf11/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/4b37184ffba8cac918b87eb29e4e3eaca845dc10fab0d22b2056035b8cb06219/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/482af4ffae42ec2a39afc5ec5b691f0197bdd5183e3b24c1e65b37ec8c7b34ba/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/40d88085e4363f64ceeb84dfd2cb5c4c5836351a2823c66ac6515c6924dec485/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1bb371e061fba7d6ae520035ece4be3079bcc0dd9b1958a76a63e22036b99b5e/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7845a11cd3bde12dcb2d8a7f5d391d7a5f9f6196dbca364e5c406b9d301ef13c/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/02139a573df90f9202f0b3ce0f77d3b291f2f8c0a0e942f01731a8205753b32a/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/8362a750b7a03e12eb3bdcb66bad69eff4db8a78b9f64849c54971d28d757bfd/mounts/shm
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/d593ef3b22a3dc6dcf5c2c676a2c71f0fa130a9282f2b27b3196bd51115cae33/merged
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/9fe77ce910dcc76fff3079b45c1ef84aa1eeac8eb41cd5cd9e5a8f6447dab2af/merged
shm              64M     0   64M   0% /var/lib/docker/containers/25fff351d34a9688d60814c5ec4b6f638a29a0b355207a2eb046ad9b66041c0d/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a68433b2f3385bb267eb9e822e6af3dca66e40f833e4b7b2c342090ac6e508c5/mounts/shm
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/a2a3f1d6073dfa5f3d0da2afe30186f539e2344174e3679cba982dc0b21a3b7b/merged
shm              64M     0   64M   0% /var/lib/docker/containers/90f649e7ad1c89c378a3e373a0bff1830e81f4b33d73a71ac96eec107598aee9/mounts/shm
overlay         149G   19G  123G  14% /var/lib/docker/overlay2/01f8c8a5ed0a18d41fba9f41ae71cffc3542cf4d7676c70fd2e002f3b3132b84/merged
shm              64M     0   64M   0% /var/lib/docker/containers/1acb10d14b07a318ad7f6d12eba52f0f045dcc3cc661c4fed86bfe9c4004ac50/mounts/shm`
- What is the current container status (`dps.sh`)?
========| System |========
    Date:  Wed 18 Sep 2019 10:06:50 AM UTC
  Uptime:  10:06:50 up 23 min,  1 user,  load average: 8.16, 9.57, 7.97

NAME                  STATUS                       PORTS
adbhoney              Up 58 seconds                      0.0.0.0:5555->5555/tcp
ciscoasa              Up About a minute
conpot_guardian_ast   Up 58 seconds                      0.0.0.0:10001->10001/tcp
conpot_iec104         Up 57 seconds                      0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 57 seconds                      0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 58 seconds                      0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 58 seconds                      0.0.0.0:22-23->22-23/tcp
cyberchef             Up About a minute (healthy)        127.0.0.1:64299->8000/tcp
dionaea               Up About a minute
elasticpot            Up 57 seconds                      0.0.0.0:9200->9200/tcp
elasticsearch         Up 57 seconds (health: starting)   127.0.0.1:64298->9200/tcp
ewsposter             Up 58 seconds
heralding             Up 59 seconds                      0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up About a minute
mailoney              Up 59 seconds                      0.0.0.0:25->25/tcp
medpot                Up About a minute                  0.0.0.0:2575->2575/tcp
nginx                 Up About a minute
p0f                   Up About a minute
rdpy                  Up About a minute                  0.0.0.0:3389->3389/tcp
spiderfoot            Up 57 seconds (healthy)            127.0.0.1:64303->8080/tcp
suricata              Up About a minute
tanner                Up 52 seconds
tanner_api            Up 57 seconds
tanner_phpox          Up 58 seconds
tanner_redis          Up About a minute                  6379/tcp
tanner_web            Up 57 seconds
head                  DOWN
kibana                DOWN
logstash              DOWN
snare                 DOWN

- What is the status of the T-Pot service (`systemctl status tpot`)?
tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-09-18 10:05:29 UTC; 4s ago
  Process: 2321 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 2349 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 2412 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 4152 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 4155 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 4168 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 4180 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 4192 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 4208 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 4214 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 4220 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 4226 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 4294 (docker-compose)
    Tasks: 47 (limit: 4915)
   Memory: 39.2M
   CGroup: /system.slice/tpot.service
           └─4294 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating tanner_redis        ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating honeytrap           ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating ewsposter           ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating conpot_kamstrup_382 ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating medpot              ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating adbhoney            ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating mailoney            ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating nginx               ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating tanner_phpox        ...
Sep 18 10:05:34 judicialsalesman docker-compose[4294]: Creating p0f                 ...

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16296      704/sshd
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      111        16904      660/mongod
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          16870      720/apache2
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          17942      681/python3
tcp6       0      0 :::64294                :::*                    LISTEN      0          13352      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          16307      704/sshd
udp        0      0 192.168.100.34:123      0.0.0.0:*                           0          16058      692/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          16056      692/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          16052      692/ntpd
udp6       0      0 :::123                  :::*                                0          16049      692/ntpd

**Comment by t3chn0m4g3** [comment]
Looks perfectly fine. However the screenshots were taken too early so some containers have not started yet.

**Comment by tXambe** [comment]
Hello,
Now I have the containers up, but don't show nothing

========| System |========
    Date:  Wed 18 Sep 2019 10:24:22 AM UTC
  Uptime:  10:24:22 up 41 min,  1 user,  load average: 9.00, 9.89, 8.80

NAME                  STATUS                       PORTS
adbhoney              Up About a minute                 0.0.0.0:5555->5555/tcp
ciscoasa              Up About a minute
conpot_guardian_ast   Up About a minute                 0.0.0.0:10001->10001/tcp
conpot_iec104         Up About a minute                 0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up About a minute                 0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up About a minute                 0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up About a minute                 0.0.0.0:22-23->22-23/tcp
cyberchef             Up About a minute (healthy)       127.0.0.1:64299->8000/tcp
dionaea               Up About a minute
elasticpot            Up About a minute                 0.0.0.0:9200->9200/tcp
elasticsearch         Up About a minute (healthy)       127.0.0.1:64298->9200/tcp
ewsposter             Up About a minute
head                  Up 4 seconds (health: starting)   127.0.0.1:64302->9100/tcp
heralding             Up About a minute                 0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up About a minute
kibana                Up 3 seconds (health: starting)   127.0.0.1:64296->5601/tcp
logstash              Up 4 seconds (health: starting)
mailoney              Up About a minute                 0.0.0.0:25->25/tcp
medpot                Up About a minute                 0.0.0.0:2575->2575/tcp
nginx                 Up About a minute
p0f                   Up About a minute
rdpy                  Up About a minute                 0.0.0.0:3389->3389/tcp
spiderfoot            Up About a minute (healthy)       127.0.0.1:64303->8080/tcp
suricata              Up About a minute
tanner                Up 59 seconds
tanner_api            Up About a minute
tanner_phpox          Up About a minute
tanner_redis          Up About a minute                 6379/tcp
tanner_web            Up About a minute
snare                 DOWN

**Comment by t3chn0m4g3** [comment]
From a T-Pot view everything looks perfectly fine. If you cannot see any traffic then you probably have a routing and / or NAT issue. Please make sure T-Pot is reachable through the internet or from within the networks you have exposed it to.

**Comment by tXambe** [comment]
I don't think I have network problems because , if I go at https://x.x.x.x:64294 , I loggin without problem

**Comment by t3chn0m4g3** [comment]
Sorry, cannot reproduce.

**Comment by tXambe** [comment]
Reinstall everything, I guess

**Comment by tXambe** [comment]
The docker of kibana don't run , I guess that's the problem.

**Comment by t3chn0m4g3** [comment]
Assuming this is resolved.
