### ISSUE TITLE
installation fails at preseed

### ISSUE THREAD

**Issue by ChristopherClayden** [dtag-dev-sec/tpotce#453]
Good afternoon,

I am having some installations issues with 19.03.1.  Installation fails at preseed.  I am using a proxy in my setup.  I have determined at the point that it fails; a DNS request goes out to github and then TPOT attempts to go out directly to github bypassing the proxy.

Is there any easy fix/solution to this issue before I consider building my own ISO?  Hoping that we can force GIT out using the proxy?

I assume I will have to build and configure GIT to use a proxy manually:

"git config --global http.proxy http://<username>:<password>@<proxy-server-url>:<port>"

Cheers-

**Comment by t3chn0m4g3** [comment]
You have to build your own T-Pot ISO image (clone the repo and run `./makeiso` as root) or run the T-Pot installer on top of a pre-installed Debian 10.x where proxy support is configured.
Also: We are not accepint proxy issues, since the feature is only experimental and some containers might not work properly unless you manually take care of proxy settings individually.

**Comment by ChristopherClayden** [comment]
Thank you for the follow up.  Can you please elaborate on which containers specifically will require a proxy update?  Cheers-

**Comment by t3chn0m4g3** [comment]
This depends on your setup. If you are using a proxy it seems likely you want to deploy T-Pot internally. Most likely logstash will not be able to pull updated translation maps for CVE IDs and reputation.
Some containers pull public IPs to enrich logs (as T-Pot does) and might not work as expected.
You find all docker related stuff in the `docker` folder. Once a container needs a start script you should do some testing.
Maybe we will extend proxy support in the future, but it is asked not often enough to entertain that thought with a priority. Especially when it comes to corporate proxy setups there is no way to get ahead of all types of authentication and / or dealing with SSL decryption / reencryption issues.
Check out the `makeiso.sh`, it will give you some hints how to get started.

However, please understand that currently we are not accepting issues in that regard and I am closing this issue now.

Thank you.
