### ISSUE TITLE
dashboard empty

### ISSUE THREAD

**Issue by tXambe** [dtag-dev-sec/tpotce#457]
# Issues
After of one week with problems I got the same error, the dasboard is empty.This already happened to me, eliminate the vm and generate a new one and it happens the same thing that is put to 98% of cpu by the process jav 1.8-openjdk and the docker of kibana don't run.

I've checked "Edit /opt/tpot/etc/tpot.yml and search for the ELK section. Change Xms values from 512 to 1024 each and uncomment mem_limit line" and and I was in that configuration.

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid

Linux explicitfield 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux

- What T-Pot version are you currently using?

19.03

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?

Standard

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VMWare ESXi 6.7

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Nothing error
- How long has your installation been running?
1 week
- Did you install upgrades, packages or use the update script?
Not
- Did you modify any scripts or configs? If yes, please attach the changes.
Not
- Please provide a screenshot of `glances` and `htop`.

![Uploading htop.JPG…]()

- How much free disk space is available (`df -h`)?
`Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           782M   44M  738M   6% /run
/dev/sda2       149G   18G  125G  13% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           782M     0  782M   0% /run/user/1000
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/4fb87e0319516660c840f0c80a1edb79f655748eeba79d594aa8b85a88a00efc/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/b93b3a40cb47e74b1c7fb94e477842745ebdc9ac978f03bbc8ca85a5e78c6b7e/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/43be4e30e698fa2380fc90c771076a2232cba7936f74b1ad6b6d5c56a5569c54/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/88a6c663dea46b2f8e623cbfc5a129cd2b0eab1863fc1f0f0efa07dd19a8ee56/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/5adcf385a4bc4238fdd9c35480407bd80f8c037616b8d7e13cd0baee6b2a2a12/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/8a61fb11640e6146768b6bffe28ab10eb5dcfc6b9891b917c3076b64c65d78c8/merged
shm              64M     0   64M   0% /var/lib/docker/containers/8931c6fb8e3845e69d0d04ef07a367805fb5d5ffcff00425d14f0202ea529d1c/mounts/shm
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/03f140536ee29908a0ee758b829c9955c17e1f50a4088ac108c4976566f5e246/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/40cc0e09569544bd73efb02a3846dec82c0cf4a1b0a56ed51468eea124107808/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/b9fa897d014942cbdb1af254e99fcfc22062127657163fa55130d6f7e4a5d367/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/d1855f9ce217808988b37983523f096f0dd3b23e14f3a660fab266109b507347/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/9f9445008e66691801b24107a15da38125a5c75bcab69b5977bdbfe0330b69ae/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/58fa60cea7c0025b75c5645af7898be551c40550948b1133db2d960af3992fcc/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/df5556a8e7623f7dd574ba7b170d01a6a4f36d5dd7b6e5e8db11b24c07cf1a07/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/1671110bd70b894f47494c68eceedd1d5ef26395957efd8c8b50d29548890443/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/e9d7f7cae3a37934112ae0c3a27d9367ca679e3782bd33a63f90990958474b69/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/d5834474ed45319b11496ceac31e9a814a1f3764bcd434bfa478d01ea7af3f6f/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/5e52ccd3235bb5dbfb76187ad9a46f5f379ec14db4798929dfe5451cd23975ca/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/c6b7cb0f451eac3b581a3526033cebb5b76127cb48f7b97144c9e251afee67f4/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/b867d990921e5d5be29a8a011eabdfa18585f560248c320d2610530eed9684b4/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/9b3baae335a3c04f52b9c2aae5f4ff8837f5df711573c6b1042e1bcbc6dd30a9/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/046b5c4cab92cd40a31fc498b8f592b447c09efc91aa4bb526c3a56404d10dd9/merged
shm              64M     0   64M   0% /var/lib/docker/containers/3f62ac15abf6b2cd086a77a747398abb873a1ced1eb30c99036b5f0ab93f7f73/mounts/shm
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/03b6cabfb5439f0c3dd89568bdf36b6ab27c2d5e32d604b73f2a06069ab406ac/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/c2a0bba7a5838fdb5e24e200a4076cf15a5bb38ed84e6c549f0371f897a31ac2/merged
shm              64M     0   64M   0% /var/lib/docker/containers/35859eaf0674d1bb615562993ec9752d2c169dde54f83b442788c832944bcbd9/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a03ea93df7f30414735a4726fff020b183585b28373f6a3a359122eb7b7026ca/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1b60374f4962bee68d5c4fe17ea84d92e7a465a9d36999618127f0a0aaab9ca7/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/34acebbf9eb9af0b39de0449a704b70ea23e5d55b0892c7e36d5475ca0bbab42/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/022135f397f187bee6d3e2ccde3332d9f4d76880b0cac146e897ad3381837989/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1ba93f23b5c3fda7097dfdb7df9c2571f7afa3633f4d00a9f667ee1f0b2f6c5f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/5e91989878d21eb9791eed5b256eb64d9b990aa4f77f92c2420108d097142791/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/908fd31b9825f3cfd0f1f0ea2374814f42822de304847fb69f258197178aed2b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bf6d5081821a0ea34c810e0a8f7027e358b28ae8cad4ab5f530fe4a08a6337ac/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/112ec2e4af82235830b5b36f589fe902524de04c46afc19cbc472f388d23d1d4/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a4c5edd337c53d461e4bdedce1e4a079c0fb1ca02fbf85b196bd37a94b48e90b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/27cfb73347b77c2402c126dbe5a09559a830a68e41be6f491cabd8dd52b3a903/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/aef7cf7a6eb062c661ad7e3a8daa20495ca174f511e69ca25fbd614d7bb19135/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/4de1d0813522ec143e6e2fa3bb046b918cdb16fec4ad9b9619a7b90dbb0c0f9d/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/58858fe71b69710f85227d7eb89c047f94d66e3e290adc69d76dc3237ae4ae70/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/502cbd1f90c35a3d66e3a74f4505c4b6411f809d3ef06094b51c114a6ce45d65/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/5b4d9d6c5858aa090ee94dce65335504fcf1b59e8d81f8b0176020ce5458a59d/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c2c557756189b21c2515dd8fa0effe3d049dbb2a45e802ff257616162ef48707/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/fb9b69d06a70c1bfe396f5e7fe3d4a1a60dbadc4ea1445a51213b65f735c70c8/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/cc2fd7b5ecf6ae320b4938c46e75bd1793177fddf2ee1f1576b641c0a1ca0dc4/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a3c08e13709daed44663a4086aa8a7c5ebc42a4201eecea818bc49200b8ef15e/mounts/shm
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/1eb0d313803cc643af17aeceb314cd585c198b0b0071225f0f3e7873955dd5ff/merged
shm              64M     0   64M   0% /var/lib/docker/containers/cfe446c548ad30823ceedf68a6aeba862f43e9b18b4fc5af3447c2e3e8206981/mounts/shm
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/25ea3c2b688840c7c4f7e408e3518e50100ed31ec0dee9d2199d31e3e1be3219/merged
shm              64M     0   64M   0% /var/lib/docker/containers/2d13dd87c13054e956f26ca96985f6b345589095a630d2b27cc8cb0f6362f082/mounts/shm
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/f77c7620dd8aa905a4d0cbbf6f1574e0f9c8780f25731adfe81702b3e5fa43ab/merged
shm              64M     0   64M   0% /var/lib/docker/containers/f51656386a32afca80cfb3b7bd8f1f483ee816ed8882702a15eac69d536b93b8/mounts/shm
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/fa69c1400886d604b2fe1ae4d138f53b1ecbcdae4a0d5e532e095bed949fc29c/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/5a9ab1cb8f41f9f5b06d93cc5f1c8926460724378f0dce82e4e8102f22ab6c69/merged
overlay         149G   18G  125G  13% /var/lib/docker/overlay2/29eb06d57ea40788f5d6e5ae816b02ea28df85a05f71be57cf205e6480e47e97/merged
shm              64M     0   64M   0% /var/lib/docker/containers/69194c27733bf2ada4bd45ec3e1fce8602e7bd72d6b997ccc3f60d1ab1dd634b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e09ffabe6d06ec573c8bb65ef49b7448b95facd44577305b727cc1034796ff05/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7569665f1a65f6a34085982425aaacab55d754ca9df449a0d5dfa42ef23b5cd6/mounts/shm
`
- What is the current container status (`dps.sh`)?
`========| System |========
    Date:  Wed 25 Sep 2019 10:39:48 AM UTC
  Uptime:  10:39:48 up 28 min,  1 user,  load average: 11.46, 9.99, 7.60

NAME                  STATUS                       PORTS
adbhoney              Up 27 seconds                      0.0.0.0:5555->5555/tcp
ciscoasa              Up 31 seconds
conpot_guardian_ast   Up 29 seconds                      0.0.0.0:10001->10001/tcp
conpot_iec104         Up 26 seconds                      0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 27 seconds                      0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 26 seconds                      0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 27 seconds                      0.0.0.0:22-23->22-23/tcp
cyberchef             Up 27 seconds (health: starting)   127.0.0.1:64299->8000/tcp
dionaea               Up 31 seconds
elasticpot            Up 28 seconds                      0.0.0.0:9200->9200/tcp
elasticsearch         Up 30 seconds (healthy)            127.0.0.1:64298->9200/tcp
ewsposter             Up 27 seconds
heralding             Up 25 seconds                      0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up 31 seconds
mailoney              Up 28 seconds                      0.0.0.0:25->25/tcp
medpot                Up 28 seconds                      0.0.0.0:2575->2575/tcp
nginx                 Up 31 seconds
p0f                   Up 30 seconds
rdpy                  Up 26 seconds                      0.0.0.0:3389->3389/tcp
spiderfoot            Up 27 seconds (health: starting)   127.0.0.1:64303->8080/tcp
suricata              Up 31 seconds
tanner                Up 18 seconds
tanner_api            Up 20 seconds
tanner_phpox          Up 28 seconds
tanner_redis          Up 27 seconds                      6379/tcp
tanner_web            Up 20 seconds
head                  DOWN
kibana                DOWN
logstash              DOWN
snare                 DOWN
`
- What is the status of the T-Pot service (`systemctl status tpot`)?
`systemctl status tpot
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-09-25 10:40:10 UTC; 8s ago
  Process: 32462 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 32488 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 32556 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 1868 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 1871 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 1889 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 1908 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 1925 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 1952 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 1958 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 1964 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 1970 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 2038 (docker-compose)
    Tasks: 43 (limit: 4915)
   Memory: 52.8M
   CGroup: /system.slice/tpot.service
           └─2038 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating elasticpot          ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating adbhoney            ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating mailoney            ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating p0f                 ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating rdpy                ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating conpot_iec104       ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating spiderfoot          ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating heralding           ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating conpot_guardian_ast ...
Sep 25 10:40:14 explicitfield docker-compose[2038]: Creating medpot              ...
`
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
`netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          16191      746/python3
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          17583      762/sshd
tcp        0      0 127.0.0.1:64296         0.0.0.0:*               LISTEN      0          809313     6987/docker-proxy
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      111        16725      784/redis-server 12
tcp        0      0 127.0.0.1:64302         0.0.0.0:*               LISTEN      0          811021     7078/docker-proxy
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          18562      791/nginx: master p
tcp6       0      0 :::64294                :::*                    LISTEN      0          13034      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          17585      762/sshd
tcp6       0      0 :::80                   :::*                    LISTEN      0          18563      791/nginx: master p
udp        0      0 192.168.224.1:123       0.0.0.0:*                           107        813946     760/ntpd
udp        0      0 192.168.100.34:123      0.0.0.0:*                           0          16601      760/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          16599      760/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          16595      760/ntpd
udp6       0      0 :::123                  :::*                                0          16592      760/ntpd`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

 docker logs kibana
Error: No such container: kibana

**Comment by Oogy** [comment]
I'm having some trouble viewing your screenshot. I'm curious how much memory you are working with, anytime I've been unable to start the ELK containers it was due to insufficient memory. Could you try tailing the logs by providing the container ID corresponding to Head, Logstash, and Kibana found in `docker ps` rather than the name?

**Comment by tXambe** [comment]
In the VM I got 8 GB of ram , but the problem is the consumption of cpu, that is 98%

**Comment by t3chn0m4g3** [comment]
Usually this is a sign of ElasticSearch trying to repair a corrupt index. Run a docker logs elasticsearch and check the errors. Does head show any signs of corrupt indexes?
In a VM environment corrupt indexes usually occur if the system host or guest is not cleanly shut down.

**Comment by tXambe** [comment]
Hello,
I don't see any error when execute docker logs elasticsearch

`docker logs elasticsearch
[2019-09-25T13:53:40,324][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] using [1] data paths, mounts [[/data (/dev/sda2)]], net usable_space [124.2gb], net total_space [148.9gb], types [ext4]
[2019-09-25T13:53:40,327][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] heap size [1.9gb], compressed ordinary object pointers [true]
[2019-09-25T13:53:40,558][INFO ][o.e.n.Node               ] [tpotcluster-node-01] node name [tpotcluster-node-01], node ID [RhfZndTyRhec8Gsb5MOIxw]
[2019-09-25T13:53:40,560][INFO ][o.e.n.Node               ] [tpotcluster-node-01] version[6.8.2], pid[1], build[default/tar/b506955/2019-07-24T15:24:41.545295Z], OS[Linux/5.2.0-2-amd64/amd64], JVM[IcedTea/OpenJDK 64-Bit Server VM/1.8.0_212/25.212-b04]
[2019-09-25T13:53:40,560][INFO ][o.e.n.Node               ] [tpotcluster-node-01] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Xms2024m, -Xmx2024m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
`

**Comment by t3chn0m4g3** [comment]
What about head?

**Comment by Oogy** [comment]
I'm unable to replicate this, the install works just fine so this is likely an issue with your system/configuration and not T-Pot.

**Comment by tXambe** [comment]
Hello,
The instalation the installation was done with the ISO image and and I didn't have any errors during the installation.

From what I have read in this forum I am not the first to happen this incident.

Thanks and a greeting

**Comment by t3chn0m4g3** [comment]
Please post Head screenshot.

**Comment by tXambe** [comment]
![Head](https://user-images.githubusercontent.com/12039753/65762868-90b53880-e111-11e9-8786-9504411fbaf8.JPG)

**Comment by t3chn0m4g3** [comment]
Head screenshot of the web application.

**Comment by t3chn0m4g3** [comment]
Unable to reproduce this, closing this for now.

**Comment by tXambe** [comment]
Hello,
And reinstall docker container elasticsearch, docker container restart elasticsearch ?

A greeting and thanks
