### ISSUE TITLE
TPOT Filtering

### ISSUE THREAD

**Issue by ChristopherClayden** [dtag-dev-sec/tpotce#458]
Good day everyone,

I believe this is more of a question rather than an issue.  Running 19.03 on the latest Debian SID.

I have two requirements.  First requirement is to filter out management access on ports 64294,64295 and 64297 and the second requirement is to filter out specific access to some of the POTS on their associated ports that we don’t want to expose.  

I am trying to use /opt/tpot/bin/rules.sh for persistence, I have the following:

#filter for mgmt. access
iptables -w -A INPUT -i ens192 -s 1.1.1.1/32 -p tcp -m multiport --dports 64297,64295,64294 -j ACCEPT
iptables -w -A INPUT -i ens192 -s 0.0.0.0/0 -p tcp -m multiport --dports 64297,64295,64294 -j DROP
#filters to limit pot exposure
iptables -w -A INPUT -i ens192 -s 0.0.0.0/0 -p tcp -m multiport --dports 21,22,23,25,110,445 -j ACCEPT
iptables -w -A INPUT -i ens192 -s 0.0.0.0/0 -j DROP

Filtering out management access is working.  For the example rules to limit out pot exposure is not working.  Iptables-legacy is superseding this.  Is rules.sh the best place/approach for the second requirement?

Cheers-

**Comment by t3chn0m4g3** [comment]
The `rules.sh` is not the right place to do so. Please search existing issues for `tpot.yml` and `docker-compose`, also the Wiki sheds some light on how to adjust T-Pot's docker-compose config for your needs.
At best you then modify NGINX docker service to only listen on 127.0.0.1. To modify Cockpit (64294) please check their [project](https://cockpit-project.org/) guides.
