### ISSUE TITLE
disconnections   T-Pot18.11

### ISSUE THREAD

**Issue by Mr-later** [dtag-dev-sec/tpotce#459]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux relaxedpurple 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- What T-Pot version are you currently using?
T-Pot18.11
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
x86_64
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No such file or directory
- How long has your installation been running?

- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/24469848/65741563-0542a400-e11f-11e9-859d-229366482025.png)
![image](https://user-images.githubusercontent.com/24469848/65741583-17244700-e11f-11e9-902d-85ab358e976c.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/24469848/65741596-286d5380-e11f-11e9-9c6d-13db66383888.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/24469848/65741612-3e7b1400-e11f-11e9-8816-f66c7d7ffba3.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/24469848/65741622-50f54d80-e11f-11e9-94c2-803ef5f5143e.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/24469848/65741665-7c783800-e11f-11e9-83d5-6d72a35564de.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

Continuous restart of containers
![image](https://user-images.githubusercontent.com/24469848/65741686-93b72580-e11f-11e9-9c84-8501145f92d2.png)

I can visit this address（https://ip:64297） occasionally.
But neither my tsec nor my system users can log in. My new users can. I don't know why.
![image](https://user-images.githubusercontent.com/24469848/65741951-a0884900-e120-11e9-9a4f-ec657d447099.png)

![image](https://user-images.githubusercontent.com/24469848/65741994-e218f400-e120-11e9-8667-9655b29b37f8.png)
nginx  also  disconnect
  

I don't know if I have made myself clear. Can you help me?

**Comment by Mr-later** [comment]
Can I  install  T-Pot 19.03  with ubuntu?

**Comment by t3chn0m4g3** [comment]
Sorry, No. You have to use the ISO or install on top of Debian Buster.
18.11 is not supported any longer.

**Comment by Mr-later** [comment]
thank you ,i will try to  install on top of Debian Buster.

**Comment by notjac** [comment]
how do i install docker on tpot ？my tpot is a iso file, but it cant "systemctl start tpot" ,said failed to start to tpot.service: unit docker.service  not found

**Comment by t3chn0m4g3** [comment]
@notjac Please use the current [release](https://github.com/telekom-security/tpotce/releases/tag/20.06.1). 18.x and 19.x are not supported anymore.
