### ISSUE TITLE
Terraform Deployment Failed

### ISSUE THREAD

**Issue by thearchitectofficial** [dtag-dev-sec/tpotce#460]
Further to #455 
I have been able to deploy using terraform however now when I connect to <ip>:64294 for webUI it asks for an ID pass but doesnt accept what I setup in tpot.conf  nor does it initiate Kibana service.

Also none of the scripts like dps.sh are found or work upon ssh access.
The error shown is "unable to resolve hostname or service unknown"

Look forward to inputs!

# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Debian Stretch
- What T-Pot version are you currently using? 
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
AWS
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
N/A
- Did you install upgrades, packages or use the update script?
N/A
- Did you modify any scripts or configs? If yes, please attach the changes.
N/A
- Please provide a screenshot of `glances` and `htop`.
N/A
 How much free disk space is available (`df -h`)?
N/A
- What is the current container status (`dps.sh`)?
N/A
- What is the status of the T-Pot service (`systemctl status tpot`)?
N/A
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
N/A
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
N/A

**Comment by t3chn0m4g3** [comment]
Please do not open multiple tickets. Thanks.

Referring this to #455
