### ISSUE TITLE
How to import Tpot data into Splunk

### ISSUE THREAD

**Issue by janiceb75** [dtag-dev-sec/tpotce#462]
I am having a problem sending Tpot data into splunk.   Upon doing so, I get this output, "--splunk-cooked-mode-v3--\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00".   Has anyone been successful in getting the data to come over via Syslog?   Thanks

**Comment by iukea1** [comment]
![](https://i.imgur.com/UhKmoes.jpg)

**Comment by t3chn0m4g3** [comment]
@janiceb75 Please post your `logstash.conf` and describe your setup and what you are trying to accomplish in more detail.

**Comment by janiceb75** [comment]
> @janiceb75 Please post your `logstash.conf` and describe your setup and what you are trying to accomplish in more detail.


Sorry for the late reply.   Here is more information:

1.  I installed a splunk forwarder on the system that I have T-pot installed on.  
2.  I configured the splunk forwarder to monitor, the directories of "/data" as well as "/data/cowrie/log" 
[logstash.txt](https://github.com/dtag-dev-sec/tpotce/files/3740461/logstash.txt)

3. I tested the connection by generating some SSH activity in T-pot. 
4.  The data that I received came over and unreadable format and mentioned "splunk uncooked data"  See attachment 1.
5. I have also included the logstash.conf file from tpot.

Please let me know if you have any additional questions.  Thanks

**Comment by janiceb75** [comment]
[logstash.txt](https://github.com/dtag-dev-sec/tpotce/files/3740467/logstash.txt)

**Comment by janiceb75** [comment]
![Splunk Output Results](https://user-images.githubusercontent.com/56306096/67030969-94b7f300-f0de-11e9-96d5-96fcb5eb92a5.PNG)
