### ISSUE TITLE
how it works

### ISSUE THREAD

**Issue by Mr-later** [dtag-dev-sec/tpotce#468]
# Issues
https://IP:64297/kibana/app/kibana
I want to know how it works
I only find these, and forward them through nginx.
![1](https://user-images.githubusercontent.com/24469848/66985140-bc16bc00-f0ee-11e9-86c7-3e0ef618e82d.png)
How the containers work together and how requests are forwarded
How to develop it
Do you have any related documents？
thank you !

**Comment by t3chn0m4g3** [comment]
The best way is to start with the README. Everything is available as open source in the repo or in upstream repos. If you like a full understanding please take the time and read up on all the involved scripts and config, deep dive into documentations of Docker, ELK stack, Reverse Proxying, NGINX and the involved tools.
