### ISSUE TITLE
> @janiceb75 Please post your `logstash.conf` and describe your setup and what you are trying to accomplish in more detail.

### ISSUE THREAD

**Issue by janiceb75** [dtag-dev-sec/tpotce#469]
> @janiceb75 Please post your `logstash.conf` and describe your setup and what you are trying to accomplish in more detail.

Sorry for the late reply.   Here is more information:

1.  I installed a splunk forwarder on the system that I have T-pot installed on.  
2.  I configured the splunk forwarder to monitor, the directories of "/data" as well as "/data/cowrie/log" 
[logstash.txt](https://github.com/dtag-dev-sec/tpotce/files/3740461/logstash.txt)

3. I tested the connection by generating some SSH activity in T-pot. 
4.  The data that I received came over and unreadable format and mentioned "splunk uncooked data"  See attachment 1.
5. I have also included the logstash.conf file from tpot.

Please let me know if you have any additional questions.  Thanks

_Originally posted by @janiceb75 in https://github.com/dtag-dev-sec/tpotce/issues/462#issuecomment-543269601_

**Comment by t3chn0m4g3** [comment]
You can start [here](https://medium.com/ibm-garage/how-to-forward-events-from-logstash-to-splunk-4f2608041feb) and adjust the `logstash.conf` by extracting it from a running container and mount it as a volume. An example for a volume can be found in our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-logstash.conf).
