### ISSUE TITLE
dionaea

### ISSUE THREAD

**Issue by luck00** [dtag-dev-sec/tpotce#47]
Hello,

It is possible to change  dionaea ftp fingerprint? Because nmap show that is a honeypot. I could modify the internal config file of dionaea but if I restart the docker the configuration is returned to default.

Thank you.

**Comment by t3chn0m4g3** [comment]
What part of the dionaea config would you like to change to mislead the nmap [fingerprinting](https://nmap.org/book/osdetect-fingerprint-format.html)?

**Comment by luck00** [comment]
I want to change the files ftp.py, smbfields.py and mssql.py

**Comment by t3chn0m4g3** [comment]
With [T-Pot 16.10](https://github.com/dtag-dev-sec/elk/tree/16.10) the latest [dionaea](https://github.com/DinoTools/dionaea/) will be included. Have you checked with @phibo from [Dinotools](https://github.com/DinoTools/dionaea/) if a change in the original source would be beneficial to dionaea on a larger scale?

You can always map your own files into a docker container altering the service configuration file in `/etc/init/dionaea.conf` with a new volume option `-v /opt/my/host/file/ftp.py:/opt/my/container/file/ftp.py`

**Comment by luck00** [comment]
I am using right now version 16.3. If I search for dionaea file ftp.py I only find a path like this /var/lib/docker/aufs/diff/e3464e801f6c1795fce9d05100a3362197f211b90bbbaaaabffe9248de913822/usr/lib/dionaea/python/dionaea/ftp.py . there is somewhere a location of the default dionaea container image?

**Comment by t3chn0m4g3** [comment]
The file you are looking for resides within a docker container. Please check the [docker documentation](https://docs.docker.com/engine/understanding-docker/) to get an understanding of docker's architecture.
