### ISSUE TITLE
NO PUEDO INGRESAR AL KIBANA https://<mi-ip>:64297

### ISSUE THREAD

**Issue by jrsanchezsilva** [dtag-dev-sec/tpotce#474]
Buenas noches, eh instalado siete veces en una maquina virtual (virtualbox, vmware) y no puedo ingresar al kibana(https://mi-ip:64297) me refiero que no me muestra el irterfaz de kibana, pero al ver la consola esta levantado todos los servicios, y todo mi firewall esta deshabilitado, por favor su apoyo si hay una configuración para poder ingresar al kibana...solo puedo ingresar https://mi-ip:64294 (web administrador), en mi instalación utilizo NextGen.

Muchas gracias, espero su apoyo.

![Captura de pantalla de 2019-10-23 20-18-43](https://user-images.githubusercontent.com/51901933/67446364-ff34cb80-f5d5-11e9-8c92-a116b1a84132.png)

![Captura de pantalla de 2019-10-23 19-57-33](https://user-images.githubusercontent.com/51901933/67446372-06f47000-f5d6-11e9-9142-93c8ae167999.png)

![Captura de pantalla de 2019-10-23 19-25-16](https://user-images.githubusercontent.com/51901933/67446381-0bb92400-f5d6-11e9-8555-46d5dc224cc2.png)

**Comment by jrsanchezsilva** [comment]
Good evening, eh installed seven times in a virtual machine (virtualbox, vmware) and I can not enter the kibana (https: // mi-ip: 64297) I mean that it does not show me the kibana irterface, but seeing the console is All services have been lifted, and all my firewall is disabled, please support if there is a configuration to enter the kibana ... I can only enter https: // mi-ip: 64294 (web administrator), in my installation I use NextGen .

**Comment by jrsanchezsilva** [comment]
Hello good night, thanks for replying, the browser I use if TLS 1.3 is enabled. (Hola buenas noches gracias por responder, el navegador que uso si esta habilitado el TLS 1.3.)

![image](https://user-images.githubusercontent.com/51901933/67612709-78fdbe00-f76a-11e9-8361-26aaebf235a3.png)

**Comment by t3chn0m4g3** [comment]
Unless you provide some info that helps me in debugging the issue (the stuff we are asking when you open an issue) I cannot help you. Thanks.
