### ISSUE TITLE
📢 Problems with swap filling up

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#476]
I was noticing the other day that swap space was filling up for no reason. You can check with: 
```
# for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r | less
```
The responsible process (`pmproxy`) is associated with the package `pcp` and been taken care of in the installer and update scripts (https://github.com/dtag-dev-sec/tpotce/commit/7d56264a8d8d1cd78c302c1b1b9893d8f928b4c4).

**Since enabling PCP was only introduced a couple of weeks ago only new installations should be affected.**

You are affected of this issue if T-Pot becomes unresponsive after a while. If that is the case please reboot T-Pot and run `/opt/tpot/update.sh`. The responsible packages `cockpit-pcp` and `pcp` will be uninstalled and blocked for future installations.

On the console you should see some output, that the mentioned packages were removed, however you can check that manually as well:
```
# dpkg-query -s cockpit-pcp pcp
dpkg-query: package 'cockpit-pcp' is not installed and no information is available

dpkg-query: package 'pcp' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
```

Afterwards please reboot.

**Comment by iukea1** [comment]
Oooffff good catch
