### ISSUE TITLE
Inaccurate geolocation data - where to update?

### ISSUE THREAD

**Issue by amishrabbit** [dtag-dev-sec/tpotce#481]
# Issues
I am observing trend data collected, specifically, by Rdpy, and noticed that there was a large volume of attacks the origin of which geolocate to the United Kingdom, which I thought was unusual. I looked up the source IP (https://community.riskiq.com/search/5.188.112.77) and it appears to be owned by an ISP based in St. Petersburg, Russia, and not in the UK.

I don't know what geolocation database this is using, but it may need to be updated. Does it use the free MaxMind GeoIP database? If so, where do I put an updated version of that database so the Kibana reports correctly reflect the country-of-origin? I didn't see instructions in the wiki or in the readme file about where that is. If it is MaxMind, please also specify which GeoIP database(s) they provide that the tpot uses.

Thank you!

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid

$ uname -a
Linux xxxxxxx 5.3.0-1-amd64 #1 SMP Debian 5.3.7-1 (2019-10-19) x86_64 GNU/Linux

- What T-Pot version are you currently using?
19.03.1

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VMware vSphere VM

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
n/a

- How long has your installation been running?
48 hours

- Did you install upgrades, packages or use the update script?
no

- Did you modify any scripts or configs? If yes, please attach the changes.
n/a

- Please provide a screenshot of `glances` and `htop`.
![glances](https://user-images.githubusercontent.com/2653726/68224865-aa695b80-ffac-11e9-9d6a-f38fe304cc14.png)
![htop](https://user-images.githubusercontent.com/2653726/68224871-af2e0f80-ffac-11e9-9bf2-9d2e626dc29c.png)

- How much free disk space is available (`df -h`)?
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             12G     0   12G   0% /dev
tmpfs           2.4G  222M  2.2G  10% /run
/dev/sda2       496G   19G  452G   5% /
tmpfs            12G     0   12G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            12G     0   12G   0% /sys/fs/cgroup
tmpfs           2.4G     0  2.4G   0% /run/user/1000

- What is the current container status (`dps.sh`)?
I could not find this file. Please provide the full path to it in future versions of this support template.

- What is the status of the T-Pot service (`systemctl status tpot`)?
]$ systemctl status tpot
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-11-05 07:57:52 UTC; 8h ago
  Process: 960 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 982 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 2391 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 2394 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 2397 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 2424 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 2448 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 2472 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 2500 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 2506 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 2512 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 2518 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 2592 (docker-compose)
    Tasks: 32 (limit: 4915)
   Memory: 533.8M
   CGroup: /system.slice/tpot.service
           └─2592 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
]$ sudo netstat -tulpen
sudo: unable to resolve host randomanorak: Name or service not known
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          17580      686/python3
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          18454      708/sshd
tcp6       0      0 :::64294                :::*                    LISTEN      0          12938      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          18456      708/sshd
udp        0      0 192.168.0.21:123        0.0.0.0:*                           0          17440      703/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          17438      703/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          17434      703/ntpd
udp6       0      0 :::123                  :::*                                0          17431      703/ntpd

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
For license reasons we are using the ones bundled with [logstash](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/elk/logstash/dist/logstash.conf#L387-L392). While building the docker image you can replace them of course with your own.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
