### ISSUE TITLE
Clean.sh PreStart in service is hanging after update.

### ISSUE THREAD

**Issue by Nicknack1234** [dtag-dev-sec/tpotce#482]
Was flying along perfectly for quite a while. Decided to update using the script yesterday. Update ran without any errors and everything came back after a reboot. Ran for about 24 hours and has now died. All containers are now offline, tpot Service is stuck on Starting. 

Manually stopping and starting service doesn't help, Hangs on start command.
Re-Running the Updater script doesn't help.

I noticed the service status seems to indicate its a issue after updateip.sh so I manually ran through the PreStart commands interactively as root. It seems that the clean.sh command is never finishing, It will dump a whole bunch of files from dionaea but then just sits there doing nothing:

![image](https://user-images.githubusercontent.com/11343300/68451410-a007c580-0229-11ea-9930-061824695c8e.png)

Process doesn't seem hung.

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- _What version of the OS are you currently using `lsb_release -a` and `uname -a`?_

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid

Linux administrativebaseball 5.3.0-1-amd64 #1 SMP Debian 5.3.7-1 (2019-10-19) x86_64 GNU/Linux

- _What T-Pot version are you currently using?_
Latest Version, Ran updater script as soon as issue occured

- _What edition (Standard, Nextgen, etc.) of T-Pot are you running?_
Standard

- _What architecture are you running on (i.e. hardware, cloud, VM, etc.)?_
VM in Vmware cluster

- _Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`._
None

- _How long has your installation been running?_
On and off for about 6 months

- _Did you install upgrades, packages or use the update script?_
Yes - Updated tpot using the script yesterday, Ran fine overnight but crashed today

- _Did you modify any scripts or configs? If yes, please attach the changes._
Changed tpot config, removed the localhost only binding on the elasticsearch container so it could be accessed from Grafana, THis was working well for 6 months, Have since undone changes and updater script also wiped the changes. Still wont startup with changes reverted.

- _Please provide a screenshot of `glances` and `htop`._
![image](https://user-images.githubusercontent.com/11343300/68450951-c6c4fc80-0227-11ea-87a6-c6ee0a74c062.png)

![image](https://user-images.githubusercontent.com/11343300/68450971-d7757280-0227-11ea-8ace-3e41c97c2c36.png)

- _How much free disk space is available (`df -h`)?_
Free: 54% 61G

- _What is the current container status (`dps.sh`)?_
All Down

- _What is the status of the T-Pot service (`systemctl status tpot`)?_
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Fri 2019-11-08 04:27:00 UTC; 22min ago
  Process: 889 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
Cntrl PID: 921 (clean.sh)
    Tasks: 4 (limit: 19153)
   Memory: 3.8G

- _What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`_
![image](https://user-images.githubusercontent.com/11343300/68451065-494dbc00-0228-11ea-82a0-ea653b5b819d.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
@Nicknack1234 Thank you.

The `clean.sh` script runs without issues here (also from latest master). Since it stops at Dionaea on your end it might be possible that too many files are present for logrotate / clean to finish successfully since there is currently running a massive campain against tcp/1433. However we had similar issues in the past and adressed this a while ago by setting the service timeout to `infinity`. 

You can set the retention from archive to clean by modifying `/etc/systemd/system/tpot.service` as follow:
```
.
.
.
ExecStartPre=-/bin/bash -c '/opt/tpot/bin/clean.sh off'
.
.
.
```

**Comment by Nicknack1234** [comment]
@t3chn0m4g3  Thanks for the response. I would say that is the problem. If I get a chance I might play with putting some error handling around it so in the event it does get overloaded it can self correct and stop the hanging. I can see the service timeout is set to infinity.
