### ISSUE TITLE
Tpot service fails and all docker containers exit after about 12 hours

### ISSUE THREAD

**Issue by CreeperFace00** [dtag-dev-sec/tpotce#483]
# Issues
The tpot service seems to fail after about 12 hours. I can run `systemctl start tpot` and the service and all docker containers come up just fine, but it always fails again after 12 hours, along with all docker containers.  

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information 

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
```
[root@singleshirt:~]# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid


[root@singleshirt:~]# uname -a
Linux singleshirt 5.3.0-1-amd64 #1 SMP Debian 5.3.7-1 (2019-10-19) x86_64 GNU/Linux
```
- What T-Pot version are you currently using?
19.03

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard (Installed using the installer script)

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Hyper-V on Windows Server 2019 Datacenter

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Install was perfect

- How long has your installation been running?
5 days

- Did you install upgrades, packages or use the update script?
Before I ran the install script I updated all packages, and installed sudo.

- Did you modify any scripts or configs? If yes, please attach the changes.
Everything is stock

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/16279973/68536640-cfdaca00-030a-11ea-819f-dc7ca1b788ad.png)
![image](https://user-images.githubusercontent.com/16279973/68536646-eed95c00-030a-11ea-9b28-75d530bae150.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/16279973/68536661-09133a00-030b-11ea-80fb-3021d8c37a82.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/16279973/68536664-23e5ae80-030b-11ea-9bd8-6a561cc9100f.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/16279973/68536669-44156d80-030b-11ea-8068-97ec06c08588.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/16279973/68536707-f6e5cb80-030b-11ea-9771-f7d32e7d073f.png)

**Comment by t3chn0m4g3** [comment]
I have never tested T-Pot on Hyper-V. Anyone else know if this is usually running fine?
Does the issue still persist?

**Comment by CreeperFace00** [comment]
I've created a workaround using cron that reboots the VM every 10 hours, that completely solved the issue. When I was running T-Pot on physical hardware I noticed it would reboot itself every so often, however this never happened on Hyper-V. I'm not entirely sure how its setup, but Hyper-V might not like the way auto reboots are being handled, if that is actually how its supposed to work.

**Comment by t3chn0m4g3** [comment]
At this point there is not much I can do, since I have no means to test this with. For now I will close this, however if you want to dig deeper into this, leave a comment for reopening or start a PR.

Thanks.
