### ISSUE TITLE
README.md Elasticpot wrong URL

### ISSUE THREAD

**Issue by MatsK** [dtag-dev-sec/tpotce#485]
# Issues

Row 145 and 529 in README.md is currently pointing to:
`    * [elasticpot](https://github.com/schmalle/ElasticPot),`
Should be changed to:
`    * [elasticpot](https://github.com/schmalle/ElasticpotPY),`

All other references to ElasticPot has been changed.

**Comment by t3chn0m4g3** [comment]
@MatsK Thanks!
