### ISSUE TITLE
suricata.yaml and etpro

### ISSUE THREAD

**Issue by hadojae** [dtag-dev-sec/tpotce#487]
I added an oinkcode into the tpot.yaml and watched that the update script pulled the rules just fine, but the suricata.yaml doesn't appear to get updated to reflect the new rules files, so it seems that the ETPRO rules are never loaded at runtime. *ETPRO rules don't start with "emerging-".

![Screenshot from 2019-11-20 16-22-15](https://user-images.githubusercontent.com/5302588/69287235-c414c080-0bb2-11ea-9168-04d1b1da1d84.png)

I noticed that the update script at /opt/tpot/docker/suricata/dist/update.sh enables all the rules. This might be problematic if you're doing this on the emerging-deleted.rules (ET OPEN) and the deleted.rules (ETPRO) as these are rules that are no longer intended to run. The disabled rules within the other rules files should be fine, we often disable these rules for performance reasons.

I would also like Suricata to write pcap to disk which can be configured in suricata.yaml. I'm not much of a docker guy, is there an obvious way to configure this that I'm missing or should I just do a rolling tcpdump on eth0 or something?

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	unstable
Codename:	sid

5.3.0-2-amd64 #1 SMP Debian 5.3.9-3 (2019-11-19) x86_64 GNU/Linux

- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Cloud
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Nope
- How long has your installation been running?
Couple hours
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
/opt/tpot/etc/tpot.yaml - added oinkcode

**Comment by t3chn0m4g3** [comment]
Personally I do not have access to ET Pro rulesets, so I cannot test. Please provide me with more info.

I have never had any issues with enabling all the rules, since we are running Suricata only in IDS mode to enrich honeypot events with more insight.

If you want to capture PCAP files you can always insert your own config into the container via volumes. Check out our Wiki for an example how to do that.

**Comment by t3chn0m4g3** [comment]
Seem to be resolved.

**Comment by ArslanArshad022** [comment]
@t3chn0m4g3 can you please guide how we can generate pcap file via volumes?
Is another tool need to be integrate with it or there is some other way?
