### ISSUE TITLE
Docker images does not start

### ISSUE THREAD

**Issue by buddybn** [dtag-dev-sec/tpotce#489]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
**$ lsb_release -a**
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
**$ uname -a**
Linux splendidchimpanzee 5.3.0-2-amd64 #1 SMP Debian 5.3.9-3 (2019-11-19) x86_64 GNU/Linux

- What T-Pot version are you currently using?
19.03.1

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nextgen

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No

- How long has your installation been running?
5 Months

- Did you install upgrades, packages or use the update script?
Yes all the time I'm using the update script

- Did you modify any scripts or configs? If yes, please attach the changes.
No, except I've added a cron job to delete the older indicies because curator job with 90 days is not enough

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/15018973/69540788-dbbfc080-0f87-11ea-9550-2b0ee0921acf.png)
![image](https://user-images.githubusercontent.com/15018973/69540826-f72acb80-0f87-11ea-9d5c-adda11dab4d0.png)

- How much free disk space is available (`df -h`)?
**# df -h**
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           797M   41M  756M   6% /run
/dev/sda2       189G   52G  128G  29% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           797M     0  797M   0% /run/user/1000
- What is the current container status (`dps.sh`)?
**# /opt/tpot/bin/dps.sh**
========| System |========
    Date:  Mon 25 Nov 2019 12:35:02 PM UTC
  Uptime:  12:35:02 up 42 min,  0 users,  load average: 0.39, 0.49, 0.46

NAME                  STATUS                       PORTS
adbhoney              DOWN                  
ciscoasa              DOWN                  
conpot_guardian_ast   DOWN                  
conpot_iec104         DOWN                  
conpot_ipmi           DOWN                  
conpot_kamstrup_382   DOWN                  
cowrie                DOWN                  
cyberchef             DOWN                  
dionaea               DOWN                  
elasticsearch         DOWN                  
ewsposter             DOWN                  
fatt                  DOWN                  
glutton               DOWN                  
head                  DOWN                  
heralding             DOWN                  
honeypy               DOWN                  
kibana                DOWN                  
logstash              DOWN                  
mailoney              DOWN                  
medpot                DOWN                  
nginx                 DOWN                  
p0f                   DOWN                  
rdpy                  DOWN                  
snare                 DOWN                  
spiderfoot            DOWN                  
suricata              DOWN                  
tanner                DOWN                  
tanner_api            DOWN                  
tanner_phpox          DOWN                  
tanner_redis          DOWN                  
tanner_web            DOWN  
- What is the status of the T-Pot service (`systemctl status tpot`)?
**# systemctl status tpot**
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-11-25 12:35:58 UTC; 1s ago
  Process: 92002 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 92022 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 92067 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=1/FAILURE)
  Process: 92071 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=1/FAILURE)
  Process: 92075 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 92087 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 92099 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 92111 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 92126 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 92132 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 92138 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 92144 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
  Process: 92217 ExecStart=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color (code=exited, status=1/FAILURE)
  Process: 92221 ExecStopPost=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset (code=exited, status=0/SUCCESS)
 Main PID: 92217 (code=exited, status=1/FAILURE)

Nov 25 12:35:58 splendidchimpanzee systemd[1]: tpot.service: Failed with result 'exit-code'.

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
**# netstat -tulpen**
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          17198      689/python3         
tcp        0      0 127.0.0.1:41221         0.0.0.0:*               LISTEN      1000       48722      5501/cockpit-bridge 
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16452      707/sshd            
tcp        0      0 127.0.0.1:43051         0.0.0.0:*               LISTEN      0          50182      5640/cockpit-bridge 
tcp6       0      0 :::64294                :::*                    LISTEN      0          13728      1/init              
tcp6       0      0 :::64295                :::*                    LISTEN      0          16463      707/sshd            
udp        0      0 195.26.136.195:123      0.0.0.0:*                           0          16350      705/ntpd            
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          16348      705/ntpd            
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          16344      705/ntpd            
udp6       0      0 :::123                  :::*                                0          16341      705/ntpd   

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by buddybn** [comment]
Now even the second honeypot that i have is also broken :(

**Comment by t3chn0m4g3** [comment]
Probably too many events within `/data/dionaea`. Please run `clean.sh` which will give you a clean slate and keep ES indices intact.

**Comment by buddybn** [comment]
**It did't help.** This is from the broken one:
34G     elk
664K    spiderfoot
40K     dionaea
32K     nginx
24K     cowrie
16K     honeytrap
16K     ews
12K     tanner
12K     adbhoney
8.0K    suricata
8.0K    rdpy
8.0K    p0f
8.0K    medpot
8.0K    mailoney
8.0K    honeypy
8.0K    heralding
8.0K    glutton
8.0K    fatt
8.0K    emobility
8.0K    elasticpot
8.0K    conpot
8.0K    ciscoasa

**And i managed to get it back to life the second honeypot by doing system stop and start tpot.** This is from the honeypot i managed to get it back to life:
25G     elk
3.8G    dionaea
2.6G    cowrie
397M    p0f
375M    suricata
42M     spiderfoot
25M     heralding
16M     fatt
16M     adbhoney
1000K   honeypy
928K    glutton
692K    conpot
368K    mailoney
256K    nginx
244K    tanner
196K    rdpy
120K    ciscoasa
16K     honeytrap
16K     ews
8.0K    medpot
8.0K    emobility
8.0K    elasticpot

**Comment by buddybn** [comment]
**# systemctl status tpot**
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-11-26 11:46:11 UTC; 4s ago
  Process: 311447 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 311467 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 311512 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=1/FAILURE)
  Process: 311518 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=1/FAILURE)
  Process: 311522 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 311534 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 311546 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 311558 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 311573 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 311579 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 311585 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 311591 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
  Process: 311664 ExecStart=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color (code=exited, status=1/FAILURE)
  Process: 311668 ExecStopPost=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset (code=exited, status=0/SUCCESS)
 Main PID: 311664 (code=exited, status=1/FAILURE)

Nov 26 11:46:11 splendidchimpanzee systemd[1]: tpot.service: Failed with result 'exit-code'.

**Comment by t3chn0m4g3** [comment]
Need to dig deeper.

Run
```
systemctl stop tpot
/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set
/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up
```

Wait for errors and then run ...
```
/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v
/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset
```

**Comment by buddybn** [comment]
Ok I found the problem. When I was looking at the result from **systemctl status tpot** i saw at one line it said:
**docker-compose[230262]: Duplicate mount points: [/data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg:rw, /data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg:rw, /data/ews/conf/ews.cfg:/o>**
After this I checked the tpot.yml file and behold there a couple of lines plus where they shoudn't be   
 ( luckily that i had the second honeypot to compare :) ) :
**# Ewsposter service
  ewsposter:
    container_name: ewsposter
    restart: always
    networks:
     - ewsposter_local
    environment:
     - EWS_HPFEEDS_ENABLE=false
     - EWS_HPFEEDS_HOST=host
     - EWS_HPFEEDS_PORT=port
     - EWS_HPFEEDS_CHANNELS=channels
     - EWS_HPFEEDS_IDENT=user
     - EWS_HPFEEDS_SECRET=secret
     - EWS_HPFEEDS_TLSCERT=false
     - EWS_HPFEEDS_FORMAT=json
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    image: "dtagdevsec/ewsposter:1903"
    volumes:
     - /data:/data
     - /data/ews/conf/ews.ip:/opt/ewsposter/ews.ip
     - /data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg
     - /data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg
     - /data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg**
So I deleted the last two lines:
**- /data/ews/conf/ews.cfg:/opt/ewsposter/ews.cfg**

**Comment by buddybn** [comment]
> Need to dig deeper.
> 
> Run
> 
> ```
> systemctl stop tpot
> /opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set
> /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up
> ```
> 
> Wait for errors and then run ...
> 
> ```
> /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v
> /opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml unset
> ```

I just read it. THANK YOU for the advice!

**Comment by t3chn0m4g3** [comment]
Thank you :bowtie:
