### ISSUE TITLE
t-pot 16.10 cannot access 127.0.0.1:8080

### ISSUE THREAD

**Issue by luck00** [dtag-dev-sec/tpotce#49]
Hello,

I install the t-pot 16.10 distribution and worked fine for a couple of days, but today I try to access kibana at 127.0.0.1:8080 and not working. Output of the status.sh seems to be OK. I restart the honeypot, I restart the services... and nothing...

Thank you.

**Comment by t3chn0m4g3** [comment]
This is a development build and I made some substantial changes which require a reinstall.

**Comment by luck00** [comment]
oky, thank you very much

**Comment by t3chn0m4g3** [comment]
Welcome 😃
