### ISSUE TITLE
Would like to use Snare/Tanner to clone my own website!

### ISSUE THREAD

**Issue by honeypuh** [dtag-dev-sec/tpotce#490]
Not an Issue more a Qurestion,
I would like to configure Snare/Tanner to use my own website.  I figured out that I have to change the last line of the snare Dockerfile(opt/tpot/docker/tanner/snare/dockerfile) and to add the homepage to files. Usually i would do it with "snare --clone <website> but how can i do it here?
Is there any doc for this? 

Best Regards 
Jannik

**Comment by iukea1** [comment]
You will have to modify the snake docker image in Tpot and then upload your image to docker hub .

The add it into your docker-compose file

**Comment by honeypuh** [comment]
Thanks @iukea1 :)

**Comment by iukea1** [comment]
@honeypuh got you fam

**Comment by honeypuh** [comment]
I have another issue @iukea1. I would like to close ports in the docker proxy but i can't find the config file. Do you have any idea?

**Comment by iukea1** [comment]
Good question.

Go back to the docker conpose file and you will see 127:0.0.0.1:port you want to close 

Delete it and recompose

**Comment by iukea1** [comment]
@honeypuh sup my bro

Good question.

Go back to the docker conpose file and you will see 127:0.0.0.1:port you want to close

Delete it and recompose

**Comment by ap0lo3p** [comment]
Hi. Regarding the problem. I modify the Dockerfile of Snare as you can see in the graph, which is located in /opt/tpot/tanner/snare. I have modified the last line to load the same page and not the random one that was set by default. I want to configure my own page in wordpress that is in one of the 10 pages by default. However, at the time of restarting the server I still see pages randomically How could I make the fixed page from the Dockerfile to modify the one I need. Thank you. Best regards.

![image](https://user-images.githubusercontent.com/60939051/74495333-95527180-4ea5-11ea-821b-92213e516310.png)

**Comment by t3chn0m4g3** [comment]
1. You have to build your own image based on the Dockerfile (`docker-compose build`)
2. Your CMD is incorrect at the end, needs to be `--page-dir 10`
3. Better way is to modify `/opt/tpot/etc/tpot.yml` with your own [command](https://docs.docker.com/compose/compose-file/compose-file-v2/#command).

**Comment by jrsanchezsilva** [comment]
BuenGood morning

As I can use only one page of the 10 test pages shown in the figure, when configuring snare Dockerfile (opt / tpot / docker / tanner / snare / dockerfile) I only want to use page ten, when restarting the server shows several times different pages, or where else you have to configure so that only one static page remains.Please support in advance thank you very much.

![image](https://user-images.githubusercontent.com/51901933/74671583-7b50b180-5179-11ea-88ed-ea9da328a887.png)

**Comment by kashmax** [comment]
Same issue,

Custom site is not working as the information in meta.json checks hash against the file. I did put the hash in the meta.json file but didn't work
