### ISSUE TITLE
Kibanna keeps restaring after a minute? and some queries?

### ISSUE THREAD

**Issue by ArslanArshad022** [dtag-dev-sec/tpotce#491]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux idealpresence 5.3.0-2-amd64 #1 SMP Debian 5.3.9-3 (2019-11-19) x86_64 GNU/Linux
- What T-Pot version are you currently using? 19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? no
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? hardware
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. no
- How long has your installation been running? for 1 month
- Did you install upgrades, packages or use the update script? no
- Did you modify any scripts or configs? If yes, please attach the changes. no
- Please provide a screenshot of `glances` and `htop`.
![htop](https://user-images.githubusercontent.com/52732698/70211515-1cbd8f00-1757-11ea-8c0c-4423cca1fc7e.PNG)

- How much free disk space is available (`df -h`)?
![space](https://user-images.githubusercontent.com/52732698/70211590-4d052d80-1757-11ea-8f63-756848ddeefa.PNG)

- What is the current container status (`dps.sh`)?
![kibana staring](https://user-images.githubusercontent.com/52732698/70211642-6b6b2900-1757-11ea-9d72-0490687e5779.PNG)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![status](https://user-images.githubusercontent.com/52732698/70211775-b9802c80-1757-11ea-9516-57c72916d27e.PNG)
it is showing some falures right now but before they are also fine and still kibana keeps restaring
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen
![netstat](https://user-images.githubusercontent.com/52732698/70211836-dd437280-1757-11ea-9d6b-679dec091e39.PNG)
`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

I have been using tpot since a while but facing some issues related to its stability.

1.  **I am facing issue of kibanna restarting after a minute.**
![kibanna issue](https://user-images.githubusercontent.com/52732698/70212508-365fd600-1759-11ea-82ae-8a77cd5b7a69.PNG)

i have performed update many times but the issue is not resolved.

2.  **Moreover whenever i give tpot command "systemctl start tpot" after stopping it takes too much time to start (Sometime half hour or more).** it become more difficult when disk is start filling up.  Is there is an alternative way to start tpot services?

3. Sometime tpot is running fine but after few hours or next day its stop working automatically what would be the reasons of stopping the services? where i can check the reasons using CLI (putty)?

**Comment by ArslanArshad022** [comment]
![kibana latest](https://user-images.githubusercontent.com/52732698/70213362-f13ca380-175a-11ea-988b-36fa5b5d7b00.PNG)

**Comment by cappetta** [comment]
I've been experiencing this same issue for quite some time.  At first I notice Kibana is failing, then the HTTP connectivity to the dashboard is gone, at time the AWS instance this is on also become unresponsive (ssh wise) and I need to hard-reboot everything. Disk space is only 5% full.

**Comment by t3chn0m4g3** [comment]
Please use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=). This has been discussed numerous times.

Since there is no official AMI support for the latest Debian (Buster) T-Pot may not run as expected on AWS, which has also been discussed.

Thanks for understanding.

**Comment by cappetta** [comment]
Ah that's right! I reverted to Stretch in AWS.  RE: Buster support - appears there was some recent updates.  tl;dr - the Buster AMI is still not on the marketplace. 

Sharing incase anyone else reads this -- https://wiki.debian.org/Cloud/AmazonEC2Image/Buster

last thought/question - any idea what the last known/good version working on Stretch is?

**Comment by t3chn0m4g3** [comment]
T-Pot is always migrating to SID. Aside from AWS this works way more stable than previous Ubuntu LTS releases.
