### ISSUE TITLE
Cloud-init file is not formatted correctly

### ISSUE THREAD

**Issue by cappetta** [dtag-dev-sec/tpotce#492]
The cloud-init setup for terraform is not functional.  I haven't tried ansible. Please test and confirm.  The work around is executing the commands directly

**Comment by t3chn0m4g3** [comment]
This is a community driven / developed feature. Happy to merge a PR if volunteers can improve and test this.

**Comment by cappetta** [comment]
Agree / Understood - I was troubleshooting it last night.  Cloud-init is finicky - working on it.

**Comment by t3chn0m4g3** [comment]
Thanks. Highly Appreciated!
