### ISSUE TITLE
Crash - Tpot and c

### ISSUE THREAD

**Issue by yldrmdgn** [dtag-dev-sec/tpotce#493]
# Issues
Hi T-Pot team. I really appriciate your project. Only T-pot and cowrie dashboard crash when I set time range or update. For example, from 15 minutes to 1 hours or past 1 week. Should I wait for the data collection to set these sort of time ranges?
Eventhough I checked some of services, restart them, copy paste errors on google, allocate more resources, I could not find a solution. I also installed it second time. 
Should I start any service or edit any table on Kibana?
If you have any suggestion, please let me know. Thanks.

![image](https://user-images.githubusercontent.com/46830964/70373230-80a0ad00-193b-11ea-9386-9c670676f5e3.png)
![image](https://user-images.githubusercontent.com/46830964/70373183-4e8f4b00-193b-11ea-925b-bd5d82b49a60.png)

Uncaught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is infinite and not of type 'long'. (https://192.168.1.115:64297/kibana/app/kibana#/dashboard/8d4e8300-ebde-11e8-9675-1b303bfb38ef?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(description:'T-Pot%20Dashboard',filters:!(),fullScreenMode:!f,options:(darkTheme:!t,useMargins:!f),panels:!((embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:16,i:'9',w:12,x:24,y:36),id:P0f-OS-Top-10,panelIndex:'9',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'21',w:20,x:28,y:86),id:Suricata-Alert-Signature-Top-10,panelIndex:'21',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'38',w:8,x:20,y:86),id:'1a097850-7c22-11e7-aa1e-6bf93670d67b',panelIndex:'38',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'43',w:24,x:24,y:52),id:e624bc50-7dd6-11e7-bee2-c98307c16efa,panelIndex:'43',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'44',w:12,x:0,y:86),id:d94ff2a0-7ec2-11e7-a286-9f03beba6417,panelIndex:'44',type:visualization,version:'6.3.0'),(gridData:(h:16,i:'45',w:12,x:36,y:36),id:'50d82860-7ea0-11e7-a286-9f03beba6417',panelIndex:'45',type:visualization,version:'6.3.0'),(embeddableConfig:(spy:(mode:(fill:!f,name:!n)),vis:(legendOpen:!t)),gridData:(h:15,i:'46',w:16,x:0,y:21),id:'7b61a6a0-7ebf-11e7-a286-9f03beba6417',panelIndex:'46',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!f)),gridData:(h:15,i:'47',w:16,x:0,y:6),id:'87428ba0-7e9d-11e7-a286-9f03beba6417',panelIndex:'47',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!f)),gridData:(h:15,i:'48',w:16,x:16,y:6),id:'762f66c0-7e9e-11e7-a286-9f03beba6417',panelIndex:'48',type:visualization,version:'6.3.0'),(gridData:(h:16,i:'49',w:12,x:12,y:36),id:'0d947000-7ebd-11e7-a286-9f03beba6417',panelIndex:'49',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'50',w:16,x:32,y:21),id:'885928c0-7ebe-11e7-a286-9f03beba6417',panelIndex:'50',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'51',w:16,x:16,y:21),id:ef227eb0-7e9d-11e7-a286-9f03beba6417,panelIndex:'51',type:visualization,version:'6.3.0'),(embeddableConfig:(mapCenter:!(24.5271348225978,-5.273437500000001),mapZoom:1),gridData:(h:15,i:'52',w:16,x:32,y:6),id:d1aa9740-7e9e-11e7-a286-9f03beba6417,panelIndex:'52',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'53',w:8,x:12,y:86),id:'772cb2b0-7ec3-11e7-a7c8-5f38ad5bf75f',panelIndex:'53',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:16,i:'54',w:12,x:0,y:36),id:'349c11c0-7ea0-11e7-a286-9f03beba6417',panelIndex:'54',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'55',w:24,x:0,y:52),id:f1a19000-7ebf-11e7-a286-9f03beba6417,panelIndex:'55',type:visualization,version:'6.3.0'),(embeddableConfig:(),gridData:(h:6,i:'56',w:48,x:0,y:0),id:e77bc660-e9d3-11e8-be2c-8fd05c77f582,panelIndex:'56',type:visualization,version:'6.4.3'),(embeddableConfig:(),gridData:(h:19,i:'57',w:24,x:0,y:67),id:'56cdedf0-ec08-11e8-96db-ebfb2a58ccf6',panelIndex:'57',type:visualization,version:'6.4.3'),(embeddableConfig:(),gridData:(h:19,i:'58',w:24,x:24,y:67),id:'9b89ddb0-ec07-11e8-96db-ebfb2a58ccf6',panelIndex:'58',type:visualization,version:'6.4.3')),query:(language:lucene,query:'*'),timeRestore:!f,title:%3ET-Pot,viewMode:view):209)
Version: 6.8.2
Build: 20415
Error: Uncaught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is infinite and not of type 'long'. (https://192.168.1.115:64297/kibana/app/kibana#/dashboard/8d4e8300-ebde-11e8-9675-1b303bfb38ef?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(description:'T-Pot%20Dashboard',filters:!(),fullScreenMode:!f,options:(darkTheme:!t,useMargins:!f),panels:!((embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:16,i:'9',w:12,x:24,y:36),id:P0f-OS-Top-10,panelIndex:'9',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'21',w:20,x:28,y:86),id:Suricata-Alert-Signature-Top-10,panelIndex:'21',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'38',w:8,x:20,y:86),id:'1a097850-7c22-11e7-aa1e-6bf93670d67b',panelIndex:'38',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'43',w:24,x:24,y:52),id:e624bc50-7dd6-11e7-bee2-c98307c16efa,panelIndex:'43',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'44',w:12,x:0,y:86),id:d94ff2a0-7ec2-11e7-a286-9f03beba6417,panelIndex:'44',type:visualization,version:'6.3.0'),(gridData:(h:16,i:'45',w:12,x:36,y:36),id:'50d82860-7ea0-11e7-a286-9f03beba6417',panelIndex:'45',type:visualization,version:'6.3.0'),(embeddableConfig:(spy:(mode:(fill:!f,name:!n)),vis:(legendOpen:!t)),gridData:(h:15,i:'46',w:16,x:0,y:21),id:'7b61a6a0-7ebf-11e7-a286-9f03beba6417',panelIndex:'46',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!f)),gridData:(h:15,i:'47',w:16,x:0,y:6),id:'87428ba0-7e9d-11e7-a286-9f03beba6417',panelIndex:'47',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!f)),gridData:(h:15,i:'48',w:16,x:16,y:6),id:'762f66c0-7e9e-11e7-a286-9f03beba6417',panelIndex:'48',type:visualization,version:'6.3.0'),(gridData:(h:16,i:'49',w:12,x:12,y:36),id:'0d947000-7ebd-11e7-a286-9f03beba6417',panelIndex:'49',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'50',w:16,x:32,y:21),id:'885928c0-7ebe-11e7-a286-9f03beba6417',panelIndex:'50',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'51',w:16,x:16,y:21),id:ef227eb0-7e9d-11e7-a286-9f03beba6417,panelIndex:'51',type:visualization,version:'6.3.0'),(embeddableConfig:(mapCenter:!(24.5271348225978,-5.273437500000001),mapZoom:1),gridData:(h:15,i:'52',w:16,x:32,y:6),id:d1aa9740-7e9e-11e7-a286-9f03beba6417,panelIndex:'52',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:29,i:'53',w:8,x:12,y:86),id:'772cb2b0-7ec3-11e7-a7c8-5f38ad5bf75f',panelIndex:'53',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:16,i:'54',w:12,x:0,y:36),id:'349c11c0-7ea0-11e7-a286-9f03beba6417',panelIndex:'54',type:visualization,version:'6.3.0'),(embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:15,i:'55',w:24,x:0,y:52),id:f1a19000-7ebf-11e7-a286-9f03beba6417,panelIndex:'55',type:visualization,version:'6.3.0'),(embeddableConfig:(),gridData:(h:6,i:'56',w:48,x:0,y:0),id:e77bc660-e9d3-11e8-be2c-8fd05c77f582,panelIndex:'56',type:visualization,version:'6.4.3'),(embeddableConfig:(),gridData:(h:19,i:'57',w:24,x:0,y:67),id:'56cdedf0-ec08-11e8-96db-ebfb2a58ccf6',panelIndex:'57',type:visualization,version:'6.4.3'),(embeddableConfig:(),gridData:(h:19,i:'58',w:24,x:24,y:67),id:'9b89ddb0-ec07-11e8-96db-ebfb2a58ccf6',panelIndex:'58',type:visualization,version:'6.4.3')),query:(language:lucene,query:'*'),timeRestore:!f,title:%3ET-Pot,viewMode:view):209)
    at window.onerror (https://192.168.1.115:64297/kibana/bundles/commons.bundle.js:3:956237)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? 
Linux fierceslipper 5.3.0-2-amd64 #1 SMP Debian 5.3.9-3 (2019-11-19) x86_64 GNU/Linux
- What T-Pot version are you currently using? = 19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? = Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? = Vsphere 6.7
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
![image](https://user-images.githubusercontent.com/46830964/70373583-4c2df080-193d-11ea-8d8c-c2165cbdf3af.png)
- How long has your installation been running? = 30 minutes
- Did you install upgrades, packages or use the update script?
![image](https://user-images.githubusercontent.com/46830964/70373173-21429d00-193b-11ea-8405-df3d86d92288.png)
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/46830964/70373648-f73eaa00-193d-11ea-8c03-dd62b07212f4.png)
![image](https://user-images.githubusercontent.com/46830964/70373667-281edf00-193e-11ea-84e3-d75fa1d7e03a.png)
- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/46830964/70372957-cd838400-1939-11ea-8a87-300bc2ce2dd0.png)
- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/46830964/70373630-ca8a9280-193d-11ea-8c00-4cb2eaa7abbf.png)
- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/46830964/70373000-4e428000-193a-11ea-9ac3-a298b8f79d19.png)
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/46830964/70373045-92358500-193a-11ea-860c-cc36af1bb470.png)
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

![image](https://user-images.githubusercontent.com/46830964/70373600-7bdcf880-193d-11ea-8b6d-da2ae9b9680b.png)

**Comment by yldrmdgn** [comment]
When I deleted Password and Username Tagcloud  from T-Pot dashboard, it works flawlessly. Crownie section might have been misconfigured on my dashboard or else.

**Comment by t3chn0m4g3** [comment]
Sorry, cannot reproduce.

Anyone else having the same issue?

**Comment by CCL-JT** [comment]
Hi, I am also having the same issue. Only when clicking the tpot or cowrie dashboards.
Kibana 6.8.6
tpot v20200316

Exactly the same results as the issue above. @yldrmdgn did you find a fix in the end? I disabled the wordclouds from the tpot dashboard but this did not work for me.
