### ISSUE TITLE
How to change the honeypot logrotation from daily to hourly?

### ISSUE THREAD

**Issue by xta-kondoh** [dtag-dev-sec/tpotce#494]
# Issues

Hello,

I are using Tpot 18.11.
I want to change logrataion from daily to hourly.

So, afret installed t-pot, I modified /opt/tpot/etc/logrotate/logrotate.conf as bellow:

```
diff  /opt/tpot/etc/logrotate/logrotate.conf  /opt/tpot/etc/logrotate/logrotate.conf-org 
42c42
< 	hourly
---
> 	daily
45c45
< 	rotate 48
---
> 	rotate 30
```

But,  what I expected didi't  happen. The logrotation seems run with daily of the default settings of T-Pot.
What's the my wrong?

And then, I have a basically question.  Where is the setting of logrotate of T-Pot?
I couldn't find the logrotate setting of honeypot in /etc/cron.daily. 

Thanks,

**Comment by t3chn0m4g3** [comment]
Correct, you can update this in `/opt/tpot/etc/logrotate/logrotate.conf`, however your version of T-Pot is outdated and reinstallation is highly recommended.

**Comment by xta-kondoh** [comment]
Thanks for your replay.

I don't have understood about logrotate action.
I checked T-Pot invoking sequences. I think it's as follow:

* T-Pot invoking sequences

 1. Reboot daily with /etc/crontab

```
   --- /etc/crontab ---
   # Daily reboot
   27 3 * * *      root    systemctl stop tpot && docker stop $(docker ps -aq) || docker rm $(docker ps -aq) || reboot
   ---
```

 2. Boot T-Pot with /etc/systemd/system/tpot.service

```
   --- /etc/systemd/system/tpot.service ---
   ExecStartPre=-/bin/bash -c '/opt/tpot/bin/clean.sh on'
   ---
```

 3. Run logrotate

```
   --- /opt/tpot/bin/clean.sh ---
   # Run logrotate with force (-f) first, so the status file can be written and race conditions (with tar) be avoided
   logrotate -f -s $mySTATUS $myCONF
   ---
```

If this boot sequence is correct, logrotate kickes just one time when rebooting T-Pot daily.
So, even if /opt/tpot/etc/logrotate/logrotate.conf is modified from daily to hourly, logrotate doesn't run houry.
Because the clean.sh run daily when rebooting T-Pot.

Is my understanding mistaken? Logrotate run in another way, not clean.sh ?

And thanks for your recommend T-Pot version. I know about it.

Thanks

**Comment by t3chn0m4g3** [comment]
Logrotate for T-Pot's folders is triggered through `clean.sh` which is triggered through the service start. If you start T-Pot only once a day (as is the default) logrotate will also only run once a day.

**Comment by xta-kondoh** [comment]
Thanks,
I got it.
