### ISSUE TITLE
Adding new sensors

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#496]
Hello! I would like to add some new sensors to TPot (i.e. wordpot, shockpot, etc), but being new to Docker/Docker-compose, I would like some guidance how to integrate said sensors with TPot infrastructure (if at all possible). Thank you!

**Comment by t3chn0m4g3** [comment]
The best start is by checking out how T-Pot's logic works. For a starting point check out the docker folder and its contents and `/opt/tpot/etc/tpot.yml`.
