### ISSUE TITLE
Exporting hpfeeds to multiple destinations?

### ISSUE THREAD

**Issue by BoaThor** [dtag-dev-sec/tpotce#50]
Hello there,
atm hpfeeds are by default exported to Sicherheitstacho.
I would like to keep this going but add some further destinations in my local network.
Can this be achieved by editing the basic ews-configs? How would the config for this look like?
Thanks,
Bo

**Comment by t3chn0m4g3** [comment]
Please check issue #41. Is that what you are looking for?

**Comment by BoaThor** [comment]
I won´t use Splunk (much to costly) I use the free to use OSSIM. But maybe the mentioned changes will help interconnecting those tools.

**Comment by t3chn0m4g3** [comment]
Splunk was just the initial question, the alerta example should get you covered.
You will find the example [here](https://github.com/dtag-dev-sec/elk/pull/4).

**Comment by SaiGonSeamus** [comment]
I'm very interested in integrating this with OSSIM & OTX. If you have any tips they would be greatly received.

**Comment by t3chn0m4g3** [comment]
I am not running a install of OSSIM. How does it consume logs? Can we forward logs to certain port?

The only solution I could think of is to forward logs with logstash either in formatted syslog style or running an external agent which can handle flatted JSON.

Please provide more info.

**Comment by BoaThor** [comment]
Forwarding in syslog was the plan here until OSSIM/USM enables hpfeed support.

**Comment by SaiGonSeamus** [comment]
OSSIM uses plugin-ins to normalise logs. There is one already for Dionaea but I have been able to test it yet. 

https://www.alienvault.com/documentation/usm-v5/plugin-management/about-plugins.htm 

https://www.alienvault.com/documentation/usm-v5/plugin-management/plugin-comp-types.htm#Remote

https://www.alienvault.com/documentation/usm-v5/plugin-management/about-cust-or-dev-plugins.htm

I have some contacts over at alienvault, we can request them to develop some plug-ins for what is needed here.

**Comment by SaiGonSeamus** [comment]
So we need to agree and provide the following information to Alienvault.

Dionaea Syslog and Suricata already exist.

Honeytrap, Snare and Cowrie would be the most likely candidates to request first from my perspective.

Provide detailed information on the originating product (the more, the better): vendor, model, particular configuration.
Define which events/data are important for you, so we can focus on getting those in USM for correlation.
Attach meaningful log samples: 2MB of logs with the events you want processed can give more relevant information than 2GB of “noise” logs.
The more information we have, the faster we will be able to create the plugin and the more accurate it will be.

**Comment by t3chn0m4g3** [comment]
You can run a local agent which collects logs from `/data/` or output logs to syslog via logstash. Please check the [logstash documentation](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html) for more info.

**Comment by BoaThor** [comment]
Ok, I´ll check that. Maybe I can get a grip of some of the logstash professions at my place.

**Comment by t3chn0m4g3** [comment]
You may Find a basic outline in [Issue 55](https://github.com/dtag-dev-sec/tpotce/issues/55).

**Comment by t3chn0m4g3** [comment]
T-Pot 16.10 contains the necessary basics to cover this request.
