### ISSUE TITLE
terraform build - aws image crashes and no admin pwd set

### ISSUE THREAD

**Issue by dober-man** [dtag-dev-sec/tpotce#500]
When using the terraform build, everything deploys fine and I can initially ssh and access the kibana dashboard. I am unable to access the cockpit dashboard since I don't know the credentials and they appear to be tied to the admin account for which a static password was never entered by me during the terraform deployment so I don't know it. 

The second issue is that the aws image starts failing instance status checks after a short period of time. I have redeployed several times with variable MTTF.  

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? (terraform build)
- What T-Pot version are you currently using? (terraform build)
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? (terraform build)
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? (terraform build - aws)
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. (no)
- How long has your installation been running? (n/a)
- Did you install upgrades, packages or use the update script? (n/a)
- Did you modify any scripts or configs? If yes, please attach the changes. (no)
- Please provide a screenshot of `glances` and `htop`. (can't access without redeploying)
- How much free disk space is available (`df -h`)? (terraform build - fresh install)
- What is the current container status (`dps.sh`)? (can't access without redeploying)
- What is the status of the T-Pot service (`systemctl status tpot`)?(can't access without redeploying)
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`(can't access without redeploying)
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries (can't access without redeploying)

**Comment by t3chn0m4g3** [comment]
Cockpit uses the credentials of the linux users available on the machine, just like SSH.

AWS is faulty ATM. Please review other issues for that matter.

**Comment by dober-man** [comment]
Thank you for the response. I will wait and keep an eye out for any updates. Please let me know if I can help with any testing or if I can provide any additional data. Great project! Thanks!

**Comment by t3chn0m4g3** [comment]
Thanks, waiting for AWS to fix Buster AMIs and interested community members run a PR :bowtie:

**Comment by dober-man** [comment]
I volunteer! :) 
Would I be better off doing a manual AWS install on Ubuntu for the time being?
Also figured out that I can reset the admin password after booting without knowing the original with: "sudo passwd admin" thanks!
