### ISSUE TITLE
clean.sh taking too long to tar files

### ISSUE THREAD

**Issue by workandresearchgithub** [dtag-dev-sec/tpotce#501]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)
- What version of the OS are you currently using `lsb_release -a` and `uname -a`?

[root@supremebrief:/home/tsec]# lsb_release -a && uname -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
Linux supremebrief 5.3.0-3-amd64 #1 SMP Debian 5.3.15-1 (2019-12-07) x86_64 GNU/Linux

- What T-Pot version are you currently using?

[root@supremebrief:/home/tsec]# cat /opt/tpot/version
19.03.1

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?

[root@supremebrief:/home/tsec]# cat /opt/tpot/etc/tpot.yml
# T-Pot (NextGen)

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?

hardware / baremetal

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.

No

- How long has your installation been running?

6 months?

- Did you install upgrades, packages or use the update script?

/opt/tpot/update.sh -y

- Did you modify any scripts or configs? If yes, please attach the changes.

clean.sh  (see attached - I modifed tar lines to use pigz)

- Please provide a screenshot of `glances` and `htop`.

(see attached)

- How much free disk space is available (`df -h`)?

[root@supremebrief:/home/tsec]# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           776M   80M  697M  11% /run
/dev/sda2       221G   10G  200G   5% /
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
tmpfs           776M     0  776M   0% /run/user/1000
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/7c8d1a88bb1db7003007598a7aac8b6095a0a13e70d49ef0b9f655e68a579342/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/b80b7cb3e33e0f3fa6b714a97a98f6ff76b831e1e6dd4fa02ea3f7124c01e8e3/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/58a933f72a8dbcd88bcc15120352a1d942db2e21da09873f0a3ca7c3d274f3b9/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/e6dae9904f586419df72058e715d616e83b122a8d84c08796ac684f6d4eec752/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/841f5434d78d4e50c9c90378e9d3155b77949e907ac87adfc401a0b175aad581/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/6f93546b16b775178fa8630e4118038da7dcdf932560c74fa602824294481c2a/merged
shm              64M     0   64M   0% /var/lib/docker/containers/49345f42b6aa2f0596ae63cba256fdb5bf0569f9997a0564feaa9c876a543501/mounts/shm
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/0ff0ee8f63f8f3ad9b7d2e509997804b8466e38edfc8f0544723488cb4a02c2a/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/71ea51fe4d33a34a39282613cbadc0c77b3c7d9e50a3220a4e44a05b2276cbd2/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/c06ecd348ba1a9af9bee0aa2305734555ce91277a765e4e43f7289f97f3b1f7c/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/c199495ff6baf6e6a03e47ff872fdfc9b52e4576326217601cab326de3235b56/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/001108982d71c40bb5a2b50264d912e6c7d9ccfa58cb99dd6767415da3e5800b/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/c678ecae838382b02ae825b0de23a0a2fdecb258cd0b1792a2c984bf2d6d1bc5/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/c32ee643ac370ad83731e45ad6265b8750e90ba346079ea9d2de6f22a4b03370/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/9192e348b1807b42e423e237f457c9e7a59217d8c9593572d78d2fa1d4feb7b3/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/3ee9d88059dec41608335b9bb1dc5ec8076d21e5749e22997d8aa508042c26dc/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/20cb379f0d3221ecbe5a6ea493911a99c0ebf095e9153bec6855411804ba937b/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/dbd34dfa77169ff562300cba29472abda0999c655729274ac3797ea860a8002a/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/6b8863ce03c9c08d2519849832cecb9ddc62166192736a51a43afb5ec59a65ac/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/547d131567f65b29b01bb8c33387f1d6bd969519fffc1b304070b7fb7c9d38f2/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/e216d3986926eec61d961607ae0719a08415ff1b5002ce76951e6e37975776cc/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/2201e9e3851afef62eed6bc70d73f8e2ab69b32a94fa35956524b7dbddcc3b84/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/4071cb7224e7b8cac779bbf8bfe2c34fb561869a669ea993c08807ed25132535/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/7da93abfb0d5686fe1ff6e0cd44d130b963a3e39f1b39f1c75d20b1a4bf7f389/merged
shm              64M     0   64M   0% /var/lib/docker/containers/f5be5528e6afe910b0460879d252c2dc5e80332513cc43e7d3f675afd4e05ada/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bb75911351cf939aa91de9e559dbf19325f3f28b4cbee05b406db6164f6f3779/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a6a8bd128960492ad8cbad08f92516bb0ba3aaf351d7ef5abebb9d6fb45570a2/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/8c90f82ba370f54f6fea1c1a11db7d5db8a95b259d16d1e98d78b31d321d3645/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/24118d6b4188bb22bbccb5ed589e2dab0df5904fa8b88ff3a7e23293c5656caa/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/ad995a160b5194398c7a09968169d6916ed5725f4b0ca8569350578800e3d75d/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/358f214850093f18365612a3f53a2dfd87c9966ecbba1d39559f9294c8b1e71f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/6b6cfbffec68f4f44195cf914a4409da5e62a64b430f9e1b3daf3375e567eefd/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1cc603d178ab34d30f7d2dc6bd706e033630287387de87a865cadd3e563c9fe5/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/ca2c5d438d11bf6d6f779b447a3379f80faf1a80cdc703f3c633fe7a370bfcde/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/0aec357a5a3fe43a8961b58b3f773b0711fe81bdcac5fe6c5687523ef65c1417/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c8e1d4175b4f6c40403e25d2daa598467a43ec04024efbcdba213ff70ae059ac/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c2cfc17c06b77068b7a93faca6b3f1c0868afb36886afbee1e712a76beefa6cc/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/64815631b262ae37a86bafa539c1aae5731c71643c00b752196fabf9eb7eddf2/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7e806a2150f1116fc05471050d9f52cb97e73eed6dd90e6fa6b9a9276b9173e3/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bd7aa1db388cdf1330e1588908951c49dc6500c7a97a29670c52e7ac8b293553/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/043c3591bfebe2230e637c93cc332370091313d2f62b7dd07990b33971fd67d2/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/41d4979a793b24c96246760505f77c14a28b233a325605116ba6241025f3e05b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/fa00bca5995687057baf987ed7e2b9def112267a042b0d51f762fae8d39913b5/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a2a6410c44f49a415fa41bd40c8c58239e528aa5f80d9cb24a97467144529a67/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bed421ae3f125581c3963e201671b69521ad4fc13fa8ac26c5c264686ce3d4ec/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/f5ff95257b91a3ebad64e8fcc5f4b83314ccbe4cfeffaf1e5fbafd91b56b2d76/mounts/shm
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/811e5254031fa19196f9a9a1286c95349a03bf3ffd9b53c68b66811a35bb4da6/merged
shm              64M     0   64M   0% /var/lib/docker/containers/1c6de9690f256628e6af169be9c1075278810bec4c7ffc577fcbe6a819400a01/mounts/shm
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/0ca8c679515dd16559d35096685f776c69aa814f33a3c38ba4c55e493540d84e/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/37df327502626249bbe0587b7fa4a8285aa67addc82b5629e637f4fcee896a1e/merged
shm              64M     0   64M   0% /var/lib/docker/containers/06960a5be0877e00a9ea3ec5a88b4e10eb709fea1ad589c930050d5b156ebdc1/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/f874a4f5cf08ee346a828d1fbecccddd68d394c9bbf1eb970ebf73c70af446e8/mounts/shm
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/2a54e8ea5f7b088d9654aab5fb763308cdc2f07e460eb9243c82793ee3a5e367/merged
shm              64M     0   64M   0% /var/lib/docker/containers/b260ee09faef9e87399c5afc5abb3c3f5d8156b289b0428fa183d9c044c1c848/mounts/shm
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/78d09dac62d653d5b43c626e102c6679df86894ecbd89bae1e12d59cbc7d9e11/merged
shm              64M   20K   64M   1% /var/lib/docker/containers/289fbc1c5db2b5c9d67eb7b7a0ae614fbf4e68621c3ed7e75d64a91e7d72f150/mounts/shm
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/fc96a5d98a27cc8b6fd98c68609f4456f9d94f4a9018475e1b78c329e50e2122/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/16048117482f5c4bcb14d6b7e247a272e78b66f4370fa331c99fe2d738b04636/merged
overlay         221G   10G  200G   5% /var/lib/docker/overlay2/456e5d6177aa46c8c6ddfa5433b7f4ee80b1f26452b1a65b70215b4949c5c4a7/merged
shm              64M     0   64M   0% /var/lib/docker/containers/ff127e2df2859993de3dfa25ce3196ada6811b46f4f8d44e78cce58d3bf9665c/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/008ec1f829ec79593f71e1f8bc1e33dbfa930dc9274b580be6cb0b33821e6980/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7c740eff244b7451db30db5da38874ed0543707885dc58d42125be1da4d626b8/mounts/shm

- What is the current container status (`dps.sh`)?

[root@supremebrief:/home/tsec]# dps.sh
========| System |========
    Date:  Fri 20 Dec 2019 05:23:40 AM UTC
  Uptime:  05:23:40 up  1:18,  2 users,  load average: 0.62, 1.14, 1.75

NAME                  STATUS                       PORTS
adbhoney              Up 17 minutes             0.0.0.0:5555->5555/tcp
ciscoasa              Up 17 minutes
conpot_guardian_ast   Up 17 minutes             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 17 minutes             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 17 minutes             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 17 minutes             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 17 minutes             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 17 minutes (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 17 minutes
elasticsearch         Up 17 minutes (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 17 minutes
fatt                  Up 17 minutes
glutton               Up 17 minutes
head                  Up 16 minutes (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 17 minutes             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 17 minutes             0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 16 minutes (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 16 minutes (healthy)
mailoney              Up 17 minutes             0.0.0.0:25->25/tcp
medpot                Up 17 minutes             0.0.0.0:2575->2575/tcp
nginx                 Up 17 minutes
p0f                   Up 17 minutes
rdpy                  Up 17 minutes             0.0.0.0:3389->3389/tcp
snare                 Up 16 minutes             0.0.0.0:80->80/tcp
spiderfoot            Up 17 minutes (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 17 minutes
tanner                Up 17 minutes
tanner_api            Up 17 minutes
tanner_phpox          Up 17 minutes
tanner_redis          Up 17 minutes             6379/tcp
tanner_web            Up 17 minutes

- What is the status of the T-Pot service (`systemctl status tpot`)?

[root@supremebrief:/home/tsec]# systemctl status tpot
● tpot.service - tpot
     Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2019-12-20 05:05:58 UTC; 18min ago
    Process: 24602 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
    Process: 24622 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
    Process: 24757 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
    Process: 24760 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
    Process: 24763 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
    Process: 24782 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
    Process: 24801 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
    Process: 24819 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
    Process: 24841 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx of>
    Process: 24847 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (co>
    Process: 24853 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=e>
    Process: 24859 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
   Main PID: 24932 (docker-compose)
      Tasks: 33 (limit: 9188)
     Memory: 148.9M
     CGroup: /system.slice/tpot.service
             └─24932 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Dec 20 05:23:43 supremebrief docker-compose[24932]: dionaea                | <dionaea.core.incident object at 0x7f4f4f967f30>
Dec 20 05:23:46 supremebrief docker-compose[24932]: head                   | [Fri Dec 20 2019 05:23:46 GMT+0000 (Coordinated Universal Time)] "GET /" "cur>
Dec 20 05:23:46 supremebrief docker-compose[24932]: kibana                 | {"type":"response","@timestamp":"2019-12-20T05:23:46Z","tags":[],"pid":1,"met>
Dec 20 05:23:50 supremebrief docker-compose[24932]: adbhoney               | INFO:ADBHoneypot:Received a connection, creating an ADBConnection.
Dec 20 05:23:50 supremebrief docker-compose[24932]: adbhoney               | INFO:ADBHoneypot:119.65.57.252 connection start (c46f90f60891)
Dec 20 05:23:50 supremebrief docker-compose[24932]: adbhoney               | INFO:ADBHoneypot:{'eventid': 'adbhoney.session.connect', 'src_ip': '119.65.57>
Dec 20 05:23:53 supremebrief docker-compose[24932]: adbhoney               | INFO:ADBHoneypot:data is none?: None
Dec 20 05:23:53 supremebrief docker-compose[24932]: adbhoney               | INFO:ADBHoneypot:3.107654333114624        119.65.57.252        connection clo>
Dec 20 05:23:53 supremebrief docker-compose[24932]: adbhoney               | INFO:ADBHoneypot:{'eventid': 'adbhoney.session.closed', 'src_ip': '119.65.57.>
Dec 20 05:24:10 supremebrief docker-compose[24932]: cyberchef              | [Fri Dec 20 2019 05:24:10 GMT+0000 (Coordinated Universal Time)] "GET /" "cur>

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`

[root@supremebrief:/home/tsec]# systemctl stop tpot && netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          20815      655/sshd
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          19239      633/python3
tcp6       0      0 :::64294                :::*                    LISTEN      0          15336      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          20817      655/sshd
udp        0      0 0.0.0.0:52565           0.0.0.0:*                           0          18809      483/rsyslogd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          17280      533/dhclient
udp        0      0 192.168.224.1:123       0.0.0.0:*                           108        139979     654/ntpd
udp        0      0 172.18.0.1:123          0.0.0.0:*                           108        139503     654/ntpd
udp        0      0 192.168.41.138:123      0.0.0.0:*                           0          15830      654/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          15828      654/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          15824      654/ntpd
udp6       0      0 :::123                  :::*                                0          15821      654/ntpd

![htop-2019-12-19 232155](https://user-images.githubusercontent.com/38447728/71232355-43330c80-22b7-11ea-8dd2-1f1220ef38fd.jpg)
![glances-2019-12-19 232155](https://user-images.githubusercontent.com/38447728/71232356-43330c80-22b7-11ea-957a-9d252967340a.jpg)
[clean.sh.txt](https://github.com/dtag-dev-sec/tpotce/files/3986847/clean.sh.txt)

------

Yesterday, after running /opt/tpot/update.sh -y, I exposed my tpot to the Internet again (it had been 6 months or so).  Today I went to look at it, and the Kibana website wouldn't respond.
When I ssh'd in and looked at htop, it appeared to be trying to tar a boatload of dionea files.  I waited like 20 min, but it didn't finish.  Since I'd worked another project where we were trying to archive netflow on a very high speed link, I recalled we were able to solve this issue with pigz, as it would tar them extremly fast.

So I thought I'd bring this option (using pigz for compression of log files) to your attention for consideration.  My ISP just recently upgraded our link to 500Mb symetrical, so likely the volumes of data will correspondinly increase.

**Comment by t3chn0m4g3** [comment]
Done (f4a078c4435625aff0c7b0eb94c9c009a3a216da). Thanks for the suggestion. You can run `update.sh` to retreive the retreive the latest settings.
