### ISSUE TITLE
honeytrap/honeytrap project

### ISSUE THREAD

**Issue by rocbr** [dtag-dev-sec/tpotce#502]
I am using tpotce for a while. Awesome project. Thanks !

Have you considered integrating the honeytrap/honeytrap project ?

it seems to be a modern project and it has some interesting features like:

1. Payload detection to determine which service should handle the request, one port can handle multiple protocols
2. Extend honeytrap with existing honeypots (like cowrie or glutton), while using the logging and listening framework of Honeytrap
3. etc

https://github.com/honeytrap/honeytrap

**Comment by t3chn0m4g3** [comment]
Thank you for being part of the community. Yes, we know Honeytrap, however it follows a different approach and implementation path than we have in mind for T-Pot at the moment.
