### ISSUE TITLE
Warning during install

### ISSUE THREAD

**Issue by xavifr** [dtag-dev-sec/tpotce#504]
Missing \ at end of file

https://github.com/dtag-dev-sec/tpotce/blob/7c5fc000c01b53bf187a2a308e4bde4a1ac4b064/iso/installer/install.sh#L656

```
          -days 3650 \
          -subj '/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd' \
          -addext "subjectAltName = IP:$myINTIP"
```

**Comment by t3chn0m4g3** [comment]
Thanks, please PR in the future :bowtie:

**Comment by xavifr** [comment]
You are right, I should have used PR. Next time!
