### ISSUE TITLE
update.sh don't get "-y" when executed by tsec user

### ISSUE THREAD

**Issue by xavifr** [dtag-dev-sec/tpotce#508]
Extra params should be passed to $0 in order to get "-y"

https://github.com/dtag-dev-sec/tpotce/blob/7c5fc000c01b53bf187a2a308e4bde4a1ac4b064/update.sh#L284

```
if [ "$myWHOAMI" != "root" ]
  then
    echo "Need to run as root ..."
-    sudo ./$0
+    sudo ./$0 $@
    exit
fi
```

**Comment by t3chn0m4g3** [comment]
Thanks. It should be executed as `root` only, so no parameters should be passed and script should stop working if not executed as `root`. Fixed now.
