### ISSUE TITLE
No such file or directory.

### ISSUE THREAD

**Issue by Santhosh-Janardhan-we45** [dtag-dev-sec/tpotce#510]
While installing Tpot in AWS - EC2 instance in ubuntu 16.04. We are getting below issue. Please do the needful. 

### Allow SSH password authentication from RFC1918 networks 

Match address 127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    PasswordAuthentication yes
### Preparing EVERYTHING flavor installation.
cp: cannot stat '/opt/tpot/etc/compose/all.yml': No such file or directory
root@ip-172-31-25-42:/home/ubuntu/t-pot-autoinstall#

**Comment by shaderecker** [comment]
Please use Debian 9/10. Ubuntu is no longer supported.

**Comment by Santhosh-Janardhan-we45** [comment]
Thank you, I have installed on Debian.
