### ISSUE TITLE
Reverse IP attribute in geoip

### ISSUE THREAD

**Issue by rocbr** [dtag-dev-sec/tpotce#512]
It would be great to include the reverse IP domain in geoip. Various analyzes and filters could be created from this field.

On the other hand, this would generate traffic originating from the honeypot to the Internet to resolve the IP's PTR DNS record. So it is something to be considered.

Thanks again for the amazing work on this project.

**Comment by t3chn0m4g3** [comment]
Thanks.

What benefits are you expecting from this?

**Comment by rocbr** [comment]
Thanks for your attention !

Basically, I see two advantages:

1. Statistics, because I will be able to analyze, for example:
### Reverse country code top level domain (cctld)
### Domain category as: .com, .org, .mil, .gov, ...
1.1 It will be possible to create graphs with this information.

2. Improved tracking of traffic source. With the help of reverse, it will be easier to identify the real source of traffic, because identification at the autonomous system or ISP level is still very generic.

Static IP allocations tend to have a more specific reverse because it is usually allocated to companies/individuals that need a static IP address. Usually those who have static IP allocation have control over the reverse IP, which is why reverse is precisely configured. Also, in some services like e-mail, reverse needs to be set up for spam control.

In the vast majority of VPS and Virtual Server Providers like OVH, Online.net, Hetzner, etc. (even on Amazon through support) it is possible to automatically configure the reverse IP address, so by the reverse is easier to identify the real user instead of the service provider.

Moreover, even dynamic IP allocations via DHCP the ISP use a simpler naming to identify the type of traffic source.

For example, this kind o naming is common:
static-200-200-200-200.company.com.br
host-200-200-200-200.isp.net
dynamic-200-200-200-200.provider.com

Therefore, even in these cases, reverse helps to analyze the source of traffic more accurately.

Make sense for you ?

**Comment by t3chn0m4g3** [comment]
I'm intrigued, however this might reduce logstash performance drastically:
https://www.elastic.co/guide/en/logstash/6.8/plugins-filters-dns.html
https://discuss.elastic.co/t/dns-filter/124379/8

If it is on interest for you I can add the dns filter plugin into the image but you have to adjust the config yourself (see the wikipage for an example).

**Comment by rocbr** [comment]
I really didn't realize there was this performance limitation in the logstash filter: "This filter, like all filters, only processes 1 event at a time".

Given the high number of honeypot events, this limitation may be difficult to overcome at this time.

Anyway I thought this functionality would be interesting for all TPOT users, so I suggested it as it would help the whole community.

I will still test this better in the future, and if I figure some way to do it smarter and faster, I will suggest it again.

Don't worry about my specific case because I can solve this specific problem through a palliative solution. Anyway, thanks for that.

**Comment by t3chn0m4g3** [comment]
Liked the idea as well, thanks for the contribution 😄 Will close this, however you can follow up on this later again.
