### ISSUE TITLE
After running install.sh is the server not reachable anymore (port:64295)

### ISSUE THREAD

**Issue by vincenthalter** [dtag-dev-sec/tpotce#513]
Im using the google cloud platform for my tpot installation. (Debian Stretch) 
After cloning the git repo, I did the following steps:
1. cd tpotce/iso/installer/
2. ./install.sh --type=user (as root)

After that my ssh conncection gets refused. ( because the ssh port changed from 22 to 64295)
Until that step, everything was fine.
But now, I cant connect to the machine anymore. The ssh connection isnt working (port 64295) and the web UI is also not working (port 64297)
[install.txt](https://github.com/dtag-dev-sec/tpotce/files/4040658/install.txt)

This is the script. Can somebody help what kind of mistake/bug this is?

**Comment by t3chn0m4g3** [comment]
Are you on AWS?

**Comment by vincenthalter** [comment]
@t3chn0m4g3 
No, I'm using the google cloud platform.
I think it should also work, or are there differences?

**Comment by t3chn0m4g3** [comment]
You should be able to access using the console. Log looks good. AWS has troubles with Sid, probably similar with GCP. Unfortunately I have no machines on either platform to test with.

**Comment by t3chn0m4g3** [comment]
Closing this for now.
