### ISSUE TITLE
All docker / tpot containers fail, do not return after a restart

### ISSUE THREAD

**Issue by jrsanchezsilva** [dtag-dev-sec/tpotce#514]
Good morning, I just saw the kibana and I have the same problem, as case # 511 
https://github.com/dtag-dev-sec/tpotce/issues/511
So far I have solved it with the following commands,

systemctl stop tpot
hash -r
pip3 install yq

If you receive comments from yq, you can start T-Pot again (systemctl start tpot), otherwise, post the output of ...

iptables-legacy -t raw -vL
... once all the T-Pot containers started.

It only lasts until the next reboot, please your support @t3chn0m4g3 , in advance thank you very much.

![image](https://user-images.githubusercontent.com/51901933/72089982-1df45580-32db-11ea-94bd-464b207b08be.png)

![image](https://user-images.githubusercontent.com/51901933/72090048-3e241480-32db-11ea-9904-66f674722dc8.png)

**Comment by t3chn0m4g3** [comment]
This is exactly how yq is being installed / updated.
None of my installations shows this kind of behavior.

**Comment by jrsanchezsilva** [comment]
Good afternoon. I enclose the confirmation of installation of grc e yq. The problem of kibana still persists.

You can verify the case https://github.com/dtag-dev-sec/tpotce/issues/511

![image](https://user-images.githubusercontent.com/51901933/72277993-054cae00-3601-11ea-849b-fa097e5e942d.png)

**Comment by t3chn0m4g3** [comment]
Is it possible you did run the `update.sh` script with `sudo` instead of being root (`sudo su -`). This would at least explain why the hashing does not work.
If that is the case you need to remove yq and then run the ùpdate.sh` script again as root.

**Comment by jrsanchezsilva** [comment]
Good afternoon, yesterday run update.sh is root mode (sudo su -), the update was done and then restart the server (physical server), so far all the containers and KIBANA are active.

![image](https://user-images.githubusercontent.com/51901933/72391074-3bba2400-36fa-11ea-9053-64b7c29dacef.png)

![image](https://user-images.githubusercontent.com/51901933/72391108-4eccf400-36fa-11ea-9756-57ebcf564003.png)

Here we can realize that it was up 20 hours ago, hopefully it will continue that way since more than 36 hours or the next restart could not reach Kibana.
- Why does the server restart automatically, what could be done in that case?
![image](https://user-images.githubusercontent.com/51901933/72391623-a6b82a80-36fb-11ea-8a0c-85abd2ac0407.png)

![image](https://user-images.githubusercontent.com/51901933/72391664-cc453400-36fb-11ea-9b84-80688397d983.png)

- Despite the updates, the image I show shows available updates; what to do about it, just update ??

![image](https://user-images.githubusercontent.com/51901933/72391312-cf8bf000-36fa-11ea-8bf8-9ed9bb7aaad9.png)

I will continue monitoring these days and I will tell you; Beforehand thank you very much.

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback. Will close this for now.

**Comment by jrsanchezsilva** [comment]
Good Morning. Seeing the containers, these are located above and created 12 hours ago. As you can see in the picture. It is normal for the physical server where the Honeypot is mounted to restart automatically.
![image](https://user-images.githubusercontent.com/51901933/72448982-f17e8480-3785-11ea-9284-1df27024e5c6.png)
![image](https://user-images.githubusercontent.com/51901933/72449048-09ee9f00-3786-11ea-9937-de023a99b8a8.png)

**Comment by jrsanchezsilva** [comment]
I just validated and 4 minutes ago the dockers have just been created again because that happens (see image), please your support.

![image](https://user-images.githubusercontent.com/51901933/72491504-3804cb00-37e8-11ea-8f99-2afe24be06aa.png)

![image](https://user-images.githubusercontent.com/51901933/72491567-6da9b400-37e8-11ea-8a69-94b878052bb2.png)

**Comment by t3chn0m4g3** [comment]
The reboot happens at around 3:00 UTC, so this is is normal.

**Comment by jrsanchezsilva** [comment]
Good morning, but the information of the attacks that it shows in Kibana I can no longer see from the previous day since the docker begins to be created at 3:00 UTC, what to do so that the server can not be restarted and can continue to store the information and visualizing in kibana, please your support.

**Comment by t3chn0m4g3** [comment]
Yes, you can. All Kibana data is persisted. All you have to do is pick a different time in the upper right corner.
