### ISSUE TITLE
link tables using primary keys (sqlite3 c++)

### ISSUE THREAD

**Issue by Guila95** [dtag-dev-sec/tpotce#515]
//my program creates the DISCIPLINES AND STUDENT tables but it can't create the table NOTE 
//

int  createTable(const char* s)
{
	sqlite3* DB;
	string sql_STUDENT = " CREATE TABLE IF NOT EXISTS  STUDENT ( "
		" ID_STUDENT INTEGER PRIMARY KEY  AUTOINCREMENT, "
		" NAME TEXT NOT NULL ,"
		" LNAME TEXT NOT NULL , "
		" AGE INT NOT NULL , "
		" EMAIL  TEXT NOT NULL UNIQUE,"
		" TEL  TEXT NOT NULL UNIQUE ,"
		" ADRESS TEXT  ); ";

	string sql_DISCIPLINE = " CREATE TABLE IF NOT EXISTS  DISCIPLINE ( "
		" ID_DISCIPLINE INTEGER PRIMARY KEY  AUTOINCREMENT, "
		" NAME_DISCIPLINE TEXT NOT NULL ); ";

	string sql_NOTE = " CREATE TABLE IF NOT EXISTS  NOTE ( "
		" ID_DISCIPLINE INTEGER AUTOINCREMENT, "
		" ID_STUDENT INTEGER AUTOINCREMENT , "
		" NOTE_ETUDIANT REAL NOT NULL ,"
		" PRIMARY KEY (ID_DISCIPLINE ,ID_STUDENT ),"
		" FOREIGN KEY (ID_DISCIPLINE)  REFERENCES DISCIPLINE  (ID_DISCIPLINE) ON DELETE CASCADE ON UPDATE NO ACTION , "
		" FOREIGN KEY (ID_STUDENT)  REFERENCES STUDENT  (ID_STUDENT) ON DELETE CASCADE ON UPDATE NO ACTION ); ";
		
	try
	{
		int exit1 = 0;
		int exit2 = 0;
		int exit3 = 0;
		int exit  = 0;
		exit = sqlite3_open(s, &DB);
		sqlite3_exec(DB, "PRAGMA foreign_keys = ON;", 0, 0, 0);
		//sqlite3_exec(DB, "COMMIT; PRAGMA foreign_keys = ON; BEGIN TRANSACTION", 0, 0, 0);

		if (exit)
		{
			cerr << " ERROR OPEN DB " << sqlite3_errmsg(DB) << endl;
			return -1;
		}
		else
		{
			cout << "OPENED DATASE SUCCESSFULLY ! " << endl;
		}
		char* messageError1;
		char* messageError2;
		char* messageError3;
		exit1 = sqlite3_exec(DB, sql_STUDENT.c_str(), NULL, 0, &messageError1);
		exit2 = sqlite3_exec(DB, sql_DISCIPLINE.c_str(), NULL, 0, &messageError2);
		exit3 = sqlite3_exec(DB, sql_NOTE.c_str(), NULL, 0, &messageError3);

		if (exit1 != SQLITE_OK)
		{
			cerr << "Error create table STUDENT " << endl;
			sqlite3_free(&messageError1);
		}
		if (exit2 != SQLITE_OK)
		{
			cerr << "Error create table DISCIPLINE " << endl;
			sqlite3_free(&messageError2);
		}
		else if (exit3 != SQLITE_OK)
		{
			cerr << "Error create table NOTE " << endl;
			sqlite3_free(&messageError3);
		}

		else
		{
			cout << " Tables  created successfully " << endl;
		}

		sqlite3_close(DB);
	}
	catch (const std::exception& e)
	{
		cerr << e.what();
	}

	return 0;
}

**Comment by Fosocles** [comment]
How is this related to TPOT?

**Comment by Guila95** [comment]
BY THE WAY, I'VE THREE TABLES : STUDENT , NOTE, DISCIPLINE. IN THE NOTE TABLE I HAVE TWO FOREIGN KEYS "ID_DISCIPLINE" AND "ID_DISCIPLINE".

**Comment by t3chn0m4g3** [comment]
Unrelated to T-Pot. Please only post issues regarding T-Pot. Thanks for understanding.
