### ISSUE TITLE
Cowrie default logins

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#516]
Hello! I can't seem to find the "settings" used by Cowrie to login into the honeypot from the attacker's point of view. I have found userdb.txt in /data/cowrie/keys/ and according to that file, using an appropriate password, I cannot login in the first few tries or at all (many users).

I would like to know how to configure and/or change Cowrie username:password after my liking. Thank you.

**Comment by t3chn0m4g3** [comment]
There are no default logins, please review the cowrie [config](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/cowrie/dist/cowrie.cfg).

**Comment by Fosocles** [comment]
I meant how to commit the change in the cowrie.cfg to have UserDB instead of AuthRandom?

**Comment by t3chn0m4g3** [comment]
You can use docker volumes for that. In the Wiki you will find an example.

**Comment by Fosocles** [comment]
I managed to solve the problem. Thank you!
