### ISSUE TITLE
Tanner failure without setenforce on CentOS 7 (SELinux)

### ISSUE THREAD

**Issue by GSMcNamara** [dtag-dev-sec/tpotce#517]
The snare server may serve a 500 error because Tanner has a failure. Within the /tmp/tanner/tanner.err file in the tanner Docker container you may see an error message such as "PermissionError: [Errno 13] Permission denied: '/var/log/tanner/tanner_report.json'" 

If so, you may have to do this bad workaround: 
setenforce 0 
docker exec -it -u 0 tanner /bin/sh
touch /var/log/tanner/tanner_report.json 
chmod 777 /var/log/tanner/tanner_report.json
exit container

---

uname -a: Linux li1291-223 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

---
Can an update in the Tanner Dockerfile fix this?

**Comment by t3chn0m4g3** [comment]
At the moment T-Pot is only developed for Debian. If you wish to use CentOS or maybe only use Snare / Tanner you might want to the check [here](https://github.com/mushorg).

**Comment by GSMcNamara** [comment]
Thank you
