### ISSUE TITLE
Attack Replay

### ISSUE THREAD

**Issue by sphereict** [dtag-dev-sec/tpotce#52]
HI 

I have completed the details below. Please could you advise me as to whether or not it is possible to replay attacks. This is a great advantage in Kippo and was wondering if the same is possible in T-Pot. If possible how do I replay the attack. Can this also be achieved with Kibana

I am also looking for the Payloads that is being recorded or captured as I would like to analyse the payloads. Where do I find this ? Can this also be viewed on Kibana dashboard for quick access ?

Looking forward to your reply.

Sincerely.
Gerhard
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 16.03
- Are you running on a Intel NUC or a VM? Production system on Hardware
- How long has your installation been running?  4 days
- Did you install any upgrades or packages? As per ISO image
- Did you modify any scripts? Nope
- Have you turned persistence on/off? On
- How much RAM available (login via ssh and run `htop`)? 18,053mb
- How much stress are the CPUs under (login via ssh and run `htop`)? No stress at all I am using a Xeon Processor
- How much swap space is being used (login via ssh and run `htop`)? 0
- How much free disk space is available (login via ssh and run `sudo df -h`)? 1Terabyte
- What is the current container status (login via ssh and run `sudo start.sh`)? started

**Comment by t3chn0m4g3** [comment]
T-Pot uses Cowrie (https://github.com/micheloosterhof/cowrie) as SSH honeypot, which is based on Kippo.





Beste Grüße,
Marco.

**Comment by sphereict** [comment]
Hi

Thank you for the reply. Can you reply attack same as kippo via the web interface ?

Sincerely.

[gerhard_email_sig_big]

**Comment by t3chn0m4g3** [comment]
The web interface (Kibana) is completely used for showing logs.

**Comment by SaiGonSeamus** [comment]
"I am also looking for the Payloads that is being recorded or captured as I would like to analyse the payloads. Where do I find this?"

I am interested in extracting the samples for analysis as well, how is this done?

**Comment by t3chn0m4g3** [comment]
All the honeypot logs and captures are stored on the host in `/data/<honeypot>`.

**Comment by sphereict** [comment]
thanks for the info. I have tried to access the data file on the host but my access is denied. i tried using sudo cd /data/ and then i am asked for a password which I type in the password either tsec or the one I added in the begining. However it states sudo cd /data/ no commands sudo cd

what do i do know ?

**Comment by sphereict** [comment]
Any feedback regarding not being able to access the /data/honeypot folder ? as described above.
Thanks
Gerhard

**Comment by t3chn0m4g3** [comment]
Run a `sudo su -` and then `cd /data/` and you should be good.

Closing this issue since the original question has been answered.
