### ISSUE TITLE
error(s) in /etc/tpot/update.sh

### ISSUE THREAD

**Issue by workandresearchgithub** [dtag-dev-sec/tpotce#520]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
--
[root@loudweakness:/home/tsec]# lsb_release -a  && uname -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
Linux loudweakness 5.4.0-2-amd64 #1 SMP Debian 5.4.8-1 (2020-01-05) x86_64 GNU/Linux
--
- What T-Pot version are you currently using?
--
[root@loudweakness:/home/tsec]# cat /opt/tpot/version
19.03.1
--
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nexgen
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
--
Baremetal – Dell M4800, 16 gig RAM, 256gig SSD
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No problems, though I noticed some errors scroll by (files attached)
Including dmesg output as this error:
[    0.361893] ACPI BIOS Error (bug): Could not resolve symbol [^CPU0._PPC], AE_NOT_FOUND (20190816/psargs-330)
--
- How long has your installation been running?
A few hours
- Did you install upgrades, packages or use the update script?
No upgrades or packages additions.  Ran /opt/tpot/update.sh, and encounterd this error:
--
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/taskrabbit/elasticsearch-dump.git /root/.npm/_cacache/tmp/git-clone-01be0412/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-01be0412/.git'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-19T01_57_16_024Z-debug.log
(2020-01-19T01_57_16_024Z-debug.log attached)
--
- Did you modify any scripts or configs? If yes, please attach the changes.
Added static IP in /etc/network/interfaces and created /etc/network/interfaces.d/eno1 with the same info
Made change to logstash config to send data to my security onion server:
vi /opt/tpot/docker/elk/logstash/dist/logstash.conf:
--
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
#    document_type => "doc"
  }
  elasticsearch {
    hosts => ["<my security onion server>:9200"]
  }
--
cd /tmp && docker cp logstash:/etc/logstash/conf.d/logstash.conf . && vi logstash.conf
--
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
#    document_type => "doc"
  }
  elasticsearch {
    hosts => ["<my security onion server>:9200"]
  }
--
 docker cp logstash.conf  logstash:/etc/logstash/conf.d/logstash.conf

- Please provide a screenshot of `glances` and `htop`.
(attached)
- How much free disk space is available (`df -h`)?
--
[root@loudweakness:/home/tsec]# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G   12M  1.6G   1% /run
/dev/sda2       227G  7.5G  208G   4% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/5308565f93e0a65e693c92242420747866cb461e97d2eeae114dc6fef86ab846/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/6ffd1447848dc755b3fc563d5bc3f45bfc6d8fe4680bfbe28057e0906eca45ad/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/962a623c9e9cea2aa6bc44a4672598e0de4661bfda7874b1e507606050325c3a/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/89f2ba10ebd00b9fd96e8c7c2a765b07456d4ed8114af6c0ac37ece5f152c898/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/9718061b3c6a3f9f20782af5b664cbc8735ff4d1bca3519c76c7206d0bb77296/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/304ddcb5815cec3bd722851d69c0fd2335bc1c5f95eecc707886f762460afa28/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/701a542f9dce9378ded4f58610f63cc2a2916b6c4de282fa18559713281cd266/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/531a3b308f14515419767b4430f2b8d8add74cca03f3aa6f2f692c2affdc6838/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/396a0dc0a674843ebbffe8ccd130b8f1f08e2a6b7f459e33a361bc2aae412855/merged
shm              64M     0   64M   0% /var/lib/docker/containers/913bf1ed91d5dfa125ce45727dc65c4b736987e7f9d6fa043b884cfc5c480b4d/mounts                     /shm
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/8e91af0d13ea5a1b076733989fa794c9cb6a576fdceae7c5817844009f0256bb/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/8d3e445cb9dd40827e6a8e74e32d325fc358af367fb3b55b2dcbe721039aa16f/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/f5430a896ad5fcd37c85e09ae518949ae15c478fa4c29f28b8e4c3a92b61de1a/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/16eb66c57943e316948cd72c49569cbb28728f508b70a0cf82222aa8ad35f7bd/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/a2b57ad9650ef38de683d47a597f58256c4852aeb3dc63b862ddbfedfc2e8dec/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/b42c3efc59bb30452eac6648058be726bba25a744d076da04fdb7fa274389935/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/67da449840ad76c001711afd8f3def42b840c9faa523781d4f3d9f42fbb617ba/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/5e3a28541b9b3b3b8ae0f0d65febb8d72c7a076c64f1a6a5c9258ca3ba0c2208/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/822760a92fd4f812f95459a87831c4492e36d20645696f4a6fa67302535a13d0/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/1d1d171a6358b8d747ba60a3be5852ef05f5810619f5dd9250d97344f4f1ed57/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/f7b78149493b4a769d35fd83a68aeb168ff5298b28452163bb20460e79953353/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/121cfc1fa58100d1d17d334cfc51f4630aafed501ed7e5eab1d22d62c44b8925/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/d7d536d7f6c42c2953c53d114cae7d10b1cc87b0808b788cea525c0eed360305/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/d174f49152ecc77005b329c8b9ef492d421ce1cc14ff330b265c048ce7e39e8c/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/cd94fd0e38a3b162965fe85761cd14598272029cbb03482062a5f6d71909bf7a/merged
shm              64M     0   64M   0% /var/lib/docker/containers/ca52378fdb6ef77da65f15f39ff0f9f4b6ca00a6e1b8f15acdaf43151d576ce9/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/0f3805d1c180aefbfeee443c13273e5a54b13a9c71e60393d5f987df02dfe6c8/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/c729a3e6d560a1081f68a7992b400339c09be44422bd8a164aecb31598ad9081/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/296e07e2408ffd6336b7ed9ade883a13c472cad1ca4a8c1a59d536cd677a2d56/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/3b4d7b3440c4707eebc46ac7964c3b72e82ecccb1545fc87a5fc63657de9b739/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/8f218149ea20621c91757faf1b192198eef0cf7f37381bed1778dd024fccf998/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/b1c7118f49275fe41fc128980b81b584e111eeb0f83795cc74d831c0db3f5e79/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/2292ac312913c80349fb8db147ca002b85c3b091056457fd47b0f5f3fb073f80/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/5d40aefb0ade6902abd518e3ec61acd079fcefc5b4e4e6195ced971ee6bb1185/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/6456596063ea54917d4af8a128541e183dba103187c076e341ca649f3d775ed5/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/e8554ca510fc0836cc860d8358139bea650ffc04e88d876e6f7c23ea7786dbaa/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/0b929bdbd01a45956c6af848082eff5fedb58bf13e44ec3d017623a295a9c8a6/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/f405c606d92b8c0cacaea6a7b050b527b5040f17a3dc7509f10c0d3760b4576b/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/c93c10bc47bb77718d1467091c957b43ec52f1509fb3aefa48578bea5e7086ae/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/67d33629da3750b7e0c33cdb84690c6d14952a7548c21201405dfd78f3158d9c/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/bcbbf577377ac77f4e35ade3e8b9d7c98b7ed6b66ffe7d6df5ee2923070bb197/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/3ef16c3ca8e8bca4a3dcf863282efc418ab74e417f98c87c7b363aa96119a926/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/7548741063cf7795b1d0fb275a60bbccd3ccf04746798c6b1bc8cebeb0e4df01/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/c60604cf31d7a564802059a6bef476e2e27ab2f807ca629e1fbb3f2e4babd200/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/ba60e98fc3edaedccaaa29616e619906e65f939f990f43bedd12a00650e1fccb/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/e2f7fd2df5ef6eec6fc1fad42fa3a68d9249e988f635e0400f18dc323d004f94/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/d16eac805932bdd9bb335283029248860cb9e2d9b12debca7cea28db9912840f/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/8854eaea2e693df570edc03b022c1d41e45724d1c60ade6ccc5bafb6f2f83c32/mounts                     /shm
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/92673faa008829287c24865798c24cc6d5b9e78ae43457dc411893e36b12ba1e/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/08b1a7a3438c76e3d35726c4615f2bd123da3c1bed84e8faf9c7d263ff010f33/merged
shm              64M     0   64M   0% /var/lib/docker/containers/375b950884b0c00f876fb2401a84a81aaa2723c494f89bc057e752679fad066f/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/7d2ce856f854e56bb575041d6415dcb942b784d994603f5411f771c68784a4da/mounts                     /shm
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/ee4a558cf8e6eca6659d7885356aace2af3e5ffce39f6c510a3a1eb55edc8d86/merged
shm              64M     0   64M   0% /var/lib/docker/containers/57e17e6049853be948371ddda8195d0d488a8746e1e6ee87aa65eb02848cdf57/mounts                     /shm
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/ce483ffb82b002766476d6b9df3a7030c370b797c7083b8ac50042dda5d79b8f/merged
shm              64M   20K   64M   1% /var/lib/docker/containers/287f5670731d8856427fb3a15f6c687ba04e18b155cc96eabb55fbebad876932/mounts                     /shm
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/3e34dc0f9bf3110944273d74be7d0f0489dd6ca47c7d326fa6a2159ade394a90/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/01d6e188cec93e3542dc2e65eba1f4b78ff022cf6a2c74367191d1ae47c559b0/merged
overlay         227G  7.5G  208G   4% /var/lib/docker/overlay2/361d5b31a9606480dd3ab89452dfb1b1c18a597a741a1c853b5adb252ad5574a/merged
shm              64M     0   64M   0% /var/lib/docker/containers/33f959812cc8f0727c29ef330bfb448821e500875e0238cd43214e72c75d0854/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/212ae2bad4a60f6e1189d53e55f5f6a4b8690c59192ede2c35a69a18b8c21c21/mounts                     /shm
shm              64M     0   64M   0% /var/lib/docker/containers/c2650b0012e65ddb113f6d6c205d17d4ea82a69ced7cf6c23085373ad079b95b/mounts                     /shm
tmpfs           1.6G     0  1.6G   0% /run/user/1000
--
- What is the current container status (`dps.sh`)?
--
[root@loudweakness:/home/tsec]# dps.sh
========| System |========
    Date:  Sun 19 Jan 2020 01:42:42 AM UTC
  Uptime:  01:42:42 up 50 min,  1 user,  load average: 0.33, 0.34, 0.29

NAME                  STATUS                       PORTS
adbhoney              Up 49 minutes             0.0.0.0:5555->5555/tcp
ciscoasa              Up 49 minutes
citrixhoneypot        Up 49 minutes             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 49 minutes             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 49 minutes             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 49 minutes             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 49 minutes             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 49 minutes             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 49 minutes (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 49 minutes
elasticsearch         Up 49 minutes (healthy)   127.0.0.1:64298->9200/tcp
fatt                  Up 49 minutes
glutton               Up 49 minutes
head                  Up 49 minutes (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 49 minutes             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 49 minutes             0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 49 minutes (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 49 minutes (healthy)
mailoney              Up 49 minutes             0.0.0.0:25->25/tcp
medpot                Up 49 minutes             0.0.0.0:2575->2575/tcp
nginx                 Up 49 minutes
p0f                   Up 49 minutes
rdpy                  Up 49 minutes             0.0.0.0:3389->3389/tcp
snare                 Up 49 minutes             0.0.0.0:80->80/tcp
spiderfoot            Up 49 minutes (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 49 minutes
tanner                Up 49 minutes
tanner_api            Up 49 minutes
tanner_phpox          Up 49 minutes
tanner_redis          Up 49 minutes             6379/tcp
tanner_web            Up 49 minutes
--
- What is the status of the T-Pot service (`systemctl status tpot`)?
--
[root@loudweakness:/home/tsec]# systemctl status tpot
? tpot.service - tpot
     Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2020-01-19 00:52:41 UTC; 50min ago
    Process: 1037 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
    Process: 1066 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
    Process: 1178 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
    Process: 1181 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
    Process: 1184 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
    Process: 1209 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
    Process: 1233 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
    Process: 1258 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
    Process: 1285 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (>
    Process: 1291 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=>
    Process: 1297 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exit>
    Process: 1303 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
   Main PID: 1378 (docker-compose)
      Tasks: 33 (limit: 19071)
     Memory: 121.7M
     CGroup: /system.slice/tpot.service
             ??1378 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Jan 19 01:43:02 loudweakness docker-compose[1378]: dionaea                | [19012020 01:43:02] connection /root/dionaea/src/connection_tcp.c:290: recv fail>
Jan 19 01:43:05 loudweakness docker-compose[1378]: dionaea                | [19012020 01:43:05] connection /root/dionaea/src/connection_tcp.c:290: recv fail>
Jan 19 01:43:08 loudweakness docker-compose[1378]: elasticsearch          | [2020-01-19T01:43:08,786][INFO ][o.e.c.m.MetaDataMappingService] [tpotcluster-no>
Jan 19 01:43:08 loudweakness docker-compose[1378]: elasticsearch          | [2020-01-19T01:43:08,816][INFO ][o.e.c.m.MetaDataMappingService] [tpotcluster-no>
Jan 19 01:43:09 loudweakness docker-compose[1378]: dionaea                | [19012020 01:43:09] connection /root/dionaea/src/connection_tcp.c:290: recv fail>
Jan 19 01:43:12 loudweakness docker-compose[1378]: dionaea                | [19012020 01:43:12] connection /root/dionaea/src/connection_tcp.c:290: recv fail>
Jan 19 01:43:13 loudweakness docker-compose[1378]: head                   | [Sun Jan 19 2020 01:43:13 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7>
Jan 19 01:43:13 loudweakness docker-compose[1378]: kibana                 | {"type":"response","@timestamp":"2020-01-19T01:43:13Z","tags":[],"pid":1,"method>
Jan 19 01:43:13 loudweakness docker-compose[1378]: cyberchef              | [Sun Jan 19 2020 01:43:13 GMT+0000 (Coordinated Universal Time)]  "GET /" "curl/>
Jan 19 01:43:15 loudweakness docker-compose[1378]: dionaea                | [19012020 01:43:15] connection /root/dionaea/src/connection_tcp.c:290: recv fail>
--
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
--
[root@loudweakness:/home/tsec]# systemctl stop tpot && netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          12973      837/sshd
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          16027      814/python3
tcp6       0      0 :::64294                :::*                    LISTEN      0          15710      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          12975      837/sshd
udp        0      0 192.168.16.1:123        0.0.0.0:*                           108        44451      835/ntpd
udp        0      0 192.168.0.1:123         0.0.0.0:*                           108        44449      835/ntpd
udp        0      0 172.31.0.1:123          0.0.0.0:*                           108        44447      835/ntpd
udp        0      0 172.30.0.1:123          0.0.0.0:*                           108        44445      835/ntpd
udp        0      0 172.29.0.1:123          0.0.0.0:*                           108        44443      835/ntpd
udp        0      0 172.28.0.1:123          0.0.0.0:*                           108        44441      835/ntpd
udp        0      0 172.27.0.1:123          0.0.0.0:*                           108        44439      835/ntpd
udp        0      0 172.26.0.1:123          0.0.0.0:*                           108        44437      835/ntpd
udp        0      0 172.25.0.1:123          0.0.0.0:*                           108        44435      835/ntpd
udp        0      0 172.24.0.1:123          0.0.0.0:*                           108        44433      835/ntpd
udp        0      0 172.23.0.1:123          0.0.0.0:*                           108        44431      835/ntpd
udp        0      0 172.22.0.1:123          0.0.0.0:*                           108        44429      835/ntpd
udp        0      0 172.21.0.1:123          0.0.0.0:*                           108        44427      835/ntpd
udp        0      0 172.20.0.1:123          0.0.0.0:*                           108        44425      835/ntpd
udp        0      0 172.19.0.1:123          0.0.0.0:*                           108        44423      835/ntpd
udp        0      0 172.18.0.1:123          0.0.0.0:*                           108        44421      835/ntpd
udp        0      0 192.168.41.138:123      0.0.0.0:*                           0          23787      835/ntpd
udp        0      0 192.168.111.33:123      0.0.0.0:*                           0          23785      835/ntpd
udp        0      0 192.168.41.241:123      0.0.0.0:*                           0          23783      835/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          23781      835/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          23777      835/ntpd
udp6       0      0 :::123                  :::*                                0          23774      835/ntpd
--

Issue:  Ran tpot update script (/opt/tpot/update.sh), and encounterd this error:
--
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/taskrabbit/elasticsearch-dump.git /root/.npm/_cacache/tmp/git-clone-01be0412/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-01be0412/.git'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-19T01_57_16_024Z-debug.log
(2020-01-19T01_57_16_024Z-debug.log attached)
--
Attachments:
[2020-01-19T01_57_16_024Z-debug.log](https://github.com/dtag-dev-sec/tpotce/files/4082155/2020-01-19T01_57_16_024Z-debug.log)
[dmesg_output.txt](https://github.com/dtag-dev-sec/tpotce/files/4082156/dmesg_output.txt)
![glances-2020-01-18 194038](https://user-images.githubusercontent.com/38447728/72673412-bc955a80-3a2f-11ea-969f-fa8cbdbc796d.jpg)
![htop-2020-01-18 194134](https://user-images.githubusercontent.com/38447728/72673413-bc955a80-3a2f-11ea-8ee6-90ea03bda461.jpg)
[install.err.txt](https://github.com/dtag-dev-sec/tpotce/files/4082157/install.err.txt)
[install.log](https://github.com/dtag-dev-sec/tpotce/files/4082158/install.log)
[syslog.txt](https://github.com/dtag-dev-sec/tpotce/files/4082159/syslog.txt)
[messages.txt](https://github.com/dtag-dev-sec/tpotce/files/4082164/messages.txt)

**Comment by t3chn0m4g3** [comment]
Thanks for reporting.
1. I cannot reproduce the `npm` error, neither as part of `update.sh` nor from command line. Please run as root (`sudo su -`) `npm install "https://github.com/taskrabbit/elasticsearch-dump" -g`, but do not update `npm` as the output says. I am guessing there was an upstream issue which has been resolved since.
2. The reported ACPI bug might be hardware specific. Since we are using Debian we are relying on its hardware support. As such please check with Debian (as suggested in `syslog.txt`, if the issue is specific to your hardware and if workarounds and firmware updates are available. Also check with Dell if they are offering updated drivers for download.

**Comment by workandresearchgithub** [comment]
--
[root@loudweakness:/home/tsec]# npm install "https://github.com/taskrabbit/elasticsearch-dump" -g
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/taskrabbit/elasticsearch-dump.git /root/.npm/_cacache/tmp/git-clone-5c81cfd7/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-5c81cfd7/.git'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-21T02_29_49_642Z-debug.log
--
[2020-01-21T02_29_49_642Z-debug.log](https://github.com/dtag-dev-sec/tpotce/files/4088925/2020-01-21T02_29_49_642Z-debug.log)

**Comment by t3chn0m4g3** [comment]
Sorry, cannot reproduce.

**Comment by workandresearchgithub** [comment]
on a lark, I just tried adding sudo in front of the command, and it worked?
--
[root@loudweakness:/opt/tpot]# sudo npm install "https://github.com/taskrabbit/elasticsearch-dump" -g
/usr/local/bin/elasticdump -> /usr/local/lib/node_modules/elasticdump/bin/elasticdump
/usr/local/bin/multielasticdump -> /usr/local/lib/node_modules/elasticdump/bin/multielasticdump
+ elasticdump@6.18.0
updated 1 package in 3.754s
--

but if I remove sudo, it doesn't:
--
[root@loudweakness:/opt/tpot]# npm install "https://github.com/taskrabbit/elasticsearch-dump" -g
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/taskrabbit/elasticsearch-dump.git /root/.npm/_cacache/tmp/git-clone-85597777/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-85597777/.git'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-21T17_52_23_962Z-debug.log
--


So, I edited update.sh, and added sudo in front of the npm command:
--
....
193 dpkg --configure -a
194 sudo npm install "https://github.com/taskrabbit/elasticsearch-dump" -g
195 pip3 install --upgrade elasticsearch-curator yq
...
--
.....re-ran it....  and it didn't work??  Looked in the file, and somehow it reverted back?
--
....
193 dpkg --configure -a
194 npm install "https://github.com/taskrabbit/elasticsearch-dump" -g
195 pip3 install --upgrade elasticsearch-curator yq
....
--

I'm thinking the sudo thing will fixi it.......but apparently the update.sh shell script is replaced during the runtime.........and it's over-writing my change before that line is executed? (https://stackoverflow.com/questions/3398258/edit-shell-script-while-its-running)

**Comment by workandresearchgithub** [comment]
ok......I'm a little slow sometimes.
Copied update.sh to myUpdate.sh, made the sudo change, and ran it......it worked with no errors on the npm install:
--
....
W: --force-yes is deprecated, use one of the options starting with --allow instead.
/usr/local/bin/elasticdump -> /usr/local/lib/node_modules/elasticdump/bin/elasticdump
/usr/local/bin/multielasticdump -> /usr/local/lib/node_modules/elasticdump/bin/multielasticdump
+ elasticdump@6.18.0
updated 1 package in 3.727s
....
--

So that's definitely what's need to resolve this........still no idea why running as root doesn't seem to provide the necessary permissions?

**Comment by t3chn0m4g3** [comment]
Runs fine here.
