### ISSUE TITLE
t-pot runs for several hours, then becomes unreachable via ssh, ping, and via the ELK or Cockpit administrative interfaces.

### ISSUE THREAD

**Issue by workandresearchgithub** [dtag-dev-sec/tpotce#522]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
--
[root@loudweakness:/home/tsec]# lsb_release -a  && uname -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
Linux loudweakness 5.4.0-2-amd64 #1 SMP Debian 5.4.8-1 (2020-01-05) x86_64 GNU/Linux
--

- What T-Pot version are you currently using?
--
[root@loudweakness:/home/tsec]# cat /opt/tpot/version
19.03.1
--
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nexgen
--

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
--
Baremetal – Dell M4800, 16 gig RAM, 256gig SSD
--

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No 
--

- How long has your installation been running?
A few days
--

- Did you install upgrades, packages or use the update script?
Yes

apt install locate fwupdate lrzip libsmbios-doc aha
--

- Did you modify any scripts or configs? If yes, please attach the changes.
Added static IP in /etc/network/interfaces and created /etc/network/interfaces.d/eno1 with the same info
Made change to logstash config to send data to my security onion server:
vi /opt/tpot/docker/elk/logstash/dist/logstash.conf:
--
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
#    document_type => "doc"
  }
  elasticsearch {
    hosts => ["<my security onion server>:9200"]
  }
--
cd /tmp && docker cp logstash:/etc/logstash/conf.d/logstash.conf . && vi logstash.conf
--
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
#    document_type => "doc"
  }
  elasticsearch {
    hosts => ["<my security onion server>:9200"]
  }
--
 docker cp logstash.conf  logstash:/etc/logstash/conf.d/logstash.conf

--

- Please provide a screenshot of `glances` and `htop`.

glances --export csv --export-csv-file ./glances-20200120-2200CT.csv (attached)
echo q | htop | aha --black --line-fix | html2text -width 9999 > htop-20200120-2204CT.txt (attached)

- How much free disk space is available (`df -h`)?
df -h > df-output-20200120-2222CT.txt (attached)
--

- What is the current container status (`dps.sh`)?
--
dps.sh > dps-output-20200120-2223CT.txt (see attached)
--

- What is the status of the T-Pot service (`systemctl status tpot`)?
--
systemctl status tpot > tpot-status-20200120-2208CT.txt (see attached)
--

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
--
systemctl stop tpot && netstat -tulpen > tpot-occupiedports-20200120-2210CT.txt
(see attached)
--

Issue:  t-pot runs for several hours, then becomes unreachable via ssh, ping, and via the ELK or Cockpit interfaces.
Manually logging in and rebooting resolves the issue.

I've looked through the logs and don't see anything that jumps out at me, but having said that, I have no idea what to look for.........The last time it occurred, my ssh session, with was running htop, showed that when the ssh session disconnected it had an uptime of 12 hours. 

I've updated the crontab so it is now rebooting every 6 hours, but ideally I'm hoping it can be stable enough to run indefinitely without requiring a frequent reboot.  

Can you point me in the direction to identify the issue that's causing it to become unreachable?
--
Attachments:
[df-output-20200120-2222CT.txt](https://github.com/dtag-dev-sec/tpotce/files/4089169/df-output-20200120-2222CT.txt)
[dps-output-20200120-2223CT.txt](https://github.com/dtag-dev-sec/tpotce/files/4089170/dps-output-20200120-2223CT.txt)
[htop-20200120-2204CT.txt](https://github.com/dtag-dev-sec/tpotce/files/4089171/htop-20200120-2204CT.txt)
[tpot-occupiedports-20200120-2210CT.txt](https://github.com/dtag-dev-sec/tpotce/files/4089172/tpot-occupiedports-20200120-2210CT.txt)
[tpot-status-20200120-2208CT.txt](https://github.com/dtag-dev-sec/tpotce/files/4089173/tpot-status-20200120-2208CT.txt)
--

**Comment by t3chn0m4g3** [comment]
According to your logs nothing particular is popping up. However we do not support all [hardware](https://github.com/dtag-dev-sec/tpotce#hardware). According to your other issues there are some hardware errors. Unfortunately I cannot reproduce this behavior.

**Comment by workandresearchgithub** [comment]
is the Nexgen edition considered to be more unstable than other editions?

What edition would you recommend if we want to make this part of our production environment?
The other question I have regards the scheduled reboots........do all editions do that?  does t-mobile do that in their production t-pots?

**Comment by t3chn0m4g3** [comment]
Please conside reading the documentaion / readme before running in production.
