### ISSUE TITLE
How to customize Snare/Tanner

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#523]
Hi. I'm trying to customize the webpages Snare is serving, but can't understand how to edit any of the 10 preinstalled sites so I made a site of my own and cloned it. The problem is, I don't know how to change _--page-dir $(shuf -i 1-10 -n 1)_ to my site directory or how to start another Snare instance in Cockpit (when I do run a new instance, it cannot connect to Tanner) and making it serve my site.

**Comment by t3chn0m4g3** [comment]
Please check with the [documentation ](https://github.com/mushorg) of Snare / Tanner and review our Dockerfiles regarding Snare / Tanner. Thank you.

**Comment by Fosocles** [comment]
Could we talk some other way because you always give me these short, vague answers which don't really help me out in any way. (Also, I've already checked the documentation. Had I found an answer to my problem, I wouldn't have opened an issue). Thank you.

**Comment by Fosocles** [comment]
No response yet. Still waiting.
