### ISSUE TITLE
Dionaea errors

### ISSUE THREAD

**Issue by xcampax** [dtag-dev-sec/tpotce#527]
# Issues

Hello,

After a fresh install last Friday, I am seeing the following Dionaea errors in the daemon.log:

#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.26.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.30.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.28.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.18.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 192.168.16.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 10.12.97.65:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.25.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.27.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.29.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 127.0.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.23.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 192.168.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.24.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.21.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.19.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 192.168.32.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.20.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.22.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.31.0.1:443 (Address already in use)
#033[35;1mconnection#033[0m /root/dionaea/src/connection.c:218: Could not bind 172.17.0.1:443 (Address already in use)

I found a hint in the Dionaea documentation that Dionaea needs to be rebuilt with kernel-headers installed, but since this is a docker image, I cannot do that, right? How can this be solved?

Thanks :)
Nora

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

What version of the OS are you currently using lsb_release -a and uname -a?
Description: Debian GNU/Linux bullseye/sid
Release: unstable
Codename: sid

What T-Pot version are you currently using?
T-Pot 19.03.1

What edition (Standard, Nextgen, etc.) of T-Pot are you running?
NextGen

What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM

Did you have any problems during the install? If yes, please attach /install.log /install.err.
not with T-Pot itself but dependency issues: had to install elasticsearch-curator and create docker service drop-in manually

How long has your installation been running?
a few days

Did you install upgrades, packages or use the update script?
yes.

Did you modify any scripts or configs? If yes, please attach the changes.
no

Please provide a screenshot of glances and htop.

How much free disk space is available (df -h)?

What is the current container status (dps.sh)?
========| System |========
Date: Mon 27 Jan 2020 08:43:40 AM CET
Uptime: 08:43:40 up 37 min, 2 users, load average: 0.43, 0.27, 0.54

NAME STATUS PORTS
adbhoney Up 36 minutes 0.0.0.0:5555->5555/tcp
ciscoasa Up 36 minutes
citrixhoneypot Up 36 minutes 0.0.0.0:443->443/tcp
conpot_guardian_ast Up 36 minutes 0.0.0.0:10001->10001/tcp
conpot_iec104 Up 36 minutes 0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi Up 36 minutes 0.0.0.0:623->623/tcp
conpot_kamstrup_382 Up 36 minutes 0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie Up 36 minutes 0.0.0.0:22-23->22-23/tcp
cyberchef Up 36 minutes (healthy) 127.0.0.1:64299->8000/tcp
dionaea Up 36 minutes
elasticsearch Up 36 minutes (healthy) 127.0.0.1:64298->9200/tcp
ewsposter Up 28 seconds
fatt Up 36 minutes
glutton Up 36 minutes
head Up 35 minutes (healthy) 127.0.0.1:64302->9100/tcp
heralding Up 36 minutes 0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy Up 36 minutes 0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana Up 35 minutes (healthy) 127.0.0.1:64296->5601/tcp
logstash Up 35 minutes (healthy)
mailoney Up 36 minutes 0.0.0.0:25->25/tcp
medpot Up 36 minutes 0.0.0.0:2575->2575/tcp
nginx Up 36 minutes
p0f Up 36 minutes
rdpy Up 36 minutes 0.0.0.0:3389->3389/tcp
snare Up 36 minutes 0.0.0.0:80->80/tcp
spiderfoot Up 36 minutes (healthy) 127.0.0.1:64303->8080/tcp
suricata Up 36 minutes
tanner Up 36 minutes
tanner_api Up 36 minutes
tanner_phpox Up 36 minutes
tanner_redis Up 36 minutes 6379/tcp
tanner_web Up 36 minutes

What is the status of the T-Pot service (systemctl status tpot)?
● tpot.service - tpot
Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
Active: active (running) since Mon 2020-01-27 08:07:07 CET; 36min ago
Process: 983 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
Process: 1563 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
Process: 1683 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
Process: 1686 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
Process: 1694 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
Process: 1713 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
Process: 1733 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
Process: 1751 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "" | awk '{print $3}') (code=exited, status=1/FAILURE)
Process: 1774 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
Process: 1780 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
Process: 1786 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
Process: 1792 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
Main PID: 1873 (docker-compose)
Tasks: 33 (limit: 9489)
Memory: 55.8M
CGroup: /system.slice/tpot.service
└─1873 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color
Jan 27 08:42:20 atgrzsl3245 docker-compose[1873]: head | [Mon Jan 27 2020 07:42:20 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.65.1"
Jan 27 08:42:49 atgrzsl3245 docker-compose[1873]: cyberchef | [Mon Jan 27 2020 07:42:49 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.66.0"
Jan 27 08:42:50 atgrzsl3245 docker-compose[1873]: kibana | {"type":"response","@timestamp":"2020-01-27T07:42:50Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0>
Jan 27 08:42:50 atgrzsl3245 docker-compose[1873]: head | [Mon Jan 27 2020 07:42:50 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.65.1"
Jan 27 08:43:19 atgrzsl3245 docker-compose[1873]: cyberchef | [Mon Jan 27 2020 07:43:19 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.66.0"
Jan 27 08:43:20 atgrzsl3245 docker-compose[1873]: kibana | {"type":"response","@timestamp":"2020-01-27T07:43:20Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0>
Jan 27 08:43:20 atgrzsl3245 docker-compose[1873]: head | [Mon Jan 27 2020 07:43:20 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.65.1"
Jan 27 08:43:49 atgrzsl3245 docker-compose[1873]: cyberchef | [Mon Jan 27 2020 07:43:49 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.66.0"
Jan 27 08:43:51 atgrzsl3245 docker-compose[1873]: kibana | {"type":"response","@timestamp":"2020-01-27T07:43:51Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0>
Jan 27 08:43:51 atgrzsl3245 docker-compose[1873]: head | [Mon Jan 27 2020 07:43:51 GMT+0000 (Coordinated Universal Time)] "GET /" "curl/7.65.1"

What ports are being occupied? Stop T-Pot systemctl stop tpot and run netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address Foreign Address State User Inode PID/Program name
tcp 0 0 127.0.0.1:61209 0.0.0.0:* LISTEN 0 20477 619/python3
tcp 0 0 0.0.0.0:64295 0.0.0.0:* LISTEN 0 22020 640/sshd
tcp6 0 0 :::64294 :::* LISTEN 0 20756 1/init
tcp6 0 0 :::64295 :::* LISTEN 0 22022 640/sshd
udp 0 0 192.168.16.1:123 0.0.0.0:* 107 24126 637/ntpd
udp 0 0 10.12.97.65:123 0.0.0.0:* 0 20356 637/ntpd
udp 0 0 127.0.0.1:123 0.0.0.0:* 0 20354 637/ntpd
udp 0 0 0.0.0.0:123 0.0.0.0:* 0 20350 637/ntpd
udp6 0 0 :::123 :::* 0 20347 637/ntpd

If a single container shows as DOWN you can run docker logs for the latest log entries

**Comment by t3chn0m4g3** [comment]
This is correct and nothing to worry about. While the Dionaea docker image ist confgiured to bind to tcp/443 its disabled in the tpot.yml in favor of citrixhoneypot.
