### ISSUE TITLE
📢 Announcement: Attention NextGen 19.03.x users 📢

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#528]
Within the next couple of days NextGen edition will receive a new image for Nginx including a new landing page. If you want to be amongst the first to checkout the new landing page just run the `/opt/tpot/update.sh` as root (`sudo su -`).

![tpot](https://user-images.githubusercontent.com/4318452/73197319-6318e400-4131-11ea-82c4-6be8fbc933fb.png)

**Comment by Patrik-Hansson** [comment]
Just upgraded, looks great !
