### ISSUE TITLE
Disable SIP traffic for Dionaea

### ISSUE THREAD

**Issue by Patrik-Hansson** [dtag-dev-sec/tpotce#529]
Trying to get rid of SIP traffic part of Dionaea. I'v commented out the ports in
/opt/tpot/etc/tpot.yml and then it doesn't show up in cockpit anymore. But there is still traffic showing up. Is there somewhere else i need to change/remote ports ?

tpot.yaml
# Dionaea service
  dionaea:
    container_name: dionaea
    stdin_open: true
    tty: true
    restart: always
    network_mode: "host"
    ports:
     - "20:20"
     - "21:21"
     - "42:42"
     - "69:69/udp"
     - "81:81"
     - "135:135"
     # - "443:443"
     - "445:445"
     - "1433:1433"
     - "1723:1723"
     - "1883:1883"
     - "3306:3306"
     # - "5060:5060"
     # - "5060:5060/udp"
     # - "5061:5061"
     - "27017:27017"
    image: "dtagdevsec/dionaea:1903"
    read_only: true
    volumes:
     - /data/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
     - /data/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
     - /data/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
     - /data/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
     - /data/dionaea:/opt/dionaea/var/dionaea
     - /data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
     - /data/dionaea/log:/opt/dionaea/var/log
     - /data/dionaea/rtp:/opt/dionaea/var/dionaea/rtp

cockpit:
0.0.0.0:135 -> 135/tcp
0.0.0.0:1433 -> 1433/tcp
0.0.0.0:1723 -> 1723/tcp
0.0.0.0:1883 -> 1883/tcp
0.0.0.0:20 -> 20/tcp
0.0.0.0:21 -> 21/tcp
0.0.0.0:27017 -> 27017/tcp
0.0.0.0:3306 -> 3306/tcp
0.0.0.0:42 -> 42/tcp
0.0.0.0:445 -> 445/tcp
0.0.0.0:69 -> 69/udp
0.0.0.0:81 -> 81/tcp

**Comment by t3chn0m4g3** [comment]
Dionaea runs on the host network stack to ensure FTP works as well. Commenting the port statements, only in this case as it runs on the host network stack, will not change what ports and services are offered by Dionaea. For this you need to change the config using a docker volume. Check out the Wiki for an example.
However the ports section is used by the firewall rules script. removing comments and such will result in traffic forwarded to NFQ (honeytrap, glutton) instead of the desired hp.

**Comment by Patrik-Hansson** [comment]
Thanks, pointed me in the right direction. Think i managed to use a volume to remove sip.yaml.
But that's not the only reason for nagging you ;) the ews.conf part of the wiki says "ash" where i believe it should say "bash". New to github so don't know if i can edit the wiki myself.

**Comment by t3chn0m4g3** [comment]
`ash` is the Alpine shell 😉

**Comment by Patrik-Hansson** [comment]
.....do i feel stupid.
