### ISSUE TITLE
Adding Decoy documents embedded with a reverse connection.

### ISSUE THREAD

**Issue by sphereict** [dtag-dev-sec/tpotce#53]
I would like to know how I can leave a decoy document for an attacker to download and once opened creates a reverse_tcp connection to my system in order to gather more intel on the attacker obviously using this to own his system. If he is stupid enough to fall for this, however no harm in trying. 

i would like to leave the documents on cowrie section as this is were the honeypot seems to record the most activity. when the attacker type's ls then a folder should be shown and inside the folder I would like to leave these documents / beacons for him/her. 

Could you be so kind as to guide me through to the process. I have tried login as attacker created a directory and added a payload.  However when I logout and log back in the directory and the payload is gone.

Any advise would be appreciated. 

Thanks
Gerhard

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by t3chn0m4g3** [comment]
Leaving ethics and the fact aside that there is no guarantee reflecting on the attacker this is not an issue regarding T-Pot.

Please understand that T-Pot is only used to collect information.
