### ISSUE TITLE
CiscoASA false positive?

### ISSUE THREAD

**Issue by xcampax** [dtag-dev-sec/tpotce#530]
# Issues

Hi there,

Already with my previous setup of T-Pot (18.something on Ubuntu) I have been seing one alleged alert for the CiscoASA honeypot daily, always at 3am, and it is the same now with 19.03.1. Our network team is insisting that this must be a false positive, and considering the timing and frequency of the alert, I am inclined to agree. Can you please comment? I did not find any such issues reported. 

Thanks :)
Nora

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

What version of the OS are you currently using lsb_release -a and uname -a?
Description: Debian GNU/Linux bullseye/sid
Release: unstable
Codename: sid

What T-Pot version are you currently using?
T-Pot 19.03.1

What edition (Standard, Nextgen, etc.) of T-Pot are you running?
NextGen

What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM

Did you have any problems during the install? If yes, please attach /install.log /install.err.
not with T-Pot itself but dependency issues: had to install elasticsearch-curator and create docker service drop-in manually

How long has your installation been running?
a few days

Did you install upgrades, packages or use the update script?
yes; performed update.sh just earlier

Did you modify any scripts or configs? If yes, please attach the changes.
no

Please provide a screenshot of glances and htop.

How much free disk space is available (df -h)?

What is the current container status (dps.sh)?
========| System |========
    Date:  Fri 31 Jan 2020 02:19:47 PM CET
  Uptime:  14:19:47 up  3:51,  1 user,  load average: 0.16, 0.14, 0.14

NAME                  STATUS                       PORTS
adbhoney              Up 4 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 4 hours
citrixhoneypot        Up 4 hours             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 4 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 4 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 4 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 4 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 4 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 4 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 4 hours
elasticsearch         Up 4 hours (healthy)   127.0.0.1:64298->9200/tcp
fatt                  Up 4 hours
glutton               Up 4 hours
head                  Up 4 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 4 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 4 hours             0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 4 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 4 hours (healthy)
mailoney              Up 4 hours             0.0.0.0:25->25/tcp
medpot                Up 4 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 4 hours
p0f                   Up 4 hours
rdpy                  Up 4 hours             0.0.0.0:3389->3389/tcp
snare                 Up 4 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 4 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 4 hours
tanner                Up 4 hours
tanner_api            Up 4 hours
tanner_phpox          Up 4 hours
tanner_redis          Up 4 hours             6379/tcp
tanner_web            Up 4 hours

What is the status of the T-Pot service (systemctl status tpot)?
● tpot.service - tpot
     Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-01-31 10:29:34 CET; 3h 50min ago
    Process: 856 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
    Process: 1087 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
    Process: 1210 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/S>
    Process: 1220 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUC>
    Process: 1231 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAIL>
    Process: 1271 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILUR>
    Process: 1290 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
    Process: 1309 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=>
    Process: 1332 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ pri>
    Process: 1338 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }>
    Process: 1344 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 >
    Process: 1350 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
   Main PID: 1432 (docker-compose)
      Tasks: 33 (limit: 9489)
     Memory: 114.4M
     CGroup: /system.slice/tpot.service
             └─1432 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Jan 31 14:18:24 atgrzsl3245 docker-compose[1432]: head                   | [Fri Jan 31 2020 13:18:24 GMT+0000 (Co>
Jan 31 14:18:51 atgrzsl3245 docker-compose[1432]: cyberchef              | [Fri Jan 31 2020 13:18:51 GMT+0000 (Co>
Jan 31 14:18:54 atgrzsl3245 docker-compose[1432]: kibana                 | {"type":"response","@timestamp":"2020->
Jan 31 14:18:54 atgrzsl3245 docker-compose[1432]: head                   | [Fri Jan 31 2020 13:18:54 GMT+0000 (Co>
Jan 31 14:19:22 atgrzsl3245 docker-compose[1432]: cyberchef              | [Fri Jan 31 2020 13:19:22 GMT+0000 (Co>
Jan 31 14:19:24 atgrzsl3245 docker-compose[1432]: kibana                 | {"type":"response","@timestamp":"2020->
Jan 31 14:19:24 atgrzsl3245 docker-compose[1432]: head                   | [Fri Jan 31 2020 13:19:24 GMT+0000 (Co>
Jan 31 14:19:52 atgrzsl3245 docker-compose[1432]: cyberchef              | [Fri Jan 31 2020 13:19:52 GMT+0000 (Co>
Jan 31 14:19:54 atgrzsl3245 docker-compose[1432]: kibana                 | {"type":"response","@timestamp":"2020->
Jan 31 14:19:55 atgrzsl3245 docker-compose[1432]: head                   | [Fri Jan 31 2020 13:19:55 GMT+0000 (Co>

What ports are being occupied? Stop T-Pot systemctl stop tpot and run netstat -tulpen

If a single container shows as DOWN you can run docker logs for the latest log entries

**Comment by t3chn0m4g3** [comment]
While this might be possible I tend to not speculate on that matter. Thanks for understanding.
