### ISSUE TITLE
Question: Turn off selected Servers

### ISSUE THREAD

**Issue by mrdavi5** [dtag-dev-sec/tpotce#533]
Hello! 
what is the best method for me to turn off certain honeypots from running? Is it amending the package yaml such as sensor.yml and remove each Honeypot section?
end goal is to have a honeypot with few services running.

**Comment by t3chn0m4g3** [comment]
Please find a hint [here](https://github.com/dtag-dev-sec/tpotce/wiki/Adjust-honeypots-docker-compose-config).
