### ISSUE TITLE
Visualize files uploaded in Cowrie

### ISSUE THREAD

**Issue by Patrik-Hansson** [dtag-dev-sec/tpotce#535]
Hi
Would like to make a feature request to have some view over files that has been uploaded in Cowrie honeypot. Looks like it's all in the cowrie.json:

`{"eventid":"cowrie.session.file_upload","filename":"dota3.tar.gz","outfile":"dl/81a78c02f5651ceebab3a28d7fff26350e6bd2e3090ad142885732d9ea5abe96","shasum":"81a78c02f5651ceebab3a28d7fff26350e6bd2e3090ad142885732d9ea5abe96","message":"SFTP Uploaded file \"dota3.tar.gz\" to dl/81a78c02f5651ceebab3a28d7fff26350e6bd2e3090ad142885732d9ea5abe96","sensor":"21aaacc79b6e","timestamp":"2020-02-05T03:50:20.592876Z","src_ip":"121.173.163.60","session":"68166bf50aad"}
`

**Comment by t3chn0m4g3** [comment]
Good idea, however, you are aware you can create visualizations for yourself with Kibana and adjust the dashboards accordingly?

**Comment by Patrik-Hansson** [comment]
What Is possible in Kibana and what I CAN do is sadly two different things :)
But i will of course try.

**Comment by t3chn0m4g3** [comment]
That's the spirit :bowtie:

**Comment by t3chn0m4g3** [comment]
Before I send you on a wild goose chase... I just realized the corresponding are not part of the index pattern yet, hence you cannot BYO viz regarding this 😅

**Comment by t3chn0m4g3** [comment]
Done, you need to import the objects (see #531), though.
![image](https://user-images.githubusercontent.com/4318452/73852399-60a04380-482f-11ea-9069-51f3ea2f5f75.png)
