### ISSUE TITLE
Error restarting dockers. 30 min for them to be up.

### ISSUE THREAD

**Issue by jrsanchezsilva** [dtag-dev-sec/tpotce#536]
Good Morning. Today I restarted the server that has the t-pot hosted. However, it took 30 minutes to be up all the dockers. I have made the updates and I am working with ELK 7.5.2. After reboot the dockers and them did not get up I could appreciate the following errors that I attached here. Thanks in advance. Best regards.

![image](https://user-images.githubusercontent.com/51901933/73955766-dfe65380-48d1-11ea-82a1-4dd633a0bb32.png)

![image](https://user-images.githubusercontent.com/51901933/73955806-f2f92380-48d1-11ea-8191-34959f5856ec.png)

**Comment by jrsanchezsilva** [comment]
What version of the OS are you currently using `lsb_release -a` and `uname -a`?
[root@voluntaryrow:~]# uname -a
Linux voluntaryrow 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux

- What T-Pot version are you currently using?
T-POT 19.03.1

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nextgen
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
physical server (Hardware)

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
None

- How long has your installation been running?
three days

- Did you install upgrades, packages or use the update script?
It was updated with the script

- Did you modify any scripts or configs? If yes, please attach the changes.
https://github.com/dtag-dev-sec/tpotce/issues/534

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/51901933/74041896-85fa9200-4994-11ea-9adc-3e7c44866303.png)


![image](https://user-images.githubusercontent.com/51901933/74041926-990d6200-4994-11ea-872c-105b2851bde7.png)

- How much free disk space is available (`df -h`)?
Filesystem      Size  Used Avail Use% Mounted on
udev            7.6G     0  7.6G   0% /dev
tmpfs           1.6G  3.5M  1.6G   1% /run
/dev/sda2       1.8T   11G  1.7T   1% /
tmpfs           7.6G     0  7.6G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/28fe807724dcc378aba282e50e5b4b4b0ced4a66c80d23d97f82e7e2232d657e/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/5d26ac53fd0674f535bb3a8e0e79c8b4baa4859a9daff02b0b2e71d92e1881ec/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/ef1a52d1f7d593c833c5a8ef56a4aadb985b877c8c0c6c82b8ae9cb779af4425/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/0b7ccb4b020f09587f6eb439577d563668b8570e5b9276eb7c0b2b1746a40a01/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/8ce8b1f283a3066fb27a3f2454d23b35675536789342345353bf83003f545bc9/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/55dcfd3a627d1d03199d284d5eb3ac4284addec26431816f2a78a611dd1a3204/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/86a60f3b6ef053d3adc1b66843a7ca9501de6e679f05077798dd7dccbb97818d/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/2b28092e9d6deb2cfb24935818e68fc45a9946f1cb26313fefbd66f5cabd90cf/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/f49235e4f27f8815ee24bdde772cf4fd6f2a63fe678b7c7baeb8b194bbf41b59/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/9d266396c8da002321433725f49ad9ed64c7309fd7db30d6f77f4c84b7aa9964/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/debacff6b1f1b90ce80d4264bb67905af1064d8eac1abebae40bc6c9d9cf2744/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/a4a9f49acae5868b5336268bf2dfa74d5a7ec9d4c5ae4f01dfd675fa24e181b1/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/de3eb17032088a2f194327544eaef746e87ac4a026a994069667c65fae11dd54/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/a35f7469051015a594c74cdc46d5b6810c09627097d154bdbd95b8168f6ed458/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/f8a683e89fcc0d5f4eff57de09f3d7e01240e1b7e138f856d0cac67b527ab38b/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/2c013c6cdf4b5468ca0df83da8d795c0e0744888da4c4c56f6a72e7aa043b8fa/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/c6b9017e988b8e6ca40b76e0ecf16482a4e47437d38d88d75f64fa34eee52359/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/68de870e41e06eecd7ad07789358f6c0056c598f936b40ef064f784f9653a039/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/6d828873b9fa1016b8e39df5a87d2c99ea47a1b7640aafbfad67ebff98c24be9/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/a2341326fe51e64a5cf3af77c38d0112d10d4a99dc7799035f9c5a2ee32fa0c6/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/65259006e701d89ac42fb83730524fba210197fdb54a97042af17123e064467f/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/b27c483128061d5818dbd25176194e6fbb2f6b664d92ed5c03a918aec7712d69/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/a117eeebe123a3ecdf5af16e9101b381ccc728e66dee7ba3d6c0fea47aa0e5b8/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/c4890eaac1b819da8eaa741595348b40a6427bb1c994cf97ab262b2fc23c4ed2/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/ec864df66409bd519e5f486523af11bca0e7a45cd16abd5bb5e20857061a626d/merged
shm              64M     0   64M   0% /var/lib/docker/containers/6d3004c3f68973be6d53a5c6de110b96ed69d5d5b34a7d5c17d23111dede0874/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/88e9b32f662a2d00615f105f2e88125863f11cd1e07fe6e5fbcd935c8306640c/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/98d4bf44bb2b69764ffef04bba80938777ee355470329b9810880a0349c1db7f/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/f8417511c4df356d8286cb421960a15fb3d37e330bf6d5d23b81f37203fe9ef9/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/b440d53c2e21e216367a792fcb11f8bd8bd437fbe5c812ca8d74f6e3233bdd63/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c7ad6b789e61c45534efc8bd8e9c0eac3daf7215ce8e6a9d23ca905f1bc229b1/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/0b1ce4bafd37c0dc780cc063a61f10a004a729d0631812503f964cc4cef0aa02/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c835eed72a0fda9fbbf13f51ecbec6fc9ca3315cb1baa334795d34b7bb757005/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/b3d8fcc2dcd47cf6323878cc5855c4aed8c118e2a139e88952f085c39cd49590/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/92cd23839bc3dfe0bb15de860f8f45659fbb21ee18c53396e964c71a29bd0d87/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/bb114a643ab5beef82993afb6cad4c67652827e5db5b263b1b44b7ca5f1dcf70/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/3de74c5d6d3cfd60a7589204c8ca0f698b517d24ca440908cf9c1ba3ae7381cc/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/2dfefc5ef3a68d287bfcecad2f924046f5260d0c338da0524c73fbbdf6508799/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7417f59525caf934abcab84a28d6c9180880cfa1fa4709485516d337a24ec374/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a111b3db3ae22e05f24a8f83d58eac6beb9ea1fb875b98543bdd5c15aa7378d6/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/ff91f783de0646d85c40103c878990f1b9fba0c60e942d95adaa74a53772793b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/461f49d100b0483f0e40cddd007106b710219b41dc6493ac52b9665b6b6685f5/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/e6d7c1dde528a8a79431d8835a6b39f7ecc2a429cb0bd95e477cc6bc9de3dd65/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a4cc1fb15eafa273308e4dc45286cd68e8270e18f51d8ec56a8b453a01fa4837/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c204d99efc9b72912f3baec49960719acfa6dcc07ac7b1f17b5809098d65a596/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/765b479ee874c4320053406e9b2ba0cce0e799b2951eee2f14afd32992adfe63/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/5f4e7c221e485471f9473be4b9c861560898ef7239e617a28d8278599e34da13/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/99754d1f6d4b0b0cb873b6061cf64c43f6f80b3c39d7a2fb548a9ea33ca3d51b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/1dec2e7f0cc91aa46774b7967b995ba12dfccbba656b7bba46e5e5eaa6d88f21/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/acec43778e4365561d62cc544a10b8807394c41b9bb2d42a3e825eef462904fe/mounts/shm
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/4da32e4294e4f9196afea6a80a0c5c74e433758a2e7970172ca731f0cf3d0ec5/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/03a82f7468bf625b9bd984e6b94d97e1c3c0f2d8d216c3ccfb1db9409671bad5/merged
shm              64M     0   64M   0% /var/lib/docker/containers/f06d81b54727f5efa8168b38b14115dcf83b87386efc1c37e725ed4a6941e568/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/8215c90dca040fbe46374a7859acf9c23a6ff9383e76d4118173fc73a1580efb/mounts/shm
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/a237d2ba57f23b263b55c5d9c5acee50abd2b76575b24d4a6e3976ff6b93414e/merged
shm              64M     0   64M   0% /var/lib/docker/containers/e2ab22f880cf537b21af2270f1c60bde6fe090bc2149d7de2e1bea757c824e2d/mounts/shm
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/a1c23da4055a2eeaeba1c44667fbd6e3d4a1d7d79747c0bce89a4a6e8b45535d/merged
shm              64M   20K   64M   1% /var/lib/docker/containers/ee0d44322dabec7b1f3ffe7ab8282145220f9ce9ae2ecadaf785f34b109ecfce/mounts/shm
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/249bc3c849c0d68cf0d61c536a92772014aa94000b29d800b15b7193e6f1d1a5/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/46f5c817bf03d89b9000c8127cc9e745e840653aef4ba93933b6f14dc9a7680e/merged
overlay         1.8T   11G  1.7T   1% /var/lib/docker/overlay2/bda83569401b51940a6d6df5be00f05d4911d8c166a96197a01092091035ded6/merged
shm              64M     0   64M   0% /var/lib/docker/containers/e1dc5c1ea1b0e0a656f6c43e963fdb917e406415318e164d1b0155ebd8deae5e/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/cdbc3704b9ab5dca3650acd412fceb0f7a4f34c9064298ef2e13f6bd32c0e7cf/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/37390500d1d8593417aee4566e56f4700f3c5759c0bd3ab1c49f40cd8816f896/mounts/shm
tmpfs           1.6G     0  1.6G   0% /run/user/1000
[root@voluntaryrow:~]# 

- What is the current container status (`dps.sh`)?
[root@voluntaryrow:~]# dps.sh
========| System |========
    Date:  Fri 07 Feb 2020 03:29:51 PM UTC
  Uptime:  15:29:51 up 11:59,  2 users,  load average: 0.60, 0.58, 0.60

NAME                  STATUS                       PORTS
adbhoney              Up 12 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 12 hours             
citrixhoneypot        Up 12 hours             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 12 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 12 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 12 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 12 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 12 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 12 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 12 hours             
elasticsearch         Up 12 hours (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 12 hours             
fatt                  Up 12 hours             
glutton               Up 12 hours             
head                  Up 12 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 12 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 12 hours             0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 12 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 12 hours (healthy)   
mailoney              Up 12 hours             0.0.0.0:25->25/tcp
medpot                Up 12 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 12 hours             
p0f                   Up 12 hours             
rdpy                  Up 12 hours             0.0.0.0:3389->3389/tcp
snare                 Up 12 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 12 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 12 hours             
tanner                Up 12 hours             
tanner_api            Up 12 hours             
tanner_phpox          Up 12 hours             
tanner_redis          Up 12 hours             6379/tcp
tanner_web            Up 12 hours             
[root@voluntaryrow:~]# 

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/51901933/74042150-fbfef900-4994-11ea-8a2c-14c0c4b1acf9.png)


- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/51901933/74042377-6748cb00-4995-11ea-8188-26aa6a3f8006.png)

![image](https://user-images.githubusercontent.com/51901933/74042389-70399c80-4995-11ea-8a48-6afb77670cfe.png)


QUESTIONS:
- Today I restarted the server that has the t-pot hosted. However, it took 30 minutes to be up all the dockers. I have made the updates and I am working with ELK 7.5.2. After reboot the dockers and them did not get up I could appreciate the following errors that I attached here. Thanks in advance. Best regards.

- Where can I locate the RUN file from where all the dockers are initialized, in order to modify the ports of KIBANA and COCKPIT?

**Comment by t3chn0m4g3** [comment]
1. Everything looks perfectly fine. I am guessing the long restart time is based on too many events which needed to be archived / packed by logrotate.
2. Changing theses ports is not supported since part of the NGINX container and / or necessary for the reverse proxy config.
