### ISSUE TITLE
T-Pot and Playlog Utility

### ISSUE THREAD

**Issue by SvenSchirgewohn** [dtag-dev-sec/tpotce#537]
for Training purposes, I would like to show (replay) some catched SSH Sessions of the cowrie honeypot. For a "Stand Alone Cowrie Honeypot" I found a nice tutorial, but I'm not able to adopt it to the T-Pot and it's container technology, caused by a lack of knowledge. Could anybody give me a hint or some steps, how this coulds be done on T-Pot?

Thanks!

**Comment by Patrik-Hansson** [comment]
Might help if you post a link to the tutorial you found. Maybe someone else will find it interesting and adopt it.

**Comment by t3chn0m4g3** [comment]
The playlog utility is part of the Cowrie image, after `docker exec -it cowrie ash` you find it in `/home/cowrie/cowrie/bin`. Within the Cowrie container you can access log data at `/home/cowrie/cowrie/log`.

**Comment by SvenSchirgewohn** [comment]
Thanks @t3chn0m4g3
 I tried this, but it seems python is not integrated in the docker image.
Got an error: _env: can't execute 'python': No such file or directory_

So I think it's not the goal for T-Pot to play cowrie logs in the container byself, what I understand, because all the data are stored and available at logstash. 

With my skills I'm not able to customize the image, so I have a bit more to learn before I can start to play with...

Nevertheless, thanks!

**Comment by t3chn0m4g3** [comment]
Try this in the container...
```
~/cowrie $ python3.7 bin/playlog 
Usage: playlog [-bfhi] [-m secs] [-w file] <tty-log-file> <tty-log-file>...

  -f             keep trying to read the log until it's closed
  -m <seconds>   maximum delay in seconds, to avoid boredom or fast-forward
                 to the end. (default is 3.0)
  -i             show the input stream instead of output
  -b             show both input and output streams
  -c             colorify the output stream based on what streams are being received
  -h             display this help
```
Works fine here.

**Comment by SvenSchirgewohn** [comment]
@t3chn0m4g3 
Thanks a lot, because it's also working here now!
Saved my day!

**Comment by t3chn0m4g3** [comment]
Welcome, thanks for the feedback 😄
