### ISSUE TITLE
No kernel module found on fresh install within vmware esxi

### ISSUE THREAD

**Issue by charlespctech** [dtag-dev-sec/tpotce#538]
Hello, I am getting a kerne module error when trying to perform a fresh install with the newest iso.

**Comment by Wolfbyte-dev** [comment]
I have the same issue :(

**Comment by itsCryne** [comment]
VirtualBox Version 5.2.34_Ubuntu r133883, same issue

**Comment by t3chn0m4g3** [comment]
Thanks. The T-Pot ISO is build off the Debian mini.iso, I am guessing it just needs rebuilding because of upstream changes. On it.

**Comment by t3chn0m4g3** [comment]
Just swapped the ISO (https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.1), works fine for me. Please confirm.

**Comment by charlespctech** [comment]
Confirmed this is working for me. Thank you

**Comment by t3chn0m4g3** [comment]
@charlespctech Thanks for the feedback and opening the issue.
