### ISSUE TITLE
Web page beforo TPOT

### ISSUE THREAD

**Issue by jrsanchezsilva** [dtag-dev-sec/tpotce#541]
Good night
The Tpot is only to collect information from the attackers ?, or fictional information such as a web page or an external mail service can be put in such a way that it is attacked and Tpot detects those behavior.
Thanks in advance, best regards.

![image](https://user-images.githubusercontent.com/51901933/74285959-d7888100-4cf4-11ea-847d-c074cb694f0d.png)

**Comment by t3chn0m4g3** [comment]
Sorry, but I do not understand what the problem is.

**Comment by jrsanchezsilva** [comment]
Good morning. It is not a problem. It is more a query regarding the use of the tool. I can place false information such as a web page or an external mail service such as bait for the attacker to see that information (services) and try to use attack tools, so that the TPOT, hosted on the server, detects that behavior, as can be done see in the chart.
Thanks in advance, best regards.

**Comment by t3chn0m4g3** [comment]
That's what Snare / Tanner is for, no need to run your own webserver for that.
However please understand that this is more an architectural question on your end which is beyond of the T-Pot scope we can provide. Please only open issues directly related to T-Pot.
Thanks for understanding.
