### ISSUE TITLE
NO DHCP in Network.

### ISSUE THREAD

**Issue by vincenthalter** [dtag-dev-sec/tpotce#544]
In my enterprise environment is no dhcp server. Is it possible to just set de static ip manually?

Ist TPOT working like that? or does the machine needs more than one IP?

**Comment by t3chn0m4g3** [comment]
Yes, however you should install T-Pot then on top of Debian ([Buster](http://ftp.debian.org/debian/dists/buster/main/installer-amd64/current/images/netboot/mini.iso)), the installer will take care of migrating to SID.
