### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by osiris2600** [dtag-dev-sec/tpotce#545]
Hi thanks for answering my previous question regarding adding more honeypots post install. I used tped.sh to activate some other options.

I can't now get a HTTPS connection to kibana and recieve "SECURE CONNECTION FAILED" "PR_END_OF_FILE_ERROR". 

I don't mind reinstalling everything but I was wondering off the top off of anyones head if they know what this could be?

Thanks in advance

**Comment by t3chn0m4g3** [comment]
#478
