### ISSUE TITLE
tpot with SID is unstable on AWS, now trying to resurrect ubuntu

### ISSUE THREAD

**Issue by cappetta** [dtag-dev-sec/tpotce#548]
Looked through the closed issue history log and I'm noticing tpot on AWS remains unstable for myself and others.  I posted an update to issue #406 and wanted to create a new issue here to obtain some information so I can research a solution.  

I've been looking at and attempting to stabilize the last known (good) ubuntu codebase.  If I am correct most of this project depends on docker assets, which should be reproducible on any OS.  I've grabbed the 18.11 installers (as I believe that is the last known working ubuntu version) and I'm hitting a few issues.  

I know Ubuntu is no longer supported yet it seems to have been a bit more stable on AWS than the debian SID is.   If you could share some info on what might be breaking the ubuntu installer I'll start researching and attempting to merge updates/resurrect that OS.  If not, any feedback on #406  would be appreciated.  

Thanks

**Comment by t3chn0m4g3** [comment]
It is working fine on OTC, so the challenges seem to be related to AWS. The move to Debian was related to instabilites we experienced with Ubuntu in general and also to focus less on a release based cycle, hence the move to SID.
Please focus on #406, AFAIK the only reason AWS is unstable is the deactivation of `ipv6` however I have no idea what side effects will be introduced upon enabling WRT to docker and the honeypots, especially with regard to logging events properly.
Appreciate if you want to dive into making this work, but I recommend finding the reasons why Debian is not working.
FWIW, once 20.06 is release I will be looking into a OS independent version of T-Pot, however this might not receive the same feature set.
I am closing this in favor of #406.
