### ISSUE TITLE
Installation in Synology VMM fails: "no kernel modules were found"

### ISSUE THREAD

**Issue by lun4r** [dtag-dev-sec/tpotce#554]
T-pot version 19.03.1
Synology DSM version: DSM 6.2.2-24922 Update 4
Device: Synology DS 918+
Using tpot.iso

https://i.imgur.com/18lbBJJ.png

**Comment by t3chn0m4g3** [comment]
If this is based on the latest ISO the error means that your plattform is not supported. I also highly doubt that T-Pot will be running smoothly on your system.

You can however install Debian 10 and install T-Pot on top of it as described in the readme.
