### ISSUE TITLE
Prevent surricata to log internal network

### ISSUE THREAD

**Issue by certrik** [dtag-dev-sec/tpotce#556]
Change config in https://github.com/dtag-dev-sec/tpotce/blob/master/docker/suricata/dist/suricata.yaml to not include internal networks.
present:        
   ```
 #EXTERNAL_NET: "!$HOME_NET"
    EXTERNAL_NET: "any"
```
after:
   ```
 EXTERNAL_NET: "!$HOME_NET"
 #EXTERNAL_NET: "any"
```

**Comment by t3chn0m4g3** [comment]
Thanks, but we want to keep it the way it is, since T-Pot is also used in internal deployments.
