### ISSUE TITLE
Tanner statistics

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#557]
Hi. How do I "read" the statistics from Tanner using either Tannerweb or Tanner API as these 2 containers have no exposed ports. Thanks.

**Comment by t3chn0m4g3** [comment]
You use the Kibana dashboard for Tanner. We do not expose Tanner's statistics.

**Comment by Fosocles** [comment]
What if I do not use Kibana, but Graylog? Also, is it a necessary service? Can I disable it/delete it?
