### ISSUE TITLE
Mail notification on each alerts

### ISSUE THREAD

**Issue by slackwaree** [dtag-dev-sec/tpotce#558]
Hi,

I running some of your old install images based on:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Normally you would not want email alert for each and every event however I use these images on lans where should be 0 events.

What I have going on is I modified the ews.conf to add a php webhook which is a simple mailer script:

```
[EWS]
ews = true
username = admin
token = admin
rhost_first = http://ip/notify.php
rhost_second = http://ip/notify.php
```

However this is not reliable it does not triggers for all events and of course the events themselves wont be passed its just a simple alert script which sends an alert email to sysadmins so they have to login the frontend and check out what is going on.

Is there an email alert in the latest version what can do what I need?

Which is again to aggregate all events from suricate, honeytrap, dionaea... and send them in email.

Also is there any way maybe in the new version that it also triggers alert if someone simply scans the host with nmap?

Thanks

**Comment by t3chn0m4g3** [comment]
This is not supported out of the box. On a sidenote, though, you should definitely quit using anything else but T-Pot 19.03.x.
You can however adjust [EWSposter ](https://github.com/dtag-dev-sec/tpotce/wiki)and deliver into you very own [PEBA ](https://github.com/dtag-dev-sec/PEBA)backend.
You can also adjust the logstash configs accordingly and check if there is a fitting plugin you can use.
