### ISSUE TITLE
Is it really necessarry to use 15 /16 subnets by default?

### ISSUE THREAD

**Issue by ctminime** [dtag-dev-sec/tpotce#560]
This is a problem for large corporate networks. In my case, this overlaps with our VPN Space. So, I currently have no way to access them (I have 6) remotely. Couldn't /28's be used instead? And maybe even make it configurable to specify a /24 for the /28's to fit into during install? That way it avoids network overlapping.  Also, is there a way for me to re-configure this? FYI My only Docker experience so far is with T-Pot.

ie. Specify 192.169.20.0/24
Then Bridged networking devices would be:
192.168.20.0/28
192.168.20.16/28
192.168.20.32/28
192.168.20.48/28
192.168.20.64/28
192.168.20.80/28
192.168.20.96/28
192.168.20.112/28
192.168.20.128/28
192.168.20.144/28
192.168.20.160/28
192.168.20.176/28
192.168.20.192/28
192.168.20.208/28
192.168.20.224/28

[root@governingpower:~]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.80.81.129    0.0.0.0         UG    0      0        0 ens5
10.80.81.128    0.0.0.0         255.255.255.240 U     0      0        0 ens5
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-2f62bb643a2c
172.19.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-af74ea95d774
172.20.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-db173b4c44c1
172.21.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-4750fc88ddd0
172.22.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-f55e62a44e13
172.23.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-d57dfea20759
172.24.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-41ad1c4eb0ba
172.25.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-072b847439fd
172.26.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-cc67ca8bfa6c
172.27.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-df18be27cfd0
172.28.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-6dd53c386f59
172.29.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-d4bda1493f03
172.30.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-665ba3438dd5
172.31.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-193d0680b577
192.168.0.0     0.0.0.0         255.255.240.0   U     0      0        0 br-f78f3e80de3a

**Comment by t3chn0m4g3** [comment]
This is the default way of docker, however you can adjust this to your needs:
https://docs.docker.com/network/bridge/
https://success.docker.com/article/how-do-i-configure-the-default-bridge-docker0-network-for-docker-engine-to-a-different-subnet

**Comment by smigool** [comment]
there is no docs on how to assign custom subnet to user-defined bridge, only on default bridge with daemon.json also need to create one?
