### ISSUE TITLE
NetxGen 19.03 Kibana Not Start 

### ISSUE THREAD

**Issue by sengkoil** [dtag-dev-sec/tpotce#562]
# Issues
<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid

- What T-Pot version are you currently using?
T-Pot 19.03

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
NextGen

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No.

- How long has your installation been running?

- Did you install upgrades, packages or use the update script?
i have installed the upgrade and also do a fresh installation, but both have the same problem.

- Did you modify any scripts or configs? If yes, please attach the changes.
No.

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/4113264/75729326-63eef800-5d25-11ea-9dc8-588ea185e563.png)

![image](https://user-images.githubusercontent.com/4113264/75729372-8b45c500-5d25-11ea-8554-2a5a6628604d.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/4113264/75729401-a9abc080-5d25-11ea-9c28-e3c4afe77934.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/4113264/75729461-d8c23200-5d25-11ea-90ce-5eb46a34d07a.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/4113264/75729855-11faa200-5d26-11ea-99ae-86aee848c8e4.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/4113264/75729914-4b331200-5d26-11ea-96d2-b70982ad09ca.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

Manage to run the tpot and get this page
![image](https://user-images.githubusercontent.com/4113264/75730027-8f261700-5d26-11ea-94c2-bf4436557a96.png)

but when click the Kibana menu it appear this page:
![image](https://user-images.githubusercontent.com/4113264/75730056-aebd3f80-5d26-11ea-8e3a-ac25725900ef.png)

**Comment by t3chn0m4g3** [comment]
Is this a fresh install or did you run the update script?

**Comment by sengkoil** [comment]
this result  is from the fresh install.
i also have run from the update script but still get the same error..Kibana did not start and exited.

**Comment by t3chn0m4g3** [comment]
Please run a `docker logs kibana` while Kibana is trying to start up, a `journalctl -u tpot.service -b` might also help to poinpoint the problem.

Please post a screenshot of `Elasticsearch Head`, especially with regard to `.kibana` entries.

I cannot reproduce this, everything works fine here.

**Comment by sengkoil** [comment]
This is some of the log when I run the command given (journalctl -u)
![image](https://user-images.githubusercontent.com/4113264/75935850-6a16dd00-5ebb-11ea-86a9-ee8f1fac8ba5.png)

what i frequently found the error is about  -- Data too large, data for [<http_request>] would be [987150302/941.4mb], which is larger than the limit of [986932838/941.2mb] --

Do you have any idea and suggestion for me...?

The screenshoot for Elasticsearch Head i can't share today since the tpot is currently down..

**Comment by UncleRaymondo** [comment]
That's definitely a very large http_request!

Some clues here: https://discuss.elastic.co/t/cause-and-how-to-avoid-data-too-large-http-request-exception/156279/3

**Comment by t3chn0m4g3** [comment]
This is a cache error of elasticsearch.

Run `curl -XPOST 'http://127.0.0.1:64298/logstash-*/_cache/clear'`to fix it and then `systemctl stop tpot`, once stopped (check with `dps.sh`find the following line in `/opt/tpot/etc/tpot.yml`:
`     - ES_JAVA_OPTS=-Xms1024m -Xmx1024m` and change it to at least:
`     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m`.

If you have 16GB of RAM you can set it to 4096 but then raise the `mem_limit: 4g` to `mem_limit: 8g`.

**Comment by sengkoil** [comment]
> This is a cache error of elasticsearch.
> 
> Run `curl -XPOST 'http://127.0.0.1:64298/logstash-*/_cache/clear'`to fix it and then `systemctl stop tpot`, once stopped (check with `dps.sh`find the following line in `/opt/tpot/etc/tpot.yml`:
> ` - ES_JAVA_OPTS=-Xms1024m -Xmx1024m` and change it to at least:
> ` - ES_JAVA_OPTS=-Xms2048m -Xmx2048m`.
> 
> If you have 16GB of RAM you can set it to 4096 but then raise the `mem_limit: 4g` to `mem_limit: 8g`.



Thanks macro ,
my problem solved ..i manage to get the kibana up and running again.
and already raised the mem_limit as per advice.

thanks again for the guide given..

**Comment by t3chn0m4g3** [comment]
Thank you for the feedback 😃
