### ISSUE TITLE
Experiencing a persistent problem with configuring apt during installation of T-Pot 19.03.1

### ISSUE THREAD

**Issue by envescent** [dtag-dev-sec/tpotce#566]
During installation of T-Pot 19.03.1 the process fails. This happens after the network is configured, the storage device is partitioned and formatted and during the process of downloading packages from the selected mirror.

The error message indicates that the installer is unable to configure apt (as it stalls out there), stating that "the installer failed to access the mirror. This may be a problem with the network, or with the mirror, retry the download, select a different mirror, or ignore the problem." 

The installer then suggests retrying, changing mirror or ignoring. None of these options were successful unfortunately. Ignoring causes a catastrophic installation failure.  In an attempt to troubleshoot (in case it may be an issue on our end), we attempted the following other steps:

1: Create a new installation disk w/new media.

2: Change the network being used (even to the point of diverting around any firewall or NAT).

3: Changing the DNS utilized.

4: Changing the mirror utilized.

5: Changing the destination storage device.

Despite trying all of the above several times on different days and times, the error remains persistent. This has been ongoing since the most recent weekend in late February. We would greatly appreciate any help resolving this problem.

**Comment by t3chn0m4g3** [comment]
1. Did you download the latest image?
2. It seems T-Pot does not receive a DHCP lease which is mandatory for the iso image.
3. If this does not work for you grab the [Debian Mini Iso](http://ftp.debian.org/debian/dists/buster/main/installer-amd64/current/images/netboot/mini.iso) and install T-Pot on top of that (see Readme).

**Comment by envescent** [comment]
Thanks for getting back with me so rapidly!

1:Yes, I believe that's the 19.03.1 from August, 2019. Also built a T-Pot installer ISO using the script provided. Both provide the same result.

2: I tried both w/DHCP and w/a static IP w/the same result. I also tried spinning up a virtual machine in ESXi and had the same result (it was behind DHCP).

3: Interesting, thanks for the tip! Perhaps that's the best bet to try for now. Though I do wonder what may be going on. I had a successful install perhaps two weeks earlier on one other machine.

Also happy to do any other sort of troubleshooting if it is helpful to the project.

**Comment by t3chn0m4g3** [comment]
@envescent The ISO was last rebuilt in Feb-2020, maybe you are using an old one?

**Comment by envescent** [comment]
@t3chn0m4g3 Certainly possible, but I am hopeful that isn't the case. It was downloaded from this link as recently as two days ago: https://github.com/dtag-dev-sec/tpotce/releases/download/19.03.1/tpot.iso. 

We also used the ISO creator tool to build a recent image with the same result.

**Comment by t3chn0m4g3** [comment]
Just to make sure, I just downloaded the ISO from GitHub again, and the installation is running fine. Did you get to the point where you can select a mirror? If yes what happens if you choose some different ones? Really interested in the outcome of the `mini.iso`.

**Comment by envescent** [comment]
Yes, I got past that point. It was when the installation was running that it would eventually stop during the configuration of apt. Then, no matter what steps were taken (retry, select another mirror, ignore) it would fail.

**Comment by t3chn0m4g3** [comment]
But it was still in the Debian Installer (before rebooting)? Besides a faulty mirror I cannot really wrap my head around what might be going wrong. Thanks for debugging this 😃

**Comment by envescent** [comment]
No problem. That is correct, it had not rebooted. It was configuring apt during the initial installation (post network configuration, mirror selection). I believe it was still downloading and installing packages. Unfortunately the error message doesn't provide a lot of detail as to what the actual source was, and instead gives some vague suggestions. If you know of a way I may be able to harvest additional details I'm happy to run through and get to that stopping point again.

**Comment by t3chn0m4g3** [comment]
I guess that is where the `mini.iso` comes in I linked above. This will allow you to install everything manually, maybe this will shed some light on it.

**Comment by t3chn0m4g3** [comment]
Fresh install ... just in case you think I am messing with you 😃 
```
[root@presidentialtext:~]# cd ..
[root@presidentialtext:/]# ls -al
total 1492
drwxr-xr-x  19 root root    4096 Mar  6 00:56 .
drwxr-xr-x  19 root root    4096 Mar  6 00:56 ..
lrwxrwxrwx   1 root root       7 Mar  6 00:35 bin -> usr/bin
drwxr-xr-x   3 root root    4096 Mar  6 00:55 boot
-rw-------   1 root root  954368 Mar  6 00:56 core
drwxrwx---  25 tpot tpot    4096 Mar  6 00:55 data
drwxr-xr-x  17 root root    3120 Mar  6 00:55 dev
drwxr-xr-x 105 root root    4096 Mar  6 00:56 etc
drwxr-xr-x   3 root root    4096 Mar  6 00:38 home
lrwxrwxrwx   1 root root      29 Mar  6 00:44 initrd.img -> boot/initrd.img-5.4.0-4-amd64
lrwxrwxrwx   1 root root      30 Mar  6 00:36 initrd.img.old -> boot/initrd.img-4.19.0-8-amd64
-rw-r--r--   1 root root    1370 Mar  6 00:55 install.err
-rw-r--r--   1 root root 1142422 Mar  6 00:55 install.log
lrwxrwxrwx   1 root root       7 Mar  6 00:35 lib -> usr/lib
lrwxrwxrwx   1 root root       9 Mar  6 00:35 lib32 -> usr/lib32
lrwxrwxrwx   1 root root       9 Mar  6 00:35 lib64 -> usr/lib64
lrwxrwxrwx   1 root root      10 Mar  6 00:35 libx32 -> usr/libx32
drwx------   2 root root   16384 Mar  6 00:34 lost+found
drwxr-xr-x   3 root root    4096 Mar  6 00:34 media
drwxr-xr-x   2 root root    4096 Mar  6 00:35 mnt
drwxr-xr-x   4 root root    4096 Mar  6 00:46 opt
dr-xr-xr-x 244 root root       0 Mar  6  2020 proc
drwx------   5 root root    4096 Mar  6 00:55 root
drwxr-xr-x  21 root root     680 Mar  6 00:56 run
lrwxrwxrwx   1 root root       8 Mar  6 00:35 sbin -> usr/sbin
drwxr-xr-x   2 root root    4096 Mar  6 00:35 srv
dr-xr-xr-x  13 root root       0 Mar  6 00:55 sys
drwxrwxrwt  11 root root    4096 Mar  6 00:56 tmp
drwxr-xr-x  14 root root    4096 Mar  6 00:43 usr
drwxr-xr-x  11 root root    4096 Mar  6 00:35 var
lrwxrwxrwx   1 root root      26 Mar  6 00:44 vmlinuz -> boot/vmlinuz-5.4.0-4-amd64
lrwxrwxrwx   1 root root      27 Mar  6 00:36 vmlinuz.old -> boot/vmlinuz-4.19.0-8-amd64
[root@presidentialtext:/]# dps.sh
========| System |========
    Date:  Fri 06 Mar 2020 12:56:48 AM UTC
  Uptime:  00:56:48 up 1 min,  1 user,  load average: 2.30, 0.70, 0.25

NAME                  STATUS                       PORTS
adbhoney              Up 36 seconds                     0.0.0.0:5555->5555/tcp
ciscoasa              Up 40 seconds
citrixhoneypot        Up 38 seconds                     0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 36 seconds                     0.0.0.0:10001->10001/tcp
conpot_iec104         Up 37 seconds                     0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 37 seconds                     0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 36 seconds                     0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 37 seconds                     0.0.0.0:22-23->22-23/tcp
cyberchef             Up 37 seconds (healthy)           127.0.0.1:64299->8000/tcp
dionaea               Up 40 seconds
elasticsearch         Up 36 seconds (healthy)           127.0.0.1:64298->9200/tcp
ewsposter             Up 38 seconds
fatt                  Up 40 seconds
glutton               Up 41 seconds
head                  Up 4 seconds (health: starting)   127.0.0.1:64302->9100/tcp
heralding             Up 38 seconds                     0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 37 seconds                     0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 4 seconds (health: starting)   127.0.0.1:64296->5601/tcp
logstash              Up 4 seconds (health: starting)
mailoney              Up 36 seconds                     0.0.0.0:25->25/tcp
medpot                Up 39 seconds                     0.0.0.0:2575->2575/tcp
nginx                 Up 41 seconds
p0f                   Up 41 seconds
rdpy                  Up 36 seconds                     0.0.0.0:3389->3389/tcp
snare                 Up 32 seconds                     0.0.0.0:80->80/tcp
spiderfoot            Up 36 seconds (healthy)           127.0.0.1:64303->8080/tcp
suricata              Up 41 seconds
tanner                Up 33 seconds
tanner_api            Up 35 seconds
tanner_phpox          Up 36 seconds
tanner_redis          Up 37 seconds                     6379/tcp
tanner_web            Up 35 seconds
[root@presidentialtext:/]# uptime
 00:57:00 up 1 min,  1 user,  load average: 2.48, 0.80, 0.28
```

**Comment by envescent** [comment]
I've no doubt you're providing objective analysis. The issue is quite flummoxing indeed. I intend to install from the mini ISO next go around and I'll let you know if there are any issues. I don't suspect that there will be. It's just one of those technological SNAFUs where it seemed as though it was a bizarre externality and not something I could account for with the system, network or otherwise.

**Comment by t3chn0m4g3** [comment]
Indeed. Thanks.

**Comment by envescent** [comment]
No problem! Thanks for syncing up with me and providing the advice to try the mini ISO! I appreciate the guidance and look forward to checking out this version of T-pot! This is a fantastic project and it really feels a much needed gap.

**Comment by t3chn0m4g3** [comment]
Thank you 🙏

**Comment by t3chn0m4g3** [comment]
@envescent Do you have an update on this?

**Comment by envescent** [comment]
Yes, it seems to be a bug in the Debian installer that relates to the date of the host. If the date is not accurate then the installation fails--without explaining why. Unfortunately the hardware utilized was pulled off the shelf after having been idle long enough that the CMOS battery had failed to keep the date accurate. So I take responsibility for the source of the issue, though I really wish the error message was more descriptive.

**Comment by t3chn0m4g3** [comment]
I was prepared for anything but a date being the cause of this problem. Thanks for the feedback. Unfortunately preseed settings WRT setting / syncing time are only handled later by the installer. However this not having a proper error message or even causing an error is highly unexpected.

**Comment by envescent** [comment]
You're welcome! Same here. I would have hoped if the date was an issue it would prompt with an option to sync via NTP to correct it, explaining what happened and why. I don't think inaccurate dates are all that uncommon for fresh installations on new / used hardware. Certainly haven't encountered this issue when the BIOS date is incorrect on other distributions or operating systems as far as I can remember.

**Comment by t3chn0m4g3** [comment]
I googled this, but I have not found anything recent or tangible WRT to the Debian Installer and / or apt. As mentioned earlier, [preseeding ](https://www.debian.org/releases/buster/example-preseed.txt) will not offer a solution to this behavior.
I will tag this as `documentation` though, so it will be easier to find. However, at this point there is unfortunately nothing I can do to resolve this.
Thanks for your time and effort to troubleshoot this issue :bowtie:
