### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by venividivinni** [dtag-dev-sec/tpotce#567]
After the clean installation of Debian 10 i took the post install method.
The machine has:
- 200GB Disk /16GB RAM and it runs with VMware Pro
- working, unproxied internet connection
- a working mirror (cd-rom is commented out)
- apt-get update & upgrade

After cloning the repo to : "root@debian:/
i run the script "install.sh"
Than i get those errors:

_root@debian:/tpotce# ./install.sh

### Installing apt-fast
--2020-03-05 18:04:59-- https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.192.133, 151.101.0.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21564 (21K) [text/plain]
Saving to: ‘/usr/local/sbin/apt-fast’

/usr/local/sbin/apt 100%[===================>] 21.06K --.-KB/s in 0.02s

2020-03-05 18:05:00 (1.30 MB/s) - ‘/usr/local/sbin/apt-fast’ saved [21564/21564]

### Checking for installer dependencies: [ NOW INSTALLING ]
./install.sh: line 240: apt-fast: command not found
./install.sh: line 241: apt-fast: command not found
########################################
########################################

Disclaimer:
This script will install T-Pot on this system.
By running the script you know what you are doing:
1. SSH will be reconfigured to tcp/64295.
2. Your Debian installation will be upgraded to Sid / unstable.
3. Please ensure other means of access to this system in case something goes wrong.
4. At best this script will be executed on the console instead through a SSH session.

########################################

Usage:
./install.sh --help - Help.

Example:
./install.sh --type=user - Best option for most users._

After this i run the script again. ( ./install.sh --type=user)
Than i get even more errors. Why are not all packages installed?
root@debian:/tpotce# ./install.sh --type=user

### Installing apt-fast
--2020-03-05 17:56:35-- https://raw.githubusercontent.com/ilikenwf/apt-fast/master/apt-fast
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21564 (21K) [text/plain]
Saving to: ‘/usr/local/sbin/apt-fast’

/usr/local/sbin/apt 100%[===================>] 21.06K --.-KB/s in 0.01s

2020-03-05 17:56:35 (1.62 MB/s) - ‘/usr/local/sbin/apt-fast’ saved [21564/21564]

### Checking for installer dependencies: [ NOW INSTALLING ]
./install.sh: line 240: apt-fast: command not found
./install.sh: line 241: apt-fast: command not found
########################################
########################################

### Checking for active services.

./install.sh: line 326: grc: command not found

### might collide with T-Pot's honeypots and prevent T-Pot from starting successfully.

Continue [y/n]?
./install.sh: line 260: dialog: command not found
./install.sh: line 274: dialog: command not found
./install.sh: line 260: dialog: command not found
./install.sh: line 274: dialog: command not found
./install.sh: line 260: dialog: command not found
./install.sh: line 274: dialog: command not found
./install.sh: line 260: dialog: command not found
./install.sh: line 274: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found
./install.sh: line 581: dialog: command not found

**Comment by t3chn0m4g3** [comment]
Runs fine here. What happens if you cancel the installer after apt-fast is installed and you try calling it manually? Does the shell know its path `which apt-fast`?

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
