### ISSUE TITLE
Time mismatch with @timestamp and timestamp from actual event

### ISSUE THREAD

**Issue by Blason** [dtag-dev-sec/tpotce#568]
# Issues

Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue:
- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running?
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
Unless you provide exact information and log data for the events being wrongfully timestamped I cannot help you.

**Comment by Blason** [comment]
My bad!! Here is the info

Here is the outut and I noticed that logs coming for port 443/445 ports

{
   "_type": "_doc",
  "_id": "BgmVr3AB2OH9d8wiKmi5",
  "_version": 1,
  "_score": null,
  "_source": {
    "dest_ip": "192.168.1.175",
    "tags": [
      "_geoip_lookup_failure"
    ],
    "@version": "1",
    "connection": {
      "transport": "tcp",
      "protocol": "smbd",
      "type": "accept"
    },
    "path": "/var/log/data/dionaea/log/dionaea.json",
    "dest_port": 445,
    "net": "Internal-Net",
    "trap_type": "Network-Trap",
     "src_ip": "192.168.1.138",
    "src_port": 60923,
    "timestamp": "2020-03-06T11:22:30.695083",
    "@timestamp": "2020-03-06T05:52:30.695Z",
    "type": "Dionaea",
    "src_hostname": "",
    "geoip": {}
  },
  "fields": {
    "@timestamp": [
      "2020-03-06T05:52:30.695Z"
    ]
  },
  "highlight": {
    "src_ip": [
      "@kibana-highlighted-field@192.168.1.138@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1583473950695
  ]
}

I am currently at IST and time is 16.55 but if you see above event is showing in kibana at 11:22

**Comment by t3chn0m4g3** [comment]
All events are stored in UTC. In Kibana events are shown per your browser / OS configured timezone. Since you are in [IST ](https://www.timeanddate.com/time/zones/ist) this explains the 5:30h difference.

**Comment by Blason** [comment]
Nah - This is not for sure; As I explained and if you see that screenshot closely RDP logs are shown perfectly fine while events for port 445 and other are appearing in different timezone.
Well my system and server TZ both are in IST

**Comment by t3chn0m4g3** [comment]
I can not spot the difference. Please point out the exact times and differences you think are not correct. From what I can see there are two events both with correct UTC  and IST timestamps.

**Comment by Blason** [comment]
See both are fired at same time First Event is showing at IST 16:51 while below is showing at 11:22
Wondering why 11:22 would appear instead of IST

**Comment by t3chn0m4g3** [comment]
That's two events (based on screenshot) and you provide JSON from Kibana which shows the browser's UTC / IST times.

LGTM
