### ISSUE TITLE
elasticpot counters not incrementing?

### ISSUE THREAD

**Issue by jamesl1234** [dtag-dev-sec/tpotce#57]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Just installed TPOT and my counters for all Honeypots are incrementing bar elasticpot.
I have hit the box from the internet on port 9200 and tried to do a few things like curl http://serveraddress:9200 and curl -XPUT 'http://serveraddress:9200/customer?pretty'
but no counters are going up.. am I doing anything wrong here?

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 16.03
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? 12Hrs
- Did you install any upgrades or packages? No
- Did you modify any scripts? No
- Have you turned persistence on/off? Have not turned anything on/off
- How much RAM available (login via ssh and run `htop`)? 6GB
- How much stress are the CPUs under (login via ssh and run `htop`)? 4%
- How much swap space is being used (login via ssh and run `htop`)? 0MB
- How much free disk space is available (login via ssh and run `sudo df -h`)? 175GB
- What is the current container status (login via ssh and run `sudo start.sh`)? command doesn't work and file does not exists on box.

**Comment by dev-t-sec** [comment]
dear james will check it asap best wishes Markus

On 08 Sep 2016, at 01:01, jamesl1234 <notifications@github.com<mailto:notifications@github.com>> wrote:

Contribution

Thank you for your decision to contribute to T-Pot.

Issues

Just installed TPOT and my counters for all Honeypots are incrementing bar elasticpot.
I have hit the box from the internet on port 9200 and tried to do a few things like curl http://serveraddress:9200 and curl -XPUT 'http://serveraddress:9200/customer?pretty'
but no counters are going up.. am I doing anything wrong here?

FAQ
Where can I find the honeypot logs?
The honeypot logs are located in /data/. You have to login via ssh and run sudo cd /data/. Do not change any permissions here or T-Pot will fail to work.

Baisc support information

  *   What T-Pot version are you currtently using? 16.03
  *   Are you running on a Intel NUC or a VM? VM
  *   How long has your installation been running? 12Hrs
  *   Did you install any upgrades or packages? No
  *   Did you modify any scripts? No
  *   Have you turned persistence on/off? Have not turned anything on/off
  *   How much RAM available (login via ssh and run htop)? 6GB
  *   How much stress are the CPUs under (login via ssh and run htop)? 4%
  *   How much swap space is being used (login via ssh and run htop)? 0MB
  *   How much free disk space is available (login via ssh and run sudo df -h)? 175GB
  *   What is the current container status (login via ssh and run sudo start.sh)? command doesn't work and file does not exists on box.

-

**Comment by jamesl1234** [comment]
Let me know if you want to see for yourself..
Drop me a line if so.

**Comment by t3chn0m4g3** [comment]
T-Pot 16.10 will include a new version of Elasticpot which will log every connection request.
