### ISSUE TITLE
Cowrie outgoing traffic

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#570]
Hi. This might not be (totally) related to T-Pot but I wish to catch & redirect SMTP traffic using Cowrie (redirect to Mailoney) but I am currently struggling "routing" traffic from one to another. Also, I'd like to send files from Cowrie to a Cuckoo instance I have installed on another server.

I have been studying cowrie.cfg and cowrie.cfg.dist for the past 3-4 hours and something about docker networking keeps ruining my brainstorming. Any ideas/suggestions are welcome. Thanks.

**Comment by t3chn0m4g3** [comment]
@Fosocles Unless you modify `tpot.yml` Cowrie will run isolated from other containers. There is an examples in the dev branch (etc/compose/nextgen.yml) regarding tanner which might help you understanding things. You might want to follow up the Cowrie and docker-compose documentation.

**Comment by Fosocles** [comment]
Will have a look, thanks. Will update (if I'm successful) in case somebody else wants to implement the same thing in their project.

**Comment by t3chn0m4g3** [comment]
Thanks.

**Comment by jrsanchezsilva** [comment]
Good morning @Fosocles , to see if I understand what you want to achieve cowrie (honeypot SSH and Telnet of medium to high interaction designed to register attacks of brute force) without detecting malicious files so that you envy your SandBox (cuckoo); or really what you want to send a CUCKOO.

**Comment by Fosocles** [comment]
Hello @jrsanchezsilva! Well, my idea is (firstly) to redirect SMTP traffic to Mailoney and record it. If you consult the original Cowrie config file, you should see a field "redirect_25" which enables this feature. The problem I'm facing is how to make Cowrie talk to Mailoney. Secondly, if the first objective will be successful, I want to send malicious files (download via ssh/telnet) from Cowrie to a Cuckoo instance (again, feature made possible using cowrie.cfg)
