### ISSUE TITLE
Forced Reboot @ 3:27a causes delay of almost 3 hours restarting

### ISSUE THREAD

**Issue by UncleRaymondo** [dtag-dev-sec/tpotce#575]
M,

So I was up in the early hours of the morning watching the console and noticed it reboot at 3:27a like you mentioned earlier on the dot. However, the services take almost 3 hours to restart, and you can clearly see a massive gap in the data while it is down...

![image](https://user-images.githubusercontent.com/5147133/76296059-bcb42700-6309-11ea-95f9-bbc00af495b7.png)

On tailing `/var/log/syslog` to see what it's actually doing, dionaea seems to be re-processing every single transaction/attack. Here's an extract of `syslog` that I just took now...

![image](https://user-images.githubusercontent.com/5147133/76296535-5d0a4b80-630a-11ea-98db-62fc63869577.png)

Any idea why it's doing this? Workaround? Is it required?

Cheers,
R

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo This is `logrotate` packing all the events. Probably too much. If you do not want logrotate to archive this you can edit `/etc/systemd/system/tpot.service` for `clean.sh on` to `clean.sh off` which will delete all files instead of rotating them on the next T-Pot start.

**Comment by Fosocles** [comment]
Can confirm. Mine takes somewhere between 30-40 mins to start, but it's not a big inconvenience. As Marco said, you can edit the service and switch off the persistence of your logs.

**Comment by UncleRaymondo** [comment]
Hmm... If we switch this off... how does this affect historical data on the dashboards?

**Comment by Blason** [comment]
The historic data is parsed by logstash and stored in elasticsearch which is in index form. There wont be any effect of deleting files from where the data is generated.

**Comment by t3chn0m4g3** [comment]
@Blason is correct. ES data is not affected and preserved according to the settings in `/opt/tpot/etc/curator` configs.

**Comment by Fosocles** [comment]
After editing `/etc/systemd/system/tpot.service` with `systemctl edit --full tpot` and changed `clean.sh on` to `clean.sh off`, but I get the following errors:

```
[...]
 ERROR: for suricata  Cannot start suricata suricata: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/data/suricata/capture-filter.bpf\\\" to rootfs \\\"/var/lib/docker/Overlay2/8677a6954ffe5be8d76b2aadc8dc8f81c17c2fccd1ac953e79449391a6ac9ea3/merged\\\" at \\\"/var/lib/docker/overlay2/8677a6954ffe5be8d76b2aadc8dc8f81c17c2fccd1ac953e79449391a6ac9ea3/merged/etc/suricata/capture-filter.bpf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
[...]
```

Basically, Tpot keeps restarting. If i restart the machine completely, then Network-Manager fails to come up/get an IP address.

I tried removing all images, containers and volumes, but the problem persists.

**Comment by t3chn0m4g3** [comment]
Closing this for now, please let me know in case this is still an issue.

**Comment by t3chn0m4g3** [comment]
Works fine here.

**Comment by Fosocles** [comment]
Not helping *cries in spanish*

**Comment by t3chn0m4g3** [comment]
Perfect.
