### ISSUE TITLE
Firewall issues with outgoing TPot connections

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#579]
Hi. I have my TPot instance behind a firewall with Virtual IPs (VIPs) for the honeypots and a "management" IP for the host. I'm trying to limit the useless outgoing connections for the host but somewhere I'm doing something wrong. I'm permitting only git, http and https (specifically port 9418, 80 and 443). After enabling the policy and restarting TPot, Docker-CE cannot start (some problem connection to dockerd socket). But, if I allow **all** outgoing services, it has no problem starting. Any ideas?

**Comment by t3chn0m4g3** [comment]
Sorry, please check with the docker project. I am not aware of such deps.
