### ISSUE TITLE
dionaea and suricata processes terminated

### ISSUE THREAD

**Issue by mattmac1** [dtag-dev-sec/tpotce#58]
After I have the standard honeypots running for a day or so I noticed dionaea and suricata stop running.
I'm running on the amazon cloud: medium server, 2 vCPUs, 4 GB memory, 64 GB storage running ubuntu 14.04.

Checking the logs I can see:

Init: dionaea main process (12794) terminated with status 125
init: dionaea main process ended, respawning

init: suricata pre-start process (10898) terminated with status 1

If I restart the server all is good for about a day or so then same happens.

**Comment by t3chn0m4g3** [comment]
@mattmac1 May I kindly ask you to provide the support information asked when opening an issue.

Thank you :bowtie:

**Comment by mattmac1** [comment]
Baisc support information

What T-Pot version are you currtently using? 16.03
Are you running on a Intel NUC or a VM? VM
How long has your installation been running? 12Hrs
Did you install any upgrades or packages? **No**
Did you modify any scripts? **No**
Have you turned persistence on/off? Have not turned anything on/off  **No**
How much RAM available (login via ssh and run htop)? **4GB**
How much stress are the CPUs under (login via ssh and run htop)? **8%**
How much swap space is being used (login via ssh and run htop)? **0**
How much free disk space is available (login via ssh and run sudo df -h)? **55GB**
What is the current container status (login via ssh and run sudo start.sh)? **don't have start.sh ... have docker-status though .. that just says Waiting for services .....**

However if I run docker stats

```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
1596ed82cf25        0.01%               93.18 MB / 4.144 GB   2.25%               2.676 kB / 648 B      32.27 MB / 589.8 kB
47d0ad573cdb        0.02%               44.71 MB / 4.144 GB   1.08%               0 B / 0 B             21.83 MB / 24.58 kB
60cdf05b4ecc        0.02%               40.11 MB / 4.144 GB   0.97%               2.16 kB / 840 B       16.97 MB / 0 B
a106de9c8334        0.06%               189 MB / 4.144 GB     4.56%               8.944 kB / 8.135 kB   47.03 MB / 4.379 MB
ea1838dc6ef5        4.74%               890.6 MB / 4.144 GB   21.49%              2 kB / 648 B          131.5 MB / 962.6 kB
```

**Comment by t3chn0m4g3** [comment]
@mattmac1 thx, can you please run a `sudo status.sh`?

**Comment by mattmac1** [comment]
Hi tried that and just get

`Waiting for services ...........................................................................................................................................................................................................................................................................................................
Services are busy or not available. Please retry later.
`

**Comment by t3chn0m4g3** [comment]
@mattmac1 Please follow the steps of #51

**Comment by mattmac1** [comment]
Ok will do thanks - will leave it running and check it tomorrow to see if containers are still up. Thanks for your help! :)

**Comment by t3chn0m4g3** [comment]
@mattmac1 Welcome :bowtie:

**Comment by mattmac1** [comment]
Still seem to have a problem with suricata:
init: suricata pre-start process (27486) terminated with status 1

Weirdly enough it always seems to be around 5am it occurs... I don't have any cron jobs running etc so not sure what it could be?

![screenshot_2016-09-15_10-07-49](https://cloud.githubusercontent.com/assets/6524325/18542673/57fd05ca-7b2c-11e6-9a07-798f8e91fcb2.png)

**Comment by t3chn0m4g3** [comment]
All containers are restarted at 3:27 UTC (`sudo cat /etc/crontab`). Have you followed through all steps of the issue I mentioned including updating docker etc.?

**Comment by mattmac1** [comment]
Yup followed the steps so not sure what's happening. Even if i stop docker completely and start it again I get the same error message.

**Comment by t3chn0m4g3** [comment]
I hope things worked out for you. If not I suggest to use T-Pot 16.10 which will be release by the end of the month.
