### ISSUE TITLE
Network connection problems after automatic reboot

### ISSUE THREAD

**Issue by atbohmer** [dtag-dev-sec/tpotce#580]
Hello,

Running 2 T-Pot 19.03.1 vmware VM's, and both lost connectivity after last nights automatic reboot. Seems the network interface is 'renamed' to eth0 on both systems.
So I did a fresh install and it seems all is broken afterwards, not even a docker installation. During Debian installation I'm able to configure an ip address, but after all installation scripts finish it's broken. In /etc/network/interfaces you will find the device it used to be, eg ens192, but ip addr and ifconfig show eth0?! Changing the  device name to eth0 in the interfaces file has no effect at all.

Some strange recent Debian deb update for udev of systemd?

Any idea?
Kind regards,
Andre

**Comment by Fosocles** [comment]
Had the same issue and do not know why. 
I fixed it by doing the following:
In commandline I did: `ifconfig eth0 (the new interface) X.X.X.X` and then pinged GW or 8.8.8.8 (in case you're behind a firewall and have ICMP disabled). 
Then, in `/etc/network/interfaces` renamed the interface from **ens18** to **eth0** and that was it.
Rebooted the system a couple of times and it (still) worked.

**Comment by htbrdd** [comment]
Fresh installs get no IP from DHCP. I have tried a couple different times. This is on proxmox. Adding eth0 to interfaces got an ip but webui would not load.

**Comment by Fosocles** [comment]
@htbrdd I'm also on Proxmox and seem to be having more problems than on VMware.

**Comment by t3chn0m4g3** [comment]
Interesting, one of the latest updates in Debian seems to handle interface naming differently. These were the last updated.
```
glib-networking-common:amd64 (2.62.3-1, 2.64.0-1)
glib-networking-services:amd64 (2.62.3-1, 2.64.0-1)
glib-networking:amd64 (2.62.3-1, 2.64.0-1)
```
However the service logs as unsuccessful which is not true as it falls back to the `eth` naming scheme, at least in my case.

I am guessing T-Pot 20.06 will be a full release pointing to either `testing` or `stable` instead of `sid`, which is an option we did not have while developing `19.03` as `stable, testing` it did not have all the deps we needed.

**Comment by t3chn0m4g3** [comment]
**TESTING ONLY - DO NOT INSTALL UPON ANY OTHER RELEASE**
I created a dev pre-release, please [download and test](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.3.dev).
If you want to use the post-install method, just run `git clone --depth=1 https://github.com/dtag-dev-sec/tpotce -b dev`.
Changes in the `dev`-branch (switched to Debian Testing) fixed the issue for me.

**Comment by Cacharro83** [comment]
Hello and installed the testing version and it works perfectly. I have tried to install the stable version and it doesn't work in any way. Is it a debian generated problem?

**Comment by htbrdd** [comment]
Just installed the testing dev version and I have an ip now.

**Comment by Cacharro83** [comment]
I have IP with the dev version but the stable version does not give IP. The message is tpot failed

**Comment by Cacharro83** [comment]
The stable version is not capable of lifting the network interfaces

**Comment by t3chn0m4g3** [comment]
Thanks for testing. Will be preparing a release ASAP.

**Comment by bukow13** [comment]
this version  git clone --depth=1 https://github.com/dtag-dev-sec/tpotce -b dev works but no way to connect with ssh -l tsec -p 64295 <your.ip>  or https://<your.ip>:64294....


Any idea ?

TY !

**Comment by bukow13** [comment]
this version :git clone --depth=1 https://github.com/dtag-dev-sec/tpotce -b dev works !!!
ty !
But no way to connect on the Admin UI: https://<your.ip>:64294 or via SSH to access the command line: ssh -l tsec -p 64295 <your.ip>


Any idea ?

ty

**Comment by t3chn0m4g3** [comment]
@bukow13 Yes, there is no tsec user in the Post Installation method.

**Comment by Fosocles** [comment]
@bukow13 that means you either: 1. connect with an already existing user or 2. create another user.
Also, you should keep in mind that the user you want to connect/login as **must** be in the **sudoers** group.

**Comment by Fosocles** [comment]
@t3chn0m4g3 so normally, to get these latest updates, I should run update.sh on my TPot?

**Comment by t3chn0m4g3** [comment]
@Fosocles These changes were introduced in the Debian Sid branch, which until today, was the choice for T-Pot. There is no option for downgrading `sid` to `testing`, only a reinstallation will solve this. However I am still researching the reason for the changes.
If renaming the interfaces works for you there is no reason to switch, all other changes will still continue via `update.sh`.

**Comment by Fosocles** [comment]
@t3chn0m4g3 Ok, fine by me. Also, I've noticed you removed cockpit-docker from install.sh. Should I try to remove it or leave it be?

**Comment by t3chn0m4g3** [comment]
@Fosocles The package is no longer available in `testing` and `sid`.

**Comment by Fosocles** [comment]
Ok, ok.
Also, do you know anything about/have encountered this error while installing TPot?
`depmod: ERROR: ../libkmod/libkmod.c:515 lookup_builtin_file() could not open builtin file '/lib/modules/5.4.0-4-amd64/modules.builtin.bin'`.

I get atleast o dozen of lines with this error both on Debian 9 and Debian 10.

**Comment by t3chn0m4g3** [comment]
New release can be found [here](https://github.com/dtag-dev-sec/tpotce/releases/tag/19.03.3). After checking all the deps it is now based on the Debian `stable` branch.

Since testing showed positive results I am closing this issue.
