### ISSUE TITLE
ISO Installation with error (DATA ERR CANT CREAT)

### ISSUE THREAD

**Issue by elpoco98** [dtag-dev-sec/tpotce#584]
My VM is in a ESXi environment.
I setup a VM with the given ISO.

After the installation the vm reboots and tpot isnt running. I get the following errors:
(i dont know if the environment or tpot is generating the error)

Error:
failed to parse value, ignoring DATA ERR CANT CREAT

![image](https://user-images.githubusercontent.com/50569806/76710934-c4aa0780-670b-11ea-85a1-563f7d80735c.png)

thanks 4 the support

**Comment by t3chn0m4g3** [comment]
Please provide the infos kindly asked upon issue creation. Thank you.

**Comment by elpoco98** [comment]
> Please provide the infos kindly asked upon issue creation. Thank you.
which infos? 
The vm is setup in esxi environment. I used the iso file to set tpot up. Before the installation i selected the "Standard" Installation.
It seems the script is running through well, but after the restart this is the result.
I cannot estimate where the error comes from to solve the problem.

**Comment by t3chn0m4g3** [comment]
Sorry, but I cannot help without more info.
