### ISSUE TITLE
Phpox's utility

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#586]
Hi. Is Phpox even used? I cannot see any logs from it. I know Tanner should use it to "detonate" certain php requests/files but I cannot seem to understand where you should see the results. Tanner_web doesn't seem to have a dedicated Sandbox tab. If I remove it does it have any impact on Tpot? Any help?

**Comment by t3chn0m4g3** [comment]
In case you are on a 19.03 tag, yes, it is not used. If you are on 20.06 I fixed it last week.

**Comment by Fosocles** [comment]
I'm still in the transition phase. Thanks for the quick reply!
