### ISSUE TITLE
RDPy crashing at login

### ISSUE THREAD

**Issue by Kikoarl** [dtag-dev-sec/tpotce#589]
This is my first post on GitHub so apologies if I made this issue wrong, or it's not even an issue and its my fault.

I installed TPOT one month ago and it works like it should, however, I noticed that RDPY module wasn't getting login credentials from all the connections it was recieving.

Then I tried to log onto the RDP, trying to replicate the behavior of an attacker, but then, when the login screens comes up, and after one second, it closes. This is what I see before crashing.
https://imgur.com/a/rKD68tx
Same result after connecting from LAN or mobile data.

After trying to troubleshoot this situation by myself I found in the RDPY logs that it tries to select a file that contains the connection resolution from /opt/rdpy/3, but rdpy doesn't exist inside /opt/
Pic of the log: https://imgur.com/a/zPF6YG2

Bear in mind that my knowledge about this topic is, at best, limited.

Thank you for creating such a wonderful tool.

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Debian GNU/Linux bullseye/sid
- What T-Pot version are you currently using?
Latest available
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? 
I'm running T-Pot 19.03.1 ISO upgraded to latest version following Github procedures.
- Did you have any problems during the install?
No.
- How long has your installation been running?
One month.
- Did you install upgrades, packages or use the update script?
Yes, after finding RDPy doesn't work as it should.
- Did you modify any scripts or configs? If yes, please attach the changes.
Yes, I changed the specified port for Cowrie module and works without issues.
- Please provide a screenshot of `glances` and `htop`.
Both screenshots are here https://imgur.com/a/SY4WwbY
- How much free disk space is available (`df -h`)? 
Around 100G.
- What is the current container status (`dps.sh`)? 
Every container is UP.
- What is the status of the T-Pot service (`systemctl status tpot`)? 
Active (running)

**Comment by t3chn0m4g3** [comment]
@Kikoarl That is the correct behavior.

**Comment by Kikoarl** [comment]
@t3chn0m4g3 So, RDPy is not able to record the session or, at least, get the credentials like Cowrie does? Thank you for answering this quick!

**Comment by t3chn0m4g3** [comment]
Username and passwords are displayed correctly, some clients might have problems though, however RDPY does need some [work](https://github.com/dtag-dev-sec/tpotce/issues/467). This needs to be solved upstream.

**Comment by Fosocles** [comment]
@Kikoarl Maybe @t3chn0m4g3 didn't explain well enough (because he's been working on TPot for quite some time now), allow me to clarify. From what I've seen/tested, RDPy is actually supposed to "crash" if you were to use Microsoft's RDP software to connect to your honeypot. I don't know how the other modes of RDPY work though. This behavior is correct because an attacker doesn't have the time to manually connect and inspect every PC/server with open/unfiltered RDP, they use bots and they use them to brute-force logins. So basically, you don't need to worry about it "crashing" because you're main purpose should collecting as many credentials as possible.
Hope this shines a bit of light on your problem.
Cheers.

**Comment by t3chn0m4g3** [comment]
LOL. Yes 😃

**Comment by Fosocles** [comment]
Just trying to give a little back to the community! 😄

**Comment by t3chn0m4g3** [comment]
Guessing this is resolved.
