### ISSUE TITLE
Dashboard not complete

### ISSUE THREAD

**Issue by cmccabe20** [dtag-dev-sec/tpotce#590]
My issue is related to the VirtualBox installation of T-Pot. Because of COVID-19, I have to work from home on a virtual machine. I set this up yesterday and I am very puzzled as to why it would be like this (no sidebar, only partially setup). I don't think this means I haven't finished setting it up but you never know. 

Thanks!
![T-Pot Screenshot](https://user-images.githubusercontent.com/62436139/77177879-a3933f00-6a9c-11ea-9ae8-6ce5de79e2c1.png)

**Comment by t3chn0m4g3** [comment]
This mean Kibana has not started (yet). Please provide all infos asked upon issue creation.
