### ISSUE TITLE
[Snare] Connection was reset

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#593]
Snare resets connection before serving the webpage as discussed [here](https://github.com/mushorg/snare/issues/244). A possible fix downgrading from Python3.8 to Python3.6. I used `FROM python:3.6-alpine3.8` in SNARE's Dockerfile and it works. 
Please investigate.

**Comment by t3chn0m4g3** [comment]
Cannot reproduce.

**Comment by Fosocles** [comment]
My bad. I modified the Dockerfile to install `alpine:latest` (as oppossed to `alpine:3.10`) and it defaults to Python3.8. Rookie mistake on my part!

**Comment by Fosocles** [comment]
Also, just a heads-up, the guys over at Mushorg are upgrading Snare/Tanner to use yaml for config files (which I think it's great).
