### ISSUE TITLE
I'm Not able to store Network Traffic and Pcap Files

### ISSUE THREAD

**Issue by CyberHacky** [dtag-dev-sec/tpotce#599]
After Latest Update, 
I'm Not able to capture and store network traffic. i need network traffic as pcap files for better analysis. could you help to me to get network traffic in pcap file format. 

will you suggest me some better configuration or tool to capture and store all incoming and outgoing Network Traffic in T-pot Honeypot machine.

**Comment by t3chn0m4g3** [comment]
By default T-Pot does not offer storing PCAPs. You can check the Wiki or search closed issues on how to modify the `tpot.yml` on how to use volumes to change configs to your liking (links are also provided upon issue opening).

**Comment by CyberHacky** [comment]
have you removed docker management from Cockpit UI. before update i was able to manage all dockers from Cockpit WEB admin panel. but now Docker Menu not available. that was good functionality  please add it.

**Comment by t3chn0m4g3** [comment]
It's not recommended for T-Pot, however you can add it with `apt-get install cockpit-docker`.

**Comment by CyberHacky** [comment]
Need more help:

1. i want to create custom Suricata rules in Tpot machine. so how we can do it. and suricata is already configured with default rules. could you please share that rules path. where you are storing those rules in machine.

**Comment by TanveerAhmad2017** [comment]
> After Latest Update,
> I'm Not able to capture and store network traffic. i need network traffic as pcap files for better analysis. could you help to me to get network traffic in pcap file format.
> 
> will you suggest me some better configuration or tool to capture and store all incoming and outgoing Network Traffic in T-pot Honeypot machine.

Hi there! did you implement the solution of storing network traffic? i so please share your thoughts. looking forward to hear form you. Thanks

**Comment by chancecardona** [comment]
(Assuming running tpot on Debian 10) The easiest way I've found to do this is to:

- copy the suricata.yaml out of the suricata container eg `docker cp suricata:/etc/suricata/suricata.yml custom_suricata.yml`
- edit the `custom_suricata.yaml` so that pcap-log is enabled and set the directory eg to `/nsm_data`
- `mkdir /nsm_data`
- edit `/opt/tpot/etc/tpot.yml` under the suricata section mount `/nsm_data` to `/nsm_data` and mount your `custom_suricata.yaml` to `/etc/suricata/suricata.yml`
- reboot the host machine to restart tpot
Log rotation can then be added as well locally if needed.

**Comment by TanveerAhmad2017** [comment]
> (Assuming running tpot on Debian 10) The easiest way I've found to do this is to:
> 
> * copy the suricata.yaml out of the suricata container eg `docker cp suricata:/etc/suricata/suricata.yml custom_suricata.yml`
> * edit the `custom_suricata.yaml` so that pcap-log is enabled and set the directory eg to `/nsm_data`
> * `mkdir /nsm_data`
> * edit `/opt/tpot/etc/tpot.yml` under the suricata section mount `/nsm_data` to `/nsm_data` and mount your `custom_suricata.yaml` to `/etc/suricata/suricata.yml`
> * reboot the host machine to restart tpot
>   Log rotation can then be added as well locally if needed.

Than you so much. it surely will help others too.
