### ISSUE TITLE
Login Issues when running TPOT on cloud server with Debian 9

### ISSUE THREAD

**Issue by SuzukiCode** [dtag-dev-sec/tpotce#601]
When I go to setup TPOT, it automatically skips the phase where you setup tsec with the password. It only lets me setup the user for the WEBGUI not the ADMINGUI. I'm not sure why it skips that part but I can't access the ADMINGUI. I try with my server's root login and that doesn't work either. I don't know what to do. Please help!

OS: Debian 9
Digital Ocean VPS
Issue, Installation skips setting up tsec account. Goes straight to web account.

**Comment by Fosocles** [comment]
I think this is normal behaviour. You get the prompt to set a password for "tsec" only if you install from the provided .iso file. If you installed Tpot on Digital Ocean, you must've install using `--type=user` argument, meaning there should be a sudo user created. If not, create one and use it to login/ssh into your system. I hope it's not to late and you didn't cut your own branch!
Cheers.

**Comment by shaderecker** [comment]
If you want to log in on the Admin UI, then just set a password for your linux user.
You can either do this by running ```passwd``` directly on the server or by supplying so called user data with cloud-init during server creation:
```
#cloud-config
password: yoursupersecurepassword
chpasswd:
  expire: false
```

**Comment by SuzukiCode** [comment]
@Fosocles @shaderecker Thank you guys both so much! It is fixed. I set the password for tsec using the "passwd" command. The user already existed but no password was set. I tested and this worked. :) Thank you for your help!
