### ISSUE TITLE
not able to host in AWS

### ISSUE THREAD

**Issue by archanchoudhury** [dtag-dev-sec/tpotce#604]
# Issues
I was trying to host this in AWS, followed all of the instruction. Once the set-up window finishes, the system went for reboot, and I lost the ssh session(which is obvious). I have enabled the ports as well to run Admin and other UI through SG, but after the system reboots, I couldn't run them from browser. I logged in on the box and checked, there was no service running on the ports which is supposed to be like- 64295, 64297.. I checked for the services and tried to restart tpot, but it threw an error.
Could you please help? I have used a community AMI for Debian.

**Comment by t3chn0m4g3** [comment]
Based on the current info there is not much we can look into. Please provide more details.
