### ISSUE TITLE
Dionaea CPU spike

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#606]
Hello Marco! Lately, it came to my attention that Dionaea fluctuates between 98% and 114% CPU load. After some research I came across this Github [issue](https://github.com/CommunityHoneyNetwork/dionaea/issues/31) which basically states that you need to add the following lines to fix the issue:

> cap_add:
>       - NET_ADMIN

After doing so, I'm seeing a stable 3% CPU usage (for the moment). Do you think it's a good idea to add these lines or should we stick with the original .yml file?

Also, do you think it's a good idea to switch from "host" to "bridge" mode (if I were to assign a static public IP for Dionaea)?

Thanks. Cheers!

**Comment by t3chn0m4g3** [comment]
1. As long Dionaea runs in "host" mode adding the `NET_ADMIN` cap is not recommended.
2. If you run in `network_local` mode at least the FTP service will not work properly.

If you can live with non-working FTP you can switch to `network_local` and add the cap.

**Comment by Fosocles** [comment]
Ok, I understand. 
What about the CPU spike, what do you think about it? Do you have it too or just me?
Regarding "NET_ADMIN", why is it not recommended for Dionaea to run in "host" mode with this capability, but it is ok for Suricata?

**Comment by t3chn0m4g3** [comment]
1. I could only trigger it with the hptest script.
2. Suricata will not work without it and it needs to listen on the host IF to work properly, it is always a tradeoff situation.

**Comment by Fosocles** [comment]
Maybe it's hardware related. I will investigate. Thanks a lot!

**Comment by ehnwebmaster** [comment]
Any news from this?

I also noticed excesive CPU 100% usage from dionaea

Just using Port 445 (SMB) consumes 100% of CPU:

top command:

>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
>  6343 tpot      20   0 1011300 196320  15020 R  99.0   2.5 819:05.91 dionaea
>  4806 tpot      20   0  422636 187944   8940 S  22.2   2.3 368:09.25 twistd

22% por twistd (cowrie ssh/telnet honeypot)

logs container:
> [08032021 23:30:22] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'\x00\x00\x00&\xffSMB+\x00\x00\x00\x00\x18\x01H\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff<<\x00\x00\x00\x00\x01\x01\x00\x01\x00a'
> [08032021 23:30:22] SMB /dionaea/smb/smb.py:154: process() returned None.
> [08032021 23:30:22] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'\x00\x00\x00&\xffSMB+\x00\x00\x00\x00\x18\x01H\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff<<\x00\x00\x00\x00\x01\x01\x00\x01\x00a'
