### ISSUE TITLE
📢 Prepare for T-Pot 20.06

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#607]
All preperations for T-Pot 20.06 have been made and you can already [upgrade](https://github.com/dtag-dev-sec/tpotce/issues/531) to it now (**downgrade is not possible!**).

Make sure the automatic updates of the containers are enabled, we will make sure the Elastic Stack Images will be updated to the latest 6.x version which is necessary prior to upgrading to 7.x (no point of return afterwards).

Starting from July, 1st the `master` repository will point to `20.06` tags for all T-Pot editions:
- From this point forward new installations will always be based on `20.06`
- These changes will only take effect on existing installations on your end if you run `update.sh`. With the only exception being NextGen if already updated to 20.06.

The update might break things, so make sure **not** to use the update script if you are unsure to update.

T-Pot 19.03.x images will not be maintained after July, 31st.

If you are new to T-Pot and do not know if you should install now, please do not hesitate to install the NextGen type which is already pointing to the `20.06` tags which means you are good to go.

**Comment by VeloxDevelopment** [comment]
@t3chn0m4g3 thank you

**Comment by t3chn0m4g3** [comment]
[Done.](https://github.com/dtag-dev-sec/tpotce/releases/tag/20.06.0) 😃

**Comment by whalehub** [comment]
@t3chn0m4g3 Thank you! 🎉

**Comment by dmille6** [comment]
is there a list of changes or new features of version 20 somewhere.. i've googled.. and searched the site cant seem to find it. (its probably right in front of me)
