### ISSUE TITLE
Containers not starting after updates

### ISSUE THREAD

**Issue by Fosocles** [dtag-dev-sec/tpotce#611]
Hi, after the weekly updates, my containers are not starting. 
The error is: "Cannot start service **X**: no status provided on response: unknown".
From what I've read on the web, it's due to some error in _runc_.
I am currently running:
Docker version 19.03.6, build 369ce74
docker-compose version 1.25.4, build 8d51620a
and
runc version: 1.0.0~rc10+dfsg1-1
Docker seems to get upgraded to 19.03.6+dfsg1-3 (I think runc also).

**Important**: This instance of TPot is still running on Debian Unstable.
Could you please confirm this is a "bug" related to the unstable kernel only?

**Comment by t3chn0m4g3** [comment]
@Fosocles I can confirm this for unstable. Bug report is listed [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956502) and maintainer is working on it.

**Comment by t3chn0m4g3** [comment]
For now a downgrade works (or reinstall which will move to `stable`)... (run all commands as root `sudo su -`)

1. Remove faulty packages
```
systemctl stop tpot
apt-get purge docker
apt-get autoremove
```
2. Adjust `vi /etc/apt/sources.list` for `testing`
```
# Debian packages for unstable
#deb http://mirror.plusserver.com/debian/debian/ unstable main contrib non-free
deb http://mirror.plusserver.com/debian/debian/ testing main contrib non-free
# Uncomment the deb-src line if you want 'apt-get source'
# to work with most packages.
#deb-src http://mirror.plusserver.com/debian/debian/ unstable main contrib non-free
deb-src http://mirror.plusserver.com/debian/debian/ testing main contrib non-free

# Security updates for stable
# deb http://security.debian.org/ stable/updates main contrib non-free
```
3. Install previous version
```
apt-get update
apt-get install docker.io=19.03.6+dfsg1-2
reboot
```

4. `reboot`

**Comment by Fosocles** [comment]
Thanks! Will give it a try tomorrow and come back with updates.

**Comment by Fosocles** [comment]
Hi. This fix works, but I will switch from sid to stable (should've made the switch some time ago). Thanks. Closing for now.
