### ISSUE TITLE
ACCESS WITHOUT PRIVILEGES AND I DO NOT SEE THE DOCKER SERVICES IN COCKPIT

### ISSUE THREAD

**Issue by jrsanchezsilva** [dtag-dev-sec/tpotce#613]
<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux grandinnocent 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

- What T-Pot version are you currently using?
20.6

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Nextgen

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Hardware

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
None

- How long has your installation been running?
months

- Did you install upgrades, packages or use the update script?
None

- Did you modify any scripts or configs? If yes, please attach the changes0
None.
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/51901933/79642746-fc6dfa00-8164-11ea-9235-1c6eb8ca437b.png)

- How much free disk space is available (`df -h`)?
![image](https://user-images.githubusercontent.com/51901933/79642759-0c85d980-8165-11ea-8105-31d86163a409.png)

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/51901933/79642825-5969b000-8165-11ea-8b50-0f9691b0b582.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/51901933/79642898-a2b9ff80-8165-11ea-8040-6abd42c59029.png)

Good morning, when entering with privileged tasks in COCKPIT, the TSEC user does not have permission to modify account, much less the roles, and at the same time in the new version the Dockers are no longer shown in the services, please support in advance many thanks.

![image](https://user-images.githubusercontent.com/51901933/79642738-ebbd8400-8164-11ea-848a-569284ad8f15.png)

![image](https://user-images.githubusercontent.com/51901933/79642952-03493c80-8166-11ea-8274-91cbe19d7f45.png)

![image](https://user-images.githubusercontent.com/51901933/79642979-2b38a000-8166-11ea-82c3-b309076e89ab.png)

about docker services where can i launch and stop it

![image](https://user-images.githubusercontent.com/51901933/79642996-57542100-8166-11ea-8f62-caad651bd617.png)

please support in advance many thanks.

**Comment by Fosocles** [comment]
The response is in the third picture you posted. User `tsec` is not in the sudoers group. 
Login as root and add tsec to sudoers. That should solve your problem.

PS: There is no need to scream (hint: caps lock).

**Comment by t3chn0m4g3** [comment]
On a side note `cockpit-docker` is not part of T-Pot anymore. You have to manually install it in the future, especially if you are on `unstable` since the developers do not provide it any longer for unstable and testing. Also there is no apparent use for T-Pot since it lacks support for `docker-compose` and as such causes more trouble.

**Comment by Fosocles** [comment]
@t3chn0m4g3 what will replace Cockpit in the future?

**Comment by t3chn0m4g3** [comment]
@Fosocles `cockpit-docker` is just a module 😃 for Docker in Cockpit, Cockpit itself will stay.

**Comment by Fosocles** [comment]
Phew, you scared me a bit :)).

**Comment by jrsanchezsilva** [comment]
Good afternoon @Fosocles, that is the problem that I do not have root access in which I cannot enter tsec to sudoers.

**Comment by Fosocles** [comment]
0. Assuming you can SSH into your machine on port 64295, but root login is disabled.
1. In Cockpit, in Terminal can you do `su -`? If yes, then simply do `usermod -a -G sudo tsec `. If not, read step 2. 
2. If you cannot access your root account via SSH nor Terminal (Cockpit), but you do have access to your machine, try resetting your root password from the Grub Menu (a simple Google search might come in handy here).
3. If everything else fails, I think you should reinstall (but this should be the last option).
