### ISSUE TITLE
TPot Network on AWS

### ISSUE THREAD

**Issue by archanchoudhury** [dtag-dev-sec/tpotce#614]
Hi,
I am planning to have a HoneyPot Network on AWS. I want to have this set-up in the following way-
1. Have Tpot Node in each region of AWS in all the accounts we have.
2. Have a management node running on top of all Slave node for collection of data. 
3. All Tpotx should run in full capacity but I don't want to visualize anything on them. All analytics and visualization should happen from management node and on this management node, no need for any honeypot feature.
4. Also want to have this deployment to use some pots as external facing and some for only internal.

What is the best guidance to have this network?  What installation should I choose this for each  Tpot Node and management node? What would be the network config required to have it only as internal honeypot. Also, could you please suggest about the risk evaluation on this? Like if any of my Pot(internal+external) gets compromised, what's next on it?

**Comment by Fosocles** [comment]
Hi. I can't answer all your questions, but here is my take on this:
1. For your management node (MGMT) you can go either Standard or Nextgen (they're both super ok), and for your "slave" nodes you can go either Sensors only or Standard/Nextgen. If you choose Sensors, you'll need to add the Logstash container and point it to your MGMT and if you choose Std/Nextgen you'll need to remove Kibana, Elasticsearch, Head containers and leave Logstash and (again) point it to your MGMT to send the logs. Also, you'll have to decide if you choose to keep the log files locally on every node (you'll need to have Logrotate enabled) or send them directly to MGMT and discard them locally (if you restart TPot service they will be deleted). The versions you should install depend on the services you're trying to emulate and/or are relevant for you (I guess you'll be making some kind of statistics after analysing them).
2. Can you elaborate the whole "internal and external" thing?

For your other questions, I think @t3chn0m4g3 can help you better.

**Comment by archanchoudhury** [comment]
Thanks @Fosocles for the inputs.

Internal- We want some of our slave pots to be open only for internal VPCs and that won't receive any traffic from internet. This is to fulfill below usecases-
1. Getting information about insider threats. A pot should be deployed within our internal network and only a minimal number of employees should know the system exists.
2. Many hackers prefer to establish command-and-control servers for communication to compromised servers on the internal network. To identify such.

External- We want our slave pots to receive traffic from internet, so it is likely to be placed with such network configuration which has ports open to internet.

**Comment by t3chn0m4g3** [comment]
There were lots of discussions in the past, please review old issues, especially #250 which is no longer pursued.

**Comment by Fosocles** [comment]
Also, make sure to check out Cockpit's documentation regarding "master-slave" servers [here](https://cockpit-project.org/guide/latest/authentication.html#initial-auth).

**Comment by archanchoudhury** [comment]
Okies, Thanks.. How about my other queries?

**Comment by t3chn0m4g3** [comment]
@archanchoudhury As mentioned above, this has been discussed more than once in the past. Please review / search the previous issues. Thanks for understanding.
