### ISSUE TITLE
How do I install my own CA certificates to MITM inbound TLS traffic (20.06)

### ISSUE THREAD

**Issue by amishrabbit** [dtag-dev-sec/tpotce#618]
As an additional method to capture honeypot data, I would like to MITM the inbound SSL/TLS connection attempts to the honeypot (not the Kibana or other management interfaces, but the inbound requests to whichever honeypot is listening on 443/tcp). In order to do this, I need to add my certificate authority root certificates into the cert store on the appliance.

Are there instructions for installing my own CA certificates into whichever certificate store the honeypots use?

This is for a NextGen installation running the 20.06 T-Pot build.

**Comment by t3chn0m4g3** [comment]
Please have a look in our Wiki. You can do this using volumes with regard to Dionaea.
