### ISSUE TITLE
Docker, containers not installing from 19.03.3 ISO or update.sh

### ISSUE THREAD

**Issue by amishrabbit** [dtag-dev-sec/tpotce#619]
I've attempted a clean installation to a brand new VMWare VM under ESXi multiple times, using both the ISO for 19.03.3 and using the install.sh script (and the update.sh script) in /opt/tpot and until I manually installed docker, the installer was neither installing Docker nor any of the Docker containers the honeypots or packages are supposed to be in. As a result, I have a nice installation of Debian with almost none of the honeypot tools.

This was always so clean in the past. What happened here, guys?

Here's the startup screen. It isn't showing the IP addresses even though the box is getting one.
![tpot without docker](https://user-images.githubusercontent.com/2653726/80239556-af36d000-861d-11ea-8062-8643666fbf55.png)

I manually installed Docker just so I could run dps.sh, and it's all down because there are no containers.
![nodocker](https://user-images.githubusercontent.com/2653726/80239566-b362ed80-861d-11ea-8b24-8899d5a9d7f0.png)

Tried installing the standard and the nextgen builds several times, but the same thing keeps happening. It isn't downloading the containers and it doesn't even know how to execute the commands because something is missing.
![docker not found](https://user-images.githubusercontent.com/2653726/80239648-d9888d80-861d-11ea-9ca1-7c21c956dda6.png)

**Comment by Fosocles** [comment]
You're obviously missing docker / docker.io.
Try doing `apt purge docker -y` and `apt install docker.io docker-compose` and see if that works. Ping back here after that.

**Comment by t3chn0m4g3** [comment]
Sorry, but without logs I cannot help.

**Comment by crypto-coffee** [comment]
I'm running into the same problem. I installed docker with @Fosocles command above and then restarted. It assigned m machine an IP, but running `sudo /opt/tpot/bin/dps.sh` still shows all the services as STATUS: DOWN. How can I fix this? @t3chn0m4g3 What logs do you need?

**Comment by crypto-coffee** [comment]
I figured it out :) my firewall was blocking outbound ICMP traffic. I allowed ICMP out, reinstalled, and it worked!

**Comment by amishrabbit** [comment]
> 
> 
> I figured it out :) my firewall was blocking outbound ICMP traffic. I allowed ICMP out, reinstalled, and it worked!

Ugh, my ISP pushed a firmware update to my DSL modem which enabled the firewall and turned on a bunch of blocking. It turns out this was the reason it didn't work for me, either. I've never heard of blocked inbound ICMP being the cause of a problem before this, but I guess there's a first time for everything.

I unblocked the inbound ICMP and suddenly the box was able to connect to everything, download everything. Before this, I was even getting a timeout trying to run the update.sh script because it couldn't make a connection to index.docker.io in fewer than 5 seconds. 

@t3chn0m4g3 I didn't post the logs because it has always been a big PITA trying to collect all that information, so in the process of trying to diagnose the issue I also built a bash script that does the log collection automatically. https://github.com/dtag-dev-sec/tpotce/issues/630

**Comment by t3chn0m4g3** [comment]
@amishrabbit Thanks. Thing is, unless I have enough logs I cannot improve the installer with corresponding checks 😢

**Comment by amishrabbit** [comment]
I totally get it, which is why I made the script, because gathering all that data is a nuisance

**Comment by lemorn** [comment]
Hello, I would like to ask how to open icmp outbound communication? I am using vmware, and running uname -a shows "Linux intactapplication 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1"
