### ISSUE TITLE
ciscoasa_honeypot need to run services on the original ports.

### ISSUE THREAD

**Issue by trust1345** [dtag-dev-sec/tpotce#622]
ciscoasa_honeypot that is used in tpotce uses the 8443tcp 5000udp ports for emulation. However, the original emulation services listen to TCP80\443 (HTTPS) and 500udp.
This is said in the blog of the manufacturer of this honeypot.
https://cymmetria.com/blog/honeypot-cisco-asa-vulnerability/
Need to run services on the original ports.
For example, do this in compose file

  ciscoasa:
    container_name: ciscoasa
    restart: always
    tmpfs:
     - /tmp/ciscoasa:uid=2000,gid=2000
    network_mode: "host"
    ports:
     - "500:5000/udp"
     - "443:8443"
    image: "dtagdevsec/ciscoasa:2006"
    read_only: true
    volumes:
     - /data/ciscoasa/log:/var/log/ciscoasa

**Comment by t3chn0m4g3** [comment]
Thanks. Because of the fact that this is a honeypot designed for a single CVE mostly unavailable in the wild we will be removing CiscoASA honeypot for the 20.06 release. Ports always need to be balanced in its usage for a multi purpose system, however you can always adjust the ports to your needs.
