### ISSUE TITLE
Maybe it makes sense transition to a clean Apache License

### ISSUE THREAD

**Issue by trust1345** [dtag-dev-sec/tpotce#623]
Maybe it makes sense (with switching to ELK7) instead of
Elastic Search migrate to Open Distro for Elasticsearch.
https://opendistro.github.io/for-elasticsearch/faq.html
In addition to resolving issues with the license (transition to a clean Apache License), also solve the issue with security. In the fork from Amazon is built-in authentication and authorization and even SAML free and out of the box.

Build container dtagdevsec/kibana: 2006 with Apache License instead of Elastic License so that tpotce can be used without fear of potential attacks from the outside elastic.co
in a container
https://hub.docker.com/r/dtagdevsec/kibana/dockerfile
To use
https://artifacts.elastic.co/downloads/kibana/kibana-oss-7.6.2-linux-x86_64.tar.gz
Instead of
https://artifacts.elastic.co/downloads/kibana/kibana-7.6.2-linux-x86_64.tar.gz
License Difference Mainly
https://www.elastic.co/downloads/kibana
https://www.elastic.co/downloads/kibana-oss

Same with Logstash
https://www.elastic.co/downloads/logstash-oss

**Comment by t3chn0m4g3** [comment]
I do not see the apparent reason to switch to OSS based on your information. Authentication and other features have been made available to the basic license, too.

**Comment by trust1345** [comment]
In issue 2 different parts.
The first part.

Replace "Elastic search" - > "Open Distro for Elasticsearch"
Plus such decision:

- Switch to an open license. Arguments of Amazon are given here, https://aws.amazon.com/ru/blogs/opensource/keeping-open-source-open-open-distro-for-elasticsearch/. My opinion is briefly that there is a chance that elastic.co can follow the path of redis or mongodb significantly limit the possibility of free use. To do this, they only apply 3 points of their license
https://github.com/elastic/kibana/blob/7.6/licenses/ELASTIC-LICENSE.txt

- "Open Distro for Elasticsearch" includes (free of charge under the apache license) most of the functionality of x-pack security (which many try to add with search-guard), and also in kibana (as plugins). This will lay the foundation (in the further development of tpotce) for distributed Installation and make tpotce multiuser a solution with division by rights, setting, dashboards, alerting. So that engineers of different levels can work with tpotce at the same time.

- Also included for free (apache license) are machine learning abnormal detection capabilities. Alerting. Performance Analyzer. SQL JDBC driver.
Short comparison of capabilities (now the capabilities are increased)
https://logz.io/blog/open-distro-for-elasticsearch/
![open_distro_comparison_table-2](https://user-images.githubusercontent.com/64325530/80372977-0bf3ee00-889d-11ea-9ffe-f73da310162b.png)
Comparison by elastic.co
https://www.elastic.co/subscriptions


- machine learning abnormal detection capabilities
https://opendistro.github.io/for-elasticsearch/blog/odfe-updates/2019/11/real-time-anomaly-detection-in-open-distro-for-elasticsearch/


The second part of a question:

- Kibana basic elastic license -> Kibana Apache license

- Logstash basic elastic license -> Logstash Apache license

It 's only a matter of licenses.

- I will repeat my arguments (which I voiced in the first part of the question)
Switch to an open license. Arguments of Amazon are given here, https://aws.amazon.com/ru/blogs/opensource/keeping-open-source-open-open-distro-for-elasticsearch/. My opinion is briefly that there is a chance that elastic.co can follow the path of redis or mongodb significantly limit the possibility of free use. To do this, they only apply 3 points of their license
https://github.com/elastic/kibana/blob/7.6/licenses/ELASTIC-LICENSE.txt

**Comment by t3chn0m4g3** [comment]
Thanks for the swift feedback and the much appreciated information.

1. At the moment we have no immediate plans for a distributed installation of T-Pot.
2. While I appreciate the Open Distro for Elasticsearch, it is not the full stack, leaving Logstash behind.
3. The way we are currently using the Elastic Stack we can change to OSS licenses in the matter of hours.

With that in mind, I'd recommend to keep it the way it is until a change is necessary.

@vorband @rverton @sp3t3rs - What's your take on this?

**Comment by vorband** [comment]
I don't see any rush to change it atm.

**Comment by sp3t3rs** [comment]
First of all, Thanks for the heads-up @trust1345! Missing logstash is kinda sad though :cry: 

Thing is, as @t3chn0m4g3 said, he'd be able to move T-Pot to the OSS version of the ELK stack very easily, so let's keep our pants on for now.

**Comment by sp3t3rs** [comment]
Argh - didn't ment to close it :sos:

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback @vorband @sp3t3rs @trust1345. All things considered we have the possibility to quickly change things should this be required.
