### ISSUE TITLE
Errors importing saved objects

### ISSUE THREAD

**Issue by cibernicola** [dtag-dev-sec/tpotce#625]
I'm trying to import all Tpot Objects from https://raw.githubusercontent.com/dtag-dev-sec/tpotce/master/etc/objects/kibana_export.json.zip to a clean elastic installation version 7.6.2
Everything works but there are 3 objects with errors:

```
Failed to import 3 of 319 objects. Import failed

this.patternCache.clear is not a function Could not locate that index-pattern-field (id: honeypot.query.keyword) Could not locate that index-pattern-field (id: direction.keyword)
```
As far as I know both versions are compatible or maybe they aren't?
Any suggestion?
Thanks for this amaxing tool!

**Comment by t3chn0m4g3** [comment]
Thanks 😇 The file has not been ported to 7.6.2 yet.

**Comment by t3chn0m4g3** [comment]
Once 20.06 is released the file will also work with the latest Elastic stack.
