### ISSUE TITLE
I can't get t-pot running

### ISSUE THREAD

**Issue by AzinGuy** [dtag-dev-sec/tpotce#626]
![1](https://user-images.githubusercontent.com/36254213/80745996-033a2c80-8ad6-11ea-8d85-660997ea52ac.PNG)

![2](https://user-images.githubusercontent.com/36254213/80746068-1ea53780-8ad6-11ea-87ed-518f9b2143ce.PNG)

T-Pot version 19.03

Standard Edition

![3](https://user-images.githubusercontent.com/36254213/80746187-51e7c680-8ad6-11ea-8e55-70c215e11731.PNG)

![4](https://user-images.githubusercontent.com/36254213/80746386-a55a1480-8ad6-11ea-8640-1bad80f2128d.PNG)

![5](https://user-images.githubusercontent.com/36254213/80746457-c7ec2d80-8ad6-11ea-8695-d2550833eb9f.PNG)

I can't get tpot running, installation never fails but all service are still down after my installation

![6](https://user-images.githubusercontent.com/36254213/80746676-244f4d00-8ad7-11ea-8fed-6ec1df57b7e6.PNG)

![7](https://user-images.githubusercontent.com/36254213/80746785-4943c000-8ad7-11ea-9cd5-b195e44f102b.PNG)

![8](https://user-images.githubusercontent.com/36254213/80747154-d424ba80-8ad7-11ea-9657-c612f6f7f6e0.PNG)

![9](https://user-images.githubusercontent.com/36254213/80747208-e868b780-8ad7-11ea-99e1-400c5a623ad8.PNG)

I am trying to get tpot running for the past week.  I am trying to work on my senior project.  So I am kinda new to this.  Any help will much appreciated.  Thank You

**Comment by Fosocles** [comment]
Hi. Can you provide some logs from `journalctl -u tpot -f` ?

**Comment by AzinGuy** [comment]
![6](https://user-images.githubusercontent.com/36254213/80870802-a9646e80-8c5d-11ea-8e1d-36dd8e282036.PNG)

![7](https://user-images.githubusercontent.com/36254213/80870809-aff2e600-8c5d-11ea-9959-bfdf92dbbc35.PNG)

**Comment by Fosocles** [comment]
So, from what I can see `jq` is missing. Try installing it and restart tpot. If it fails again, please update with more logs.

**Comment by AzinGuy** [comment]
![8](https://user-images.githubusercontent.com/36254213/80871517-f0546300-8c61-11ea-9b29-e5be2d14d351.PNG)


![9](https://user-images.githubusercontent.com/36254213/80871522-f9453480-8c61-11ea-86d2-090e348a5999.PNG)

![10](https://user-images.githubusercontent.com/36254213/80871524-fcd8bb80-8c61-11ea-9a8d-9428bdc9fff9.PNG)

![11](https://user-images.githubusercontent.com/36254213/80871529-019d6f80-8c62-11ea-93f7-b67cdcb703f9.PNG)

**Comment by Fosocles** [comment]
`Ethtool` missing.

**Comment by AzinGuy** [comment]
Thank you the good new I am not getting any error when I run systemctl start tpot but dps.sh is all down
![1](https://user-images.githubusercontent.com/36254213/80892802-b85d1800-8c81-11ea-9775-d959a98f30c9.PNG)

**Comment by Fosocles** [comment]
From your latest screenshot I can see you're missing yet another tool (`grc`). Although your installation doesn't encounter any major error, some packages are not installed correctly/at all. Please review your logs to track the error (using systemctl).

**Comment by AzinGuy** [comment]
Okay we are almost there.  I installed some tool and now the bottom four says its down.  I have updated everything that need to be updated.

![2](https://user-images.githubusercontent.com/36254213/80916585-77f7ab80-8d0e-11ea-9bd2-c0187fa02915.PNG)

**Comment by AzinGuy** [comment]
hello

**Comment by t3chn0m4g3** [comment]
Please provide the installation logs (as kindly requested upon opening the issue). From the looks of it and the awesome help @Fosocles provided some repositories failed or could not be reached.

**Comment by AzinGuy** [comment]
Opps sorry I did figure it out and Its working thank you for your help guys
