### ISSUE TITLE
Several inconsistencies after install

### ISSUE THREAD

**Issue by cskwrd** [dtag-dev-sec/tpotce#628]
1. The installer doesn't create a system user when doing type `user` or `auto`.
1. Unable to manage containers from cockpit web UI.
1. Visualizations don't appear to pull data correctly.
![image](https://user-images.githubusercontent.com/10216235/81124599-7939fb80-8efb-11ea-897e-c6a54768c308.png)
![image](https://user-images.githubusercontent.com/10216235/81124640-8f47bc00-8efb-11ea-9b2f-16a34e998b91.png)
![image](https://user-images.githubusercontent.com/10216235/81124695-b7cfb600-8efb-11ea-85bd-d7796d6af03b.png)

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
```
Linux controlledfighter 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
```
- What T-Pot version are you currently using? `master`
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? `Nextgen`
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? `cloud - DO`
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`. `No`
- How long has your installation been running? `several hours`
- Did you install upgrades, packages or use the update script? 
`apt update && apt full-upgrade` then `install.sh --type=user`
- Did you modify any scripts or configs? If yes, please attach the changes. `no`
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/10216235/81123893-c4530f00-8ef9-11ea-94cc-1b188684e234.png)
![image](https://user-images.githubusercontent.com/10216235/81123928-d5038500-8ef9-11ea-89f0-0a8fcbfef524.png)

- How much free disk space is available (`df -h`)? `143G on /`
- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/10216235/81124100-36c3ef00-8efa-11ea-860c-f7807d1f353c.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/10216235/81124171-63780680-8efa-11ea-9208-5a7d46ae91de.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by Fosocles** [comment]
1. That's the correct behavior (post-install with either `user` or `auto` doesn't create user `tsec`, but rather use any existing user(s) on the system).
2. If I remember correctly, `docker-cockpit` has been removed from TPot. You could manually install it and get the appropriate tab in the UI, but I think @t3chn0m4g3 strongly disagrees.
3. I have no idea. try restarting your containers and/or `tpot.service`. 

You'll have to wait for @t3chn0m4g3's input on your last issue, but he's been missing for the last couple of days.

**Comment by cskwrd** [comment]
Thank you very much for your response. What are the recommended groups that the user should belong to, to properly administer a TPot instance in the cloud?

**Comment by Fosocles** [comment]
Well, I usually do `tpot` and `sudo` (you'll need this particular one for `docker-cockpit`).

**Comment by t3chn0m4g3** [comment]
1. Correct, since this is a manual installation type and it is assumed that there already is a systems / user account provided.
2. Known issue see #613 
3. Known issue see #531

**Comment by cskwrd** [comment]
@t3chn0m4g3, so for `auto` type, it would be the assumption that we are creating a new user outside the process then?

Why would it be bad to manage docker from the cockpit admin page?

**Comment by t3chn0m4g3** [comment]
1. Yes
2. People tend to start / stop containers within Cockpit which usually leaves `docker-compose` puzzled.

**Comment by cskwrd** [comment]
Thanks! @t3chn0m4g3 @Fosocles
