### ISSUE TITLE
Mailoney: _jsonparsefailure in Dashboard, no GeoIP

### ISSUE THREAD

**Issue by OXERY** [dtag-dev-sec/tpotce#629]
Hi,

on two newly installed Tpots I get a _jsonparsefailure in Mailoney, GeoIP information is also missing.
No errors in the mailoney log.. Here is an example document in json:
`{
  "_index": "logstash-2020.05.06",
  "_type": "doc",
  "_id": "xxxxxxxxxxxxxxxx",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-05-06T05:29:38.764Z",
    "tags": [
      "_jsonparsefailure"
    ],
    "dest_port": 25,
    "host": "xxx",
    "t-pot_hostname": "xxx",
    "t-pot_ip_ext": "xxx.xxx.xxx.xxx",
    "@version": "1",
    "t-pot_ip_int": "192.168.xxxx.xxxx",
    "message": "[1588742977.85][111.77.xxxx.xxxx:33826] DATA",
    "path": "/data/mailoney/log/commands.log",
    "type": "Mailoney"
  },
  "fields": {
    "@timestamp": [
      "2020-05-06T05:29:38.764Z"
    ]
  },
  "highlight": {
    "type": [
      "@kibana-highlighted-field@Mailoney@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1588742978764
  ]
}`

**Comment by Fosocles** [comment]
Missing GeoIP means lookup failure, so it's not a big deal. You could add/update Logstash's geoip databases to provent future issues.

**Comment by t3chn0m4g3** [comment]
@OXERY As long you see the event in Kibana this is normal behavior as @Fosocles described.

**Comment by OXERY** [comment]
Ok, got that. Thank you. Changed the logstash.conf in /opt/tpot/docker/elk/logstash/dist/ to use up2date-mmdb-Files from maxmind.
How can I rebuild the container? tpot.yml seems to make use of a precompiled image and I don't know how to edit..

**Comment by t3chn0m4g3** [comment]
Examples [here](https://github.com/dtag-dev-sec/tpotce/wiki).

**Comment by OXERY** [comment]
Thx, will take a look into it and get back to you soon

**Comment by Fosocles** [comment]
Or, if you don't want to recompile the images, you can simply mount your files as docker volumes.

**Comment by OXERY** [comment]
Changed the logstash.conf with the mentioned doc @t3chn0m4g3 https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-logstash.conf

mmdb is correctly linked and accessible, but Kibana still shows the tag "_jsonparsefailure" with message (example) "[1588936059.35][xxx.xxx.xxx.xxx:54047] QUIT", like mentioned in my first post

**Comment by t3chn0m4g3** [comment]
Sounds to me if the IP is not included in mmdb.

**Comment by Fosocles** [comment]
These databases are not 100% accurate, meaning there will always be **that one IP** which has no information associated. A few "unknown" IPs are nothing and, sooner or later, those dbs will be updated.
These being said, happy threat hunting!

**Comment by OXERY** [comment]
Mailoney is now running for nearly a week. A few days with the integrated geoip mmdb, a few days with the updated ones. When I filter for type: mailoney and NOT tags: "_jsonparsefailure" I don't get any entries back - it is not working at all....

**Comment by Fosocles** [comment]
From what I know, this particular instance of Mailoney (from TPot) logs data as a Python Dictionary which is serialized it into a Json string. 

Personally, I'm using Graylog and not having any problems with Mailoney/any other honeypot, but here's my 2 cents: you might have a misconfigured Grok or some JSON filter enabled on Mailoney (in particular). 

Have you made any changes to `logstash.conf` and/or using some sort of log collector script/jumpbox?

**Comment by OXERY** [comment]
No I used the latest Tpot-Iso Image to install. I only made changes to the logstash.conf for using different geoip database files, as mentioned above.

**Comment by t3chn0m4g3** [comment]
Works perfectly fine here with an installation I performed last week.

![image](https://user-images.githubusercontent.com/4318452/81546512-c7775080-937a-11ea-9059-6c475ed4ee67.png)

The installation works perfectly fine as do the docker images which are the same on both our ends.

**Comment by t3chn0m4g3** [comment]
Closing this, mechanisms all work as they supposed to. Thanks for understanding.
