### ISSUE TITLE
t-pot-autoinstall compatibility is now broken

### ISSUE THREAD

**Issue by arshak** [dtag-dev-sec/tpotce#63]
https://github.com/dtag-dev-sec/t-pot-autoinstall is still referring to 1603 instead of 1610 and not getting errors like

chmod: cannot access ‘/home/ubuntu/honeypot/installer/data/home/*’: No such file or directory
chmod: cannot access ‘/home/ubuntu/honeypot/installer/data/upstart/*’: No such file or directory

**Comment by t3chn0m4g3** [comment]
@arshak thanks and fixed, please clone again and retry.

**Comment by arshak** [comment]
@t3chn0m4g3 thanks, that fixed it!
