### ISSUE TITLE
The wireless interface will be removed when tpot.service starts

### ISSUE THREAD

**Issue by NieNoRc** [dtag-dev-sec/tpotce#633]
I installed the tpot 19.03 on the raspberry pi 4 (4GB RAM). The installation is based on existed system(raspbian) by the command`./install.sh --type=user` 
And the mode is standard. I know that the docker images  can't run on ARM architecture. So I built images by the dockerfiles(some need to be modified) and disabled the ELK. And I set that the tpot need start manually. 
My raspberry Pi is connected with Internet by wireless interface. The gateway is 192.168.1.1 and the LAN is 192.168.1.0/24. When I start tpot.service, the interface 'wlan0' will be removed. So I do:
`ifconfig wlan0 up` 
and 
`route add -net 192.168.1.0/24 wlan0`
`route add -net 0.0.0.0/0 gw 192.168.1.1 wlan0`
But I still can't access the Internet even I do `systemctl stop tpot`
If I stop tpot and reboot,  the interface returned and I can access the Internet.
So I wonder how to configure to prevent the removal of wireless interface when tpot start.

**Comment by t3chn0m4g3** [comment]
Impressive and congrats, but T-Pot is not compatible with Raspi and as such we cannot test and reproduce errors outside x86-64. Thanks for understanding.

**Comment by NieNoRc** [comment]
@t3chn0m4g3 Excuse me, but I think this issue is not related to the architecture. It may appear on a x86 laptop I guess. So I wonder which files control and management network interfaces when the tpot is running. Thanks!
