### ISSUE TITLE
 Why does my machine reboot regularly every day ？

### ISSUE THREAD

**Issue by Raul1718** [dtag-dev-sec/tpotce#634]
When i finally installed TPot completly, Tpot seems to be working.
But, when i changed some nginx  configuration.
The next day, I found that the configuration was restored.

Later, I checked it out.My machine reboot regularly every day,so  containers and Tpot service restart regularly every day. 

As shown in the figure below:

[![YJP1w8.png](https://s1.ax1x.com/2020/05/11/YJP1w8.png)](https://imgchr.com/i/YJP1w8)

 It should not be a problem for cloud service providers, I suspect it's Tpot.

and my basic support info see this link:
https://github.com/dtag-dev-sec/tpotce/issues/624

**Comment by Fosocles** [comment]
Tpot has built-in cronjobs. See /etc/crontab and comment accordingly.

**Comment by Raul1718** [comment]
@Fosocles yes, I saw it. But what's this cronjob purpose?

**Comment by t3chn0m4g3** [comment]
Should T-Pot for any reason hang, at least once a day a reboot will resolve a corresponding situation.

**Comment by Raul1718** [comment]
@t3chn0m4g3 what's "hang" means? some  docker containers down?
Can i delete the reboot command in /etc/crontab?

**Comment by Fosocles** [comment]
There seems to be a language barrier here. You can treat a "hang" or a "system hang" as an error/freeze. You can find more info [here](https://en.wikipedia.org/wiki/Hang_(computing)).

Of course you can delete/disable that crontab, but you'll have to regularly check your instance to see if there's any error and/or manually restart whatever service is troublesome.

**Comment by Raul1718** [comment]
@Fosocles ok. I see thank you.
