### ISSUE TITLE
Config Spelling Mistake

### ISSUE THREAD

**Issue by PR3R00T** [dtag-dev-sec/tpotce#635]
tpotce/docker/dionaea/dist/etc/services/smb.yaml - Line 27 missing "m" in comment.

**Comment by t3chn0m4g3** [comment]
Eagle eye. Thanks, seems to be an [upstream error](https://github.com/DinoTools/dionaea/blob/master/conf/services/smb.yaml), too.

**Comment by PR3R00T** [comment]
Ah, I also see it in the Dionaea documentation for the SMB service example. Would this issue be automatically raised with the Dionaea repo or would you like me to raise one?

**Comment by t3chn0m4g3** [comment]
I will fix it here. Would be great if you could open upstream and link here.

**Comment by PR3R00T** [comment]
https://github.com/DinoTools/dionaea/issues/282 has been raised to report the bug.

**Comment by t3chn0m4g3** [comment]
Thx
