### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by 0999ad** [dtag-dev-sec/tpotce#639]
Hi Team,

This by far the best HP I have come across! It's awesome.

I am trying to add users via "Manage and Administer the Elastic Stack" when I click on Security Settings I get the message 

Permission denied
You do not have permission to manage users.

How can I add users?
How do I gain full admin privileges over the stack?

Many thanks in advance

**Comment by 0999ad** [comment]
Hi

**Comment by 0999ad** [comment]
What version of the OS are you currently using 
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

Linux compatiblepeak 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

    What T-Pot version are you currently using?
    What edition (Standard, Nextgen, etc.) of T-Pot are you running?
19.03

    What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM - on ESXi
    Did you have any problems during the install? If yes, please attach /install.log /install.err.
None
    How long has your installation been running?
+24Hrs
    Did you install upgrades, packages or use the update script?
No
    Did you modify any scripts or configs? If yes, please attach the changes.
No
    Please provide a screenshot of glances and htop.
 
    How much free disk space is available (df -h)?
Lots

    What is the current container status (dps.sh)?
========| System |========
    Date:  Fri 15 May 2020 10:38:47 AM UTC
  Uptime:  10:38:47 up  7:10,  1 user,  load average: 0.87, 1.51, 1.36

NAME                  STATUS                       PORTS
adbhoney              Up 7 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 7 hours             
conpot_guardian_ast   Up 7 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 7 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 7 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 7 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 7 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 7 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 7 hours             
elasticpot            Up 7 hours             0.0.0.0:9200->9200/tcp
elasticsearch         Up 7 hours (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 7 hours             
head                  Up 7 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 7 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeytrap             Up 7 hours             
kibana                Up 7 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 7 hours (healthy)   
mailoney              Up 7 hours             0.0.0.0:25->25/tcp
medpot                Up 7 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 7 hours             
p0f                   Up 7 hours             
rdpy                  Up 7 hours             0.0.0.0:3389->3389/tcp
snare                 Up 7 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 7 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 7 hours             
tanner                Up 7 hours             
tanner_api            Up 7 hours             
tanner_phpox          Up 7 hours             
tanner_redis          Up 7 hours             6379/tcp
tanner_web            Up 7 hours 

    What is the status of the T-Pot service (systemctl status tpot)?
[root@compatiblepeak:~]# systemctl status tpot
● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Fri 2020-05-15 10:44:05 UTC; 1min 28s ago
  Process: 962 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
Cntrl PID: 984 (clean.sh)
    Tasks: 7 (limit: 4700)
   Memory: 211.3M
   CGroup: /system.slice/tpot.service
           ├─ 984 /bin/bash /opt/tpot/bin/clean.sh on
           ├─1167 tar -I /usr/bin/pigz -cvf /data/dionaea/bistreams.tgz /data/dionaea/bistreams/
           ├─1168 /bin/sh -c /usr/bin/pigz
           └─1169 /usr/bin/pigz

    What ports are being occupied? Stop T-Pot systemctl stop tpot and run netstat -tulpen

[root@compatiblepeak:~]# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          17623      678/python3         
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16412      696/sshd            
tcp6       0      0 :::64294                :::*                    LISTEN      0          13738      1/init              
tcp6       0      0 :::64295                :::*                    LISTEN      0          16414      696/sshd            
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          15422      594/dhclient        
udp        0      0 192.168.1.162:123       0.0.0.0:*                           0          16329      695/ntpd            
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          16327      695/ntpd            
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          16323      695/ntpd            
udp6       0      0 :::123                  :::*                                0          16320      695/ntpd            
[root@compatiblepeak:~]#

**Comment by 0999ad** [comment]
![Screenshot 2020-05-15 at 12 00 10](https://user-images.githubusercontent.com/34707278/82043547-b17fcd80-96a3-11ea-922a-7a354a4ab04f.png)

**Comment by t3chn0m4g3** [comment]
Thank you!

In Elastic Stack this feature is deliberately disabled for T-Pot. If you want to add users in this regard you need to review the configs for ELK and adjust the config to your needs via volume (find a volume example in the Wiki). Otherwise you can add users according to the Readme.

**Comment by 0999ad** [comment]
> Thank you!
> 
> In Elastic Stack this feature is deliberately disabled for T-Pot. If you want to add users in this regard you need to review the configs for ELK and adjust the config to your needs via volume (find a volume example in the Wiki). Otherwise you can add users according to the Readme.

Thank you for your super fast reply, I shall look in to it. my plan is to integrate this with a  threat intel platform and see what I can find :)
Again thank you for the fast reply .

Ad0999
