### ISSUE TITLE
Error on ./makeiso.sh on 16.10

### ISSUE THREAD

**Issue by SaiGonSeamus** [dtag-dev-sec/tpotce#64]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? New
- Did you install any upgrades or packages? no
- Did you modify any scripts?no
- Have you turned persistence on/off? no
- How much RAM available (login via ssh and run `htop`)? N/A
- How much stress are the CPUs under (login via ssh and run `htop`)? N/A
- How much swap space is being used (login via ssh and run `htop`)? N/A
- How much free disk space is available (login via ssh and run `sudo df -h`)? N/A
- What is the current container status (login via ssh and run `sudo start.sh`)? N/A

Getting this error with the latest build. Worked fine yesterday.

(udisksctl power-off:2318): GLib-GIO-CRITICAL **: g_dbus_interface_dup_object: assertion 'G_IS_DBUS_INTERFACE (interface_)' failed
./makeiso.sh: line 274:  2318 Segmentation fault      udisksctl power-off -b $myTARGET 2>&1

**Comment by t3chn0m4g3** [comment]
@SaiGonSeamus thanks for the info, but I cannot reproduce, works just fine with ubuntu 16.04.1 LTS.
Does this only occur if you write to USB or every time?
If USB, is it possible that you pull the USB drive before the script has finished and you see the bash prompt again?
What linux version are you using? (``cat /etc/issue``)?

**Comment by SaiGonSeamus** [comment]
Not USB. Each time I try to write to the HD of a Debian GNU/Linux 8 \n \l VM host I'm using.

Have deleted the directory and done a fresh clone, same error.

**Comment by t3chn0m4g3** [comment]
@SaiGonSeamus Hm, the subroutine running ``udisksctl`` is only called if you answer **yes** to write to a USB drive. Writing to HD (generating the ISO) does not call that command.

**Comment by SaiGonSeamus** [comment]
I was answering yes and selecting /dev/sda/ . The build part flashed in front of me. It must not have worked yesterday. My apologies.
