### ISSUE TITLE
Curator for elastic is not compatible

### ISSUE THREAD

**Issue by ovcrash** [dtag-dev-sec/tpotce#641]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- What T-Pot version are you currently using?
/opt/tpot]$ cat version
19.03.
It seems that the curator version is not compatible with the elastic version currently in the image.

if i run this command :
/opt/tpot/etc/curator]$ sudo curator --config curator.yml --dry-run actions.yml

i get this error:
Unable to create client connection to Elasticsearch.  Error: Elasticsearch version 7.6.2 incompatible with this version of Curator (5.2.0)

if i go inside /var/log/curator.log we see the same error:
/opt/tpot/etc/curator]$ tail /var/log/curator.log
2020-05-15 18:00:40,768 ERROR     Elasticsearch version 7.6.2 incompatible with this version of Curator (5.2.0)

Per the elastic document, the version of curator 5.2.0 is not comptaible: https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/version-compatibility.html

The minimus version for elasticsearch 7.6.2 is curator 5.7 : https://www.elastic.co/guide/en/elasticsearch/client/curator/5.7/version-compatibility.html

The current version of curator is 5.8.1 :
https://www.elastic.co/guide/en/elasticsearch/client/curator/5.8/version-compatibility.html

I think the version of curator should be updated.
Thanks.

**Comment by t3chn0m4g3** [comment]
Thanks. This is a regression after moving to Debian stable.

Need to install via pip again as maintainers currently do not provide a more recent version.

**Comment by t3chn0m4g3** [comment]
@ovcrash This is fixed now. You can either do a fresh install or run `/opt/tpot/update.sh`.

Should this unexpectedly not work please let me know and I will reopen.

Thanks again for reporting.
