### ISSUE TITLE
Azure Post-Install Crash/Unresponsive

### ISSUE THREAD

**Issue by RicardoPires19** [dtag-dev-sec/tpotce#644]
Hello, I created a VM in Azure and did a Post-Install. Everything works, but after an hour the VM becomes extremely unresponsive, I lose access to Kibana, Cockpit and even SSH. The logs in cockpit have no errors, and I've tried also the fix in #406, but to no avail.

![image](https://user-images.githubusercontent.com/7210193/82805493-08dc2580-9e7c-11ea-88e0-eaa788594c86.png)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux vividground 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Installing on Debian 9.7 or 10.4 doesn't solve the issue

- What T-Pot version are you currently using?
19.03, upgrading to version 20 doesn't fix the issue.
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Azure VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
I don't think so, but here it is just in case.
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.

- How long has your installation been running?
2 hours max.
- Did you install upgrades, packages or use the update script?
apt-get update
apt-get upgrade
apt-get dist-update
apt-get install git
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/7210193/82802058-36be6b80-9e76-11ea-9a6d-86384ee12f2f.png)
![image](https://user-images.githubusercontent.com/7210193/82802141-505fb300-9e76-11ea-8017-fb64dcf66144.png)

- How much free disk space is available (`df -h`)?
953G - 99%
- What is the current container status (`dps.sh`)?
All containers function normally. The problem is that after an hour or 2 the VM becomes unresponsive and I can't perform any actions.
- What is the status of the T-Pot service (`systemctl status tpot`)?
tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-05-25 10:44:57 WEST; 5min ago
 Main PID: 1554 (docker-compose)
    Tasks: 32 (limit: 9529)
   Memory: 1.2G
   CGroup: /system.slice/tpot.service
           └─1554 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Loading plugin SaveFile v1.0.1
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Loading plugin logattacker v1.0.2
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Loading plugin logjson v1.1.0
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Servers will run as user honeytrap (2000).
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Servers will run as group honeytrap (2000).
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Loading default responses.
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Connections will be handled in normal mode by default.
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Logging to /opt/honeytrap/var/log/honeytrap.log.
May 25 10:50:38 vividground docker-compose[1554]: honeytrap              |   Core module initialized.
May 25 10:50:39 vividground docker-compose[1554]: honeytrap              | [2020-05-25 09:50:39]  ***** requesting tcp connection on ****.

After stopping and starting tpot.service, dps.sh shows that all containers are running.
![image](https://user-images.githubusercontent.com/7210193/82803300-33c47a80-9e78-11ea-9bd1-86c30c9d6684.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/7210193/82802491-e562ac00-9e76-11ea-8e5f-44bac38f2605.png)

**Comment by t3chn0m4g3** [comment]
I have no access to Azure and #406 would have been my first recommendation. It seems the images some of the cloud providers use are modified to some extent and we have no influence on that.

**Comment by t3chn0m4g3** [comment]
Were you able to resolve this?

**Comment by RicardoPires19** [comment]
No, and my Azure Free Trial has also expired so there isn't much I can do now. But this seems to be exclusive to Azure. I've tried the Post-Install method with a different cloud provider and it worked with no problems.

**Comment by t3chn0m4g3** [comment]
Appreciate the feedback, but since there is nothing we can really do I am closing this. Thanks for understanding.
