### ISSUE TITLE
NFQ spoken on unknown ports feature active?

### ISSUE THREAD

**Issue by ChriDr** [dtag-dev-sec/tpotce#645]
Hi there, 

First of all I would like tot hank you very much for this awesome projects and your contribution.

I would like to know whether the feature of honeytrap or dionaea is active, where a new service get started every time, when a connection is established to non existing services? Within dionaea  this feature is called nfq:

https://dionaea.readthedocs.io/en/latest/service/nfq.html

I found some iptables rules for nfq within the github source code for the main branch, but I am not sure what exactly is active. 

Thank you four your help,

**Comment by iukea1** [comment]
Please keep me in the loop on this if possible! This is something I was looking into but sadly got distracted

**Comment by ChriDr** [comment]
So it seems that this feature is activated within the honeytrap configuration.  I propose that  this should be activated for services within 1 - 1023 port range as well. As an example, if one connects to port 1 via telnet, it does not work. For all port, which are > 1023, it does.

Best,

**Comment by t3chn0m4g3** [comment]
The rules script will ensure to forward all non used ports (per definition in `/opt/tpot/etc/tpot.yml`) to either glutton or honeytrap. We are not using Dionaea for that.
