### ISSUE TITLE
After intstall, there are many docker start faild.

### ISSUE THREAD

**Issue by NeverMore00wolf** [dtag-dev-sec/tpotce#646]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Linux sophisticatedprotection 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
- What T-Pot version are you currently using?
19.03.3
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
hardware 
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
./install.sh  line696 addgroup  command not find
./install.sh line697 adduser command not find
chown :invalid tpot:tpot
./install.sh reboot command not find
- How long has your installation been running?
3days
- Did you install upgrades, packages or use the update script?
- Did you modify any scripts or configs? If yes, please attach the changes.
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)?
1T
- What is the current container status (`dps.sh`)?
NAME                  STATUS                       PORTS
amazing_hertz          Exited (0) About an hour ago
competent_archimedes   Exited (2) 33 minutes ago
cowrie                 Up 2 hours                     0.0.0.0:22-23->22-23/tcp
cranky_galois          Exited (2) 29 minutes ago
cyberchef              Up 2 hours (healthy)           127.0.0.1:64299->8000/tcp
dionaea                Up 2 hours
distracted_leavitt     Exited (2) 33 minutes ago
elasticpot             Up 2 hours                     0.0.0.0:9200->9200/tcp
ewsposter              Up 4 seconds
fervent_franklin       Exited (0) About an hour ago
flamboyant_allen       Exited (0) 35 minutes ago
mailoney               Up 2 hours                     0.0.0.0:25->25/tcp
nginx                  Up 2 hours
nifty_shockley         Exited (0) About an hour ago
recursing_chaum        Exited (0) About an hour ago
snare                  Up 2 hours                     0.0.0.0:80->80/tcp
suricata               Up 2 hours
tanner                 Up 2 hours
tanner_api             Up 2 hours
tanner_phpox           Up 2 hours
tanner_redis           Up 2 hours                     6379/tcp
tanner_web             Up 2 hours
adbhoney              DOWN
ciscoasa              DOWN
conpot_guardian_ast   DOWN
conpot_iec104         DOWN
conpot_ipmi           DOWN
conpot_kamstrup_382   DOWN
elasticsearch         DOWN
head                  DOWN
heralding             DOWN
honeytrap             DOWN
kibana                DOWN
logstash              DOWN
medpot                DOWN
p0f                   DOWN
rdpy                  DOWN
spiderfoot            DOWN

- What is the status of the T-Pot service (`systemctl status tpot`)?
tpot can start 
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by t3chn0m4g3** [comment]
The installation seems to have failed. Without proper logs I can only recommend to reinstall.
