### ISSUE TITLE
How to transfer /data  file to another instance live

### ISSUE THREAD

**Issue by reverso031** [dtag-dev-sec/tpotce#647]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

uname- a
Linux decentbrick 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Cloud-GCP
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
3 hours
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.

- How much free disk space is available (`df -h`)?
Enough 
- What is the current container status (`dps.sh`)?
All up and running
- What is the status of the T-Pot service (`systemctl status tpot`)?
Active
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

I have setup tpot on cloud GCP.I have everything going well.But when i use ~/.2fa....sh .It failed and then don't give me access after reboot on port 64294.It says wrong username and password.I figured when i run this script this doesn't create image that i saw in local setup and it directly terminate connection.
Can you also help me bit ,how can i extract /data from GCP into another instance or via putty .It doesn't let me in .I have created public ,private key using putty but i cant login back .Before installing tpot it was working fine.

**Comment by t3chn0m4g3** [comment]
Just tar the `data` folder and extract it on the new installation, but stop T-Pot service before you do so.
