### ISSUE TITLE
NET::ERR_CERT_INVALID on fresh install

### ISSUE THREAD

**Issue by hackdefendr** [dtag-dev-sec/tpotce#648]
- What version of the OS are you currently using `lsb_release -a` and `uname -a`? 
Linux verticalmonkey 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
- What T-Pot version are you currently using?
19.03
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
an hour
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
No
- Please provide a screenshot of `glances` and `htop`.
<img width="1088" alt="Screen Shot 2020-05-31 at 10 06 30 AM" src="https://user-images.githubusercontent.com/2224217/83355659-7a0d5400-a326-11ea-9549-980f4cb7773a.png">

This is a fresh installation under Hyper-V.  The installation runs without issue and T-Pot starts up as it should. The problem is with the self-signed certificate. No browser is accepting it so I can't monitor anything.

The easiest solution (for me) would be to use my wildcard cert, but I can't find any documentation for replacing the nginx.crt/nginx.key being used. Is it as simple as drop in and replace the two files, then restart services?

**Comment by t3chn0m4g3** [comment]
Please review #478.
