### ISSUE TITLE
Glutton "query" field items missing from Kibana report

### ISSUE THREAD

**Issue by amishrabbit** [dtag-dev-sec/tpotce#650]
Hello there. While creating a custom Kibana report widget that outputs the contents of the "keyword.query" value from the glutton.log data, I discovered that queries beyond a certain length (in bytes) appear not to be getting added to the report.

I don't know whether to upload this bug ticket here, or with the developers of some other component (Glutton, Elasticsearch, Kibana?), but I thought I'd start here.

I discovered that this particular query line (590 bytes in length) in the logs was not being displayed in the report in Kibana:

![glutton log with long query crop](https://user-images.githubusercontent.com/2653726/83818785-6c88fe80-a685-11ea-98e5-3203b58b05a6.png)

Here is how the report is built in Kibana's editor:

![glutton query strings kibana report editor crop](https://user-images.githubusercontent.com/2653726/83818844-90e4db00-a685-11ea-8e23-d5ee6c30f39f.png)

This is the output in the report:
![glutton query strings kibana report editor](https://user-images.githubusercontent.com/2653726/83818941-ca1d4b00-a685-11ea-8b22-7d1b885f2cd7.png)

Here's the CSV output of a report spanning the timeslice which I expect to contain the rogue "query" log entry:

[Glutton query strings(1).zip](https://github.com/dtag-dev-sec/tpotce/files/4733092/Glutton.query.strings.1.zip)

Here is the log file that contains the "query" log line that seems to be too long: 

[glutton.log.zip](https://github.com/dtag-dev-sec/tpotce/files/4733093/glutton.log.zip)

Basic support info is in the zip below

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)
[bugticket_log.zip](https://github.com/dtag-dev-sec/tpotce/files/4733080/bugticket_log.zip)

**Comment by t3chn0m4g3** [comment]
You have created a visualization which is ranked to max. 200 entries. If you really want to know if the field was ingested correctly you need to look up the event in `Discover`.

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.

**Comment by amishrabbit** [comment]
Hi Marco. There aren't more than 50 entries. I created the report based on the information observed in Discover.

**Comment by t3chn0m4g3** [comment]
@amishrabbit According to your screenshots I cannot see any reference to Discover. If the event is correctly visible in Discover there might me some limits with the visualization involved I do not have any influence on.
