### ISSUE TITLE
Option to send logs to dshield project

### ISSUE THREAD

**Issue by rcKillam** [dtag-dev-sec/tpotce#654]
**Is your feature request related to a problem? Please describe.**
- Sending cowrie logs to the dshield project in the steps outlined in the link is a bit daunting for a newb to docker like myself. I would be really awesome for tpot to just do it automatically (with the user's permission and apikey.

**Describe the solution you'd like**
- During install it would be nice if it would ask if the user would like to send data to the project.
- Somewhere in the admin panel, add a location to add the apikey and appropriate information post install.
- Possibly add a link somewhere in the webconsole to access the dshield data.

**Describe alternatives you've considered**

**Additional context**
- https://isc.sans.edu/diary/TPOT%27s+Cowrie+to+ISC+Logs/25976

**Comment by t3chn0m4g3** [comment]
@rcKillam Data sharing with third parties is something which varies from user to user. Some want to transfer to MISP, others to DSHIELD others just do not want to share at all. This is the reason why we do not support sharing through honeypots but through EWSPoster via HPFeeds. You may find an example on how to mount individual configs as volumes in our [Wiki](https://github.com/dtag-dev-sec/tpotce/wiki/Reconfigure-ews.cfg). Based on the example you can reconfigure Cowrie to send events to DShield.
Thanks for understanding.
