### ISSUE TITLE
ewsposter 403 Client Error: FORBIDDEN for url: https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage

### ISSUE THREAD

**Issue by mfld-pub** [dtag-dev-sec/tpotce#655]
post-install on debian 10 buster succeeds but logs reveal that it may not be feeding sicherheitstacho.eu

I did a fresh install on a test system and waited a week to see if it was a temporary issue on the API endpoint but it is on-going and reproducible.

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Linux israelishadowbox 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

- What T-Pot version are you currently using?
19.03.3 - from postinstall script on debian 10 minimal.

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
nextgen 

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Hetzner Cloud

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
None noticed but I found this in /install.err:

npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rxn7esww/elasticsearch-curator/

- How long has your installation been running?
8 days

- Did you install upgrades, packages or use the update script?
Yes to both.

- Did you modify any scripts or configs? If yes, please attach the changes.
None

- Please provide a screenshot of `glances` and `htop`.
![htop](https://user-images.githubusercontent.com/66289900/85103968-36797c00-b23a-11ea-80e7-53d7ce2f2fe4.JPG)

![glances](https://user-images.githubusercontent.com/66289900/85103976-38dbd600-b23a-11ea-9e83-b869e7456f4d.JPG)

- How much free disk space is available (`df -h`)?

All are below 20% utilization

- What is the current container status (`dps.sh`)?
========| System |========
    Date:  Fri 19 Jun 2020 08:37:12 AM CEST
  Uptime:  08:37:12 up  5:09,  1 user,  load average: 1.71, 1.48, 1.35

NAME                  STATUS                       PORTS
adbhoney              Up 5 hours             0.0.0.0:5555->5555/tcp
ciscoasa              Up 5 hours
citrixhoneypot        Up 5 hours             0.0.0.0:443->443/tcp
conpot_guardian_ast   Up 5 hours             0.0.0.0:10001->10001/tcp
conpot_iec104         Up 5 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp
conpot_ipmi           Up 5 hours             0.0.0.0:623->623/tcp
conpot_kamstrup_382   Up 5 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp
cowrie                Up 5 hours             0.0.0.0:22-23->22-23/tcp
cyberchef             Up 5 hours (healthy)   127.0.0.1:64299->8000/tcp
dionaea               Up 5 hours
elasticsearch         Up 5 hours (healthy)   127.0.0.1:64298->9200/tcp
ewsposter             Up 5 hours
fatt                  Up 5 hours
glutton               Up 5 hours
head                  Up 5 hours (healthy)   127.0.0.1:64302->9100/tcp
heralding             Up 5 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp
honeypy               Up 5 hours             0.0.0.0:7-8->7-8/tcp, 0.0.0.0:2048->2048/tcp, 0.0.0.0:2323-2324->2323-2324/tcp, 0.0.0.0:4096->4096/tcp, 0.0.0.0:9200->9200/tcp
kibana                Up 5 hours (healthy)   127.0.0.1:64296->5601/tcp
logstash              Up 5 hours (healthy)
mailoney              Up 5 hours             0.0.0.0:25->25/tcp
medpot                Up 5 hours             0.0.0.0:2575->2575/tcp
nginx                 Up 5 hours
p0f                   Up 5 hours
rdpy                  Up 5 hours             0.0.0.0:3389->3389/tcp
snare                 Up 5 hours             0.0.0.0:80->80/tcp
spiderfoot            Up 5 hours (healthy)   127.0.0.1:64303->8080/tcp
suricata              Up 5 hours
tanner                Up 5 hours
tanner_api            Up 5 hours
tanner_phpox          Up 5 hours
tanner_redis          Up 5 hours             6379/tcp

- What is the status of the T-Pot service (`systemctl status tpot`)?

● tpot.service - tpot
   Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-06-19 03:28:01 CEST; 5h 10min ago
  Process: 888 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)
  Process: 912 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)
  Process: 1121 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)
  Process: 1124 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)
  Process: 1130 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)
  Process: 1147 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)
  Process: 1166 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)
  Process: 1183 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)
  Process: 1203 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)
  Process: 1209 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)
  Process: 1215 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)
  Process: 1221 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)
 Main PID: 1298 (docker-compose)
    Tasks: 33 (limit: 4915)
   Memory: 49.9M
   CGroup: /system.slice/tpot.service
           └─1298 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color

Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Starting CISCO-ASA Modul.
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Send Limit is set to : 500. Adapting to limit!
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |     -> 0 EWS alert records send ...
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Starting Tanner Modul.
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Send Limit is set to : 500. Adapting to limit!
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |     -> 0 EWS alert records send ...
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Starting Glutton Modul.
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Send Limit is set to : 500. Adapting to limit!
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |     -> 0 EWS alert records send ...
Jun 19 08:38:30 israelishadowbox docker-compose[1298]: ewsposter              |  => Sleeping for 13 seconds ....

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          17098      658/python3
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          16189      701/sshd
tcp6       0      0 :::64294                :::*                    LISTEN      0          13267      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          16191      701/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          16176      673/dhclient
udp        0      0 192.168.42.3:123        0.0.0.0:*                           0          18610      708/ntpd
udp        0      0 xxx.xxx.xxx.xx:123      0.0.0.0:*                           0          18608      708/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          18606      708/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          18602      708/ntpd
udp6       0      0 :::123                  :::*                                0          18599      708/ntpd

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

docker logs ewsposter | head -n 50

docker logs ewsposter
EWS Poster v1.9.7a (c) by Markus Schroer <markus.nospam@telekom.edit>

 => Create ews.idx counterfile
 => Using external IP address xxx.xxx.xxx.xxx
 => [ERROR] Could not determine a valid private IP
 => Create lock socket successfull.
 => Sender : No Jobs to send in /opt/ewsposter/spool/
 => Starting Glastopf V3.x Modul.
    => [GLASTOPFV3] [INFO] Missing sqlitedb file /data/glastopf/db/glastopf.db. Skipping !
 => Starting Dionaea Modul.
    -> [INFO] No entry's in Dionaea Database. Skip !
 => Starting Honeytrap Modul.
    => [HONEYTRAP] [ERROR] Missing Attacker File /data/honeytrap/log/attacker.log. Abort !
    -> Calculate MD5sum for Payload Files
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting Conpot Modul.
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting Cowrie Modul.
 => Send Limit is set to : 500. Adapting to limit!
 => Starting Elasticpot Modul.
    => [ELASTICPOT] [ERROR] Missing LogFile /data/elasticpot/log/elasticpot.log. Skip !
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting Suricata Modul.
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting RDPY Modul.
 => Send Limit is set to : 500. Adapting to limit!
    -> 1 EWS alert records send ...
 => Starting MAILONEY Modul.
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting VNCLOWPOT Modul.
    => [VNCLOWPOT] [ERROR] Missing LogFile /data/vnclowpot/log/vnclowpot.log. Skip !
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting HERALDING Modul.
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...
 => Starting CISCO-ASA Modul.
 => Send Limit is set to : 500. Adapting to limit!
    -> 0 EWS alert records send ...

**Comment by t3chn0m4g3** [comment]
In the logs you provided `ewsposter` seems to work without problems. The only thing I could see is that `curator` might not be installed correctly (was [fixed](https://github.com/dtag-dev-sec/tpotce/commit/4cc1aa08c22708c9e7412a838932a2dababaacb6) 10 days ago), but this does not explain the error message you receive.
Personally I cannot reproduce this. How many events do you have in a 24h timeframe in Kibana?

**Comment by mfld-pub** [comment]
Kibana says last 24 hours saw 34k Dionaea, 6k Cowrie and ~8k others so there are close to 50k events. 

I just tried docker logs ewsposter | head -n 500 and did not see the "403 Client Error: FORBIDDEN for url: https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage" anymore. 

But if I tail /var/lib/docker/overlay2/cc7ed47d2128720684734d8fb40031532569e00f65081674c0b0d3e59b5b5fbb/merged/opt/ewsposter/log/ews.log I can find it occurring today.

2020-06-19 08:06:08 [ewswebservice] HTTP Errorcode != 200 (403 Client Error: FORBIDDEN for url: https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage)
2020-06-19 08:06:09 [ewswebservice] HTTP Errorcode != 200 (403 Client Error: FORBIDDEN for url: https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage)
2020-06-19 08:06:09 [ewswebservice] HTTP Errorcode != 200 (403 Client Error: FORBIDDEN for url: https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage)
2020-06-19 08:06:09 [ewswebservice] HTTP Errorcode != 200 (403 Client Error: FORBIDDEN for url: https://community.sicherheitstacho.eu/ews-0.1/alert/postSimpleMessage)

**Comment by t3chn0m4g3** [comment]
Thank you for the swift feedback. Looking into it.

**Comment by sp3t3rs** [comment]
Hi Micheal,

thanks for the heads up. The 403 replies are indeed "normal". It happens, when your request gets load balanced on a backend node that is currently unavailable for community (so basically, your :smile:) data ingestion. However, this should unlikely result in data not beeing transmitted since ewposter has retry-mechanism that will resubmit the data - it's very likely that with one of the next retries (if I remember correctly, limit is five times), ewsposter will reach a backend node that is enabled for community. 

We're aware that this is a little bit annoying, but for us it's currently the only way to slize the backend node capability. But we're on it and the problem will be gone with the next backend redeployment.

Cheers
Simon

DT Honeypot Backend Operations

**Comment by mfld-pub** [comment]
Fantastic! I just wanted to be sure we are uploading correctly, not to miss out on whatever small piece of the puzzle we can contribute.

**Comment by sp3t3rs** [comment]
Hi @mfld-pub ,

just wanted to give you a heads-up, that those nasty 403 HTTP Errors are gone!
From now on, every requests gets balanced on a community-enabled backend node.

Have fun using T-Pot and also submitting data! 

Cheers
Simon 

on behalf of
Deutsche Telekom Security
Honeypot Backend Operations
