### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by nu11secur1ty** [dtag-dev-sec/tpotce#656]
When I try to compose all containers locally "docker-compose build"

 ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3vnq3s3g/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3vnq3s3g/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-igaizf2h/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-8_uxqlsq/overlay --compile Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 /usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8_uxqlsq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 3.0a5' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet >= 0.4.16 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'conpot_IEC104' failed to build: The command '/bin/sh -c sed -i 's/dl-cdn/dl-2/g' /etc/apk/repositories &&     apk -U add              build-base              file              git              libev              libtool              libcap              libxslt              libxslt-dev              mariadb-dev              pkgconfig              python3              python3-dev              py-cffi              py-cryptography              tcpdump              wget &&     git clone --depth=1 https://github.com/mushorg/conpot /opt/conpot &&     cd /opt/conpot/ &&     sed -i "s/tmp_mib_dir = tempfile.mkdtemp()/tmp_mib_dir = tempfile.mkdtemp(dir=os.environ['CONPOT_TMP'])/" /opt/conpot/conpot/protocols/snmp/snmp_server.py &&     sed -i 's/port="2121"/port="21"/' /opt/conpot/conpot/templates/default/ftp/ftp.xml &&     sed -i 's/port="8800"/port="80"/' /opt/conpot/conpot/templates/default/http/http.xml &&     sed -i 's/port="6230"/port="623"/' /opt/conpot/conpot/templates/default/ipmi/ipmi.xml &&     sed -i 's/port="5020"/port="502"/' /opt/conpot/conpot/templates/default/modbus/modbus.xml &&     sed -i 's/port="10201"/port="102"/' /opt/conpot/conpot/templates/default/s7comm/s7comm.xml &&     sed -i 's/port="16100"/port="161"/' /opt/conpot/conpot/templates/default/snmp/snmp.xml &&     sed -i 's/port="6969"/port="69"/' /opt/conpot/conpot/templates/default/tftp/tftp.xml &&     sed -i 's/port="16100"/port="161"/' /opt/conpot/conpot/templates/IEC104/snmp/snmp.xml &&     sed -i 's/port="6230"/port="623"/' /opt/conpot/conpot/templates/ipmi/ipmi/ipmi.xml &&     pip3 install --no-cache-dir -U setuptools &&     pip3 install --no-cache-dir . &&     cd / &&     rm -rf /opt/conpot /tmp/* /var/tmp/* &&     setcap cap_net_bind_service=+ep /usr/bin/python3.7 &&     mkdir -p /etc/conpot /var/log/conpot /usr/share/wireshark &&     wget https://github.com/wireshark/wireshark/raw/master/manuf -o /usr/share/wireshark/manuf &&     cp /root/dist/conpot.cfg /etc/conpot/conpot.cfg &&     cp -R /root/dist/templates /usr/lib/python3.7/site-packages/conpot/ &&     addgroup -g 2000 conpot &&     adduser -S -s /bin/ash -u 2000 -D -g 2000 conpot &&     apk del --purge             build-base             cython-dev             file             git             libev             libtool             libxslt-dev             mariadb-dev             pkgconfig             python3-dev             py-cffi             wget &&     rm -rf /root/* &&     rm -rf /tmp/* &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1

**Comment by t3chn0m4g3** [comment]
This compose file only exists for developers. Since upstream repos change frequently it is expected to run into errors.

**Comment by nu11secur1ty** [comment]
Thanks, dear friend.
