### ISSUE TITLE
T-Pot is not accessible (Network issue.)

### ISSUE THREAD

**Issue by jnanesh-byte** [dtag-dev-sec/tpotce#661]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Debian 10 Buster 
Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

- What T-Pot version are you currently using?

19.03

- What edition (Standard, Nextgen, etc.) of T-Pot are you running?

- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
Virtual box VM - Base machine is in cloud.

- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
Nope

- How long has your installation been running?
2 weeks

- Did you install upgrades, packages or use the update script?
No

- Did you modify any scripts or configs? If yes, please attach the changes
Nope.
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/59313440/85952007-2f621480-b984-11ea-88ce-f740b2104059.png)

- How much free disk space is available (`df -h`)?
Filesystem      Size  Used Avail Use% Mounted on
udev            5.9G     0  5.9G   0% /dev
tmpfs           1.2G   11M  1.2G   1% /run
/dev/sda2       149G   16G  127G  11% /
tmpfs           6.0G     0  6.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           6.0G     0  6.0G   0% /sys/fs/cgroup
tmpfs           1.2G     0  1.2G   0% /run/user/1000

- What is the current container status (`dps.sh`)?
running
- What is the status of the T-Pot service (`systemctl status tpot`)?
running
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
root@metropolitancarpet:~]# netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          15469      536/sshd
tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          15750      518/python3
tcp6       0      0 :::64294                :::*                    LISTEN      0          12197      1/init
tcp6       0      0 :::64295                :::*                    LISTEN      0          15480      536/sshd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          14290      458/dhclient
udp        0      0 10.0.2.15:123           0.0.0.0:*                           0          15446      537/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          15444      537/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          15440      537/ntpd
udp6       0      0 :::123                  :::*                                0          15437      537/ntpd

Hi, 

I have installed tpot 19.03 in Virtualbox VM which was built on Hetzner Cloud ubuntu machine. As informed in tpot installation document I kept network setting as a bridged network but I'm not able to access web URL/unable ssh machine. But when I change the network setting to NAT web url and ssh works fine from any other network but not seeing any attacks. Honeypot logs show all internal IP's only. Please suggest to me how to fix this.
FYI, I have tried assigning static IP but no luck.
TIA:)

**Comment by t3chn0m4g3** [comment]
I am not familiar with Hetzner, however I just released [T-Pot 20.06](https://github.com/dtag-dev-sec/tpotce/releases/tag/20.06.0), maybe this improves things.

**Comment by mfld-pub** [comment]
We use a lot of Hetzner so I can probably provide some pointers here. 
In Hetzner dedicated servers you can run a virtual instance in bridged mode and assign it an additional IP address. Hetzner can provide a virtual MAC address for it so if correctly allocated the virtual instance will perform as expected in bridged mode.

In Hetzner Cloud you cannot bridge a virtual guest because they have no mechanism for additional public IP addresses on Hetzner Cloud instances. The additional MAC address originating from the bridged guest would have nowhere to go.

References:
How it works on dedicated:
https://wiki.hetzner.de/index.php/Zusaetzliche_IP-Adressen/en
https://superuser.com/questions/1420259/hetzner-reported-not-allowed-mac-addresses-in-subnet

For Hetzner Cloud there is AFAIK no way to bridge a guest.

I have had T-Pot Nextgen run successfully on their new AMD EPYC based instances, the CPX31 is the lowest tier that will work.

**Comment by jnanesh-byte** [comment]
Thank you for the response, I will try to fix this. Please keep this issue open for another 2-3 days.
