### ISSUE TITLE
cowrie download in kibana

### ISSUE THREAD

**Issue by N0NameN0** [dtag-dev-sec/tpotce#664]
hi,
i'am using the fresh new 2020.06 out of the box iso.
All seems ok except the **Cowrie - Top Downloads**
i have **wget** commands in the command line input and i can find the files in the /data/cowrie/dl
but nothing in the kibana view
![image](https://user-images.githubusercontent.com/1048113/86299821-80327100-bc01-11ea-950a-7cbf92c18a25.png)

do i have to activate something ?

**Comment by t3chn0m4g3** [comment]
Just reviewed it, works perfectly fine here...
![image](https://user-images.githubusercontent.com/4318452/86336853-ac291300-bc50-11ea-9edd-4485afcf12b2.png)

The visualization however works only if Cowrie provides the corresponding `filename` field in relation to the event. If the field is not present or empty the visualization cannot display any info.

**Comment by N0NameN0** [comment]
what version are you using ?? 
without any modification in config file ? 
BTW i'm using the standard installation choice.

**Comment by t3chn0m4g3** [comment]
Need the original Cowrie JSON Log file in /data/cowrie/log. If the field is not present there or empty there is nothing for Logstash process and for Kibana to render.

**Comment by N0NameN0** [comment]
i logged by the honey door and try a wget : 

i can find this in /data/cowrie/log/cowrie.json : 
```
{"eventid":"cowrie.command.input","input":"wget http://test-debit.free.fr/image.iso","message":"CMD: wget http://test-debit.free.fr/image.iso","sensor":"6d8342e03a1d","timestamp":"2020-07-02T13:28:41.486682Z","src_ip":"X.X.X.X","session":"001e050cb193"}
{"eventid":"cowrie.session.file_download","url":"http://test-debit.free.fr/image.iso","outfile":"dl/0f8120de197fe6cc20a8b6e61eb7e9bff7fcf7281fe790e04b218932133d7536","shasum":"0f8120de197fe6cc20a8b6e61eb7e9bff7fcf7281fe790e04b218932133d7536","destfile":"/root/image.iso","message":"Downloaded URL (http://test-debit.free.fr/image.iso) with SHA-256 0f8120de197fe6cc20a8b6e61eb7e9bff7fcf7281fe790e04b218932133d7536 to dl/0f8120de197fe6cc20a8b6e61eb7e9bff7fcf7281fe790e04b218932133d7536","sensor":"6d8342e03a1d","timestamp":"2020-07-02T13:28:52.693501Z","src_ip":"X.X.X.X","session":"001e050cb193"}
```
but still nothing at top 10 kibana side :/

**Comment by t3chn0m4g3** [comment]
Ahh, yes. Cowrie is using a different handler for URL provided files. If you want to see the downloaded files you need to change the keyword of the visualization from `filename.keyword` to `url.keyword`. You can also save it as a new visualization. However it is not possible to have them both in the same unless you choose to split tables.

**Comment by t3chn0m4g3** [comment]
I will provide new Kibana objects to reflect this.

**Comment by N0NameN0** [comment]
btw there is no "url.keyword" but "http.url.keyword"

i try with it but nogood result, still empty (enven with a new wget try )

```
{
  "aggs": {
    "3": {
      "terms": {
        "field": "http.url.keyword",
        "order": {
          "_count": "desc"
        },
        "size": 5
      },
      "aggs": {
        "4": {
          "terms": {
            "field": "outfile.keyword",
            "order": {
              "_count": "desc"
            },
            "size": 5
          }
        }
      }
    }
  },
  "size": 0,
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    },
    {
      "field": "end_time",
      "format": "date_time"
    },
    {
      "field": "flow.start",
      "format": "date_time"
    },
    {
      "field": "start_time",
      "format": "date_time"
    },
    {
      "field": "timestamp",
      "format": "date_time"
    },
    {
      "field": "tls.notafter",
      "format": "date_time"
    },
    {
      "field": "tls.notbefore",
      "format": "date_time"
    }
  ],
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        },
        {
          "query_string": {
            "query": "type:\"Cowrie\"",
            "analyze_wildcard": true,
            "time_zone": "Europe/Paris"
          }
        }
      ],
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "2020-06-26T12:06:40.720Z",
              "lte": "2020-07-03T12:06:40.720Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

**Comment by t3chn0m4g3** [comment]
`url.keyword` is there, but not indexed thus not available for visualization. `http_url.keyword` does not belong to Cowrie and will not work. As I said I will provide new objects.

**Comment by N0NameN0** [comment]
ok, and thank you for your patience ;) so i will wait for the new objects.

**Comment by t3chn0m4g3** [comment]
[update.ndjson.zip](https://github.com/dtag-dev-sec/tpotce/files/4887269/update.ndjson.zip)

Download the attached NDJSON archive and import it into Kibana as [described](https://github.com/dtag-dev-sec/tpotce/wiki/Import---Export-Kibana-Objects). Let me know if this works for you.

**Comment by N0NameN0** [comment]
i have now 2 viz in cowrie view ;) let see if it can display wgeted files ;)

**Comment by N0NameN0** [comment]
w00t !!
![image](https://user-images.githubusercontent.com/1048113/86854970-c41dee00-c0b9-11ea-9473-a0c8046f2764.png)

thx a lot ;)

**Comment by N0NameN0** [comment]
hi,
i think there is a little problem ;)

have a look a the file id here
![image](https://user-images.githubusercontent.com/1048113/87036682-7a352500-c1eb-11ea-9149-cb284766aa89.png)

then the id here ;)
![image](https://user-images.githubusercontent.com/1048113/87036738-8e792200-c1eb-11ea-9a85-4cb8c74a352b.png)

**Comment by t3chn0m4g3** [comment]
@N0NameN0 Yes, you made two screenshots that seem completely unrelated. Please be more specific and include timestamps :)

**Comment by N0NameN0** [comment]
how can they be "completely" unrelated since i can see reference to "/data/cowrie/downloads/" on both ?? ;)
i tought i could find all downloaded files from cowrie sessions in /data/cowrie/downloads/ and referenced under the same id in this kibana vizu.

do i miss something ?

**Comment by t3chn0m4g3** [comment]
All I see are two separate screenshots without timely relations. For all I know based on the screenshots, the files' timestamps do not reflect the timeframe of the dashboard search.

**Comment by N0NameN0** [comment]
lemme retry ;)

![image](https://user-images.githubusercontent.com/1048113/87052899-9fcd2900-c201-11ea-9be8-c382a4a2ad88.png)

![image](https://user-images.githubusercontent.com/1048113/87052913-a3f94680-c201-11ea-9565-7e00b5600bfb.png)

is this better ? ;)

**Comment by t3chn0m4g3** [comment]
Since T-Pot restarts every 24h it seems that the downloads were already archived in `/data/cowrie/downloads.tgz.x`.

**Comment by N0NameN0** [comment]
you seems to be right : 

![image](https://user-images.githubusercontent.com/1048113/87053589-6e089200-c202-11ea-8339-68cd5829ac4f.png)
