### ISSUE TITLE
Top 10 suricata CVE mal formated

### ISSUE THREAD

**Issue by N0NameN0** [dtag-dev-sec/tpotce#665]
instead of count them, i only get 1 and several in the CVE ID field : 

![image](https://user-images.githubusercontent.com/1048113/86368881-068c9880-bc7e-11ea-9344-b3d5a60d9068.png)

**Comment by t3chn0m4g3** [comment]
This points to Emerging Threat rules that are triggering reference multiple CVEs if triggered.

**Comment by N0NameN0** [comment]
i understand that, but have a look at my screenshot 

look at the first line, i have 3 times the SAME CVE id for a count at 1
and for the seconde line i have 2 times the SAME CVE ID for a count a 1

shouldn't have i something like this ? 
![image](https://user-images.githubusercontent.com/1048113/86468597-0224b600-bd38-11ea-82f3-67d69ed43144.png)

**Comment by t3chn0m4g3** [comment]
This means there was a communication that span accross multiple log events. Each log event, if CVE is detected and present, counts as 1.

**Comment by N0NameN0** [comment]
strange but ok. ;)
