### ISSUE TITLE
Error: failed to start containers: head

### ISSUE THREAD

**Issue by alphaDev23** [dtag-dev-sec/tpotce#666]
Using 19.03.  All other containers are running.

The container 'head' (What is this for?) will not start because the port is already allocated.  No other container appears to be using this port.  The following commands demonstrate the failure.

root@tpot-3:/etc/systemd/system]# docker ps -a |grep -i created
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                 PORTS                                                                                                                                                            NAMES
f0ff16261ab0        dtagdevsec/head:1903            "node_modules/http-s…"   5 hours ago         Created                                                                                                                                                                                 head

[root@tpot-3:/etc/systemd/system]# sudo docker start head
Error response from daemon: driver failed programming external connectivity on endpoint head (7ca1de1492d031181968af494b8a06a02805ce6b6a032ecbcc07b9e85ed35bef): Bind for 127.0.0.1:64302 failed: port is already allocated
Error: failed to start containers: head

[root@tpot-3:/etc/systemd/system]# ss -taln |grep 64302
LISTEN    0         128              127.0.0.1:64302            0.0.0.0:*       

[root@tpot-3:/etc/systemd/system]# sudo docker ps -a |grep 64302

**Comment by t3chn0m4g3** [comment]
1. [Elasticsearch Head](http://mobz.github.io/elasticsearch-head/)
2. What does `docker ps -a` tell you?
3. By the end of this month 19.03.x will no longer be supported.

**Comment by alphaDev23** [comment]
It appears that docker-proxy is using the same port that head wants to use:

 ss -talnp |grep 64302
LISTEN    0         128              127.0.0.1:64302            0.0.0.0:*        users:(("docker-proxy",pid=1530,fd=4))

What is docker-proxy used for and why is it mapped to the same port that another container is defined as using?  Also, it may not be necessary to include Elasticsearch Head as an image; while it is a nice to have, it is freely available as a Chrome add-in it adds to the complexity of honeypot and may increase the attack surface.  

As a note, in tpot.service I commented out all the commands that i) were on ExecStartPre removing old containers, images and volumes, and ii) on ExecStop the compose T-Pot down, remove containers and volumes.  While I understand conceptually why these may be desired, these commands lead to other issues such as the containers continuously restarting and not being in a stable state.  If a daily update is needed, I believe a docker pull and a docker compose-up will accomplish the same without have to remove networks, images, volumes, etc.  Regarding images, these appear to be rarely updated and regardless utilize copy-on-write so the drive space is deminimus relative to logs, for example. 

Regarding docker ps -a:
[root@tpot-3:/etc/systemd/system]# docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                  PORTS                                                                                                                                                            NAMES
42976e0447e6        dtagdevsec/snare:1903           "/bin/sh -c 'snare -…"   18 hours ago        Up 18 hours             0.0.0.0:80->80/tcp                                                                                                                                               snare
36394cb234b0        dtagdevsec/kibana:1903          "/usr/share/kibana/b…"   18 hours ago        Up 18 hours (healthy)   127.0.0.1:64296->5601/tcp                                                                                                                                        kibana
f0ff16261ab0        dtagdevsec/head:1903            "node_modules/http-s…"   18 hours ago        Created                                                                                                                                                                                  head
4ad2e089f47b        dtagdevsec/logstash:1903        "/bin/sh -c 'update.…"   18 hours ago        Up 18 hours (healthy)                                                                                                                                                                    logstash
fb1888d1adaf        dtagdevsec/tanner:1903          "tanner"                 18 hours ago        Up 18 hours                                                                                                                                                                              tanner
850398d01d51        dtagdevsec/tanner:1903          "tannerweb"              18 hours ago        Up 18 hours                                                                                                                                                                              tanner_web
50d9ac8c7323        dtagdevsec/tanner:1903          "tannerapi"              18 hours ago        Up 18 hours                                                                                                                                                                              tanner_api
446a5a81d6cf        dtagdevsec/p0f:1903             "/bin/sh -c 'exec /o…"   18 hours ago        Up 18 hours                                                                                                                                                                              p0f
fabac8e1b86e        dtagdevsec/elasticsearch:1903   "/usr/share/elastics…"   18 hours ago        Up 18 hours (healthy)   127.0.0.1:64298->9200/tcp                                                                                                                                        elasticsearch
fc2a9210f0d5        dtagdevsec/honeytrap:1903       "/opt/honeytrap/sbin…"   18 hours ago        Up 18 hours                                                                                                                                                                              honeytrap
49d44b3ce44f        dtagdevsec/conpot:1903          "/bin/sh -c 'exec /u…"   18 hours ago        Up 18 hours             0.0.0.0:623->623/tcp                                                                                                                                             conpot_ipmi
2da5bf4c0022        dtagdevsec/suricata:1903        "/bin/sh -c 'SURICAT…"   18 hours ago        Up 18 hours                                                                                                                                                                              suricata
493a0f83dd5c        dtagdevsec/conpot:1903          "/bin/sh -c 'exec /u…"   18 hours ago        Up 18 hours             0.0.0.0:10001->10001/tcp                                                                                                                                         conpot_guardian_ast
608f826a621a        dtagdevsec/cowrie:1903          "/usr/bin/twistd --n…"   18 hours ago        Up 18 hours             0.0.0.0:22-23->22-23/tcp                                                                                                                                         cowrie
b224f912286d        dtagdevsec/conpot:1903          "/bin/sh -c 'exec /u…"   18 hours ago        Up 18 hours             0.0.0.0:161->161/tcp, 0.0.0.0:2404->2404/tcp                                                                                                                     conpot_iec104
f46a5efec51f        dtagdevsec/ciscoasa:1903        "/bin/sh -c 'cp -R /…"   18 hours ago        Up 18 hours                                                                                                                                                                              ciscoasa
c93522e51e6e        dtagdevsec/dionaea:1903         "/opt/dionaea/bin/di…"   18 hours ago        Up 18 hours                                                                                                                                                                              dionaea
f9951c3885f0        dtagdevsec/ewsposter:1903       "/bin/sh -c 'sleep 1…"   18 hours ago        Up 13 seconds                                                                                                                                                                            ewsposter
ad815f8e329d        dtagdevsec/adbhoney:1903        "/bin/sh -c 'nohup /…"   18 hours ago        Up 18 hours             0.0.0.0:5555->5555/tcp                                                                                                                                           adbhoney
e4c834d1afe9        dtagdevsec/rdpy:1903            "/bin/sh -c 'exec /u…"   18 hours ago        Up 18 hours             0.0.0.0:3389->3389/tcp                                                                                                                                           rdpy
e6fb55578fd6        dtagdevsec/cyberchef:1903       "http-server -p 8000"    18 hours ago        Up 18 hours (healthy)   127.0.0.1:64299->8000/tcp                                                                                                                                        cyberchef
4710abe68b1c        dtagdevsec/heralding:1903       "/bin/sh -c 'exec he…"   18 hours ago        Up 18 hours             0.0.0.0:110->110/tcp, 0.0.0.0:143->143/tcp, 0.0.0.0:993->993/tcp, 0.0.0.0:995->995/tcp, 0.0.0.0:1080->1080/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5900->5900/tcp   heralding
bdaf020698c6        dtagdevsec/phpox:1903           "python3.6 sandbox.py"   18 hours ago        Up 18 hours                                                                                                                                                                              tanner_phpox
b03ba2ab39ec        dtagdevsec/nginx:1903           "/bin/sh -c 'exec ng…"   18 hours ago        Up 18 hours                                                                                                                                                                              nginx
b2797d48d1e1        dtagdevsec/medpot:1903          "./medpot"               18 hours ago        Up 18 hours             0.0.0.0:2575->2575/tcp                                                                                                                                           medpot
cfadaf7d596c        dtagdevsec/conpot:1903          "/bin/sh -c 'exec /u…"   18 hours ago        Up 18 hours             0.0.0.0:1025->1025/tcp, 0.0.0.0:50100->50100/tcp                                                                                                                 conpot_kamstrup_382
32b6c58fd4a0        dtagdevsec/mailoney:1903        "/usr/bin/python mai…"   18 hours ago        Up 18 hours             0.0.0.0:25->25/tcp                                                                                                                                               mailoney
33441a19f7f8        dtagdevsec/redis:1903           "docker-entrypoint.s…"   18 hours ago        Up 18 hours             6379/tcp                                                                                                                                                         tanner_redis
df35b3f087f6        dtagdevsec/spiderfoot:1903      "/usr/bin/python sf.…"   18 hours ago        Up 18 hours (healthy)   127.0.0.1:64303->8080/tcp                                                                                                                                        spiderfoot
ad0895891d52        dtagdevsec/elasticpot:1903      "/usr/bin/python3 ma…"   18 hours ago        Up 18 hours             0.0.0.0:9200->9200/tcp                                                                                                                                           elasticpot

**Comment by t3chn0m4g3** [comment]
Yeah this is pretty much caused by your changes in the tpot.service.

**Comment by alphaDev23** [comment]
What is docker-proxy used for and why is it mapped to the same port that another container is defined as using?

**Comment by t3chn0m4g3** [comment]
If you want it to work revert the changes. T-Pot is destroying the containers for security reasons since their state do not matter to us.

**Comment by alphaDev23** [comment]
It does not work when the changes are reverted as previously stated.  You did not answer my questions which are straight forward.  The mere fact that a container is using an existing port of another service raises security concerns of its own because it goes to the design.

Additionally, the simple act of removing images causes services to be down longer than needed because docker needs to re-pull all images.  docker-compose up has options to recreate volumes and containers without have to destroy all the containers first.
