### ISSUE TITLE
Management NIC VS Scanning NIC

### ISSUE THREAD

**Issue by myrsecurity** [dtag-dev-sec/tpotce#668]
Hi I'm new to this product and actively testing;

Ive deployed TPOT on an ESX server with only 1 NIC and 2 Vswitches, and monitors internal traffic. 

The Management Network Port Monitoring Group of the LAN Vswitch is set to Promiscuous and picks up traffic etc
![image](https://user-images.githubusercontent.com/53452334/86539295-92f7bf00-befb-11ea-9ce7-bc4352378a08.png)

![image](https://user-images.githubusercontent.com/53452334/86539306-b1f65100-befb-11ea-8f94-13ed55da43b6.png)
Basically with 1 interface Im able to Inspect and run Management services (ELK etc ) as the traffic in that virtual monitoring port group is mirrored. 
While this is ok for testing, still dont understand how to place the interface on a external segment of the network.

Im now trying to deploy TPOT on my physical network hosted in a QNAP equipped with ESX functionality very similar or Identical to a VMWare Dedicated machines

The physical switch port 2 is mirrored to port 24 where all traffic in/out the internet flows: : internet--router--port24switch 

Problem is I dont know how to add more interfaces to this VM so I can assign 1 interfaces for inspecting the traffic / listening  (port 2 ) and another interface for management ( ELK login etc ). 
\
Is there an option to position this in a Network Tap? how do guys deal with this basic stuff? 

Thanks

**Comment by t3chn0m4g3** [comment]
T-Pot's NSM capabilities are by default limited to the host it runs on and as such only one NIC is supported. However you can add more NICs but this also means you have to adjust at least the interfaces Suricata is listening on. You find the `Dockerfile` and `docker-comppose` file [here](https://github.com/dtag-dev-sec/tpotce/tree/master/docker/suricata).
