### ISSUE TITLE
How T-POT can achieve a multi-node (machine) distributed deployment?

### ISSUE THREAD

**Issue by Raul1718** [dtag-dev-sec/tpotce#670]
**Is your feature request related to a problem? Please describe.**
My company recently developed this requirement internally: a multi-node (machine) distributed deployment.But deploy T-POT on every machine is unrealistic.It's resource-intensive, and it's a bit cumbersome to deploy(For example, all the machines have to be installed as debian,But my company is all basically centos).
Then we came up with an idea: Using port traffic forwarding,Forwarding port traffic from the A\B\C machine to the T-POT machine.

**Describe alternatives you've considered**
But the scheme for traffic forwarding，I had tried Tried a lot of ways.such as iptables\nginx\haproxy\rinetd，But none of them can get the original IP(Attacker Ip). Other methods involve changing the route.As far as I know, the different docker routes for T-POT are complex.So for now, I'm stuck here.

That's why I'm here to consult with masters:
1. What are the options for distributed deployment of T-POT?
2. What's the alternative solution for port forwarding?

Requesting an answer. Please. 
Thank you very very... much. ^^

**Comment by t3chn0m4g3** [comment]
Duplicate, closing in favor of #250
