### ISSUE TITLE
No such file or directory: '/opt/tpot/etc/tpot.yml

### ISSUE THREAD

**Issue by djeronimo** [dtag-dev-sec/tpotce#671]
Hi there, fresh install of t-pot 20.06 off the prebuilt iso.  I get this error when the tpot services starts No such file or directory: '/opt/tpot/etc/tpot.yml.  I can see the tpot.yml file is a link to /opt/tpot/etc/compose/.yml

**Comment by t3chn0m4g3** [comment]
Please attach the required support info, this usually means that the installation was interrupted.

**Comment by Pablo-Araya** [comment]
sudo systemctl stop tpot

sudo /opt/tpot/bin/tped.sh 

> select STANDARD and "yes", after that start again

sudo systemctl start tpot

> Use "dps.sh" for monitoring if takes like 3 to 5 min to be UP with all services
