### ISSUE TITLE
Kibana not loading after removing all honeypots

### ISSUE THREAD

**Issue by jackthelad999** [dtag-dev-sec/tpotce#672]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br> Kibana not loading on port 64297 hosted locally on a VM.
<br> Met system spec requirements. 8GB RAM
<br> Removed all honeypots to test but kibana still doesn't load. Management interface on port 64294 does work.

<a name="info"></a>

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
## ⚠️ Basic support information (commands are expected to run as `root`)
`Distributor ID: Debian`
`Description:    Debian GNU/Linux 10 (buster)`
`Release:        10`
`Codename:       buster`
`Linux willingpeak 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`

- What T-Pot version are you currently using?
20.06
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
VM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
1 day
- Did you install upgrades, packages or use the update script?
Ran upgrade script
- Did you modify any scripts or configs? If yes, please attach the changes.
Removed honeypots from tpot.yml
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/66276031/87088284-6c53c400-c22c-11ea-9feb-176022141df4.png)
![image](https://user-images.githubusercontent.com/66276031/87088322-7bd30d00-c22c-11ea-9385-ec0dec13b1f0.png)

- How much free disk space is available (`df -h`)?
`Filesystem      Size  Used Avail Use% Mounted on`
`udev            4.1G     0  4.1G   0% /dev`
`tmpfs           829M  9.3M  819M   2% /run`
`/dev/sda2        71G  8.6G   59G  13% /`
`tmpfs           4.1G     0  4.1G   0% /dev/shm`
`tmpfs           5.0M     0  5.0M   0% /run/lock`
`tmpfs           4.1G     0  4.1G   0% /sys/fs/cgroup`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/470e7568771f3ce9e2f092aed7be6b03012df3222302f0a15407bd6f83d0aa8e/merged`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/8fac4188e5bcb92285be61ca019c3fd261128d395d76a8efdb701f1f5140c3f4/merged`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/9763cbbdbdf62a0c6fd558201e0e137b26cd57a243ee511c68f40a98ad8024d0/merged`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/75e666eb394dcd4534b207af7b290f38442148d2d5f39c14749c1d45818103f9/merged`
`shm              64M     0   64M   0% /var/lib/docker/containers/1d7af01856a5cb60407f9444709021a0962bf73e01fcbe66cb84f7393bb6e66d/mounts/shm`
`shm              64M     0   64M   0% /var/lib/docker/containers/32111666c1bcd6b2d85dd7a5f6f63dda7dc09b6b96869548f8d978423dadd29f/mounts/shm`
`shm              64M     0   64M   0% /var/lib/docker/containers/bf3df97b3313b5d6f6abfd979cfff0400d3748afd4c8edba3b94c22e39da85be/mounts/shm`
`shm              64M     0   64M   0% /var/lib/docker/containers/94335d1d12029be88d6a86d16e48841db925cdd716f6c0f0e9266853e7cd8dde/mounts/shm`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/28996865be4fb1498bc87b835e060dbfa76548b06e4bd65bbd7ef1480ca54982/merged`
`shm              64M     0   64M   0% /var/lib/docker/containers/f960e231749194934c08ed5c6f56fffd5d4b29645afd4121353a7d38a6ce6804/mounts/shm`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/16e936af57df57f4d9566ed5b227c5c000644d96236b6f8b20399cd627dcbdc5/merged`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/0c558caede59495d63e5498bb95b89ad29ad6e06cd0b3ac17903c5b04664d9f1/merged`
`overlay          71G  8.6G   59G  13% /var/lib/docker/overlay2/d1eecc5641162add3534f5f07fc099899b43e43963f3383114e1a12d1c094ef4/merged`
`shm              64M     0   64M   0% /var/lib/docker/containers/d38830bab083b9e2dd84569ad5627389ad7330ff84cefbcbaf9f19233b289393/mounts/shm`
`shm              64M     0   64M   0% /var/lib/docker/containers/7e71e104148406f902999e8c1e97e3c7045d53fa4ebbe2fb54d4c28225ca59b5/mounts/shm`
`shm              64M     0   64M   0% /var/lib/docker/containers/53b884bd7e22bf811ef6d5c72ec2df36d1c561b918c22be782f43e27a9e10984/mounts/shm`
`tmpfs           829M     0  829M   0% /run/user/1000`

- What is the current container status (`dps.sh`)?
`NAME                  STATUS                       PORTS`
`elasticsearch       Up 33 minutes (healthy)   127.0.0.1:64298->9200/tcp`
`head                Up 32 minutes (healthy)   127.0.0.1:64302->9100/tcp`
`kibana              Up 32 minutes (healthy)   127.0.0.1:64296->5601/tcp`
`logstash            Up 32 minutes (healthy)  `
`nginx               Up 33 minutes`
`tanner_api          Up 33 minutes`
`tanner_phpox        Up 33 minutes`
`tanner_redis        Up 33 minutes      6379/tcp`

- What is the status of the T-Pot service (`systemctl status tpot`)?
`Loaded: loaded (/etc/systemd/system/tpot.service; enabled; vendor preset: enabled)`
`Active: active (running) since Thu 2020-07-09 20:05:15 UTC; 48min ago`
`  Process: 1768 ExecStartPre=/opt/tpot/bin/updateip.sh (code=exited, status=0/SUCCESS)`
`  Process: 1814 ExecStartPre=/bin/bash -c /opt/tpot/bin/clean.sh on (code=exited, status=0/SUCCESS)`
`  Process: 1878 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml down -v (code=exited, status=0/SUCCESS)`
`  Process: 2383 ExecStartPre=/usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml rm -v (code=exited, status=0/SUCCESS)`
`  Process: 2386 ExecStartPre=/bin/bash -c docker network rm $(docker network ls -q) (code=exited, status=1/FAILURE)`
`  Process: 2401 ExecStartPre=/bin/bash -c docker volume rm $(docker volume ls -q) (code=exited, status=1/FAILURE)`
`  Process: 2417 ExecStartPre=/bin/bash -c docker rm -v $(docker ps -aq) (code=exited, status=1/FAILURE)`
`  Process: 2431 ExecStartPre=/bin/bash -c docker rmi $(docker images | grep "<none>" | awk '{print $3}') (code=exited, status=1/FAILURE)`
`  Process: 2450 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) rx off tx off (code=exited, status=0/SUCCESS)`
`  Process: 2456 ExecStartPre=/bin/bash -c /sbin/ethtool -K $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) gso off gro off (code=exited, status=0/SUCCESS)`
`  Process: 2462 ExecStartPre=/bin/bash -c /sbin/ip link set $(/sbin/ip address | grep "^2: " | awk '{ print $2 }' | tr -d [:punct:]) promisc on (code=exited, status=0/SUCCESS)`
`  Process: 2468 ExecStartPre=/opt/tpot/bin/rules.sh /opt/tpot/etc/tpot.yml set (code=exited, status=0/SUCCESS)`
` Main PID: 2474 (docker-compose)`
`    Tasks: 10 (limit: 4915)`
`   Memory: 97.4M`
`   CGroup: /system.slice/tpot.service`
`           └─2474 /usr/bin/python3 /usr/bin/docker-compose -f /opt/tpot/etc/tpot.yml up --no-color`
`Jul 09 20:52:05 willingpeak docker-compose[2474]: head             | [2020-07-09T20:52:05.219Z]  "GET /" "curl/7.69.1"`
`Jul 09 20:52:06 willingpeak docker-compose[2474]: kibana           | {"type":"response","@timestamp":"2020-07-09T20:52:06Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0.0.1:5601","user-agent":"curl/7.67.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":9,"contentLength":9},"message":"GET / 302 9ms - 9.0B"}`
`Jul 09 20:52:35 willingpeak docker-compose[2474]: head             | [2020-07-09T20:52:35.330Z]  "GET /" "curl/7.69.1"`
`Jul 09 20:52:36 willingpeak docker-compose[2474]: kibana           | {"type":"response","@timestamp":"2020-07-09T20:52:36Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0.0.1:5601","user-agent":"curl/7.67.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":14,"contentLength":9},"message":"GET / 302 14ms - 9.0B"}`
`Jul 09 20:53:05 willingpeak docker-compose[2474]: head             | [2020-07-09T20:53:05.454Z]  "GET /" "curl/7.69.1"`
`Jul 09 20:53:06 willingpeak docker-compose[2474]: kibana           | {"type":"response","@timestamp":"2020-07-09T20:53:06Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0.0.1:5601","user-agent":"curl/7.67.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":14,"contentLength":9},"message":"GET / 302 14ms - 9.0B"}`
`Jul 09 20:53:35 willingpeak docker-compose[2474]: head             | [2020-07-09T20:53:35.556Z]  "GET /" "curl/7.69.1"`
`Jul 09 20:53:37 willingpeak docker-compose[2474]: kibana           | {"type":"response","@timestamp":"2020-07-09T20:53:37Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0.0.1:5601","user-agent":"curl/7.67.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":17,"contentLength":9},"message":"GET / 302 17ms - 9.0B"}`
`Jul 09 20:54:05 willingpeak docker-compose[2474]: head             | [2020-07-09T20:54:05.666Z]  "GET /" "curl/7.69.1"`
`Jul 09 20:54:07 willingpeak docker-compose[2474]: kibana           | {"type":"response","@timestamp":"2020-07-09T20:54:07Z","tags":[],"pid":1,"method":"get","statusCode":302,"req":{"url":"/","method":"get","headers":{"host":"127.0.0.1:5601","user-agent":"curl/7.67.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":302,"responseTime":50,"contentLength":9},"message":"GET / 302 50ms - 9.0B"}`

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
`tcp        0      0 0.0.0.0:61209           0.0.0.0:*               LISTEN      0          15332      524/python3                                      `
`tcp        0      0 127.0.0.1:36923         0.0.0.0:*               LISTEN      1000       32964      3855/cockpit-bridge                              `
`tcp        0      0 0.0.0.0:64295           0.0.0.0:*               LISTEN      0          15502      535/sshd                                         `
`tcp6       0      0 :::64294                :::*                    LISTEN      0          12531      1/init                                           `
`tcp6       0      0 :::64295                :::*                    LISTEN      0          15513      535/sshd                                         `
`udp        0      0 192.168.1.69:123        0.0.0.0:*                           0          15395      534/ntpd                                         `
`udp        0      0 127.0.0.1:123           0.0.0.0:*                           0          15393      534/ntpd                                         `
`udp        0      0 0.0.0.0:123             0.0.0.0:*                           0          15389      534/ntpd                                         `
`udp6       0      0 :::123                  :::*                                0          15386      534/ntpd  `
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
containers are all running
N/A
I also checked TLS version. The management interface is available on port 64294.
Using virtualbox 5.2.42 and Debian 9 as a host.

**Comment by t3chn0m4g3** [comment]
Please compare the changes you made to the shipped compose files.

**Comment by jackthelad999** [comment]
So do you mean diff them ? Where do I find the original files ?

**Comment by t3chn0m4g3** [comment]
`/opt/tpot/etc/compose`

**Comment by jackthelad999** [comment]
That file wasn't modified by me. I changed /opt/tpot/etc/tpot.conf.

**Comment by jackthelad999** [comment]
When I curl it form command line I receive 401:
` curl -k https://X.X.X.69:64297`
`401 Authorization Required`

**Comment by t3chn0m4g3** [comment]
Looks it is working as it is supposed to.

**Comment by jackthelad999** [comment]
Sorry, just to be clear, I was testing if the interface was available via curl. It doesn't load in the browser !

**Comment by jackthelad999** [comment]
Browser version is firefox 68.10.0esr

**Comment by jackthelad999** [comment]
Installed over NAT then changed to bridged as there was no option to config an IP in the startup wizard. Guessing this may be the issue. Starting from scratch, again..
