### ISSUE TITLE
T-Pot installation on RedHat using Docker

### ISSUE THREAD

**Issue by jjoseph8008** [dtag-dev-sec/tpotce#675]
Hi,

I wanted to double check and confirm whether t-pot can be installed on red hat as a docker container.
From documentation it sounds like it will not run on red hat as docker containers and a debian install is required with docker.
Please let me know.

Thanks
Joseph

**Comment by t3chn0m4g3** [comment]
Sorry, but RedHat is not supported. It was only requested a few times which makes me think not supporting it is not so much of a dealbreaker :bowtie:
