### ISSUE TITLE
How can I let T-POT test Web attack like SQL inject or XSS? 

### ISSUE THREAD

**Issue by zaijianbch** [dtag-dev-sec/tpotce#676]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
Linux scottishbrochure 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
- What T-Pot version are you currently using?
20.06
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
KVM
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
No
- How long has your installation been running?
3 days
- Did you install upgrades, packages or use the update script?
No
- Did you modify any scripts or configs? If yes, please attach the changes.
/opt/tpot/docker/suricata/dist/suricata/dist/suricata.yaml 
#- emerging-trojan.rules  > - emerging-trojan.rules

/opt/tpot/bin/rules.sh
![image](https://user-images.githubusercontent.com/23326846/88275813-94552400-cd10-11ea-84ad-8c6ef88e4c81.png)

- Please provide a screenshot of `glances` and `htop`.
glances
![image](https://user-images.githubusercontent.com/23326846/88275910-ba7ac400-cd10-11ea-9a53-593780d1b47f.png)
htop
![image](https://user-images.githubusercontent.com/23326846/88275962-d3837500-cd10-11ea-8d5f-b3d3a4372308.png)

- How much free disk space is available (`df -h`)?
130G
- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/23326846/88276060-fc0b6f00-cd10-11ea-8dfd-80b20780a1f7.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/23326846/88276109-18a7a700-cd11-11ea-9af1-a1a2e5b10283.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
It;s OK
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

**Comment by zaijianbch** [comment]
I find the way to show web attack. Use alert.metadata.tag.keyword..............

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback. Seems resolved.
