### ISSUE TITLE
Failed to run preseeded command

### ISSUE THREAD

**Issue by punto2018** [dtag-dev-sec/tpotce#678]
I'm trying to install TPOT on both VM and phisical machine without success.
During "Finish the installation" step I always get the following:

_Execution of preseeded command "in-target apt-get -y install grub-pc; in-target grub-install --force $(debconf-get partman-auto/disk); update-dev; .......  failed with exit code 1._

I've tried both legacy and uefi mode. 
Seem some sort of issue with grub. 
The strange thing is that I've installed it in VirtualBox, in another machine, some days ago without any problem. Maybe a bad update of grub?

**Comment by t3chn0m4g3** [comment]
I have encountered this only with physical machines, when there were issues with the hard disk containing a different linux distro. Never encountered this in VM. Is it a fresh machine?

**Comment by punto2018** [comment]
Fresh machine, but the hard drive was not formatted... do you think it is needed?
And why on the "fresh" virtual machines?

**Comment by punto2018** [comment]
I've tried with a formatted ssd, updating bios, both legacy and uefi, 2 different machines. Always the same error.
I think it is due to some change on the modules that are downloaded during the installation.

The issue is critical, the distro can't be installed. If nobody dig into it the project is dead.

Hope for an help of the community
Thanks

**Comment by t3chn0m4g3** [comment]
You can always install on a freshly installed Debian 10. There is no need for using the ISO installer.

**Comment by punto2018** [comment]
FLASH! I think that my firewall is blocking some network interaction... maybe maybe...

**Comment by t3chn0m4g3** [comment]
For me the install works perfectly fine in VMs and on physical machines. Not all cases of hardware can be supported, please check out the README.MD for instructions on how to perform a post install of T-Pot.

**Comment by punto2018** [comment]
Ok, here the solution: if your network is not working there will not be any advice, just random errors, so be careful.
After this issue I hitted other 2 problems:

sdhci: it is not a tpot issue, but a debian issue. anyway I cant find a valid solution.

[  348.925502] mmc0: Timeout waiting for hardware cmd interrupt.
[  348.925511] mmc0: sdhci: ============ SDHCI REGISTER DUMP ===========
[  348.925516] mmc0: sdhci: Sys addr:  0x00000000 | Version:  0x0000a402
[  348.925521] mmc0: sdhci: Blk size:  0x00000000 | Blk cnt:  0x00000000
[  348.925525] mmc0: sdhci: Argument:  0x00000000 | Trn mode: 0x00000000
[  348.925530] mmc0: sdhci: Present:   0x01ff0001 | Host ctl: 0x00000000
[  348.925534] mmc0: sdhci: Power:     0x0000000f | Blk gap:  0x00000000
[  348.925538] mmc0: sdhci: Wake-up:   0x00000000 | Clock:    0x0000fa07
[  348.925543] mmc0: sdhci: Timeout:   0x00000000 | Int stat: 0x00018000
[  348.925547] mmc0: sdhci: Int enab:  0x00ff0003 | Sig enab: 0x00ff0003
[  348.925551] mmc0: sdhci: ACmd stat: 0x00000000 | Slot int: 0x00000001
[  348.925556] mmc0: sdhci: Caps:      0x67ea64b2 | Caps_1:   0x00000000
[  348.925560] mmc0: sdhci: Cmd:       0x00000502 | Max curr: 0x00000001
[  348.925564] mmc0: sdhci: Resp[0]:   0x00000000 | Resp[1]:  0x00000000
[  348.925568] mmc0: sdhci: Resp[2]:   0x00000000 | Resp[3]:  0x00000000
[  348.925572] mmc0: sdhci: Host ctl2: 0x00000000
[  348.925576] mmc0: sdhci: ADMA Err:  0x00000000 | ADMA Ptr: 0x00000000
[  348.925578] mmc0: sdhci: ============================================

Cant install GRUB.
After tried every combination, GRUB and LILO there isn't a way to intall a bootloaded on my system. I've solved with a grub usb pen drive that start the ssd.

**Comment by t3chn0m4g3** [comment]
Thanks for the feedback, seems to be resolved WRT T-Pot.
