### ISSUE TITLE
Advice for blocking IP addresses?

### ISSUE THREAD

**Issue by xme** [dtag-dev-sec/tpotce#680]
Hello,
It's not really an issue but I'm more looking for an advice and I did not find relevant information on the documentation.
What could be the best way to completely block some IP addresses to reach a tpot instance?
It is recommended to use the OS firewall (ufw, iptables, etc) or at tpot level?
Any advice?

**Comment by t3chn0m4g3** [comment]
The best way is to run T-Pot behind a router / switch / firewall / etc. where you can block IPs. If that is not possible the second best way is to modify [rules.sh](https://github.com/dtag-dev-sec/tpotce/blob/master/bin/rules.sh) to persist your rule settings.

**Comment by xme** [comment]
Tx!

**Comment by t3chn0m4g3** [comment]
Welcome :bowtie:

**Comment by Olli1336** [comment]
A little bit late but maybe helpful for the future: I handled it just with IP tables. 

Command: iptables -A INPUT -s IP -j DROP
