### ISSUE TITLE
Email notification when attack discovered

### ISSUE THREAD

**Issue by greyRen66** [dtag-dev-sec/tpotce#683]
Hello guys,

first I would like to thank you for your work developing TPOT! It is really useful to recognize possible attacks!
Now I wanted to ask, if there is a "quick" way to get a notification via Email when an attack was discovered.
We use TPOT internally, so it is seldom attacked, but we would like to be notified when it happens :).
Thanks in advance.

Kind regards
Ren

**Comment by t3chn0m4g3** [comment]
Thank you :bowtie:
Out of the box there is no option to do that. However I created an example on how to do that with the [alerta cli](https://github.com/dtag-dev-sec/tpotce/issues/204). Since it was not of any interest I did not put it into production though and you have to rebuild the logstash image to include Alerta CLI und setup [Alerta](https://alerta.io/) as well.

**Comment by t3chn0m4g3** [comment]
And there is the [eMail output](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-email.html) plugin as well. You can use the same logic as in #204 and use the eMail output, however this also requires you the rebuild the logstash docker image to include the email plugin.

**Comment by greyRen66** [comment]
Dear t3chn0m4g3 ,

thank you for your fast answer!
I am new to elastic search and docker, so I think I will have to do some research first on to rebuild the logstash image to apply the "alerta cli" config you propose. :)

When I have applied it, I will let you know how it works.

Have a nice day!

Kind regards,
Ren

**Comment by furiiibond** [comment]
> Dear t3chn0m4g3 ,
> 
> thank you for your fast answer! I am new to elastic search and docker, so I think I will have to do some research first on how to rebuild the logstash image to apply the "alerta cli" config you propose. :)
> 
> When I have applied it, I will let you know how it works.
> 
> Have a nice day!
> 
> Kind regards, Ren

Hello, did you manage to implement the email alerts in T-pot that would also greatly interest me ?
