### ISSUE TITLE
Issue with Azure post-install

### ISSUE THREAD

**Issue by hoddy898** [dtag-dev-sec/tpotce#684]
Hi,

I have been attempting to set up an instance of TPot for use for my university assignment (so please excuse the lack of Linux/Docker knowledge, I'm still quite new). I had it working in Azure, running the Debian 10 (with Backports kernel) image type for TPot version 19.03 on a B2ms instance. I simply followed the post-install user guide and it worked flawlessly. 

I have since tried with 20.06 and am running into an issue when installing. The installation goes seemingly as normal, apart from installing/configuring the docker.io package. Below are the items that seem to fail/look strange:

[Install Errors.txt](https://github.com/dtag-dev-sec/tpotce/files/5079071/Install.Errors.txt)

The install continues but after the reboot the instance is completely unreachable, meaning I cannot obtain any logs to look further into what went wrong with docker.io after the install is complete.

I then stopped the install midway through on a fresh instance and looked into journalctl to see if it had any more info, here is what I found:

[journalctl output.txt](https://github.com/dtag-dev-sec/tpotce/files/5079156/journalctl.output.txt)

I have also tried installing docker (and verifying that it is running) before installing TPot, and I was a root user both times - still the same output.

Thanks in advance and please let me know if you need any more information

**Comment by mfld-pub** [comment]
Have you reviewed the Azure boot diagnostics and the Azure serial console for the instance ? You can enable those when you create an instance and they give you some troubleshooting opportunities where networking is borked. 

![ticket684](https://user-images.githubusercontent.com/66289900/90324995-8a89ae00-dfa8-11ea-81f6-e9161414b780.JPG)

My uneducated hunch is it may be some issue with your network security group or the way Azure does NAT. I suggest you get access to the instance and take a look at the networking situation. How much RAM did you give the instance ?

**Comment by hoddy898** [comment]
Thanks for the reply.

I've checked boot diagnostics and serial console after it reboots. I can't see any tcp_out Blocked events and the instance appears to get the correct route table. 

Only error I can see is the following:
`2020/08/16 10:02:05.565732 INFO Daemon Error getting cloud-init enabled status from service: Command '['service', 'cloud-init', 'status']' returned non-zero exit status 4.`
`2020/08/16 10:02:05.567952 INFO Daemon cloud-init is enabled: False`
`2020/08/16 10:02:05.568666 INFO Daemon Using waagent for provisioning`
`2020/08/16 10:02:05.587128 INFO Daemon Error getting cloud-init enabled status from systemctl: Command '['systemctl', 'is-enabled', 'cloud-init-local.service']' returned non-zero exit status 1.`

The instance goes into Grub after the reboot, I'm guessing that thats why I've got no SSH access. As to why it goes into Grub, I'm not quite sure. Would it be useful for me to show you the serial console whilst it's failing to set up docker.io and pull the images?

The NSG allows all traffic out and everything in to 22 and my IP to the new SSH port. I also gave the VM 8GB of RAM, which I believe is recommended. Grub can't find a filesystem, the OS Disk is 30GB but I've also tried with up to 128GB with no change

**Comment by mfld-pub** [comment]
Sorry for the confusion, the TCP-Outs from my console screenshot have nothing to do with T-Pot. This was just the first instance I had on my screen that has the serial console provisioned. The point was only the two areas I highlighted in red. I should have cropped that tighter.

With your instance: I'd probably start over. Provision debian 10 minimal and follow this https://github.com/dtag-dev-sec/tpotce#post-install-user

**Comment by hoddy898** [comment]
Just provisioned a new instance using the Debian 10 image (**without** the backports kernel) as suggested and it worked the first time, thank you so much! No idea why it didn't work on the other Debian image
