### ISSUE TITLE
Question aobut honeypot possibilities.

### ISSUE THREAD

**Issue by 0x7fff9** [dtag-dev-sec/tpotce#71]
I am getting a lot of noise on my home firewall regarding UDP 500 attacks.
I've been searching and it's not only from the shadow server [Shadow](https://isakmpscan.shadowserver.org/) but from many IP addresses trying different combos of user/PW, DH group and proposal type.

This leads me to [gitVPN](https://github.com/jpillora/docker-ipsec-vpn-server)
Could this or something similar get integrated as a honeypot and capture what's going on in the wild?

Thanks!!!
cheers.

**Comment by t3chn0m4g3** [comment]
If you want to capture specific traffic you need to implement a corresponding honeypot or sinkhole.
