### ISSUE TITLE
Use other conpot templates 

### ISSUE THREAD

**Issue by armadupi** [dtag-dev-sec/tpotce#72]
On its [repo](https://github.com/mushorg/conpot/tree/master/conpot/templates), conpot has several other templates than kamstrup to decide between on launch.
Is it possible to start/restart the conpot container with another template? Or can I somehow pass it to the Dockerfile? 
Maybe it needs a complete new config since the ports are different. If a new container is needed, how to create one with a different template (I might manage that)? How to choose between conpot with kamstrup template or another? I guess there is no need to change anything to send the data to Kibana.

I noticed the other templates aren't in the [repo](https://github.com/dtag-dev-sec/conpot) of the dockerized container of conpot but I thought the question would be more appropriate on this repo.

I know very little about the inner workings of Docker so please excuse me if it is a trivial question. It might be a nice future improvement and maybe other honeypots have different templates available to use. I am running the latest version of T-Pot.

**Comment by t3chn0m4g3** [comment]
For T-Pot we chose a setup that allows for running all honeypots in parallel. If you want to mount your own config please read up on [Docker volumes](https://docs.docker.com/engine/tutorials/dockervolumes/)

**Comment by t3chn0m4g3** [comment]
Have a look at #79, should cover your question as well.
