### ISSUE TITLE
UI-For-Docker can't login

### ISSUE THREAD

**Issue by armadupi** [dtag-dev-sec/tpotce#73]
When I open the tab UI-For-Docker on the web interface, I arrive on the page where I have to specify the new admin password. However, when I enter one, nothing happens. Nothing happens because on the loading of the page, there are two 404 Not Found errors on:
1. GET https://IP:64297/api/users/admin/check 
2. GET https://IP:64297/api/settings

Sometimes, I manage to get to this page where 2 fatal errors are shown (couldn't reproduce often)
![screenshot from 2017-01-06 15-17-54](https://cloud.githubusercontent.com/assets/24959575/21720516/f07aa988-d423-11e6-946f-6ec312ea604d.png)
I don't know if there are linked to the 404 errors and are very generic.

Any idea what the problem is?
Many thanks.

- What T-Pot version are you currently using? 16.10 with everything installed
- Are you running on a Intel NUC or a VM? On a desktop
- How long has your installation been running? Recently restarted
- Did you install any upgrades or packages? No
- Did you modify any scripts? No
- Have you turned persistence on/off? No, still off
- How much RAM available (login via ssh and run `htop`)? >3GB
- How much stress are the CPUs under (login via ssh and run `htop`)? Load average <1
- How much swap space is being used (login via ssh and run `htop`)? 0
- How much free disk space is available (login via ssh and run `sudo df -h`)? 
- What is the current container status (login via ssh and run `sudo start.sh`)? status.sh? All running

**Comment by t3chn0m4g3** [comment]
Thanks, will look into it - [Portainer](https://github.com/portainer/portainer) added a new feature which breaks revers proxy config 😢

**Comment by t3chn0m4g3** [comment]
@armadupi this is fixed now. Please login and run
```
sudo su -
update-images.sh
```
T-Pot will reboot and everything should work fine.

I tested with Chrome.
