### ISSUE TITLE
Add -f flag for rm commands in install.sh

### ISSUE THREAD

**Issue by ctindel** [dtag-dev-sec/tpotce#74]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Any chance you can change these to rm -f so that when you re-run the script because of a failure, those commands don't make the script fail because the files were already removed?

rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
rm /usr/share/nginx/html/index.html

Also for this command you should check if the /usr/bin/node file exists before putting the symlink in, since it does exist in the default node install on ubuntu.

ln -s /usr/bin/nodejs /usr/bin/node

**Comment by t3chn0m4g3** [comment]
Even with your suggested options the scripts is not built for second run. We are currently looking into options to minimize host dependencies allowing for rolling releases. So stay tuned 😄 
However, pull requests are always welcome.
