### ISSUE TITLE
New fresh installed T-Pot 16.03, no 2fa_enable.sh found

### ISSUE THREAD

**Issue by franboj** [dtag-dev-sec/tpotce#75]
It's been a couple of clean instalations now on a VMWare VM, the installation goes flawesly but, once I log in with my tsec user, I can't find the 2fa_enable file, so I'm stuck here. I tried to google a bit but found nothing about this problem so I'd love some help to continue. Really interested in using T-Pot to do a small study and present a project with it.

Hope to hear something soon!

**Comment by t3chn0m4g3** [comment]
@franboj Please use [T-Pot 16.10](https://github.com/dtag-dev-sec/tpotce/releases)

**Comment by franboj** [comment]
@t3chn0m4g3 Just did, still no 2fa file. Installed the standard version. Can't log-in to ip:64297, no services working, nothing. Installation gave no problems at all.

**Comment by t3chn0m4g3** [comment]
@franboj Please check [First-Run](https://github.com/dtag-dev-sec/tpotce#first-run). There is no 2FA.
