### ISSUE TITLE
[ASK]Malware detection using T-POT

### ISSUE THREAD

**Issue by ilfanarif** [dtag-dev-sec/tpotce#78]
Hello team..<br/>
I'm currently learn about malware and i want to analyze a malware using t-pot installed in my virtual machine. Could someone give me any suggestion what kind of malware should i use and how to run it so the malware could be detected on my t-pot?

**Comment by t3chn0m4g3** [comment]
@ilfanarif Please check the sites and forums of the initial honeypot creators. You can find the links [here](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md#credits).

**Comment by ilfanarif** [comment]
@t3chn0m4ge Ok sir. But can you help me to add VirusTotal sensor to T-Pot?

**Comment by ilfanarif** [comment]
oke mr. can i connect this t-pot to virustotal? help me

**Comment by t3chn0m4g3** [comment]
@ilfanarif T-Pot does not offer support for VirusTotal, only some of the used honeypots do.

**Comment by ilfanarif** [comment]
Can I add virustotal api to dionaea?
And how to add other honeypot sensor to t-pot?

**Comment by ilfanarif** [comment]
sir. can I contact you for it?
Maybe chat with facebook, twitter, bbm or line..
I need teacher for it

**Comment by t3chn0m4g3** [comment]
@ilfanarif I am really sorry, but this is outside the scope of T-Pot. Please review the documentation on [docker volumes](https://docs.docker.com/engine/tutorials/dockervolumes/). If you want to map your very own [Dionaea config](https://github.com/dtag-dev-sec/dionaea/tree/master/dist/etc) into the container you have to modify the start script `/etc/systemd/system/dionaea.service` and mount them into the container.
