### ISSUE TITLE
hpfeed

### ISSUE THREAD

**Issue by sphereict** [dtag-dev-sec/tpotce#81]
Good day

I am using the Tpot16.10 versions and notice that you support hpfeeds.

I have previously used the MHN and when deploying honeypots at other locations I could get the logs automatically feeding to the main system. 

I would like to use TPOT in the same manner as I prefer your interface over everyone else. 
Could you assist with the following:
[HPFEED]
hpfeed = false
host = 0.0.0.0 ( This must be my server ip ? )
port = 0 ( lets say 10000 )
channels = 0 ( Not sure need your help )
ident = 0 ( How to setup Ident ) in main TPOT.
secret= 0 ( How to create secret in main TPOT )

Your help will be greatly appreciated. 
I would liek to deploy this to our branches and get the feeds directly coming into the main TPOT system.

Sincerely.
Gerhard

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?
- Are you running on a Intel NUC or a VM?
- How long has your installation been running?
- Did you install any upgrades or packages?
- Did you modify any scripts?
- Have you turned persistence on/off?
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

**Comment by schmalle** [comment]
Hi Gerhard,
I am not sure, if i understand the question right, tpot only supports sending out alarms in hpfeeds format, but is not a hpfeeds server. 
Havent used mhn, so i dont know, if this can act as a reciever,
Best regards
Markus

**Comment by sphereict** [comment]
Hi Markus
If using the Hpfeeds broker will that not assist with receiving hpfeeds to Tpot ? Or am I understanding this incorrectly ?

**Comment by t3chn0m4g3** [comment]
@sphereict As @schmalle pointed out, T-Pot is not equipped to be a network receiver for other T-Pots or honeypots. Please also see issue #79 which covers basically the same topic.
