### ISSUE TITLE
Custom suricata.yaml persistence

### ISSUE THREAD

**Issue by SunstriderX** [dtag-dev-sec/tpotce#83]
Hello again :)

I'm fine-tuning the config of the suricata.yaml file to fit it my needs (leaving the base config as it is to avoid messing up with the tailored solution for the T-Pot) and when I copy it inside the Suricata container and restart it, it works as I expect it to. However, when I reboot the whole host, the config is lost, and the default one is loaded.
I know that for logstash if I copy a `logstash.conf` file into `/data/elk/logstash/conf/` it will be loaded into the container once it starts, however, this effect does not appear to apply to `/data/suricata/suricata.yaml` on the host. I've been trying to see if I can find where this persistence is defined, but haven't been able to.
Based on the above, my question is: Is there persistence available for the suricata.yaml file? If not, can I modify the config to make it persistent? (maybe `suricata.service` ?)

As usual, thanks a lot for your time and assistance on this!

**Comment by t3chn0m4g3** [comment]
@SunstriderX You have to modify `suricata.service` in
```
/etc/systemd/system
/data/systemd
```
```
[...] docker [...] -v /your/suricata.yaml:/path/to/suricata.yaml [...]
```

**Comment by SunstriderX** [comment]
Awesome! Worked like a charm! Thanks for the explanation, I'm still learning the docker basics :)

**Comment by arnydo** [comment]
Hey guys. I followed your advice and was able to push in a custom config.
This worked perfect, the first time...
I made an additional change to the source file on the host but the change is not reflected in the container.
I verified that the volume was mounted in the container as expected.

Am I missing something?
