### ISSUE TITLE
Issue #80 and more info - suricata

### ISSUE THREAD

**Issue by rnbwkat** [dtag-dev-sec/tpotce#85]
Currently running t-pot on a VPS with the needed hardware requirements. I was reading Issue 80 about not getting Suricata running - having the same issue. Looking at the install, and then trying to start it by hand looks to be an error in the ethtool command to try to configure the interface:
```
[root@misspiggy:/etc/init.d]# /bin/bash -c /sbin/ethtool --offload $(/sbin/ip route | /bin/grep $(/bin/hostname -I | /usr/bin/awk '{print $1 }') | /usr/bin/awk '{print $3 }') rx off tx off
ethtool: bad command line argument(s)
For more information run ethtool -h
[root@misspiggy:/etc/init.d]# systemctl start suricata
Job for suricata.service failed because the control process exited with error code. See "systemctl status suricata.service" and "journalctl -xe" for details.
[root@misspiggy:/etc/init.d]# systemctl status suricata.service
 - suricata.service - suricata
   Loaded: loaded (/etc/systemd/system/suricata.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2017-03-02 12:17:30 EST; 6s ago
  Process: 7618 ExecStartPre=/bin/bash -c /sbin/ethtool --offload $(/sbin/ip route | /bin/grep $(/bin/hostname -I | /usr/bin/awk '{print $1 }') | /usr/bin/awk '{print $3 }') rx off tx off (code=exited, status=1/FAILURE)
  Process: 7611 ExecStartPre=/usr/bin/docker rm -v suricata (code=exited, status=1/FAILURE)
  Process: 7605 ExecStartPre=/usr/bin/docker stop suricata (code=exited, status=1/FAILURE)

Mar 02 12:17:29 misspiggy systemd[1]: suricata.service: Control process exited, code=exited status=1
Mar 02 12:17:29 misspiggy systemd[1]: Failed to start suricata.
Mar 02 12:17:29 misspiggy systemd[1]: suricata.service: Unit entered failed state.
Mar 02 12:17:29 misspiggy systemd[1]: suricata.service: Failed with result 'exit-code'.
Mar 02 12:17:30 misspiggy systemd[1]: suricata.service: Service hold-off time over, scheduling restart.
Mar 02 12:17:30 misspiggy systemd[1]: Stopped suricata.
Mar 02 12:17:30 misspiggy systemd[1]: suricata.service: Start request repeated too quickly.
Mar 02 12:17:30 misspiggy systemd[1]: Failed to start suricata.
```
Going to see about troubleshooting, but it seems to be related to the awk of print $3, as that is blank, and therefore, the 'rx off tx off' parameters are invalid with the ethtool command. Breaking the pieces apart  (masking first and second octet)- 

# /sbin/ip route 
```
default via xxx.yy.44.1 dev ens3 
xxx.yy.44.1 dev ens3  scope link 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
```
# hostname -I | awk '{print $1}'
```
xxx.yy.46.82
```
And then `/usr/bin/awk '{print $3 }') rx off tx off`  is blank, and therefore the rx off tx off ends up being invalid.  Any thoughts?

**Comment by t3chn0m4g3** [comment]
Can you please run the following commands and post the outputs:
```
/sbin/ip route | /bin/grep $(/bin/hostname -I | /usr/bin/awk '{print $1 }') | /usr/bin/awk '{print $3 }'
/sbin/ip route | /bin/grep $(/bin/hostname -I | /usr/bin/awk '{print $1 }')
hostname -I
```
The first command should give you the IF name, not the IP.

**Comment by t3chn0m4g3** [comment]
Is the `/sbin/ip route` output the actual output, yours is missing **scope link src** for the local IF? It usually looks like this:
```
default via 172.20.254.1 dev ens33
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
11.22.33.0/24 dev ens33  proto kernel  scope link  src 11.22.33.120
```
Unfortunately I do not have a AWS VPS, so I cannot check myself.

**Comment by rnbwkat** [comment]
$ /sbin/ip route | /bin/grep $(/bin/hostname -I | /usr/bin/awk '{print $1 }') | /usr/bin/awk '{print $3 }'
$

Yep - blank. FYI
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

I did fix it by hardcoding the interface for now and it all works. but something is up with my ip route command.

**Comment by rnbwkat** [comment]
Upgrading from 16.04 to 16.10 seems to have resolved the problem.  A downrev version of iproute2 package.

**Comment by t3chn0m4g3** [comment]
Thanks for your feedback. This is rather interesting, did my tests with `16.04.2`, too without any problems. Really seems to be an issue of the VPS.
Can you retest please? If it works fine I will recommend 16.10 for VPS installations.

**Comment by rnbwkat** [comment]
I will standup another 16.04 in this same VPC and see if the issue is the same.  I have other resources to standup more 16.04 but from different providers, so I shall see if there are issues. It might take a day to complete.

**Comment by t3chn0m4g3** [comment]
Thank you!
