### ISSUE TITLE
Cowrie honeypot detection

### ISSUE THREAD

**Issue by battletux** [dtag-dev-sec/tpotce#91]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

It appears that mirai bots are picking up that they are in a honey pot and not fully downloading their payload. I have resolved this in a standalone instance of cowrie on another box by copying over the 'echo' and 'sh' commands from the local filesystem to the ~/pickle.fs/bin folder.

I would like to do this in T-Pot but I can not see where within the cowrie container the faux filesystem is located. Could you please point me to the relevant location so that I can do this?

On my standalone cowrie instance the ttylogs went from a filesize of 91K (mirai failing to grab the payload) to ~131K where it was successfully downloading the payload, and thus the sample being captured in the downloads folder.

### Baisc support information

- What T-Pot version are you currently using?
16:10
- Are you running on a Intel NUC or a VM?
VM - Virtualbox
- How long has your installation been running?
3 weeks
- Did you install any upgrades or packages?
no
- Did you modify any scripts?
no
- Have you turned persistence on/off?
no
- How much RAM available (login via ssh and run `htop`)?
8gb
- How much stress are the CPUs under (login via ssh and run `htop`)?
<10%
- How much swap space is being used (login via ssh and run `htop`)?
0bytes
- How much free disk space is available (login via ssh and run `sudo df -h`)?
96G
- What is the current container status (login via ssh and run `sudo start.sh`)?
Script not found. All containers showing running and green in Web GUI.

**Comment by t3chn0m4g3** [comment]
@battletux Thanks for the information.

The issues have been discussed at the Cowrie Github Repo, [here](https://github.com/micheloosterhof/cowrie/issues/411).

**Comment by t3chn0m4g3** [comment]
Latest version and fixes have been introduced with dtag-dev-sec/cowrie@2aa8531

@battletux If you like you can test the latest T-Pot 17.06 alpha and check if your findings are fixed:
```
git clone https://github.com/dtag-dev-sec/tpotce -b 17.06
cd tpotce
sudo ./makeiso.sh
```
Feedback welcome, beware of dragons :bowtie:

**Comment by t3chn0m4g3** [comment]
@battletux I am assuming this is fixed with the update. If not, please let me know.
