### ISSUE TITLE
Possible to add additional web console users?

### ISSUE THREAD

**Issue by xECK29x** [dtag-dev-sec/tpotce#92]
I wanted to see if it is possible to create a second user to login to the web console. I would prefer not to share the initial user account I created with a few colleagues of mine. Is it possible to create a second Linux user and give rights to access the console?

Thanks for the great work, this project keeps getting better and better, been using it on and off for over a year.

-----------

# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [x] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [x] Check the [FAQ](#faq)
- [x] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using? 16.10
- Are you running on a Intel NUC or a VM? VM
- How long has your installation been running? 1 year+
- Did you install any upgrades or packages? n
- Did you modify any scripts? n
- Have you turned persistence on/off? n
- How much RAM available (login via ssh and run `htop`)? n/a
- How much stress are the CPUs under (login via ssh and run `htop`)? n/a
- How much swap space is being used (login via ssh and run `htop`)? n/a
- How much free disk space is available (login via ssh and run `sudo df -h`)? n/a
- What is the current container status (login via ssh and run `sudo start.sh`)? n/a

**Comment by t3chn0m4g3** [comment]
Thank you :bowtie: 

Here you go:
`sudo htpasswd /etc/nginx/nginxpasswd <username>`

**Comment by xECK29x** [comment]
Thanks!!
