### ISSUE TITLE
Request attack map

### ISSUE THREAD

**Issue by dpicollege** [dtag-dev-sec/tpotce#93]
Hello,
Could you develop attack map it's very needed and useful.
and  in attack map it's important to have information about every interaction with honeypot
Thanks indeed

**Comment by t3chn0m4g3** [comment]
The attack map is already part of T-Pot (Kibana dashboard). You may also visit [Sicherheitstacho](http://sicherheitstacho.eu).

**Comment by dpicollege** [comment]
thanks but I mean real time attack map like Sicherheitstacho that show just my honeypot not all honeypot
