### ISSUE TITLE
Dest_Ip in a server with a lot of Ips

### ISSUE THREAD

**Issue by jonnynux** [dtag-dev-sec/tpotce#95]
Hi guys,
I'm developing a honeypot project and I've installed T-Pot some days ago. I have a server where I've mapped a lot of IP's throught vpns. I can capture all the traffic but I lost the destination IP's. It's a Docker NAT issue?

Thank you.

**Comment by t3chn0m4g3** [comment]
@jonnynux Currently we do not capture the destination IP within the ELK stack. However it will be featured in T-Pot 17.06.

**Comment by t3chn0m4g3** [comment]
Feature implemented for 17.06
https://github.com/dtag-dev-sec/tpotce/commit/1453e26f76cf26074d961a15dbc1f2f218afd980
https://github.com/dtag-dev-sec/elk/commit/383117a4cc7bace0330c5ecc817fc4b402bb5cef
https://github.com/dtag-dev-sec/elk/commit/c97ece511c4fde8ad59f914282dba889abd7b2dd

**Comment by jonnynux** [comment]
Looking at the code it seems it's a single external IP. I explain better our situation: we have a single server with a primary management IP (reachable only through the internal network), than we have a lot of public IPs mapped in a same number of internal VPNs, so we have configured them all in /etc/network/interfaces (public IP is not visible, only external router can view them)
What if need to do is:
* Exclude from monitoring the management IP
* Determine from witch IP the honeypot event is been captured (VPN IP or public IP is the same).

Thanks
