### ISSUE TITLE
Dockerized Bro

### ISSUE THREAD

**Issue by MarcinNaw** [dtag-dev-sec/tpotce#98]
Hey guys,

just a quick question. You are already using suricata, are you also planning to support bro?

Regards, Marcin

**Comment by t3chn0m4g3** [comment]
Currently it is not on the roadmap, currently I can not think of apparent benefits of supporting bro as well.

**Comment by t3chn0m4g3** [comment]
@MarcinNaw Can you think of advantages of using bro as well?

**Comment by MarcinNaw** [comment]
Well, I agree that using Bro has **no apparent advantages**.

But, (and that's just my personal experience): Honeypots are widely used at universities and research labs, which are also closer to do forensics with BRO. Pure signature based IDS such as Snort etc are rather used by operators, but they seldom deploy honeypots. 

_Bro is not about trying to tell you what's bad, it tries to tell you what's happening_.
It would introduce a second level of logging with analyzers for many protocols and would allow experts to reuse their tools. This would be an alternative to the ELK stack.

**Comment by t3chn0m4g3** [comment]
@MarcinNaw Thanks for your insight, will think about if providing a pluggable docker image might be interesting.

However you are the first person to ask for Bro 😃 🥇

**Comment by jjjan** [comment]
bro is awesome and we want it. good suggestion. and another things is i suggest is nDPI.
add Open and Extensible LGPLv3 Deep Packet Inspection Library.

**Comment by t3chn0m4g3** [comment]
@jjjan Please be more specific and supply links. Thanks :bowtie:

**Comment by funtimes-ninja** [comment]
Another project that uses bro is here -> https://github.com/rocknsm/rock

A nice project, but it doesn't come with all the power of t-pot and the easy setup of t-pot

**Comment by t3chn0m4g3** [comment]
I created a poll, please [vote here](http://doodle.com/poll/9qs959ed3fncknz8). If 20+ supporters are found (will check for fakes :wink:) I will include Bro as an option for 18.x, if technically feasible.

**Comment by t3chn0m4g3** [comment]
The poll was open for more than 6 months. While there seems to an interest in Bro the 20+ supporters have not been met. Closing the poll and the FR.
